= REST APIs
:toc: true

:page-title: About rest APIs
:page-pageid: rest-apis
:page-description: About REST APIs

The ThoughtSpot REST APIs enable your client applications to access data from the ThoughtSpot application.
Client applications can use the REST APIs for the following purpose:

* get pinboard and visualization data from the ThoughtSpot application.
* get ThoughtSpot data by programmatically sending a search query.
* list the metadata object and visualization headers in the repository.
* transfer ownership of all objects from one user to another and more.
* embed data from visualizations and pinboards in a web page, portal, or application.

The REST APIs return data as a JSON string. To embed data into your application, extract the data from the JSON file, and render it on your Web page.

REST APIs retrieve live data from ThoughtSpot, so whenever the Web page is rendered, the current values will be shown.

== Swagger portal
To access REST APIs on Swagger:

. Log in to your ThoughtSpot instance as an admin user.
. Access the Swagger portal.
+
If you have already logged into your ThoughtSpot instance, use the following URL to access the portal:

+
----
https://<your-thoughtspot.com>/external/swagger
----
+
++++
<a href="{{tshost}}/external/swagger" id="preview-in-playground" target="_blank">Go to Swagger Portal</a> 
++++


+
The portal displays a list of REST API services available for the logged in ThoughtSpot users.

. Click on a header to expand and view the list of services.
. Click on a service name to view more details about the API service.



== List of APIs
The following APIs are available for ThoughtSpot users.


=== Authentication and session management
You can use the xref:session-api.adoc[session APIs] to manage ThoughtSpot user sessions.
[width="80%" cols="2,2"]
[options='header']
|====
|Request URL|Description|
`*POST* /tspublic/v1/session/login` |Authenticate and log in a user.
|`*POST* /tspublic/v1/session/logout`|Log out a user from an existing session.
|`*POST* /tspublic/v1/session/auth/token`|Obtain an authentication token for a user.
|====

=== User management
You can use the xref:user-api.adoc[user APIs] to manage ThoughtSpot users.
[width="80%" cols="2,2"]
[options='header']
|====
|Request URL|Description|
`*GET* /tspublic/v1/user/list`|Get all users, groups, and their inter-dependencies.
|`*POST* /tspublic/v1/user/updatepassword`|Change the password of a user account.
|`*POST* /tspublic/v1/user/updatepreference`|Modify a user profile.
|`*POST* /tspublic/v1/user/transfer/ownership`|Transfer ownership of all objects from one user to another.
|`*POST* /tspublic/v1/user/sync`|Synchronize principal from your client application with ThoughtSpot.
|====

=== User group management
You can use the xref:group-api.adoc[group APIs] to configure privileges for ThoughtSpot user groups.
[width="80%" cols="2,2"]
[options='header']
|====
|Request URL|Description|
`*POST* /tspublic/v1/group/addprivilege` |Add a privilege to a group.
|`*POST*/tspublic/v1/group/removeprivilege` |Remove a privilege from a group.
|====

=== TML APIs
You can use the xref:tml-api.adoc[tml APIs] to import and export TML  objects.
[width="80%" cols="1,1"]
[options='header']
|====
|Request URL|Description|
`*POST* /tspublic/v1/metadata/tml/import` |Validate and import the TML objects.
|`*POST* /tspublic/v1/metadata/tml/export`|Export TML objects.
|====

=== Data APIs
You can use the data APIs to query and embed data from the ThoughtSpot application.
[width="85%" cols="1,3,3"]
[options='header']
|====
|Data API|Request URL|Description|
xref:pinboarddata.adoc[Pinboard Data]|`*POST* /tspublic/v1/pinboarddata`|Fetch the pinboard data from the ThoughtSpot application.
|xref:pinboard-export-api.adoc[Pinboard export]| `*POST* /tspublic/v1/export/pinboard/pdf`|Download a pinboard or specific visualizations from a pinboard as a PDF file.
.3+|xref:metadata-api.adoc[Metadata]|
`*GET* /tspublic/v1/metadata/listobjectheaders`|List the metadata object headers in the repository
|`*GET* /tspublic/v1/metadata/listvizheaders`|Get the visualization headers from the ThoughtSpot system.
|`*GET* /tspublic/v1/metadata/listas`| Get a list of metadata objects for a user or user group.
|xref:search-data-api.adoc[Search data] |`*POST* /tspublic/v1/searchdata`|Search data from a specific data source in the ThoughtSpot application.

|====
