= ThoughtSpot REST APIs
:toc: true

:page-title: ThoughtSpot REST APIs
:page-pageid: rest-apis
:page-description: ThoughtSpot REST API provides service endpoints for administration, embedding, and data management.

The ThoughtSpot REST API framework lets you create, access, edit, and manage objects and resources in the ThoughtSpot system programmatically. 
 
ThoughtSpot REST API supports several resource collections and operations in two distinct versions: 

* REST API v1
+
The legacy framework with several endpoints to create, edit, administer and manage ThoughtSpot objects and data. 

* REST API V2 
+
The REST API v2 [beta blueBackground]^BETA^ framework is a new developer-focused solution that provides additional functionality and interactive Playground experience.

For more information about the differences between these two REST API versions, see xref:rest-api-v1v2-comparison.adoc[REST API v1 and v2 comparison].

== REST API Playground

ThoughtSpot users with Developer or Administrator privileges can access the REST v1 and v2[beta blueBackground]^BETA^ endpoints in the *Develop* tab. The portal provides a separate Playground for each REST API version and lets you explore the API endpoints, request and response workflows.

* To try out the xref:rest-api-v1.adoc[REST v1 APIs], click **REST Playground v1**. +
* To access the xref:rest-api-v2.adoc[REST v2 Playground][beta blueBackground]^BETA^, click **REST Playground v2**.

==  API endpoints
For a complete list of API endpoints and information about how to make an API call to these endpoints, see the following reference pages:

* xref:rest-api-reference.adoc[REST API v1 Reference]
* xref:rest-api-v2-reference.adoc[REST API v2 Reference]
