= REST APIs
:toc: true

:page-title: About rest APIs
:page-pageid: rest-apis
:page-description: About REST APIs

ThoughtSpot provides RESTful APIs to let you programmatically create, access, and manage ThoughtSpot objects and resources. Using REST APIs, your client application can perform the following operations:

* get pinboard and visualization data from the ThoughtSpot application.
* get ThoughtSpot data by programmatically sending a search query.
* list metadata object headers for visualizations in the repository.
* transfer ownership of objects from one user to another.
* embed data from visualizations and pinboards in a web page, portal, or application.
* import, export, and validate scriptable files and automate deployments

== Resource endpoints

ThoughtSpot resources are represented as JSON objects and are identified using a unique URI. The base URI of the API endpoints constitutes the following:

* The hostname or IP address of your ThoughtSpot application instance.
* Port number
* Name of the ThoughtSpot API service
* The version number

For example, in the `\https://<your-thoughtspot-hostname:port>/callosum/v1/tspublic/v1/session/login` URL, the base URI is `\https://<your-thoughtspot-hostname:port>/callosum/v1` and `/tspublic/v1/session/login` is the resource path. 

== HTTP request methods

ThoughtSpot REST APIs support Create, Read, Update and Delete (CRUD) operations and allow applications to use the standard HTTP verbs in API requests:
 
* **GET** to query information, such as getting a list of users, objects, or metadata headers.
* **POST** to create, add, or exchange data. 
* **PUT** to update the parameters in resource representation.
* **DELETE** to remove a specific data, association, or object. 

== Data format

The REST APIs allow you to send and receive data in JSON format. To embed this data in your application, you can import or extract the data from the JSON file. You can also use the scriptable files in ThoughtSpot Modeling Language (TML) to represent objects in a reusable, editable, and easy-to-read format. ThoughtSpot allows you to export, validate, and import these scriptable files. 

== List of APIs
For a complete list of API endpoints and information about how to make an API request to these points, see xref:rest-api-reference.adoc[REST API Reference].
