= REST API v1 authentication
:toc: true
:toclevels: 1

:page-title: User authentication and session management
:page-pageid: api-auth-session
:page-description: To access ThoughtSpot objects and resource endpoints, authenticate and log in to the ThoughtSpot system

To create, access, and modify ThoughtSpot objects and resources through the REST API, you must log in as an authorized user. Any completed log-in process will return session cookies from the ThoughtSpot system, which must be included with any subsequent REST API call.

When using the REST API through a web browser, ThoughtSpot recommends that you use the xref:configure-saml.adoc[SAML SSO] or xref:trusted-authentication.adoc[trusted authentication] service to authenticate to ThoughtSpot. A successful log-in using the Visual Embed SDK via either of those two methods will establish the session within the web browser. 

Once the session is established in the browser, you can set the `withCredentials: true` property for any `XMLHttpRequest` object or `credentials: "include"` as part of a `Fetch` object to pass the cookies along when making REST API requests:

[source,javascript]
----
// Simple XMLHttpRequest
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

// Using Fetch with Promises
return async fetch(
            apiFullEndpoint, {
            method: 'GET',
            headers: {
                "Accept": "application/json",
                "X-Requested-By": "ThoughtSpot"
            },
            credentials: "include"
            })
----


[TIP]
====
If you are accessing the REST API outside a web browser, create a long-lived session object in your code, and then call the log-in API using that session object. Make subsequent REST API calls with the same session object to send the session cookies along with the other aspects of the REST API call.
==== 

== Sign in a ThoughtSpot user

include::{path}/log-in-api.adoc[]

== Obtain authentication token

include::{path}/auth-token-api.adoc[]

== Authenticate and log in with a token

include::{path}/login-token-api.adoc[]

== Log out of a user session

include::{path}/log-out-api.adoc[]

