= Configure privileges for user groups
:toc: true

:page-title: Manage user groups
:page-pageid: api-user-group-management
:page-description: Manage user groups using REST APIs

Each user group in ThoughtSpot assigns a set of privileges to its users. When a user is assigned to a group in ThoughtSpot, the default privileges associated with a group are assigned to its users. 

ThoughtSpot also has a default group called `ALL_GROUP`. When you create new users in ThoughtSpot, they are automatically added to `ALL_GROUP`.

By default, the members of `ALL_GROUP` do not have the permission to download or upload data. You can use the Group APIs to globally add the following privileges to all the users in `ALL_GROUP`.

* `DATADOWNLOADING`
+
Allows users to download data from search results and Liveboards. When the `DATADOWNLOADING` privilege is applied, the users can download all the data sources that a group can access.

* `USERDATAUPLOADING`
+
Allows users to upload their data to ThoughtSpot.

== Add a privilege to a user group

To add a privilege to a group, send a `POST` request to the following endpoint URL:

----
POST /tspublic/v1/group/addprivilege
----
=== Request parameters
[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|The type of privilege to add. Valid values are `DATADOWNLOADING` and `USERDATAUPLOADING`.

|`groupNames`|string|A JSON array of group names to which you want to add the privilege. To add a privilege to all user groups, specify `ALL_GROUP`.
|====

=== Example request

.cURL

[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=DATADOWNLOADING&groupNames=ALL_GROUP' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/group/addprivilege'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/group/addprivilege
----

=== Example response

----
204 - Success
----

== Remove a privilege from a user group

To delete a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege from the system default `ALL_GROUP` group, send a `POST` request to the following endpoint URL:

----
POST /tspublic/v1/group/removeprivilege
----
=== Request parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|Type of the privilege to delete. Valid values are `DATADOWNLOADING` and `USERDATAUPLOADING`.

|`groupNames`|string|A JSON array of group names. To remove the privilege from all user groups, specify `ALL_GROUP`.
|====


=== Example request

.cURL

[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=USERDATAUPLOADING&groupNames=ALL_GROUP' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/group/removeprivilege'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/group/removeprivilege
----

=== Example response

----
204 - Success
----

////
## Error Codes

<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
    <tr> <td><code>10003</code></td>  <td>Authentication token of type could not be authenticated by any configured realms.  Use valid realm that can authenticate these tokens.</td> <td><code>401</code></td></tr>

  </tbody>
</table>
////
