= Manage users
:toc: true

:page-title: Manage users 
:page-pageid: api-user-management
:page-description: Manage users using REST APIs

The user access control in ThoughtSpot is applied based on the users and groups configured in your ThoughtSpot application instance. The users and groups are stored locally in ThoughtSpot, even if the authentication is done using the SAML SSO or trusted authentication service. 

To provide access to ThoughtSpot content or define role-based privileges, you need to add users and groups in ThoughtSpot. You can link:https://cloud-docs.thoughtspot.com/admin/users-groups/add-user.html[add users manually, window=_blank] or through the REST API service.

ThoughtSpot provides the following set of REST APIs for managing users:
[width="80%" cols="2,2"]
[options='header']
|====
|Request URL|Description|
`*GET* /tspublic/v1/user/list`|Get all users, groups, and their inter-dependencies.
|`*POST* /tspublic/v1/user/updatepassword`|Change the password of a user account.
|`*POST* /tspublic/v1/user/transfer/ownership`|Use this API to transfer ownership of all objects from one user to another.
|`*POST* /tspublic/v1/user/sync`|Synchronize principal from your client application with ThoughtSpot.
|====

== Fetch users and groups
To fetch a list of all users, groups, and their inter-dependencies, send a `GET` request to the following endpoint:

----
GET /tspublic/v1/user/list
----
=== Example request

.cURL

[source, cURL]
----
curl -X GET --header 'Accept: application/json' 'https://<base-uri>/callosum/v1/tspublic/v1/user/list'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/user/list
----

=== Example response

[source, JSON]
----
[
  {
    "name": "Administrator",
    "displayName": "Administration Group",
    "created": 1354006445722,
    "modified": 1354006445987,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT"
  },
  {
    "name": "Analyst",
    "displayName": "Analyst Group",
    "created": 1354006445722,
    "modified": 1354006445987,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT"
  },
  {
    "name": "rls-group-3",
    "displayName": "rls-group-3",
    "description": "Contains directly rls-group-1, rls-group-2 and belongs directlsy to rls-group-5",
    "created": 1459376495060,
    "modified": 1459376590681,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": rls-group-5,
    "visibility": "DEFAULT"
  }
  ]
----
=== Object properties
A typical principal object contains the following properties:

[width="100%" cols="1,3"]
[options='header']
|====
|Property|Description 
|`name`|Name of the principal. This field, in conjunction with whether the object is a user or group, is used to identify a user or group. The name of the principal must be unique. 
|`displayName`|Display name of the principal.
|`description`|Description of the principal. 
|`mail`|The email address of the user. This field is populated only for the user objects. It is ignored if the object type is a group. 
|`principalTypeEnum` a|Type of the user created in the ThoughtSpot system. 
Valid values are:

* `LOCAL_USER`
* `LOCAL_GROUP`
|`password` a|The password of the user. This field is populated only for the user object. It is ignored in the case of groups. 
Password is only required:

* if the user is of `LOCAL_USER` type.
* when the user is created for the first time. In subsequent updates, the user password is not updated even if it changes in the source system. 
|`groupNames` a|Name of the groups to which a principal belongs. For example, `Administrator`, `ALL_GROUP`, and so on. Groups and users can belong to other groups. 
|`visibility`| Whether the users of the group can share objects with other users in the group.
|====


== Change password

To change the password of the user, send a POST request to the following endpoint:
----
POST /tspublic/v1/user/updatepassword
----
=== Request parameters
[width="100%" cols="1,2,3"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`name`|string|Name of the user.
|`currentpassword`|string|The current password of the user.
|password|string|A new password of the user. 
|====
=== Example request

.CURL
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'name=guest¤tpassword=test&password=foobarfoobar' 'https://<base-uri>/callosum/v1/tspublic/v1/user/updatepassword'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/user/updatepassword
----

=== Example response

----
204 - Successful password update
----


== Transfer ownership

To transfer ownership of _all_ objects from one user to another, send a `POST` request:

----
POST /tspublic/v1/user/transfer/ownership
----

[NOTE]
You cannot transfer objects to or from the system user or the administrative user.

=== Request parameters 
[width="100%" cols="2,2,4"]
[options='header']
|====
|Query Parameter|Data Type|Description
|`fromUserName`| string|Username to transfer from.
|`toUserName`|string|Username to transfer to.
|====

=== Example request

.CURL
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<base-uri>/callosum/v1/tspublic/v1/user/transfer/ownership?fromUserName=guest&toUserName=guest1'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/user/transfer/ownership?fromUserName=guest&toUserName=guest1
----

=== Example response
----
204 - Successful login
----

== Synchronize principals

To synchronize ThoughtSpot users and groups with your external database, send a `POST` request to the following endpoint:

----
POST /tspublic/v1/user/sync
----

The payload takes principals containing all users and groups present in the external database. 
A successful API call returns the object that represents the changes made in the ThoughtSpot system.

During this operation:

* Objects (users or groups) present in ThoughtSpot, but not present in the external list are deleted in ThoughtSpot.
* Objects present in ThoughtSpot and the external list are updated such that the object attributes in ThoughtSpot match those present in the list.
+
This includes group membership.

* Objects not present in ThoughtSpot, but present in the external list  are created in ThoughtSpot.
 
=== Request parameters

This API uses `multipart/form-data` content type.

[width="100%" cols="1,1,4"]
[options='header']
|===
|Form Parameter|Data Type|Description

|`principals`|string|Specifies a list of principal objects.
This is a JSON file containing all users and groups present in the external database.

|`applyChanges`
|boolean
|A flag indicating whether to sync the users and groups to the system, and apply the difference evaluated.
Use this parameter to validate a difference before applying changes.

|`removeDeleted`
|boolean
|A flag indicating whether to remove deleted users/groups.
When true, this flag removes any deleted users or groups.

|`password`
|string
|Specifies a password.
|===

=== Example request

.CURL
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'applyChanges=false' 'https://<base-uri>/callosum/v1/tspublic/v1/user/sync'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/user/sync
----

=== Example response

This example covers user objects (with emails), group objects, and their relationships.

* `created` and `modified` dates may be left blank for new users.
* `principalTypeEnum` value specifies if the principal is a user or a group.

Here, `test1` user belongs to two groups, `Customer Success` and `Marketing`. 
`test2` belongs to the group `Administrator`. 
`All` is a default group to which every user belongs;
you may omit it from the input.

Set `visibility` to `NON_SHARABLE` if you do not want users to link:https://cloud-docs.thoughtspot.com/admin/users-groups/add-user.html#sharing-visibility[share objects] with users in this group.

[source, JSON]
----
[
  { "name": "Customer Success",
    "displayName": "Customer Success",
    "description": "CS",
    "created": 1568926267025,
    "modified": 1568926982242,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT" },

  { "name": "All",
    "displayName": "All Group",
    "created": 1354006445722,
    "modified": 1354006445722,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT" },

  { "name": "Marketing",
    "displayName": "Marketing",
    "description": "Marketing Group",
    "created": 1587573582931,
    "modified": 1587573583003,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT" },

  { "name": "test1",
    "displayName": "test one",
    "description": "",
    "created": 1587573554475,
    "modified": 1587573589986,
    "mail": "test1@test.com",
    "principalTypeEnum": "LOCAL_USER",
    "groupNames": [ "All", "Customer Success", "Marketing" ],
    "visibility": "DEFAULT" },

  { "name": "test2",
    "displayName": "test two",
    "created": 1587573621279,
    "modified": 1587573621674,
    "mail": "test2@test.com",
    "principalTypeEnum": "LOCAL_USER",
    "groupNames": [ "Administrator", "All" ],
    "visibility": "DEFAULT" }
]
----


////
## Error Codes
<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
   <tr> <td><code>10000</code></td>  <td>Internal server error.</td> <td><code>500</code></td></tr>
    <tr> <td><code>10002</code></td>  <td>Bad request. No user found with the given username.</td> <td><code>400</code></td></tr>
    <tr> <td><code>10003</code></td>  <td>Unable to authenticate user</td><td><code>403</code></td></tr>
  </tbody>
</table>
////
