= Authentication
:toc: true
:toclevels: 1

:page-title: Manage user sessions
:page-pageid: api-auth-session
:page-description: Manage user sessions with REST APIs

To create, access, and modify ThoughtSpot objects and resources through the REST API, you must log in as an authorized user. ThoughtSpot recommends that you use the xref:configure-saml.adoc[SAML SSO] or xref:trusted-authentication.adoc[trusted authentication] service to authenticate to ThoughtSpot. If trusted authentication is enabled on your instance, you must obtain an authentication token to log in and include the authorization token when making subsequent requests from that session. 

ThoughtSpot also supports local management of user profiles. For initial development and testing purposes, you can create users in ThoughtSpot and manage their profiles locally. However, in large production environments, avoid creating local user profiles to reduce the administration overhead.

== Sign in a ThoughtSpot user

include::{path}/log-in-api.adoc[]

== Obtain authentication token

include::{path}/auth-token-api.adoc[]

== Authenticate and log in with a token

include::{path}/login-token-api.adoc[]

== Log out of a user session

include::{path}/log-out-api.adoc[]

