= REST API v1 authentication
:toc: true
:toclevels: 1

:page-title: User authentication and session management
:page-pageid: api-auth-session
:page-description: To access ThoughtSpot objects and resource endpoints, authenticate and log in to the ThoughtSpot system

To create, access, and modify ThoughtSpot objects and resources through the REST API, you must log in as an authorized user. A successful login operation returns session cookies from the ThoughtSpot system, which must be included in subsequent REST API calls.

When using the REST API through a web browser, ThoughtSpot recommends that you use the xref:configure-saml.adoc[SAML SSO] or xref:trusted-authentication.adoc[trusted authentication] service to authenticate to ThoughtSpot. A successful login using the Visual Embed SDK via either of those two methods will establish the session within the web browser.

== Basic authentication

include::{path}/log-in-api.adoc[]

A successful login returns a session cookie that can be used in your subsequent API calls. For more information, see xref:api-auth-session.adoc#sessionCookies[Session cookies for subsequent API calls].

== Trusted authentication

For trusted authentication, you must obtain a token from ThoughtSpot via `/tspublic/v1/session/auth/token` and send it in your login request to the `/tspublic/v1/session/login/token` API endpoint.

=== Obtain a token for trusted authentication

include::{path}/auth-token-api.adoc[]

=== Authenticate and log in with a token (trusted authentication)

include::{path}/login-token-api.adoc[]

[#sessionCookies]
== Session cookies for subsequent API calls

If the login operation is successful, the API returns cookie details in the response header.
----
Set-Cookie: JSESSIONID=b9a5b821-fa91-49ea-99fc-12817a141e76; Path=/; HttpOnly
Set-Cookie: clientId=76d83461-1b8a-425a-9116-66c8d6f006bb; Path=/; Secure; HttpOnly
----
The session cookie is automatically set in the request header when you make your subsequent API calls via a web browser. REST clients in a non-browser environment must pass this cookie in the request header in their subsequent API calls.

== Make a test API call
You can make a test API call to verify if your token is valid and allows access to ThoughtSpot objects. For example, you can send a `GET` request `/tspublic/v1/metadata/listvizheaders` to fetch the visualization headers of a Liveboard.

Note that if you are using a Web browser or Postman to make a REST API call, the session cookie obtained from the  `/tspublic/v1/session/login/token` or `/tspublic/v1/session/login` API call is automatically set. REST clients in a non-browser environment must include the session cookie in the request header as shown in the following example:

[source,cURL]
----
curl -X GET \
--header 'Accept: text/html' \
--header 'X-Requested-By: ThoughtSpot' \
--header 'Cookie: JSESSIONID=fc3424f9-d3f0-4a24-bd33-400fd826cac7; clientId=70cf1328-af97-40b2-9bd5-1c520e133963' \
'https://<ThoughtSpot-Host>/callosum/v1/tspublic/v1/metadata/listvizheaders?id=d084c256-e284-4fc4-b80c-111cb606449a'
----

Once the session is established in the browser, you can set the `withCredentials: true` property for any `XMLHttpRequest` object or `credentials: "include"` as part of a `Fetch` object to pass the cookies along when making REST API requests:

[source,javascript]
----
// Simple XMLHttpRequest
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

// Using Fetch with Promises
return async fetch(
            apiFullEndpoint, {
            method: 'GET',
            headers: {
                "Accept": "application/json",
                "X-Requested-By": "ThoughtSpot"
            },
            credentials: "include"
            })
----

[NOTE]
====
If you are accessing the REST API outside a web browser, create a long-lived session object in your code, and then call the login API using that session object. Make subsequent REST API calls with the same session object to send the session cookies along with the other aspects of the REST API call.
====

== Log out of a user session

include::{path}/log-out-api.adoc[]
