= Manage users and user groups
:toc: true

:page-title: Manage users
:page-pageid: api-user-management
:page-description: You can manage users and user groups using REST APIs

The user access control in ThoughtSpot is applied based on the users and groups configured in your application instance. The users and groups are stored locally in ThoughtSpot, even if the authentication is done using the SAML SSO or trusted authentication service.

To provide access to ThoughtSpot content or define role-based privileges, you need to add users and groups in ThoughtSpot. You can create link:https://cloud-docs.thoughtspot.com/admin/users-groups/add-user.html[user accounts, window=_blank] and link:https://cloud-docs.thoughtspot.com/admin/users-groups/add-group.html[user groups, window=_blank] in the UI or by using xref:rest-api-reference.adoc[REST APIs].

== Group privileges

Each user group includes a set of privileges for its users. When a user is assigned to a group in ThoughtSpot, the default privileges associated with a group are assigned to its users. The group privileges allow users belonging to a group to perform specific operations and access workflows. If a user belongs to more than one group, they will have the highest level of privileges from all the groups they belong to. 

[NOTE]
====
If a user group belongs to another user group, it inherits privileges from its parent group.
====

include::{path}/group-privileges.adoc[]

[NOTE]
====
ThoughtSpot also has a default group called `ALL_GROUP`. When you create new users in ThoughtSpot, they are automatically added to `ALL_GROUP`. By default, the members of `ALL_GROUP` do not have permission to download or upload data. To globally add the following privileges to all the users in `ALL_GROUP`, you can use the Group APIs.
====
