= Manage user groups
:toc: true

:page-title: Manage user groups
:page-pageid: api-user-group-management
:page-description: Manage user groups using REST APIs

To configure or remove privilege from a single or multiple groups, use the group REST API service.

== Add a privilege to a user group

All users in the system are always a part of the `ALL_GROUP` group.
By default, this group does not have either permission.

All the data sources which the `ALL_GROUP` group has permissions to are downloadable when `DATADOWNLOADING` is applied.

To add a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege to the system default `ALL_GROUP` group, send a `POST` request to the following endpoint URL:

----
POST /tspublic/v1/group/addprivilege
----
=== Request parameters
[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|Specifies a privilege type to add. Valid values are `DATADOWNLOADING` or`USERDATAUPLOADING` privilege.

|groupNames|string|Specifies a group name to add the privilege to. Valid value is `ALL_GROUP` group. 

|====

=== Example request

.CURL
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=DATADOWNLOADING&groupNames=ALL_GROUP' 'https://<base-uri>/callosum/v1/tspublic/v1/group/addprivilege'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/group/addprivilege
----

=== Example response

----
Not applicable
204 - Success
----

== Remove a privilege from a user group

To delete a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege from the system default ``ALL_GROUP``group, send a `POST` request to the following endpoint URL:

----
POST /tspublic/v1/group/removeprivilege
----
=== Request parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|Specifies a privilege type to delete. Valid values are `DATADOWNLOADING` or`USERDATAUPLOADING` privilege.

|groupNames|string|Specifies a group name to delete the privilege to. Valid value is `ALL_GROUP` group. 

|====

=== Example request

.CURL
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=USERDATAUPLOADING&groupNames=ALL_GROUP' 'https://<instance>/callosum/v1/tspublic/v1/group/removeprivilege'
----

.Request URL
----
https://<instance>/callosum/v1/tspublic/v1/group/removeprivilege
----

=== Example response

----
Not applicable
204 - Success
----

////
## Error Codes

<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
    <tr> <td><code>10003</code></td>  <td>Authentication token of type could not be authenticated by any configured realms.  Use valid realm that can authenticate these tokens.</td> <td><code>401</code></td></tr>

  </tbody>
</table>
////
