= Authentication and security
:toc: true

:page-title: Authentication and security overview
:page-pageid: auth-overview
:page-description: You can configure SAML SSO, trusted authentication method and security settings to authenticate embed users and authorize cross-origin content requests.

To allow your application users to access ThoughtSpot content, make sure you configure security settings for CORS and CSP.

To authenticate and authorize embed users, you must also configure an authentication method in ThoughtSpot.


== User configuration

[div boxDiv boxFullWidth]
--
+++<h5>Developer access</h5>+++

xref:user-roles.adoc[Create a user group with Developer privilege and assign developer users to this group] to enable access to the *Develop* tab in the ThoughtSpot UI.
--

== Authentication methods

[div boxDiv boxFullWidth]
--
+++<h5>SAML SSO authentication</h5>+++

If you plan to use an external directory service for authenticating your application users, you need to xref:configure-saml.adoc[enable SAML SSO on ThoughtSpot and add SAML redirect domains to the allowed list].
--

[div boxDiv boxFullWidth]
--
+++ <h5>Trusted authentication</h5>+++

If you plan to use a token-based authentication service to authenticate user sessions,  xref:trusted-authentication.adoc[enable trusted authentication] on ThoughtSpot.
--

== Authorization and access control

[div boxDiv boxFullWidth]
--
+++ <h5>Authentication and authorization</h5>+++

Use xref:authentication-authorization.adoc[REST APIs or the ThoughtSpot UI to define authorization settings] for object-level access and sharing privileges.
--

[div boxDiv boxFullWidth]
--
+++<h5>Access control and data security</h5>+++

Learn how to use various ThoughtSpot features, such as group privileges, object sharing, Row-level security (RLS), and Column-level security (CLS), to xref:configure-user-access.adoc[control user access to ThoughtSpot application workflows and data objects].
--

== CORS and CSP allowed domains

[div boxDiv boxFullWidth]
--
+++<h5>Security settings</h5>+++

xref:security-settings.adoc[Add your application domain to the CORS and CSP allowed list] and set your application as a trusted host for secure data exchange.
--



== Additional resources

[div boxDiv boxFullWidth]
--
* xref:configure-user-access.adoc[Access control and data security for ThoughtSpot deployments]
* xref:embed-authentication.adoc[Authentication and security attributes for embedded ThoughtSpot instances] 
* xref:api-user-management.adoc[Managing users and groups with REST APIs]
--