= REST API v2 Authentication
:toc: true
:toclevels: 1

:page-title: User authentication and session management
:page-pageid: api-authv2
:page-description: REST V2 APIs supports cookie-based and bearer token authentication methods.

The REST API v2 framework supports the following types of authentication:

OAuth 2.0 bearer token authentication::
In this method, the REST clients must xref:authentication.adoc#oauth-token[obtain an OAuth access token] to authenticate to ThoughtSpot. The access token is a string, which you must include in the `Authorization` header to authorize your API requests.

Trusted authentication::
In this method, the REST clients must xref:authentication.adoc#trustedAuthToken[obtain a login token] to sign in to a ThoughtSpot instance. Before sending an API request to get a login token from ThoughtSpot, you must enable *Trusted authentication* on the *Security Settings* page in the *Develop* tab and get the `secret_key`. You must send the  `secret_key` in your API request to obtain a login token from ThoughtSpot. After you receive the token, make sure you send it in the `Authorization` header in your API calls. +

Cookie-based authentication::
In this method, REST clients can create a session with cookies and pass these cookies in the header when making an API call.
+
[IMPORTANT]
====
The REST API SDK does not support cookie-based authentication. Clients using the REST API SDK libraries must use the OAuth bearer token or the trusted authentication method to log in to ThoughtSpot.
====

[TIP]
====
If you are accessing the REST API outside a web browser, create a long-lived session object in your code, and then call the login API below using that session object. Make subsequent REST API calls with the same session object to send the session cookies along with the other aspects of the particular REST API call.
====

[#loginTS]
== Sign in to ThoughtSpot

To create, access, and modify ThoughtSpot objects and resources through the REST API, you must log in as an authorized user. A successful log-in process returns session cookies from the ThoughtSpot system, which you must include in the subsequent REST API calls.

To sign in to ThoughtSpot and create a session, send a `POST` request to the `/tspublic/rest/v2/session/login` API endpoint.

=== Resource URL
----
POST /tspublic/rest/v2/session/login
----
=== Request Parameters

[width="100%" cols="1,4"]
[options='header']
|====
|Parameter|Description
|`username`|__String__. Username of the user account.
|`password`|__String__. The password of the user account.
|`rememberme`|__Boolean__. A flag to remember the user session. When set to `true`, a session cookie that persists in subsequent API calls is set. The system default is `false`.
|====

[IMPORTANT]
====
You can create a session either by using `userName` and `password` or  by passing a token in the Authorization header. If you are using trusted authentication, you can obtain a login token from the `/tspublic/rest/v2/session/getToken` endpoint and add it in the `Authorization` header.

When you send `userName`, `password`, and the `Authorization` header in an API request, the user credentials take precedence over the `Authorization` header.
====

=== Example request

.cURL
[source, cURL]
----
curl -X POST \
  --url 'https://<ThoughtSpot-host>/tspublic/rest/v2/session/login' \
  -H 'Accept: application/json'\
  -H 'Accept-Language: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "userName": "tsUser2022",
  "password": "fhEg23!3bbN!",
  "rememberMe": true
}'
----

.Request URL
----
https://<ThoughtSpot-host>/tspublic/rest/v2/session/login
----

=== Session response

If the operation is successful, the API returns a response with `tokenType` set as `Cookie`.

[source, JSON]
----
{
  "userName": "tsUser2022",
  "token": "",
  "tokenCreatedTime": "-1",
  "tokenExpiryDuration": "-1",
  "tokenType": "Cookie"
}
----

=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful login
|**500**|Operation failed or unauthorized request
|===

[#oauth-token]
== Get an OAuth access token

For OAuth 2.0 bearer token-based authorization, you must obtain an OAuth access token and send it in the `Authorization` header when making an API request. To obtain an OAuth token, send a `POST` request to the  `/tspublic/rest/v2/session/gettoken` endpoint.

[NOTE]
====
By default, the OAuth access token is valid for 24 hours. If the token expires and the client tries to make an API call with an expired token, the server returns an error. You can configure the token expiry duration as per your requirement or request for a new access token and use it in your subsequent API calls.
====


=== Resource URL

----
POST /tspublic/rest/v2/session/gettoken
----

=== Request parameters

[width="100%" cols="1,4"]
[options='header']
|====
|Parameter|Description
|`username`|__String__. Username of the user account.
|`password`|__String__. The password of the user account.
|`tokenExpiryDuration`  __Optional__|__String__. Duration in seconds after which the authorization token expires. By default, the token is valid for 24 hours.
|====

=== Example request

.cURL
[source, cURL]
----
curl -X POST \
  --url 'https://<ThoughtSpot-host>/tspublic/rest/v2/session/gettoken' \
  -H 'Accept: application/json'\
  -H 'Accept-Language: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "userName": "tsUser2022",
  "password": "Test_TS@1234!",
  "tokenExpiryDuration": "120000"
}'
----

.Request URL
----
https://<ThoughtSpot-host>/tspublic/rest/v2/session/gettoken
----

=== Session response

If the operation is successful, the API returns an OAuth access token. Make sure you use this access token in the `Authorization` header in your subsequent API call.

----
"userName":"tsadmin"
"token":"dHNhZG1pbjpKSE5vYVhKdk1TUlRTRUV0TWpVMkpEVXdNREF3TUNSRGRVZFRLM2hQUzNKUVNUSm1jMnBsTlRNdmMwVkJQVDBrTmsxeFZYWmhNR2R1TUVabFQzTXZiSE5qTW5ONVdfdG1Zalo0ZFVSTWIyNXZWVmRtTWxGeWEwVnhORDA="
"tokenCreatedTime":"1642662844229"
"tokenExpiryDuration":"1642749244229"
"tokenType":"Bearer"
----

=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|An OAuth access token is granted
|**500**|Operation failed or unauthorized request
|===

== Revoke a token

To revoke a token granted for the currently logged-in user, send a `POST` request to the `/tspublic/rest/v2/session/revoketoken` endpoint.


=== Resource URL
----
POST /tspublic/rest/v2/session/revoketoken
----

=== Request parameters

None


=== Example request

.cURL
[source, cURL]
----
curl -X POST \
  --url 'https://<ThoughtSpot-host>/tspublic/rest/v2/session/revoketoken' \
  -H 'Authorization: Bearer {OAUTH_TOKEN}'\
  -H 'Content-Type: application/json'\
  -H 'Accept-Language: application/json'
----

.Request URL

----
https://<ThoughtSpot-host>/tspublic/rest/v2/session/revoketoken
----

=== Example response

If the API request is successful, the access token is revoked and the current user session becomes invalid. Before making another API call, you must obtain a new token.


=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful token revocation
|**500**|Failed operation or unauthorized request
|===

[#trustedAuthToken]
== Get a login token for trusted authentication

The trusted authentication method involves the following steps:

. Enable Trusted authentication in the *Develop* > *Customizations* > *Security Settings* page.
. Copy the secret key.
. Send a `POST` request with the user credentials and secret key to the `/tspublic/rest/v2/session/gettoken` endpoint and obtain a login token.
. Use the login token in the `Authorization` header to log in to ThoughtSpot and create a user session using cookies.


=== Resource URL

Use this endpoint to get a login token:

----
POST /tspublic/rest/v2/session/gettoken
----

=== Request parameters

[width="100%" cols="1,4"]
[options='header']
|====
|Parameter|Description
|`username`|__String__. Username of the user account.
|`password`|__String__. The password of the user account.
|`secretKey`|__String__. The `secret_key` obtained from ThoughtSpot. The `secret_key` is generated when *Trusted authentication* is enabled on the `Security Settings` page in the `Develop` tab.
|`accessLevel` a|__String__. Type of access. Valid values are: +

* `FULL` +
Allows access to the entire ThoughtSpot application. When a token has been requested in `FULL` mode, it will create a full ThoughtSpot session in the browser and application. The token for `Full` access mode persists through several sessions and stays valid until it expires.

* `REPORT_BOOK_VIEW` +
Allows view access to the object specified in `tsObjectId`. The user can access only one object at a time. If the user requires access to another object, a new token request must be sent.

|`tsObjectId`| __String__. The GUID of the Liveboard or visualization.
This parameter is required only for the `REPORT_BOOK_VIEW` access mode.

|`tokenExpiryDuration`  __Optional__|__String__. Duration in seconds after which the authorization token expires. By default, the token is valid for 24 hours. If a new `secret_key` is generated, the token will become invalid despite the token expiry value set in this attribute.
|====


=== Example request

.cURL
[source,cURL]
----
curl -X POST \
  --url 'https://<ThoughtSpot-Host>/tspublic/rest/v2/session/gettoken' \
  -H 'Accept: application/json'\
  -H 'X-Requested-By: ThoughtSpot'\
  -H 'Accept-Language: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "userName": "tsadmin",
  "password": "admin",
  "secretKey": "c08fbabae66b8a933ce260363a21ebf3c1eb4367efc7147d834b0ef5d710b6c4",
  "accessLevel": "FULL",
  "tokenExpiryDuration": "86400"
}'
----

.Request URL

----
https://<ThoughtSpot-Host>/tspublic/rest/v2/session/gettoken
----

=== Example response

[source,JSON]
----
{
"userName":"tsadmin",
"token":"dHNhZG1pbjpKSE5vYVhKdk1TUlRTRUV0TWpVMkpEVXdNREF3TUNRd2FGaFlRMkZXUVhCTE4wZ3dXRlp3Yld3eGVVMUJQVDBrT0dGRlpXOVJiMVp1Y0N0WGNFdEJhR1Z2YjFscGFETjFOMnRDS3pjNVV6VmxVRUV5TTFGeFN6QlBPRDA=",
"tokenCreatedTime":"1648051501240",
"tokenExpiryDuration":"1648052401240",
"tokenType":"Bearer"
}
----

Note the login token and use it in the `Authorization` header to xref:authentication.adoc#loginTS[log in to ThoughtSpot] and create a user session.


=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|An OAuth access token is granted
|**500**|Failed operation or unauthorized request
|===


== View session info

To get details of the session object for the currently logged-in user, send a `GET` request to the `/tspublic/rest/v2/session` endpoint.


=== Resource URL

----
GET /tspublic/rest/v2/session
----

=== Request parameters

None

=== Example request

.cURL
[source, cURL]
----
curl -X GET \
  --url 'https://<ThoughtSpot-host>/tspublic/rest/v2/session' \
  -H 'Authorization: Bearer {OAUTH_TOKEN}'\
  -H 'Content-Type: application/json'\
  -H 'Accept-Language: application/json'
----

.Request URL

----
https://<ThoughtSpot-host>/tspublic/rest/v2/session
----


=== Example response

If the API request is successful, ThoughtSpot returns the following response:

[source, JSON]
----
{
   "onboardingActivity":{
      "pinsSpotlightSeen":true,
      "pinsFlowSeen":true,
      "onboardingComplete":true,
      "worksheetTourSeen":false,
      "onboardingSeen":true,
      "autoAnswerTourSeen":false
   },
   "privileges":[
      "ADMINISTRATION",
      "AUTHORING",
      "USERDATAUPLOADING",
      "DATADOWNLOADING",
      "DATAMANAGEMENT",
      "SHAREWITHALL",
      "A3ANALYSIS",
      "DEVELOPER"
   ],
   "integerFormat":{

   },
   "userGUID":"59481331-ee53-42be-a548-bd87be6ddd4a",
   "orgPrivileges":{
      "0":[
         "ADMINISTRATION",
         "AUTHORING",
         "USERDATAUPLOADING",
         "DATADOWNLOADING",
         "DATAMANAGEMENT",
         "SHAREWITHALL",
         "A3ANALYSIS",
         "DEVELOPER"
      ]
   },
   "dateFormat":{
      "formatPattern":"MM/dd/yyyy"
   },
   "timezone":"America/Los_Angeles",
   "authToken":"G7j9RAiW7jpjMVV8Kud14u9HD7kGH/w5FSUQs7sKFSo=",
   "dataFlowPort":9000,
   "locale":"",
   "firstLoginDate":1354092845722,
   "currentOrgId":-1,
   "dataFlowHost":"10.79.129.64",
   "apiVersion":"v1",
   "canChangePassword":true,
   "dateTimeFormat":{
      "formatPattern":"MM/dd/yyyy h:mm a"
   },
   "userPreferences":{
      "savedAuthorFilter":"ALL",
      "showWalkMe":true,
      "notifyOnShare":true,
      "analystOnboardingComplete":false,
      "preferredLocale":"en-US"
   },
   "decimalFormat":{

   },
   "userProperties":{
      "persona":"business_user",
      "mail":"bong.cha@thoughtspot.com"
   },
   "isSystemUser":false,
   "userEmail":"bong.cha@thoughtspot.com",
   "configInfo":{
      "cloudExpressConfiguration":{
         "contactUrl":"https://www.thoughtspot.com"
      },
      "materializationConfig":{
         "refreshWindowStartTime":"01:00AM",
         "materializationHours":8,
         "enabled":true,
         "maxMaterializedViewsPerCluster":50
      },
      "homepagePinboardFetchBatchSize":10,
      "emailValidation":false,
      "identityServiceUrl":"https://identity.dataplane-private.aws-us-west-2.thoughtspotdev.cloud/v1",
      "enableEurekaSearchDeduplication":false,
      "maxColdStartHeadlinesPerPinboard":1,
      "enableColumnSummariesByDefault":true,
      "isAnswerV2OnByDefault":true,
      "chartGenConfiguration":{
         "maxLegendCardinality":80,
         "maxMeasuresLineColumnChart":3,
         "maxMeasuresBarChart":4
      },
      "enableCJA":false,
      "countWithNull":false,
      "queryUpdateDebounceThresholdMS":1000,
      "maxColumnLimitForLightColumns":0,
      "disableAnswer":false,
      "disableCopyLink":false,
      "embedSettingsLockedEnabled":false,
      "atlasActionObjectUGFeatureEnabled":true,
      "intercomAppId":"bvnke30h",
      "enableEurekaWorksheetDisablement":false,
      "enableBypassRLSPrivilege":true,
      "openVizUrlInSameTab":false,
      "isEverywhereEnabled":true,
      "ldapConfiguration":{
         "realms":"$adLdapRealm",
         "enforceBindingPriorToAuthentication":false,
         "bindPassword":"",
         "displayNameAttributeKey":"name",
         "emailAttributeKey":"mail",
         "enabled":true,
         "bindUsername":"",
         "updateLdapAttributes":true
      },
      "idleSenseConfig":{
         "shutdownWarningDurationMin":2,
         "enabled":false,
         "clusterIdleDurationThresholdMin":120
      },
      "swaggerSpecFilterEnabled":true,
      "nodeTelegrafConfig":{
         "resolveWaitMs":300000,
         "maxTimeoutMs":300000
      },
      "autoCompleteConfig":{
         "requestTimeout":10000
      },
      "maxUniversalSearchResults":-1,
      "useDomainQualifiedName":true,
      "customerAdminEmail":"sre@thoughtspot.com",
      "enableSageUserFeedback":false,
      "enableEurekaDebugInfo":false,
      "oidcConfiguration":{
         "updateOIDCAttributes":true,
         "displayNameAttributeKey":"name",
         "overrideSamlRedirectWithOidc":false,
         "emailAttributeKey":"email",
         "oidcGroupAttributeKey":"roles",
         "userNameKey":"sub",
         "enabled":false,
         "oidcLoginPageRedirect":false,
         "identityDomain":"",
         "updateUserGroupsFromOIDC":false,
         "callbackUri":"/callosum/v1/oidc/callback",
         "scope":"openid email",
         "forceAuthn":false,
         "oidcLoginUri":"/callosum/v1/oidc/login",
         "subjectKey":"sub",
         "logoutEnabledInUI":false
      },
      "fullEmbedConfiguration":{
         "poweredFooterHidden":false,
         "alertBarHidden":false,
         "isPinboardVizDownloadAsCSVEnabled":true,
         "pinboardCreationPrivilegeEnabled":true,
         "isPinboardVizDownloadAsPNGEnabled":true,
         "isPinboardDownloadAsPDFEnabled":true,
         "isPinboardVizDownloadAsXLSXEnabled":true,
         "isPinboardVizDownloadAsPDFEnabled":true,
         "primaryNavHidden":true,
         "profileAndHelpOptionsInNavBarHidden":false
      },
      "experimentation":{
         "growth":{
            "production":false,
            "clusterName":"grapes",
            "clusterId":"grapes",
            "devSdkKey":"AJsnywXjJsHuM5NaVskc3",
            "prodSdkKey":"8C9koGFcqNP8HNAo62p1n",
            "enabled":false
         },
         "legacyPinsFlow":{
            "production":false,
            "clusterName":"grapes",
            "clusterId":"grapes",
            "devSdkKey":"N4d428S41gxqCwf4LYq9J",
            "prodSdkKey":"Jq3bRgW6b8wyU5bVHXg1H",
            "enabled":false
         }
      },
      "walkMeConfiguration":{
         "enableWalkme":false,
         "enableTestEnvForWalkme":false
      },
      "enableDoubleClickDrillDown":false,
      "enablePendo":true,
      "schedulerServiceUrl":"https://scheduler.dataplane-private.aws-us-west-2.thoughtspotdev.cloud/v1",
      "disableFeedback":false,
      "partnerServiceConfig":{
         "fromEmail":"ThoughtSpot <trial@cloud.thoughtspot.com>"
      },
      "enableInstantSearch":false,
      "enableSnapshotCapture":false,
      "memcachedConfigInfo":{
         "memcacheExpirySec":2592000,
         "memcacheInvalidatedObjectExpirySec":30,
         "cacheFlushTimeoutMs":10000,
         "devDisableAsyncCaching":false,
         "memcachedEasyAddress":"/ea/*/memcached/memcached/memcached/0",
         "shouldUseMemcache":true,
         "cacheRequestTimeoutMs":2000,
         "maxNumHeaderRowsToCache":10000000
      },
      "selfClusterId":"grapes",
      "enableEurekaSynonymWorkflow":false,
      "isPublicUser":false,
      "autoGenConfig":{
         "relationshipGen":{
            "maxDataJoinCandidates":5,
            "minMetadataSimilarityPercent":30,
            "allowDateColumnJoins":false,
            "enableTableData":true,
            "minDomainSetCardinality":5,
            "columnNameNoKeywordWeight":92,
            "enabled":true,
            "colTypeScoreWeight":30,
            "colNameScoreWeight":50,
            "dataScoreWeight":20,
            "minDataOverlapPercent":20,
            "maxRowSample":500,
            "enableMixpanelLogging":true,
            "allowBooleanColumnJoins":false,
            "columnDataTypePenalty":2
         },
         "answerGen":{
            "enabled":true
         },
         "allTablesConnectionId":"bfc6feb4-8dac-402c-8ae8-78b43d318777",
         "worksheetGen":{
            "defaultWorksheetName":"My Worksheet",
            "enabled":true
         }
      },
      "calendars":{
         "default":{
            "weekStartDay":1,
            "quarterStartMonth":8
         }
      },
      "dataWorkspace":{
         "createSpotAppEnabled":false,
         "dbtIntEnabled":true,
         "dataAppV2Enabled":true,
         "sqlEditorEnabled":true,
         "destinationsEnabled":false,
         "salesForceEnabled":true,
         "googleSheetsEnabled":true,
         "slackEnabled":true,
         "spotAppEnabled":true,
         "enabled":true,
         "spotAppAdminEnabled":false
      },
      "defaultFilterNonCascading":false,
      "showCommunityLink":true,
      "tseScheduleFeatureEnabled":false,
      "enliteMetricsDisabled":false,
      "signUpConfiguration":{
         "signUpButtonLink":"",
         "signUpEnabled":true,
         "signUpButtonText":""
      },
      "disableSharing":false,
      "tableAggregatesEnabled":true,
      "sessionConfig":{

      },
      "enableVizDataExport":true,
      "intercomEnabled":false,
      "slackConfiguration":{
         "enabled":false
      },
      "isPinboardV2OnByDefault":false,
      "addNullFilterSuggestion":true,
      "useLegacyEmbeddedPinboardActionConfig":false,
      "exploreEnabled":true,
      "isLiveboardEnabled":true,
      "metadataMigrationEnabled":true,
      "pipelineStatusBatchTime":5,
      "analystOnboardingConfig":{
         "setupV2Enabled":true,
         "videoURL":"https://fast.wistia.net/embed/iframe/dmue1pc6fp",
         "enabled":false
      },
      "enableMapTiles":false,
      "enliteEnabled":false,
      "enableWorksheetOverAggrWorksheet":true,
      "enableLenientContentDiscoverability":false,
      "pinboardFilterConfiguratorDisabled":false,
      "vizEmbedConfiguration":{
         "poweredFooterHidden":false,
         "disableTransformations":false
      },
      "customCalendarConfig":{
         "dateFormat":"MM/dd/yyyy",
         "useCalendarTableForGregorian":false,
         "allowUniqueNamesAtDatasourceLevel":false,
         "defaultClusterCalendar":"fiscal",
         "enabled":true,
         "useCalendarTableForFiscal":false
      },
      "docHiddenInDevelopTab":true,
      "listSearchDebouncingInMS":500,
      "teamEdition":{
         "integrationsEnabled":false,
         "dataPipelineEnabled":false,
         "dbtIntegrationEnabled":false,
         "createSpotAppEnabled":false,
         "sqlEditorEnabled":false,
         "spotAppEnabled":false,
         "enabled":true,
         "spotAppAdminEnabled":false
      },
      "trialVersionConfig":{
         "trialAccountLifeDays":30,
         "trialClusterRegisterUrl":"https://www.thoughtspot.com/thoughtspot-cloud/trial",
         "maxUserLimitInGroup":50,
         "trialClusterUrl":"https://try-internal.thoughtspot.com/",
         "enableTrialVersion":false,
         "expiredAccountLifeDays":60,
         "fromEmail":"ThoughtSpot <trial@cloud.thoughtspot.com>",
         "maxResendCount":30
      },
      "embraceDependentOnFalcon":true,
      "freeTrialActivationEnabled":false,
      "sendDebugHeaders":false,
      "loginConfig":{
         "passwordConfig":{
            "passwordStrategy":"GUESS_ESTIMATE",
            "passwordHistorySize":10
         }
      },
      "dataFormatConfig":{
         "shouldFormatData":false,
         "hyperlinkColumns":[

         ],
         "shouldFormatHyperlink":false,
         "titleCasingConfig":{
            "shouldIgnoreArticles":true,
            "ignoreWords":[
               "but",
               "a",
               "a.m",
               "or",
               "in",
               "for",
               "is",
               "an",
               "onto",
               "off",
               "p.m",
               "the",
               "into",
               "a.d",
               "and",
               "b.c",
               "by",
               "of",
               "to"
            ],
            "strictTitleCasingLength":5
         }
      },
      "searchDataInNav":false,
      "tseSeekwellLicenseEnabled":true,
      "scriptabilityConfig":{
         "enabled":true
      },
      "enableAppDynamics":true,
      "enableUniversalSearchHdfsLogging":false,
      "askExpertConfig":{
         "allowListingAllExperts":true,
         "removeObjectToExpertEdges":false,
         "deprecated":true,
         "notifyOtherExpertsOnResolution":true,
         "enabled":true,
         "maxExpertCount":2
      },
      "enableUniversalSearchStalenessCheck":true,
      "blinkHelpConfigList":[
         {
            "iconFilePath":"",
            "id":"BLINK_KEYWORDS",
            "title":"Keywords",
            "enabled":true,
            "url":"{docsUrl}{versionNameForLink}/reference/keywords.html"
         },
         {
            "iconFilePath":"",
            "id":"BLINK_RELEASE_NOTES",
            "title":"Release notes",
            "enabled":true,
            "url":"{docsUrl}{versionNameForLink}/release/notes.html"
         },
         {
            "iconFilePath":"",
            "id":"BLINK_DOCUMENTATION",
            "title":"Documentation",
            "enabled":true,
            "url":"{docsUrl}{versionNameForLink}"
         },
         {
            "iconFilePath":"",
            "id":"BLINK_DOWNLOADS",
            "title":"Downloads",
            "enabled":true,
            "url":"{docsUrl}{versionNameForLink}/release/downloads.html"
         }
      ],
      "aaqEnabled":true,
      "embedActionConfigList":[
         {
            "application":"NONE",
            "name":"action-new",
            "context":"NONE",
            "userGroupList":[

            ],
            "id":"a10c51c5-7524-4dae-940d-3d842e2a55f1",
            "detail":{
               "additionalUrlHeaders":"{}",
               "encodeUser":"",
               "apiKey":"X-API-KEY",
               "apiValue":"",
               "function":"action-new",
               "authToken":"",
               "link":"www.thoughtspot.com/",
               "authSelect":"NONE",
               "appActionType":""
            },
            "availability":[
               "GLOBAL"
            ],
            "type":"URL",
            "version":"v4",
            "actionAssociationMap":{
               "ANSWER":{
                  "822ca554-c214-42f0-abfc-df5ed37d1017":{
                     "context":"MENU",
                     "enabled":"true"
                  }
               }
            }
         }
      ],
      "isSaas":false,
      "enableOrgs":false,
      "samlConfiguration":{
         "samlLoginPageRedirect":true,
         "samlGroupAttributeKey":"roles",
         "disableSessionNotOnOrAfterCheck":false,
         "updateUserGroupsFromSAML":true,
         "displayNameAttributeKey":"name",
         "orgMappingKey":"",
         "emailAttributeKey":"mail",
         "enabled":true,
         "disableMaxAuthenticationAgeCheck":false,
         "mobileAppRedirectEnabled":true,
         "groupMapping":"{}",
         "forceAuthn":true,
         "updateSamlAttributes":true,
         "logoutEnabledInUI":true
      },
      "enableSchemaViewer":false,
      "atlasActionObjectFeatureEnabled":true,
      "maxParallelQueriesPerViz":5,
      "embeddedUseCase":false,
      "identityServicePublicUrl":"https://identity.dataplane-public.thoughtspotdev.cloud/v1",
      "tseSeekwellFeatureEnabled":false,
      "a3Config":{
         "instantInsightsOnSearchPageEnabled":false,
         "a3PinboardExpiryInSeconds":86400,
         "enableCustomRInSearchPage":true,
         "enableFollowV2":true,
         "instantInsightsAnalysisDepth":0,
         "inlineAutoAnalysisEnabled":false,
         "enableMonitorV2":true,
         "restrictCustomRToAdmins":false,
         "disableObjectRequestCache":false,
         "enableKPIChartOnAttributes":true,
         "emptySearchPageInsightsEnabled":false,
         "spotIQV2Experience":true,
         "answerSpotiqSnapshotEnabled":false,
         "a3LiveDataAnalysisEnabled":true,
         "listPageMaxTimelyJobsForSorting":1000,
         "oneTimeTimelyJobsExpiryInSeconds":172800,
         "enableThresholdBasedAlerts":false,
         "pinboardInsightsTimeoutInSeconds":30,
         "relatedQueriesEnabled":false,
         "enableAnomalyExplanation":true,
         "enableNewSpotIQBinary":true,
         "enableSeasonalityDetection":true,
         "homepageInsightsFromRepoEnabled":false,
         "enableMonitorOnTse":true,
         "instantInsightsFeedbackEnabled":false,
         "homepageInsightsEnabled":false,
         "isSpotIQV2OnByDefault":true,
         "enableInsightsWriteToRepo":true,
         "maxPerUserSubscription":50,
         "executiveSummaryLevel":1,
         "enableCustomRFetchAllColumns":true,
         "enableFollowFeature":true,
         "relatedTableInsightsAnalysisDepth":0,
         "experimentalRLSCheckEnabled":false,
         "pinboardSpotiqSnapshotEnabled":false,
         "enableMonitor":false,
         "enableInsightsReadFromRepo":false,
         "enableKPIChart":true
      },
      "userFileUploadSizeLimit":52428800,
      "enableEurekaTypeaheadRecentObjects":false,
      "enableHomepageV2":false,
      "requestAccessConfiguration":{
         "dataSourceRequestAccessLevel":"VIEW",
         "sendEmailsToEditors":true,
         "objectRequestAccessLevel":"ALL"
      },
      "disableMobileDeeplink":false,
      "licenseEnforcementDisabled":true,
      "tableJoinV2Enabled":true,
      "enableLearningMode":true,
      "enableSearchAssist":true,
      "useSubGroupInRLS":true,
      "dataPipelineConfig":{
         "threadPoolSize":31,
         "bufferLength":102000,
         "disableHTTPS":false,
         "useConfidentVaultForSeekwellURL":true,
         "chunkLength":1024,
         "seekwellURL":""
      },
      "enableUniversalSearch":false,
      "enlitePrivileged":false,
      "slackBotConfiguration":{
         "tablePrintDataBatchSize":20
      },
      "autoFormatColumnNames":true,
      "constantTimeReference":0,
      "teams":{
         "hardDelete":true,
         "teamMembershipLimit":100,
         "enabled":false,
         "expiredAccountLifeDays":60
      },
      "onboardingConfiguration":{
         "maxQueryLogs":10,
         "cloudBusinessOnboardingEnabled":false,
         "queryHistoryEnabled":false,
         "onboardingVideoURL":"https://fast.wistia.net/embed/iframe/wykwdrk2em",
         "defaultGroups":[
            "Demo Retail Group"
         ],
         "maxNumDefaultPinboard":3,
         "enabled":true
      },
      "scheduledReportingConfig":{
         "mailTrackingEnabled":true,
         "validateWhitelistedDomains":true,
         "thresholdSizeInMbToZip":25,
         "tablePrintDataBatchSize":100,
         "whitelistedDomains":[
            "thoughtspot.com",
            "pactera.com",
            "thoughtspot.int",
            "rizepoint.com"
         ],
         "maxTotalAttachmentSizeInMb":25,
         "mailTrackingEventName":"scheduled_report_tracking",
         "enabled":true,
         "maxRecipientLimit":1000,
         "showWhitelistedDomains":true
      },
      "maxCSVFileUploadCount":-1,
      "isMultipleDemoDataSetsEnabled":false,
      "customBrandingFontCustomizationEnabled":true,
      "universalSearchMaxLogQueueLength":1000,
      "maxColdStartSizePriorityList":3,
      "exportServiceConfig":{
         "exportServiceEnabled":true,
         "resolveWaitMs":300000,
         "maxTimeoutMs":300000
      },
      "exportConfig":{
         "keepPageHeadersOnlyOnFirstPageInPdf":true,
         "disableTSBrandingInPDF":false,
         "fileNameMaxCharacterLimit":100,
         "applyNumberFormattingInExcel":true,
         "applyColumnFormattingInExcel":true,
         "csvFormatVersion":"V2",
         "applyConditionalFormattingInExcel":true,
         "clipFiltersInPdf":true,
         "addBOMToCSV":false,
         "exportDateAsStringInXLS":false,
         "writeRowDataFromNewPageInPdf":false,
         "useNotoSansCJKFontInPDF":false
      },
      "enableEurekaSearch":false,
      "adminPrivilegeSegregation":false,
      "userPersonaConfiguration":{
         "dataManagementCheckEnabled":true
      },
      "installedSchemaVersion":"2.1.1",
      "isNebulaDevEnabled":false,
      "enableNotificationOnShare":true,
      "debugConfiguration":{
         "sendDebugInfoToUI":false
      },
      "askExpertEnabled":true,
      "useGetEncoding":false,
      "dataManagerServiceConfig":{
         "sageQueryTimeoutMs":600000,
         "isEnabled":true,
         "queryPriority":{
            "embraceStatsQuery":100,
            "sampleDataQuery":11000,
            "autogenSampleDataQuery":11,
            "queryHistoryQuery":12000,
            "sageDataIndexingQuery":1000,
            "callosumReportBookQuery":10
         }
      },
      "answerV2Experience":true,
      "embedUrls":{
         "UNSUBSCRIBE_URL":"https://wine-grapes.corp.thoughtspot.com:443/#/user-preference",
         "ANSWER_URL":"https://wine-grapes.corp.thoughtspot.com:443/#/saved-answer/{object-id}?{ts-query-params}",
         "PINBOARD_URL":"https://wine-grapes.corp.thoughtspot.com:443/#/pinboard/{object-id}?{ts-query-params}",
         "INSIGHT_URL":"https://wine-grapes.corp.thoughtspot.com:443/#/insight/{object-id}",
         "PINBOARD_VIZ_URL":"https://wine-grapes.corp.thoughtspot.com:443/#/pinboard/{object-id}/{sub-object-id}?{ts-query-params}"
      },
      "socialProof":true,
      "enableNPSMetrics":false,
      "blinkAjaxGzipConfig":{
         "gzipBlacklistMode":false,
         "gzipPathPrefixes":[
            "/callosum/v1/systest",
            "/callosum/v1/metadata/pinboard/save"
         ],
         "gzipAll":false,
         "enableRequestGzip":true
      },
      "licenseEnabled":false,
      "maxConcurrentDataCalls":-1,
      "emailConfig":{
         "companyName":"Your Company",
         "thoughtspotLogoUrl":"https://storage.pardot.com/710713/5660/TS_logo_260x68.png",
         "welcomeEmailConfig":{
            "supportEmail":"",
            "customMessage":"",
            "learnMoreLink":"",
            "getStartedLink":"https://wine-grapes.corp.thoughtspot.com/",
            "enabled":true,
            "addMixpanelTokens":true,
            "fromEmail":"TS Admin <no-reply@customer.thoughtspot.com>"
         },
         "productName":"ThoughtSpot",
         "fromEmail":"no-reply@notification.thoughtspot.com"
      },
      "vizRenderingQueueTimeoutMS":30000,
      "adminPortalEnabled":false,
      "allowEDocWriteToDatabase":true,
      "licenseConfig":{
         "contactEmail":"express@thoughtspot.com",
         "contactUrl":"https://www.thoughtspot.com"
      },
      "blockNonEmbedFullAppAccess":false,
      "updateEmbedActionInZK":true,
      "sharingConfiguration":{
         "enableVizSharing":true,
         "enableVizSharingWithLink":true,
         "enableDataSourceSharing":true
      },
      "tseSeekwellGoogleSheetsFeatureEnabled":false,
      "notificationConfig":{
         "groupMemberShareNotificationLimit":500,
         "asyncShareEmailServiceThreadCount":10,
         "accessRequestEmailThreadCount":5
      },
      "blinkActionConfigList":[
         {
            "dialogSize":"medium",
            "id":"1620742783729",
            "title":"Test-receive",
            "url":"http://10.82.144.126:8081/receive"
         }
      ],
      "edocRLSSupported":true,
      "enablePendoHelp":true,
      "maxPinboardTableDataBatchSize":0,
      "isAnswerUndoStackEnabled":true,
      "objectsLimitConfig":{
         "maxPinboards":100,
         "maxAnswers":400,
         "enableMaxObjectsLimit":false
      },
      "blinkConfig":"{\"walkmeConfiguration\":{\"enableWalkme\":true,\"enableTestEnvForWalkme\":false}}",
      "customBrandingEnabled":true,
      "firstPinExperienceEnabled":true,
      "documentationConfig":{
         "communityUrl":"https://community.thoughtspot.com/",
         "learningCenterUrl":"https://training.thoughtspot.com/",
         "onlineDocUrl":"https://docs.thoughtspot.com/software/",
         "performFirstSearchDocUrl":"https://thoughtspot.wistia.com/medias/uf5h6du15r/",
         "snowflakeConnectionDocUrl":"https://thoughtspot.wistia.com/medias/ladjhdc2na/"
      },
      "publicUserName":"demouser",
      "inviteModalType":"DEFAULT",
      "isFilterAwareQueryHash":false,
      "exploreMeasureFiltersEnabled":false,
      "hideDataTabOnNoManageDataPermission":false,
      "enableEurekaAdvancedTypeahead":true,
      "disableAnswerDisplayModePreference":false,
      "learnConfig":{
         "learnPinboardId":"2ff57a24-cf90-485f-8b4b-45fc17474c6f"
      },
      "disableStatsDbFalconNotification":true,
      "clusterType":"PROD",
      "fetchPivotSummaryFromBackend":true,
      "enableAggrWsTableJoin":true,
      "enableFullStory":false,
      "maxNumSearchIQPreferredColumnsAllowed":15,
      "tseClientId":"LOCAL",
      "enableSnapshotCaptureForAnswerV2":true,
      "highCardinalityMaxDataSize":20000,
      "geoMapConfig":{
         "dataBatchSize":5000
      },
      "tseSeekwellSFDCFeatureEnabled":false,
      "embraceConfig":{
         "falconRpcTimeOutInMS":3600000,
         "isAwsSecretsManagerEnabled":false,
         "fetchTableData":true,
         "disableSpotIQQueries":false,
         "enabled":true,
         "startTimeGetJobsInSeconds":864000,
         "doIndexing":true,
         "mode":"PRE_RELEASE",
         "timeZoneOverride":"",
         "enableNotificationOnSyncFailures":true,
         "syncDeadlineInSeconds":14400,
         "offsetOneTimeSync":5000000,
         "ignoreCaseCollation":false,
         "databaseMode":"MIXED",
         "showEmbraceStats":true,
         "disableQuestionAnswerHeadlineQueries":false,
         "isCaseSensitive":true,
         "databasesWithExtOauthEnabled":[
            "RDBMS_SNOWFLAKE"
         ],
         "jobRunStatusPollIntervalInSeconds":15,
         "enableCustomCalDatabaseList":[
            "RDBMS_GCP_BIGQUERY",
            "RDBMS_SNOWFLAKE",
            "RDBMS_REDSHIFT",
            "RDBMS_TERADATA",
            "RDBMS_ORACLE_ADW",
            "RDBMS_SAP_HANA",
            "RDBMS_AZURE_SQL_DATAWAREHOUSE",
            "RDBMS_DATABRICKS"
         ],
         "isConfidantVaultEnabled":false,
         "databasesWithOauthEnabled":[
            "RDBMS_SNOWFLAKE",
            "RDBMS_REDSHIFT",
            "RDBMS_AZURE_SQL_DATAWAREHOUSE",
            "RDBMS_DREMIO",
            "RDBMS_DATABRICKS"
         ],
         "timeToWaitForMetadataIndexingInSec":60,
         "excludedDataSources":[

         ],
         "enableCurrentDateToLiteral":false,
         "isSyncEnabled":false,
         "nullsLastInDesc":true,
         "connectionConfig":{
            "RDBMS_GCP_BIGQUERY":{
               "connectionProperties":{
                  "TIMEOUT":"600"
               }
            },
            "RDBMS_SNOWFLAKE":{
               "connectionProperties":{
                  "ABORT_DETACHED_QUERY":"true",
                  "CLIENT_RESULT_CHUNK_SIZE":"48",
                  "QUOTED_IDENTIFIERS_IGNORE_CASE":"FALSE",
                  "CLIENT_MEMORY_LIMIT":"500"
               }
            }
         },
         "calendarLimitConfig":{

         },
         "nullsLastInAsc":true,
         "dataEventLog":{
            "logPath":"data/external_query_event.bin",
            "rolloverMaxAgeSeconds":30,
            "rolloverMaxSizeBytes":104857600,
            "enabled":true
         },
         "sourceToggleEnabled":false
      },
      "disableWorksheetSampleValues":true,
      "eurekaSearchBarInNav":false,
      "maxNumSearchIQPreferredDateColumnsAllowed":1,
      "selfClusterName":"Wine",
      "enablePinboardFollow":true,
      "showUnsecuredDependents":true,
      "tsePostgresEnabled":true,
      "callosumSaaSTest":1,
      "maxPrincipalObjectsBatchSize":30,
      "maxFilterValues":10000,
      "optimizelyDataFileFetchInterval":300000,
      "demoDataConfiguration":{
         "demoPinboardGuids":[
            "d084c256-e284-4fc4-b80c-111cb606449a"
         ],
         "demoConnectionGuids":[
            "2aa36dbd-dda6-4497-a6db-bc47e128862e"
         ],
         "demoWorksheetGuids":[
            "cd252e5c-b552-49a8-821d-3eadaa049cca"
         ],
         "demoTableGuids":[
            "a633dccd-b449-46df-a0fc-92034d6858cb",
            "7d174ef2-2482-4e61-9d6e-1e1d709d96b0",
            "757f2434-66ef-43ad-9820-ba9008072155"
         ],
         "demoGroupGuids":[
            "fb61e25d-5db0-4c18-8e97-9468459f5ac1"
         ]
      },
      "pinboardV2Experience":false,
      "mixpanelConfig":{
         "production":false,
         "apiHost":"https://mixpanel.proxy.thoughtspot.cloud",
         "clusterName":"grapes",
         "clusterId":"grapes",
         "devSdkKey":"f14b3a7f47b202a3ca8e03397df2ff48",
         "prodSdkKey":"bbd66bca010bd4bb2cb3bed77fa6db02",
         "apiHostEnabled":true,
         "enabled":false
      },
      "showNeedHelp":true,
      "tseLicenseConfig":{
         "freeTrialStartDate":1641530251363,
         "freeTrialExpired":true,
         "freeTrialEnabled":true
      },
      "allowPartialPinboardEDocImport":false,
      "apiPlaygroundConfig":{
         "enabled":true
      },
      "schedulerKafkaBroker":"b-1.dataplane-msk.6zbdso.c10.kafka.us-west-2.amazonaws.com:9092,b-2.dataplane-msk.6zbdso.c10.kafka.us-west-2.amazonaws.com:9092,b-3.dataplane-msk.6zbdso.c10.kafka.us-west-2.amazonaws.com:9092",
      "useQueryHashForWorkerSelection":true,
      "informaticaCloudConfig":{
         "useTimelyForScheduling":true,
         "enabled":false,
         "expressionAssistantUrl":"https://docs.thoughtspot.com/expressions-asst.html"
      },
      "defaultChartDataSize":5000,
      "activeConnectionThreshold":500,
      "useCustomEmbedUrls":false,
      "isUpgradeModeEnabled":false,
      "showUnderlyingDataForChasmTrap":true,
      "disallowPrivilegeAddition":[

      ],
      "prodClusterIdRegex":"^([0-9]{4}X[0-9]*)$|^([a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{5})$",
      "showLoginWithUserEmail":false
   },
   "state":"ACTIVE",
   "allUserGroupDisplayName":"All Group",
   "isFirstLogin":false,
   "allUserGroupId":"b25ee394-9d13-49e3-9385-cd97f5b253b4",
   "userCreatedTime":1354006445722,
   "releaseVersion":"8.4.0.sw-53",
   "preferenceProto":"Cg4KCAgBEAAYASAAGAAoAA==",
   "userGroupMask":6,
   "userDisplayName":"Administrator",
   "userExpirationTime":-1,
   "userName":"tsadmin",
   "license":"EAA",
   "allUserGroupMemberUserCount":1175,
   "acceptLanguage":"application/json",
   "logicalModelVersion":1040203,
   "partialJSessionGUID":"55d251ce-4d7c-4d",
   "expirationTime":1652887519,
   "timeFormat":{
      "formatPattern":"HH:mm:ss"
   },
   "accessibleOrgs":[
      "0"
   ],
   "clientState":{
      "preferences":{
         "answer-display-mode-preference-key":"TABLE-MODE",
         "PANEL_STATE":"EXPANDED",
         "PINBOARD_V2":false,
         "delayedSearchTip":true,
         "SAGE_SEARCH_BUTTON_TOUR_SEEN":true,
         "homePinboardId":"b2d68a4f-cf67-4723-966f-8a592fdbf8b9",
         "SUPPRESS_IN_USE_SOURCE_REMOVAL_WARNING":true,
         "ANSWER_V2":true,
         "sageDataSource":[
            "375d11ae-9c8f-43dc-a758-6be332d3facc",
            "406da2d5-9f81-46c2-9a62-bebf7b495ded"
         ],
         "SEARCH_MODE":"CLASSIC",
         "SPOT_IQ_V2":true,
         "LEARNING_MODE_TOGGLE_SEEN":true,
         "OPEN_ANSWER_EDIT_PANEL":"INFO_CARD",
         "LEARNING_MODE":false
      },
      "a3Preferences":{
         "SHOULD_HIDE_SPLASH_SCREEN_KEY":true,
         "SHOULD_HIDE_COLUMNS_TAB_INFO_KEY":true,
         "SHOULD_HIDE_ADVANCED_TAB_INFO_KEY":true
      },
      "tips":{
         "navBarHelpTip":true,
         "chartConfigChipTip":true,
         "learnLinkSeen":true,
         "favoriteCardTip":true,
         "activityCard":true,
         "recentlyViewedCard":true,
         "enliteToggleToSearchIQTip":true,
         "enliteNavPopover":true,
         "communityLinkSeen":true,
         "trendingCard":true,
         "enliteSearchPopover":true,
         "followCardTip":true
      }
   },
   "userType":"LOCAL_USER",
   "homePinboardGuid":"4e555cec-163c-4a4f-a11a-7be3c103f5b6"
}
----

=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful retrieval of session information
|**500**|Failed operation or an unauthorized request
|===

== Log out of a session

To log out of the current session, send a `POST` request to the `/tspublic/rest/v2/session/logout` endpoint.


=== Resource URL
----
POST /tspublic/rest/v2/session/logout
----

=== Example request

.cURL
[source, cURL]
----
curl -X POST \
  --url 'https://<ThoughtSpot-host>/tspublic/rest/v2/session/logout' \
  -H 'Content-Type: application/json'\
  -H 'Accept-Language: application/json'
----

.Request URL
----
https://<ThoughtSpot-host>/tspublic/rest/v2/session/logout
----

////
If the logout request is sent as an AJAX call, add the following parameter to send credentials with the request:

----
xhrFields: { withCredentials: true }
----
////

=== Session response

If the API request is successful, the currently logged-in user is signed out of ThoughtSpot.

=== Response codes

[options="header", cols="2,4"]
|===
|HTTP status code|Description
|**200**|The user is logged out of ThoughtSpot
|**500**|Logout failure/unauthorized request
|===
