== Authentication
:toc: true

:page-title: Authentication
:page-pageid: authentication
:page-description: Authentication


You can control which type of authentication you use between your client application and ThoughtSpot.

=== No Authentication

You can simply not set up authentication.
This would require the user to be _already logged into ThoughtSpot_, before interacting with the client application.
This approach is for testing the client.
Do not use this in a production environment.

=== SAML SSO

To avoid showing the ThoughtSpot login page in the iFrame and provide a seamless login experience, you should configure SSO so that your users are automatically authenticated to ThoughtSpot, and the pages are loaded immediately.

Before you can embed all or part of ThoughtSpot, you must authenticate to ThoughtSpot using SAML with the public REST API call.

////
For more information, see  https://cloud-docs.thoughtspot.com/admin/ts-cloud/authentication-integration.html[Managing authentication with SAML].
Note that this does not assign the user to any groups, which must be managed manually or via the APIs.

After authentication, a URL is provided to call the desired visualization, and populate it into an `<iframe>` element.

You must link:{{ site.baseurl}}/admin/setup/configure-SAML-with-tscli.html[configure SAML] on your ThoughtSpot instance before using this method.

////

=== Trusted authentication service

A ThoughtSpot installation can enable support for token-based authentication service.
This allows an installation to use a central authentication service rather than using ThoughtSpot to authenticate.
In this architecture, ThoughtSpot provides the service with a token that allows it to authenticate on behalf of users.

A trusted authenticator application or service obtains a token from ThoughtSpot.
This token is used to obtain trust from other third-party client applications that need access to ThoughtSpot.
In the following scenario, the trust authenticator forwards requests for ThoughtSpot data from client applications to ThoughtSpot.

==== Enable Trusted Authentication

If you are using Trusted Authentication, enable this capability from the command line:
[source,console]
----
$ tscli tokenauthentication enable
----
This command turns on trusted authentication and returns something like the following:
[source,console]
----
Token generated. Copy the GUID in the box.

 ########################################
 # b0cb26a0-351e-40b4-9e42-00fa2265d50c #
 ########################################

 Override added successfully
----

The key inside the hashes is the ThoughtSpot secret key.  This key is needed to make calls to get a token for an individual user.  

To disable trusted authentication, run the following command at the command line:

[source,console]
----

 $ tscli tokenauthentication disable

----

This command disables token authentication and the secret token.

For more information, see
https://docs.thoughtspot.com/6.3/app-integrate/embedding-viz/trusted-authentication.html[Configure trusted authentication].
////
==== Trusted Authentication Workflow

. The user will log into the web application using the customer provided authentication capabilities.  
. The trusted authentication service  calls the ThoughtSpot service to log in, using a service account that has admin privileges. This step creates a session for the next call. 
. After establishing a session, the token service will make calls to ThoughtSpot to get a token for the user using the +session/login/token +service.  
. On success,  the token service returns a unique token for future calls on behalf of the user.
The user is now authenticated, though the calls take a special format as described below.



A user who is already logged into client-application interacts with a ThoughtSpot embed point, which initiates the following processes:

. The client-side application requests a user token from the trusted authenticator.
. The trusted authenticator requests a user token from ThoughtSpot.
. ThoughtSpot verifies the authenticator and returns a user token.
. The authenticator returns the user token to the client.
. The client forwards the user token to ThoughtSpot.
. ThoughtSpot validates the token and returns information commensurate with that authenticated user's authorization.

== Cross-origin HTTP Requests (CORS)

Collecting user credentials from one application (domain) and sending them to another application (such as ThoughtSpot) can present security vulnerabilities.
Cross-origin or cross-domain verification prevents such security risks.

When embedding, you must enable CORS between your client application domain and the ThoughtSpot domain.
This protects your data, so that another actor cannot use the same URL to embed the visualization in its own Web pages.


== Decide if you need to change the feedback email

ThoughtSpot has an automated feature that collects feedback from users and sends it to ThoughtSpot Support.
Depending on what and how you embed, user actions with your embedded application can trigger feedback.
You can continue to forward feedback in this manner or direct the feedback to another email.
To learn how to change the feedback email, see link:{{site.baseurl }}/admin/setup/work-with-ts-support.html#manage-the-feedback-contact[Manage the feedback contact].

== Remove the ThoughtSpot branded footer

The ThoughtSpot footer appears by default in the ThoughtSpot application.
It also appears with an embed application that encompasses an individual Pinboard, or a full application.
In embed applications that are have a single visualization, you can ask your ThoughtSpot support engineer to disable the footer.


To embed with the navigation bar, call: +https://<thoughtspot-url>?embedApp=false#/+ +
To embed without the navigation bar, call: +https://<thoughtspot-url>?embedApp=true#/+ 

If you use +embedApp=true+ with this link, you will get the home page with no navigation bar, so you will need to provide navigation to use ThoughtSpot.  


////
