= Browser settings for embedding
:toc: true

:page-title: Browser settings
:page-pageid: browser-settings
:page-description: Browser settings for embedding

ThoughtSpot supports rendering embedded content in the following web browsers: 

* Google Chrome
* Microsoft Edge
* Mozilla Firefox
* Opera
* Safari

== Embedded content and browser cookies

As a security measure, most browsers allow cookies only when they originate from the same domain name as the main application URL. Some browsers like Safari and Firefox block cookies from third-party content provider sites by default. 

To avoid this issue, you might want to host your embedded ThoughtSpot instance in the same domain as its parent application. To customize the ThoughtSpot domain URL for your instance, contact ThoughtSpot Support.  

////
If you do not want to customize your domain, you may need to enable third-party cookies and cross-site tracking on your browser:

 * On Safari, go to *Preferences* > *Privacy* and clear the *Prevent cross-site tracking* checkbox. 
 * On Firefox, go to *Preferences* > *Privacy & Security* > *Enhanced Tracking Protection* and allow cross-site cookies.
 
If the embedded content is not rendered despite these configuration changes, contact ThoughtSpot Support. 
////

=== Same-Site cookie behavior on Google Chrome

Google Chrome 80 or later versions use the `SameSite` cookie attribute to disable the use of third-party content.  
For third-party application integrations that rely on cookies, the SameSite cookie attribute must be set to `None`. This setting is enabled by default on ThoughtSpot cloud instances.
 