= Browser settings for embedding
:toc: true

:page-title: Browser settings
:page-pageid: browser-settings
:page-description: Browser settings for embedding

ThoughtSpot supports rendering embedded content in the following web browsers: 

* Google Chrome
* Microsoft Edge
* Mozilla Firefox
* Opera
* Safari

== Same-Site cookie behavior

Google Chrome 80 or later versions use the `SameSite` cookie attribute to disable the use of third-party content.  

For third-party application integrations that rely on cookies, the SameSite cookie attribute must be to `None`. This setting is enabled by default on ThoughtSpot cloud instances.

== Embedded content rendition 

Some browsers like Safari and Firefox block cookies from third-party content provider sites by default. If the embedded ThoughtSpot content is blocked on these browsers, do the following: 

. Check if the domain URL of your ThoughtSpot instance is the same as its parent application. To customize the ThoughtSpot domain URL for your instance, contact ThoughtSpot Support.  
. Enable third-party cookies and cross-site tracking on your browser:

 * On Safari, go to *Preferences* > *Privacy* and clear the *Prevent cross-site tracking* checkbox. 
 * On Firefox, go to *Preferences* > *Privacy & Security* > *Enhanced Tracking Protection* and allow cross-site cookies.
+ 
. Reload your application.
  