= Access control and data security
:toc: true
:toclevels: 2

:page-title: User access to embedded objects
:page-pageid: embed-object-access
:page-description: You can define user access to view or edit embedded objects and related workflows.

ThoughtSpot supports the following features to control user access to ThoughtSpot objects and application data.

* User groups with system privileges
* Sharing visibility 
* Object-level permissions
* Row-level security (RLS) and column-level security (CLS) for data security
* Granular access to buttons and menu actions in the embedded app (applicable to embedded ThoughtSpot instances)

== User groups and system privileges

Along with user authentication for application access, ThoughtSpot provides an additional layer of authorization and access control through user groups and system privileges. 

System privileges determine the workflows and actions that users can perform within the ThoughtSpot application context. 

ThoughtSpot allows you to define several types of privileges for a given user group:

* Role-specific privileges for administrators, developers, and other user personas.
* Data-related privileges to allow or prevent access to upload, download, or manage data.
* Workflow-specific privileges to enable or disable access to features such as SpotIQ analysis, scheduling Liveboards, or the experimental features available for evaluation and early adoption.
* Sharing privilege to control a user's or group's visibility in the *Share* dialog. 

For more information about system privileges, see  link:https://cloud-docs.thoughtspot.com/admin/users-groups/about-users-groups.html[Understand groups and privileges, window=_blank].

== Sharing visibility

The Sharing visibility configuration allows users and groups to be set as *SHARABLE* or *NOT SHARABLE*.

For example, if _UserA_ is marked as *SHARABLE*, other users can view _UserA_ in the *Share* dialog when they try to share an object.

Similarly, if a user group is set as *NOT SHARABLE*, it does not appear in the *Share* dialog when a user tries to share an object.

[NOTE]
====
Avoid using the same group for sharing permissions and other privileges. Because a user can share with anyone in a group they belong to, they can potentially share restricted data.
====

== Object-level permissions

ThoughtSpot users can share objects such as Liveboards, answers, tables, worksheets, and table columns. Users can set either `read-only` or `edit` permissions at the individual object level when sharing an object with another user or a user group. A user can automatically share objects with anyone else in the groups to which they belong.

When an object is shared, users can view all the data regardless of the permissions set at the parent object level. For example, a user can view a shared Liveboard without having access to its underlying worksheet or table from which the visualizations in the Liveboard are built.

[NOTE]
====
If your application instance has classic Answer Experience enabled, administrators can restrict user access to Liveboards by selecting the *Cannot create or update Liveboards*  checkbox in the admin UI. Note that this feature is deprecated on clusters on which the New Answer Experience is enabled. ThoughtSpot recommends that you use the `disabledActions` and `hiddenActions` parameters in the Visual Embed SDK to define granular access. For more information, see xref:embed-actions.adoc[Show or hide actions].
====

== Data access control with RLS and CLS

When a user shares an object with a user group, all users in that group can view data. You can override this behavior by applying RLS and CLS controls. 

Row-level Security::
RLS defines which groups or users can access the rows of a table. Administrators and owners can define rules on table rows to allow or prevent access to data based on group membership or user authentication. With RLS, even if a user has access to a worksheet, they can only view the rows to which they have access. 
Using RLS, you can restrict access to sensitive data and filter tables to show only relevant data. RLS controls are applied at the table level, so it automatically extends to all worksheets, saved answers, and Liveboards based on that table, every time.

+
For more information, see link:https://cloud-docs.thoughtspot.com/admin/data-security/about-row-security.html[Row Level Security, window=_blank].

+
A comprehensive examples and best practices guide is available on the link:https://community.thoughtspot.com/customers/s/article/How-to-secure-your-data-in-ThoughtSpot[ThoughtSpot Community, window=_blank].
 
Column-level security::

CLS restricts user access to specific columns of a table. When CLS is applied, users see only the columns that they are allowed to view. Object owners can configure CLS by sharing a relevant set of columns in a table with a specific user or user group. 

+
For more information, see link:https://cloud-docs.thoughtspot.com/admin/data-security/share-source-tables.html[Sharing tables and columns, window=_blank].

== Granular access to menu actions

If you are using Visual Embed SDK to embed ThoughtSpot objects and you want to restrict user access to certain menu actions, you can use the `visibleActions`, `disabledActions` or `hiddenActions` attributes. For more information, see xref:embed-actions.adoc[Show or hide UI actions].
