= Access control and data security
:toc: true
:toclevels: 2

:page-title: User access to embedded objects
:page-pageid: embed-object-access
:page-description: You can define user access to view or edit embedded objects and related workflows.

ThoughtSpot supports the following features to control user access to ThoughtSpot objects and application data.

* User groups with system privileges
* Sharing visibility 
* Object-level permissions
* Row-level security (RLS) and column-level security (CLS) for data security
* Visual Embed SDK for granular access (applicable to ThoughtSpot embedded instances)

== User groups and system privileges

Along with user authentication for application access, ThoughtSpot provides an additional layer of authorization and access control through user groups and system privileges. 

System privileges determine the workflows and actions that users can perform within the ThoughtSpot application context. 

ThoughtSpot allows you to define several types of privileges for a given user group:

* Role-specific privileges for administrators, developers, and other user personas.
* Data-related privileges to allow or prevent access to upload, download, or manage data.
* Workflow-specific privileges to enable or disable access to features such as SpotIQ analysis, scheduling pinboards, or the experimental features available for evaluation and early adoption.
* Sharing privilege to control a user's or group's visibility in the *Share* dialog. 

For more information about system privileges, see  link:https://cloud-docs.thoughtspot.com/admin/users-groups/about-users-groups.html[Understand groups and privileges, window=_blank].

== Sharing visibility

The Sharing visibility configuration allows users and groups to be set as *SHAREABLE* or *NOT SHAREABLE*. 

For example, if _UserA_ is marked as *SHAREABLE*, other users can view _UserA_ in the *Share* dialog when they try to share an object. 

Similarly, if a user group is set as *NOT SHAREABLE*, it does not appear in the *Share* dialog when a user tries to share an object.

[NOTE]
====
Avoid using the same group for sharing permissions and other privileges. Because a user can share with anyone in a group they belong to, they can potentially share restricted data.
====

== Object-level permissions

ThoughtSpot users can share objects such as pinboards, answers, tables, worksheets, and table columns. Users can set either `read-only` or `edit` permissions at the individual object level when sharing an object with another user or a user group. A user can automatically share objects with anyone else in the groups to which they belong. 

When an object is shared, users can view all the data regardless of the permissions set at the parent object level. For example, a user can view a shared pinboard without having access to its underlying worksheet or table from which the visualizations in the pinboard are built. 

[NOTE]
====
If your application instance has classic Answer Experience enabled, administrators can restrict user access to pinboards by selecting the *Cannot create or update Pinboards*  checkbox in the admin UI. Note that this feature is deprecated on clusters on which the New Answer Experience is enabled. ThoughtSpot recommends that you use the `disableActions` and `hideActions` parameters in the Visual Embed SDK to define granular access. For more information, see xref:embed-actions.adoc[Disable or hide menu actions].
====

== Data access control with RLS and CLS

When a user shares an object with a user group, all users in that group can view data. You can override this behavior by applying RLS and CLS controls. 

Row-level Security::
RLS defines which groups or users can access the rows of a table. Administrators and owners can define rules on table rows to allow or prevent access to data based on group membership or user authentication. With RLS, even if a user has access to a worksheet, they can only view the rows to which they have access. 
Using RLS, you can restrict access to sensitive data and filter tables to show only relevant data. RLS controls are applied at the table level, so it automatically extends to all worksheets, saved answers, and pinboards based on that table, every time. 

+
For more information, see link:https://cloud-docs.thoughtspot.com/admin/data-security/about-row-security.html[Row Level Security, window=_blank].

+
A comprehensive examples and best practices guide is available on the link:https://community.thoughtspot.com/s/article/How-to-secure-your-data-in-ThoughtSpot-Examples-and-Best-Practices[ThoughtSpot Community, window=_blank].
 
Column-level security::

CLS restricts user access to specific columns of a table. When CLS is applied, users see only the columns that they are allowed to view. Object owners can configure CLS by sharing a relevant set of columns in a table with a specific user or user group. 

+
For more information, see link:https://cloud-docs.thoughtspot.com/admin/data-security/share-source-tables.html[Sharing tables and columns, window=_blank].

== Granular access to menu actions

If you are using Visual Embed SDK to embed ThoughtSpot objects and you want to restrict user access to certain menu actions, you can use the `disableActions` and `hideActions` parameters. 

For more information on disabling or hiding an action, see xref:embed-actions.adoc[Disable or hide menu actions].

== Sync authorization from other systems
SSO in ThoughtSpot is mostly concerned with determining who the user is (authentication). To set what a user can see and do (authorization), you will need to set the various features listed above. While an administrator can set all of these values within the ThoughtSpot UI or through direct REST API commands, you may want or need to sync authorization settings automatically from other systems within your environment. 

There are three general ways to configure syncing with external systems:

- Schedule batch sync processes to ThoughtSpot 
- Integrate ThoughtSpot sync commands into existing system processes
- Send ThoughtSpot sync commands when user session is created (SSO)

=== Authentication and authorization when user session is created
If using xref:configure-saml.adoc[SAML] for SSO, ThoughtSpot can create users automatically from the SAML assertion, and add the user to existing ThoughtSpot groups. 

When using xref:trusted-authentication.adoc[trusted authentication], the authenticator service will use a service account with server administrator privileges. The service account can send the REST API commands to xref:user-api.adoc#create-user[create the user] and xref:group-api.adoc#add-user-to-group[add them to the appropriate groups] prior to requesting the login token.

=== REST API commands to set authorization 
Additional REST API commands can be sent to ThoughtSpot to set all of the other authorization properties beyond group membership. These commands are relevant regardless of whether you are building a scheduled sync process or setting the values when creating a user session.

==== Manage groups
Groups have several uses within ThoughtSpot. The REST API can xref:group-api.adoc#create-group[create] and xref:group-api.adoc#delete-group[delete] groups for any of these purposes. 

Row-level security (RLS) rules place the group name (not the display name) directly within SQL queries. To give a user a particular value within an RLS rule, you create a group whose name matches a value within the database, then assign the user to that group. 

User privileges are inherited from all the groups they belong to which have privileges assigned (not all groups have privileges). Privileges can be set on groups through the xref:group-api.adoc#create-group[create] and xref:group-api.adoc#update-group[update group] APIs, or modified individually using the xref:group-api.adoc#add-privilege[add privilege to group] and xref:group-api.adoc#remove-privilege[remove privilege from group] endpoints.  
 
==== Manage users within groups 
Users must belong to groups to inherit the authentication aspects assigned to those groups. REST APIs exist to individually xref:group-api.adoc#add-user-to-group[add a user to group] and xref:group-api.adoc#delete-user-assoc[remove a user from a group] or to do a bulk xref:group-api.adoc#addMembers[add] or xref:group-api.adoc#removeMembers[remove] of multiple users to and from multiple groups in one API call. 

==== Share content to groups and users 
Access to objects is granted as sharing rights on the object to groups and users. The single REST API endpoint for xref:pageid=security-api.adoc#share-object[sharing an object] allows for sharing to users and groups, and can also remove sharing rights from an object. 
