= SAML SSO Authentication
:toc: true

:page-title: SAML SSO Authentication
:page-pageid: saml-sso
:page-description: SAML SSO Configuration

The Security Assertion Markup Language (SAML) Single Sign-On (SSO) authentication method enables client applications to allow federated users to access the embedded content. The SAML SSO authentication method eliminates the need for displaying a login page when a user requests access to the embedded visualizations or pinboards.
In the SAML SSO authentication method, users authenticate to the SAML identity provider at your federation to obtain access to the ThoughtSpot content embedded in your application.

To allow ThoughtSpot to trust login requests from your corporate authentication servers, you must configure SAML settings in the ThoughtSpot application.

[#admin-portal]
== Enable SAML authentication
You need admin privileges to enable SAML SSO authentication.

. Configure the ThoughtSpot application instance on your IDP server.
. Log in to your ThoughtSpot application instance.
. From the top navigation bar, click the **Admin** tab.
. Click *SAML*.
. Click *Configure*.
. Configure the following attributes:

ThoughtSpot Service Address::
A fully qualified and resolvable domain name for the ThoughtSpot service. For example, *thoughtspot.thoughtspot-customer.com*.
Port::
Port of the server where your ThoughtSpot instance is running. For example, port `443`.
Unique Service Name::
The unique key used by your Identity Provider to identify the client. For example, *urn:thoughtspot:callosum:saml*.
Skew Time in Seconds::
The allowed skew time, after which the authentication response is rejected and sent back from the IDP. The commonly used value is `86400`. The default value is *3600*.
Protocol::
The authentication mechanism for ThoughtSpot. For example, `http` or `https`.
IDP Metadata XML File::
For example, *idp-meta.xml*. Provide an absolute path to your Identity Provider’s metadata file. The IDP metadata file is provided by your IDP.  You need this file so that the configuration persists over upgrades. It is a best practice to set it up on persistent or HA storage (NAS volumes), or in the same absolute path on all nodes in the cluster.
Automatically add SAML users to ThoughtSpot upon first authentication::
Specify if you want to add SAML users to ThoughtSpot when they first authenticate. If you select *yes*, the new users will be added to  ThoughtSpot upon their first successful SSO login.
If you select *no*, the SAML users will not be added in ThoughtSpot upon first successful SSO login. Instead, you must link:https://cloud-docs.thoughtspot.com/admin/users-groups/add-user.html[add users manually, window=_blank].
. Click *Save*.

== Allow SAML Redirect Domains
If you have to redirect SAML users to a login URL to a host server in a different domain, make sure you add the SAML redirect domains to the  list of allowed domains in ThoughtSpot.

To whitelist a SAML redirect domain, follow these steps:

. Log in to your ThoughtSpot application instance.
. Click the *Develop* tab.
. Under *Customizations*, click *Settings*.
. In SAML redirect domains, add the domains to whitelist.
+
You can add multiple domains as comma-separated values.

. Click *Save changes*.
