= Customize CSS using SDK [beta betaBackground]^Beta^
:toc: true
:toclevels: 1

:page-title: Customize styles and layout
:page-pageid: custom-css
:page-description: Customize styles, design, and layout of embedded ThoughtSpot app using custom CSS

ThoughtSpot provides advanced style customization capabilities with the custom CSS framework. The custom CSS feature allows you to override the default styles, color schemes, design elements, and typography of ThoughtSpot elements to match the look and feel of your host application.

== Before you begin

* See xref:style-customization.adoc#_scope_of_customization[Scope of customization] to understand feature limitations. For best results, you can combine the customization settings in the UI and custom CSS. However,
note that CSS overrides take precedence over the style customization settings configured in the UI.
* Try it out in the Playground.
The *Visual Embed* Playground now includes the *Apply Styles* checkbox, using which you can try out the variables and rules.
To preview the CSS settings:
. Go to *Develop* > *Visual Embed* > *Playground*.
. Select the embed element. For example,  *Full App*.
. Select *Apply custom styles*.
+
The following code text is added to the `init` function in the code panel on the Playground:
+
[source,javascript]
----
customizations: {
    style: {
      customCSSUrl: "https://cdn.jsdelivr.net/gh/thoughtspot/custom-css-demo/css-variables.css", // location of your style sheet
      // To apply overrides for your style sheet in this init, provide variable values below, eg
      customCSS: {
        variables: {
          "--ts-var-button--secondary-background": "#F0EBFF",
          "--ts-var-button--secondary--hover-background": "#E3D9FC",
          "--ts-var-root-background": "#F7F5FF",
        },
      },
    },
  },
----
. Change the style specifications for any variable and click `Run`. For a complete list of variables, see xref:css-customization.adoc#supported-variables[Supported variables].

++++
<a href="{{previewPrefix}}/playground/fullApp" id="preview-in-playground" target="_blank">Try it out</a>
++++

[#supported-variables]
== Supported variables and rules
ThoughtSpot provides a default CSS file containing the most common variables and rules supported in a given release version. You can apply the overrides within the given file or directly in the code.

The following example shows the supported variables:

[width="100%" cols="7,5,5"]
[options='header']
|======
|Variable|UI element/area|  Description
|`--ts-var-root-background`|Application pages|Application-wide setting +
Background color of the application page
The color code setting applies to all pages in the app.
|`--ts-var-root-color`|Text on application pages| Application-wide setting +
Color of the text on application pages +
|`--ts-var-root-font-family`|Text on application pages| Application-wide setting +
Font type for the text on application pages
|`--ts-var-root-text-transform`|Text on application pages|Application-wide setting +
Capitalization specification for all text in the app.
|`--ts-var-nav-background`|Top navigation panel |Element-level setting +
Background color of the ThoughtSpot navigation panel.
|`--ts-var-nav-color`|Top navigation panels |Element-level setting +
Font color of the ThoughtSpot navigation panel.
|`--ts-var-button-border-radius`|Main button|Application-wide setting +
Border-radius of main buttons. For example, the *Search data* button in the top navigation panel.
|`--ts-var-button--icon-border-radius`|Small buttons|Application-wide setting +
Border-radius of small buttons such as secondary buttons. For example, share and favorite buttons.
|`--ts-var-button--primary-color`|Primary buttons|Element-level setting +
Font color of the text on primary buttons. For example, the *Go* button on the search bar, the primary action buttons on  Liveboard, answer, data workspace, SpotIQ, or Home page.
|`--ts-var-button--primary--font-family`|Primary buttons|Element-level setting +
Font family specification for the text on primary buttons.
|`--ts-var-button--primary-background`|Primary buttons|Element-level setting +
Background color of the primary action buttons. For example, the primary action buttons such as *Pin* and *Save* on the answer page, data workspace, SpotIQ, or Home page.
|`--ts-var-button--primary--hover-background`|Primary buttons|Element-level setting +
Background color of the primary action buttons when a pointer hovers over these buttons.
|`--ts-var-button--secondary-color`|Secondary button| Element-level setting +
Font color of the text on the secondary action buttons.
|`--ts-var-button--secondary--font-family`|Secondary button| Element-level setting +
Font family specification for the text on the secondary action buttons.
|`--ts-var-button--secondary-background`|Secondary action button|Element-level setting +
Background color of the secondary action buttons.
|`--ts-var-button--secondary--hover-background`|Secondary button|Element-level setting +
Background color of the secondary action button when a pointer hovers over these buttons.
|`--ts-var-button--tertiary-color`|Tertiary button|Element-level setting +
Font color of the tertiary button. For example, the *Undo*, *Redo*, and *Reset* buttons on the search results page.
|`--ts-var-button--tertiary-background`|Tertiary button|Element-level setting +
Background color of the tertiary button.
|`--ts-var-button--tertiary--hover-background`|Tertiary button|Element-level setting +
Background color of the tertiary button when a pointer hovers over these buttons.
|`--ts-var-viz-title-color`|Title text of a visualization/answer|Element-level setting +
Font color of the title text of a visualization or answer.
|`--ts-var-viz-title-font-family`|Title text of a visualization/answer|Element-level setting +
Font family specification for the title text of a visualization/answer.
|`--ts-var-viz-title-text-transform`|Title text of a visualization/answer|Element-level setting +
Capitalization specification for the title text of a visualization/answer.
|`--ts-var-viz-description-color`|Visualization/answer description and subtitle |Element-level setting +
Font color of the description text and subtitle of a visualization or answer.
|`--ts-var-viz-description-font-family`|Visualization/answer description and subtitle|Element-level setting +
Font family specification of description text and subtitle of a visualization or answer.
|`--ts-var-viz-description-text-transform`|Visualization/answer description and subtitle|Element-level setting +
Capitalization specification for description text and subtitle of a visualization or answer.
|`--ts-var-viz-border-radius`|Visualization tiles +
Liveboard header panel|Element-level setting +
Border-radius for the visualization tiles and header panel on a Liveboard.
|`--ts-var-viz-box-shadow`|Visualization tiles +
Liveboard header panel|Element-level setting +
Box shadow property for the visualization tiles and header panel on a Liveboard.
|`--ts-var-viz-background`|Visualization tiles +
Liveboard header panel| Element-level setting +
Background color of the visualization tiles and header panel on a Liveboard.
|======

==== Sample CSS file with variable definitions

[source,html]
----
:root {
/******** App ********/

  /* Application-wide background, app-wide text color, app-wide font, app-wide text transform */
  --ts-var-root-background: #FFF0F0;
  --ts-var-root-color: #FFF0F0;
  --ts-var-root-font-family: Optimo-Plain,Helvetica Neue,Helvetica,Arial,sans-serif;
  --ts-var-root-text-transform: initial;

  /******** Top navigation panel ********/
  /*Font color and background color of the navigation panel*/
  --ts-var-nav-color: #F9B3B9;
  --ts-var-nav-background: #B6313E;

  /******** Buttons ********/
  /* Application-wide button design for main buttons. For example, Search data*/
  --ts-var-button-border-radius: 5px;

  /* Application-wide button design for smaller buttons. For example, share and favorite buttons*/
  --ts-var-button--icon-border-radius: 5px;

  /* Primary buttons: For example, the Pin and Save button on the search results page */
  --ts-var-button--primary-color: #ffffff;
  --ts-var-button--primary-background: #2770ef;
  --ts-var-button--primary--hover-background: #B6313E;
  --ts-var-button--primary--font-family: Optimo-Plain,Helvetica Neue,Helvetica,Arial,sans-serif;

  /* Secondary buttons. For example, the Go button on the search bar, the Edit and Explore buttons on the Liveboard page*/
  --ts-var-button--secondary-color: #1d232f;
  --ts-var-button--secondary-background: #eaedf2;
  --ts-var-button--secondary--hover-background: #FCD4D7;
  --ts-var-button--secondary--font-family: Optimo-Plain,Helvetica Neue,Helvetica,Arial,sans-serif;

  /* Tertiary buttons. For example, the Undo, Redo buttons on the search results page*/
  --ts-var-button--tertiary-color: #1d232;
  --ts-var-button--tertiary-background: #FFFFFF;
  --ts-var-button--tertiary--hover-background: #f5f5f5;

  /******** Visualizations ********/
  /* Visualization title text customization*/
  --ts-var-viz-title-color: #C0C6CF;
  --ts-var-viz-title-font-family: Optimo-Plain,Helvetica Neue,Helvetica,Arial,sans-serif;;
  --ts-var-viz-title-text-transform: Capitalize;

  /* Visualization subtitle and description text customization*/
  --ts-var-viz-description-color: #A4A4A3;
  --ts-var-viz-description-font-family: Optimo-Plain,Helvetica Neue,Helvetica,Arial,sans-serif;
  --ts-var-viz-description-text-transform: Capitalize;

  /* Visualization tile customization*/
  --ts-var-viz-border-radius: 15px;
  --ts-var-viz-box-shadow: 1px 2px 5px #888888;
  --ts-var-viz-background: #F6F8FA;
}
----

=== Get started with CSS customization

To get started with CSS customization:

. In the init call, add the location of the style sheet in the `customCssUrl` attribute.

+
[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.None,
    customCssUrl: "cdn.jsdelivr.net/gh/thoughtspot/custom-css-demo/complete.css"
});
----
+
customCssUrl::
__String__. The path of the CSS file with variables for customization. You can use the default CSS file containing the most common variables and rules that ThoughtSpot supports. You can apply the overrides within the given file or directly in the code.
+
The following example shows how to override the variables in the `init` code:

+
[source,javascript]
----
customCSS: {
    variables: {
        "--ts-var-button--secondary-background": "#F0EBFF",
        "--ts-var-button--secondary--hover-background": "#E3D9FC",
        "--ts-var-root-background": "#F7F5FF",
    },
}
----
. After you modify the styles, load the CSS and start your application.

== Additional resources

* link:https://github.com/thoughtspot/custom-css-demo/blob/main/css-variables.css[Custom CSS demo GitHub Repo, window=_blank]
