= Custom actions

:page-title: Actions customization
:page-pageid: custom-action-intro
:page-description: Add custom actions


[div boxDiv boxFullWidth]
--
*xref:customize-actions-menu.adoc[Custom actions overview]*

Learn more about what custom actions are and where you can use them. 
--

== How to configure custom actions

[div boxDiv boxFullWidth]
--
*xref:custom-actions-url.adoc[Configure a custom action to send data to a URL]*

Learn how to create a custom action to send ThoughtSpot data to a specific URL target. 

*Requires Developer privilege*.

--

[div boxDiv boxFullWidth]
--
*xref:custom-actions-callback.adoc[Configure a callback custom action]*

Learn how to create a custom action that can trigger a callback from your host application to send ThoughtSpot data. 

*Requires Developer privilege*.

--

[div boxDiv boxFullWidth]
--
*xref:custom-actions-viz.adoc[Add a custom action to a specific visualization]*

Learn how to assign a custom action to a specific visualization in a search answer or pinboard. 

Requires edit privileges to modify a search answer or a visualization in a pinboard. 

--

[div boxDiv boxFullWidth]
--
**xref:custom-actions-worksheet.adoc[Add custom actions to all visualizations built from a worksheet] **[tag greenBackground]#New# 

Learn how to assign a custom action to a specific worksheet, so that it appears on all visualizations generated using that worksheet. 

Requires edit privileges to access and modify the worksheet.
--

== Custom action examples

[div boxDiv boxFullWidth]
--
*xref:push-data-to-external-app.adoc[View callback custom action example]*

Learn more about the callback custom action workflow, the steps required to push data to an external app. 
--


[div boxDiv boxFullWidth]
--
*xref:callback-response-payload.adoc[Custom action response payload]*

View examples of the custom action response payload with search answer and pinboard data.
--
