= Customize links
:toc: true

:page-title: Link customization
:page-pageid: customize-links
:page-description: Customize link format

ThoughtSpot users receive system-generated links in email notifications, which allow them to access various objects such as pinboards and visualizations. By default, the links generated by ThoughtSpot point users to a standalone ThoughtSpot application URL. If you have embedded ThoughtSpot in your application, you might want to generate links in the format that preserves your host application context. ThoughtSpot allows you to customize the format of these links in the ThoughtSpot Developer portal.

== System-generated links

ThoughtSpot generates links during various operations:

* Links to pinboards
+
These links provide access to a pinboard object and are sent in email notifications in the following scenarios:

** When a user shares a pinboard with another user
** When a user follows a pinboard and subscribes to receive notifications
** When a user schedules a job for a pinboard and adds recipients to receive email notification about the job status

* Links to visualizations within a pinboard
+
ThoughtSpot users can copy these links  and send these to another user through emails or messaging platforms like Slack.

* Links to answers
+
These links provide access to answers from a search query. ThoughtSpot sends these links in email notifications when a user shares an answer with another user or a user group.


* Links to the SpotIQ analyses page
+
ThoughtSpot generates this link when a user runs the SpotIQ analysis on the data obtained from a search query, saved answer, or a visualization in a pinboard. This link points users to the *SpotIQ Analyses* page and is sent in email notifications.

* Links to unsubscribe from notifications
+
The *Unsubscribe* link is included in system-generated emails to allow users to turn off email notifications. This link points users to the *Profile* settings page in ThoughtSpot.

== Link format for a ThoughtSpot embedded instance

By default, ThoughtSpot generates links that point users to a standalone ThoughtSpot application URL. If you have embedded ThoughtSpot in your application, you might want to generate links in the format that suits your host application context. For embedded instances, ThoughtSpot allows you to customize the format of these links in the Developer portal.

The *Link Settings* page in the Developer portal displays the default link format for the system-generated links. You can either prefix your application domain URL to the default link format or customize the entire URL. ThoughtSpot recommends that you use the following variables when you customize a link format:

* `{object-id}` to represent the ID of a pinboard, answer, or the SpotIQ analyses. In  pinboard, answer, and spotIQ analyses links, this variable is substituted by the GUID of the object.
* `{sub-object-id}` to represent the ID of a visualization. In pinboard visualization links, this variable is substituted by the GUID of the visualization.

[IMPORTANT]
====
Make sure the {object-id} and {sub-object-id} variables are used only for ThoughtSpot objects. If the link format has two {object-id} variables, your application users may not receive the correct links. For example, if the link format is  `\https://www.mysite.com/?myobject-id={object-id}/pinboard-id={object-id}`, ThoughtSpot may replace both these variables with the pinboard GUID when it generates the pinboard link.
====

== Customize link format

To customize the link format, follow these steps:

. Go to *Develop* > *Customizations* > *Links*.
. In the *Links Settings* page, specify the link format.
+

Pinboard sharing URL::
+
This URL provides a link to a ThoughtSpot pinboard object.

+
The default link format is `\https://<ThoughtSpot-Host>/#/pinboard/{object-id}`. You can customize this format to generate a link that represents the objects in your host application context. For example, if your host application is `www.mysite.com`, you can configure this link format  as shown here:

+
----
https://www.mysite.com/pinboard/{object-id}
----
+
----
https://www.mysite.com/?pinboard={object-id}
----
Pinboard visualization URL::
+
This URL provides a link to a specific ThoughtSpot visualization in a pinboard.

+
The default link format is `\https://<ThoughtSpot-Host>/#/pinboard/{object-id}/{sub-object-id}`.You can customize this format to represent the object attributes of your host application. For example, if your host application is `www.mysite.com`, you can configure this link format as shown here:

+
----
https://www.mysite.com/pinboard/{object-id}/{sub-object-id}
----
+
----
https://www.mysite.com/?pinboard={object-id}/viz={sub-object-id}
----
Answer sharing URL::
This URL provides a link to a shared answer from a search query.
The default link format is `\https://<ThoughtSpot-Host>/#/saved-answer/{object-id}`. If your host application is `www.mysite.com`, you can configure this link format as shown here:

+
----
https://www.mysite.com/saved-answer/{object-id}
----
+
----
https://www.mysite.com/?answer={object-id}
----
SpotIQ analytics page::
+
This URL provides a link to the SpotIQ analyses page.

+
The default link format is `\https://<ThoughtSpot-Host>/#/insight/{object-id}`. If your host application is `www.mysite.com`, you can configure this link format as shown here:

+
----
https://www.mysite.com/insight/{object-id}
----
+
----
https://www.mysite.com/?insights={object-id}
----
Unsubscribe link::
+
This URL provides a link to the *Profile* settings page in ThoughtSpot.

+
The default link format is `\https://<ThoughtSpot-Host>/#/user-preference`. If your host application is `www.mysite.com`, you can configure this link format as shown here:

+
----
https://www.mysite.com/user-preference
----
+
----
https://www.mysite.com/?unsubscribe
----


+
. Click *Save changes*.
. To verify if the links are generated in the format you configured, subscribe to a pinboard and check the links in the email notifications.
