= Configure a callback action
:toc: true

:page-title: Actions customization
:page-pageid: custom-action-callback
:page-description: Add custom actions

ThoughtSpot allows you to programmatically set up a callback function from the parent application which triggers on the click of a custom action. For example, if you want to push insights from ThoughtSpot into your app or trigger an event to an external application, you can add a custom action in Thoughtspot and set up a callback in the parent application. When the user clicks this action on the *Answers* or *Pinboards* page, it initiates a callback to the parent application.

== Before you begin

* Make sure you have the developer privileges to add a custom action.
* Make sure the link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/new-answer-experience[new Answer experience, window=_blank] is enabled on your cluster. 

== Add a callback custom action

To add a callback custom action:

. Go to *Develop* > *Customizations* > *Actions*.
. Click *Create action*.
. Add a label for the custom action.
. Select the *Callback* option.
. Add an ID for the callback function.

+
This ID is used as a reference for the custom action in the Visual Embed SDK. You can use this ID to register a callback event, disable or hide the custom action on a ThoughtSpot application page.

. If you want to add the custom action on all ThoughtSpot visualization pages, select the *Automatically add as global action to all visualizations* checkbox. 
+
If the custom action is available for all visualizations, it is marked as a __global__ action. If you do not select this checkbox, the custom action can be added to a specific visualization page locally by the ThoughtSpot users. For more information, see xref:custom-actions-viz.adoc[Custom actions for visualizations].

. To add the custom action only in the contextual menu, select the *Only allow in context menu* checkbox. 
+
When you select this checkbox, the custom action will be added only in the contextual menu that appears when a user right-clicks on a visualization.

. Click *Add action*.
+
The custom action is added to the *My actions* list in the Developer portal.

. To view and verify the custom action you just created, navigate to a visualization page.

For more information about how to push data to an external application using a callback custom action, see xref:push-data-to-external-app.adoc[Callback custom action example].