= Custom domain configuration
:toc: true
:toclevels: 1

:page-title: Custom domain configuration
:page-pageid: custom-domain-config
:page-description:  

When you embed ThoughtSpot into your app, your application URL will be set as  `<your-company-name>.thoughtspot.cloud` by default. The system-generated email notifications from your embedded ThoughtSpot instance will also include `thoughtspot.cloud` in the domain name.

To ensure that embedding works on browsers that don't allow third-party cookies, such as Safari's default security setting and Firefox when in strict mode, you may want to set the domain name of the ThoughtSpot instance to the same domain as your host application. For example, you might want to use `<app-name>.<your-company-name>.com` as your base URL, instead of `<your-company-name>.thoughtspot.cloud`.

Similarly, you may want to include your business domain name instead of `thoughtspot.com` in all system-generated notifications. For example, you might want your Liveboard schedule notifications to show the sender's address as `<user-name>@<your-domain-name>`, instead of the default `TS Admin no-reply@notifications.thoughtspot.com`.

For all such domain-related customizations, we recommend that you contact ThoughtSpot Support. We also recommend that you read the following guidelines before initiating a request for the domain name or URL change.

== Domain URL customization

If you want to customize the application domain URL that appears in the browser, we recommend that you contact ThoughtSpot support to initiate a URL change request. ThoughtSpot may require the following information to complete this operation:

* The domain name that you want to use. Make sure you have a valid and registered domain name.
* A CNAME record to point the custom domain to the default domain. For example, to set your custom domain URL as `<app>.<yourdomain>.com`, you must create a CNAME record to point  `<app>.<yourdomain>.com` to  `<cluster-name>.thoughtspot.cloud`. 
* Contact personnel for updating your DNS records after your cluster is migrated to the new domain.
* Your preferred maintenance window for this operation.

[IMPORTANT]
====
The domain URL customization does not update the email domain name in ThoughtSpot system-generated notifications. You must contact the ThoughtSpot Support team to customize the email domain.
====

== Email customization

ThoughtSpot supports customizing the email domain, sender ID welcome email message text, and product name in system-generated notifications such as the Liveboard and answer sharing notifications, Liveboard job scheduled emails, and so on.

[width="100%" cols="3,6"]
[options='header']
|====
|To customize|Steps to configure
|Email domain name|Contact ThoughtSpot Support and provide the email domain name. 
|Sender ID a|Contact ThoughtSpot Support to customize the sender ID.  

To customize the sender ID, you must provide an email address from which you want to send notifications.

[NOTE]
====
Make sure the email address you provide is a valid email account that you can access.
When ThoughtSpot support triggers the email verification process, you will receive a verification email with a link. You must click this link within 24 hours to confirm your email address and authorize its use. If you don’t complete the email verification process within 24 hours, contact ThoughtSpot support to start the email verification process again.
====

|Message text for welcome emails|Go to *Admin* > *Onboarding* > *Custom message* in ThoughtSpot UI and add the message text. 
|Product name in the email notifications|Go to *Admin* > *Onboarding* > *Product name* in the ThoughtSpot UI and add the product name.

|====

For information about additional customization settings for email notifications and onboarding experience, see xref:customize-email-settings.adoc[Customize email notifications and onboarding experience].

== Post-customization checks

* Verify if the ThoughtSpot instance loads with the new domain URL.
* Make sure you add the new domain URL to the xref:security-settings.adoc[CORS and CSP allowed list in the ThoughtSpot UI].
* If your setup uses SAML authentication for SSO, make sure the IdP server has the correct domain URLs. 
* Try sharing an object and verify if the system-generated notifications show the custom email domain name. 
