= Customization and rebranding
:toc: true

:page-title: Customization and rebranding
:page-pageid: customization-intro
:page-description: You can insert custom buttons or menu items in ThoughtSpot UI

You can customize the look and feel of the embedded ThoughtSpot content to match the styles and layout of your host application. You can also create new buttons and actions to provide additional workflows to your application users. 

ThoughtSpot also allows you to customize the format of the links used in system-generated notifications.

[div boxDiv boxFullWidth]
--
+++<h5>Customize layout and styles</h5>+++

Customize styles, application logo, font specifications for charts and tables, background color of the application UI, and the footer text. For step-by-step instructions, see xref:customize-style.adoc[Customize layout and styles].
--

[div boxDiv boxFullWidth]
--
+++<h5>Add custom actions</h5>+++

Insert xref:custom-actions.adoc[custom actions] into the ThoughtSpot UI to send data to a specific URL endpoint or trigger a callback workflow to the parent application. 
--

[div boxDiv boxFullWidth]
--
+++<h5>Customize link format</h5>+++

You can xref:customize-links.adoc[customize system-generated links to use a URL format that preserves your host application context]. These links are used in notifications that are generated when a user shares an object, schedules a Liveboard job, or runs SpotIQ analyses.
--

[div boxDiv boxFullWidth]
--
+++<h5>Customize domain name or URL</h5>+++

If you want to host your embedded content on a specific domain URL, xref:custom-domain-configuration.adoc[you can customize the domain name of your ThoughtSpot instance]. You can also xref:custom-domain-configuration.adoc[customize the email domain name] for system-generated notifications.
--

[div boxDiv boxFullWidth]
--
+++<h5>Customize onboarding settings</h5>+++

ThoughtSpot allows you to customize the message text of welcome emails and add your product name in system-generated email notifications. If you have admin user privileges, you can xref:customize-email-settings.adoc[customize email settings and onboarding experience] for your application users.
--
 