= Configure a custom URL action 
:toc: true

:page-title: Send data to a URL using a custom action
:page-pageid: custom-action-url
:page-description: Add custom actions to send data to a URL

ThoughtSpot allows you to add a custom action to trigger a data payload to a specific URL target. For example, you may search in ThoughtSpot for a specific data set and want to programmatically deliver this data to a Slack channel. The ThoughtSpot Developer portal allows you to add a custom menu item in the visualization pages and trigger a workflow when a user clicks the action.

== Before you begin

* Make sure you have the developer privileges to add a custom action.
* If you want to use a third-party domain as the URL target, add the URL domain to the xref:security-settngs.adoc[CORS and CSP connect-src allowlist].
* Make sure the link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/new-answer-experience[new Answer experience, window=_blank] is enabled on your cluster. 

== Add a custom action

To add a custom menu item to send data to a specific URL, follow these steps:

. Go to *Develop* > *Customizations* > *Custom actions*.
. Click *Create action*.
. Add a label for the custom action. For example, Send Survey.
. Make sure the *URL* option is selected.
. Add the target URL that you want to invoke when a user clicks this action in the UI. 
+
Note that the custom action ID is generated automatically. 
+
. To view additional settings, click *Show URL settings*.
. From the *Authorization* drop-down, select an authentication method. ThoughtSpot will use the specified authentication method to invoke the URL or make an API call.
+
[IMPORTANT]
The authentication information you specify in these fields is visible to other authenticated users, even if they do not have Developer or Admin privileges.

* *None*
+
If you do not want to use an authentication method, select `None`. 

* *Basic authentication*
+
Select this authentication method if your server requires ThoughtSpot to pass the authentication information, such as `username` and `password` in the `Authorization` header. If selected, enter the `username` and `password`.

* *Bearer*
+
Select this authentication method if your server requires ThoughtSpot to obtain a security token and send the token in the `Authorization` headers during an API call. Specify the security `token` to use for authentication and authorization.  

* *API key*
+
Select this authentication method if you want ThoughtSpot to use an API key during API calls to the URL target. Specify the API key value to use in the `X-API-Key` request header. 

+
. If the URL endpoint requires specific data for the custom action workflow, you can configure the custom action to send the data attributes as query parameters. For example, you may want to send database information in query parameters to the URL endpoint when the custom action workflow is triggered. Make sure these query parameters are defined as key-value pairs.
 
. If you want to add the custom action on all ThoughtSpot visualization pages, select the *Automatically add as global action to all visualizations* checkbox. 
+
If the custom action is available for all visualizations, it is marked as a *Global* action. If you do not select this checkbox, the custom action can be added to a specific visualization page locally by the ThoughtSpot users. For more information, see xref:custom-actions-viz.adoc[Custom actions for visualizations].
+

. To define which user groups can access the custom action, click *Show advanced availability settings*, and select the user groups. By default, the custom action will be available to all ThoughtSpot users.
 
. Click *Add action*.
+
The custom action is added to the *My actions* list in the Developer portal.
. To view and verify the custom action you just created, navigate to a visualization page.
