=  Embedded app deployment
:toc: true
:toclevels: 1

:page-title: Deployment and administration overview
:page-pageid: deploy-overview
:page-description: Best practices and recommended methods for deploying embedded analytics, multi-tenant workspace, and access control.   
You can deploy embedded analytics using TML and REST API, set up a multi-tenant or single-tenant workspace, and define access permissions for user visibility and data security. 

[div boxDiv boxFullWidth]
--
+++<h5>Development and deployment</h5>+++

Learn how to xref:development-and-deployment.adoc[develop content and deploy embedded analytics] using the TML and REST API framework.
--

[div boxDiv boxFullWidth]
--
+++<h5>Best practices for deployments with multi-tenant and single-tenant database models</h5>+++

Learn how to deploy a multi-tenant workspace and achieve multi-tenancy at the user and data level. Understand the xref:multi-tenancy-best-practices.adoc[best practices for multi-tenant database and single-tenant database models].
--

[div boxDiv boxFullWidth]
--
+++<h5>Deploy a multi-tenant cluster with Orgs</h5>+++

Configure multiple tenant-specific workspaces called xref:orgs.adoc[Orgs] on your ThoughtSpot Cloud application instance.
--