= Deployment and administration
:toc: true
:toclevels: 1

:page-title: Deployment and administration overview
:page-pageid: deploy-overview
:page-description: Best practices and recommended methods for deploying embedded analytics, multi-tenant workspace, and access control.   
You can deploy embedded analytics using TML and REST API, set up a multi-tenant or single-tenant workspace, and define access permissions for user visibility and data security. 

[div boxDiv boxFullWidth]
--
+++<h5>Development and deployment</h5>+++

Learn how to xref:development-and-deployment.adoc[develop content and deploy embedded analytics] using the TML and REST API framework.
--

[div boxDiv boxFullWidth]
--
+++<h5>Best practices for deployments with multi-tenant and single-tenant database models</h5>+++

Learn how to deploy a multi-tenant workspace and achieve multi-tenancy at the user and data level. Understand the xref:multi-tenancy-best-practices.adoc[best practices for multi-tenant database and single-tenant database models].
--

[div boxDiv boxFullWidth]
--
+++<h5>Access control and data security</h5>+++

Learn how to use various ThoughtSpot features, such as group privileges, object sharing, Row-level security (RLS), and Column-level security (CLS), to xref:configure-user-access.adoc[control user access to ThoughtSpot application workflows and data objects].
--

[div boxDiv boxFullWidth]
--
+++<h5>Custom domain configuration</h5>+++

To ensure that embedding works on browsers that don't allow third-party cookies, xref:custom-domain-configuration.adoc[you can set the domain name of the ThoughtSpot instance to the same domain as your host application].

You can also xref:custom-domain-configuration.adoc[customize the email domain name] for system-generated notifications.
--