= Deprecation announcements
:toc: true
:toclevels: 2

:page-title: Deprecation announcements
:page-pageid: deprecated-features
:page-description: This article lists features deprecated and no longer supported in ThoughtSpot Everywhere

As ThoughtSpot products evolve, sometimes existing features are deprecated and replaced with new and improved functionality. +
A deprecated feature may continue to be functional for a while, but may not be maintained or supported with the new workflows and functionality. Deprecated features will eventually be removed from the product and not supported in later releases.
////
De-supported::
A de-supported feature no longer exists in the product. When you upgrade to a newer release, any workflows that rely on a de-supported feature no longer work.

////

== Deprecation of REST API v2 [beta betaBackground]^Beta^ endpoints

The REST API v2 [beta betaBackground]^Beta^ endpoints will be deprecated starting from 8.10.0.cl release. +
The REST API v2 [beta betaBackground]^Beta^ endpoints will remain functional but will be removed from the Playground page in the *Develop* tab when the REST API v2.0 endpoints are rolled out.

[NOTE]
====
If your current deployment is using REST API v2 [beta betaBackground]^Beta^ endpoints, your implementation will continue to work. However, ThoughtSpot recommends that you start using the REST API v2.0 endpoints as and when they are Generally Available (GA).
====

=== REST API v2.0 rollout

To ensure a smooth transition for early adopters of the REST API v2 [beta betaBackground]^Beta^ feature, ThoughtSpot will roll out the REST API v2.0 endpoints in the following manner:

* The new v2.0 API endpoints will be introduced incrementally over the subsequent releases and all API operations supported by the REST API v2 [beta betaBackground]^Beta^ version will be replaced. ThoughtSpot encourages you to start using the REST API v2.0 endpoints as and when they are GA and fully qualified for production use cases.
* With the introduction of the new REST API v2.0 endpoints, the current REST API v2 [beta betaBackground]^Beta^ endpoints will be deprecated. The current REST Playground v2 in the *Develop* tab will be replaced with the new REST API v2.0 Playground.

=== REST API SDK
The current REST API SDK version will be deprecated from 8.8.0.cl onwards.
The upcoming REST API v2.0 endpoints and Playground will not support the SDK in the initial release. In later releases, a new version of the SDK will be published on the Playground, GitHub repo, NPM, PyPi, MVN Package Manager, and Nuget Package Manager sites.

[NOTE]
====
If you are using the REST API SDK, the existing version continues to work with REST API v2 [beta betaBackground]^Beta^ endpoints. ThoughtSpot does not recommend using REST API v2.0 endpoints with the SDK in its current state.
====

=== Documentation changes
The API documentation for the REST API v2 [beta betaBackground]^Beta^ will continue to be available until the REST API v2 endpoints are functional. However, all references to the REST API SDK will be removed in the upcoming versions of Developer Documentation.

The API documentation for the new REST API v2.0 endpoints will be made available when the new endpoints are released for customer use.
