= Development and deployment
:toc: true
:toclevels: 1

:page-title: Development and deployment using TML and REST API
:page-pageid: development-and-deployment
:page-description: Development and deployment following SDLC practices can be achieved using TML and REST API

== Overview
When an deploying embedded analytics, there is typically a set of defined practices for development, testing, and deployment of content similar to the processes used for development of code for integration between the systems. 

The ThoughtSpot system contains many types of objects which link together. All of the objects are modeled using the link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/tml.html[ThoughtSpot modeling language (TML), window=_blank]. The TML for an object can be viewed and edited through the UI and via REST APIs. With the proper understanding of TML and how the APIs work, you can integrate ThoughtSpot into your source control system and programmatically move content through your development and deployment phases.  

[NOTE]
====
This article assumes an understanding of how ThoughtSpot uses groups and sharing to control visibility of content to different groups. Please see the xref:multi-tenancy-best-practices.adoc[multi-tenancy best practices guide] for a thorough explanation of how to control object access using ThoughtSpot groups.
====

== ThoughtSpot modeling language (TML)
Every object type in ThoughtSpot has a representation in link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/tml.html[ThoughtSpot modeling language (TML), window=_blank]. TML documents are available by default in the easy-to-read link:https://en.wikipedia.org/wiki/YAML[YAML, window=_blank] format, and can also be requested in JSON format from the ThoughtSpot REST API.

Almost every aspect of an object can be defined or modified via TML, with a few limitations around making updates to very complicated data modeling features. While building content in ThoughtSpot is most easily achieved via the web-based UI, TML allows for integrating into common SDLC processes, deploying changes across a whole environment, and scripting complex SaaS deployments.

=== REST API endpoints for TML
There are two REST API endpoints for working with TML, one to xref:tml-api.adoc#export[export (download)] and one to xref:tml-api#import[import (upload)]. The APIs can retrieve and upload multiple TML files at a time, which tells the system to look at name references within the set of uploaded TML files first, before looking to existing objects on the ThoughtSpot server. If you are importing TML files one-at-a-time, you will often need to include the `fqn` property to specify between objects with the same name.

The TML import REST API call itself does not specify any objects. All details of the object to be created or modified are specified *within the uploaded TML file*, including the GUID of an object you wish to update. 

==== Download object TML
If you want to store TML within Git or any other version control system, you'll use the xref:tml-api.adoc#export[export REST API endpoint] to retrieve the TML representations of the objects on the ThoughtSpot server. Alternatively, you might use the ThoughtSpot server itself as your system of record, but export TML and apply changes programmatically prior to importing these modified TML files as new objects. 
 
You can pass any number of GUIDs in the `export_ids` argument, although it may be simpler to retrieve one at a time. 
 
The `formattype` argument can be set to `YAML` or `JSON`. YAML is more human-readable and matches the view when you edit TML within the ThoughtSpot UI, while JSON may be easier to process for programmatic manipulation. 
 
The `export_associated` argument retrieves the TML objects for all related objects when used. This can be used for grabbing a full set of dependencies, but generates a more complex response that must be parsed into individual elements.
 
==== Create new objects
To create a new object on the server, you call the import API with the *force_create* property set to *true*. Even if the TML document has a GUID, *force_create=true* should result in a new object on the server with a new GUID. That said, it is easy to remove the TML guid property prior to publish along with the *force_create=true* command in the API, and you will see both in many examples.

==== Update existing objects
To update an existing object on the ThoughtSpot server, you must find the GUID of the object to be updated, then update the TML document's *guid* property. The xref:metadata-api.adoc[metadata APIs], in particular xref:metadata-api.adoc#object-header[/metadata/listobjectheaders] can be used to determine the GUID of an existing object. 


=== Names and GUIDs
ThoughtSpot enforces unique names only on *connections*. Duplicate names are allowed for all other object types (tables, worksheets, pinboards, etc.). Every object has a globally unique ID (GUID) for identifying the object without any ambiguity. Within the link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/tml.html[ThoughtSpot Modelling Language (TML) specification, window=_blank], the `fqn` property is available to specify a GUID when names might be ambiguous.

Even though ThoughtSpot allows naming things the same, you can simplify some processes by setting your own best practice rules for object naming. If your objects have unique names, you won't have to look up GUIDS via the REST API to use TML.

Because GUIDs are randomly generated when an object is first created, if you need to track relationships between objects and you cannot use a naming pattern, you should store the relationships between various GUIDs for later reference. For example, if you want to know which pinboards are copies from a particular template, store the returned GUIDs of the child versions when you first publish them, so that you can push future updates from the parent pinboard to the descendents.

== ThoughtSpot data and content object types
ThoughtSpot has many different types of objects, which can broadly be split into data objects and content objects. Each object type has specific properties and relationships to other objects. The link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/tml.html[TML documentation, window=_blank] contains full descriptions of all of the properties of each object type.

=== Data objects
Data objects represent the various components of the data model within ThoughtSpot: *connections*, *tables*, *joins*, *views*, and *worksheets*. 

==== Connections
Connections contain the details and credentials necessary to connect to a cloud data warehouse. Every table, join, view, and worksheet all is linked to a particular connection, and relationships between those objects can only exist within the scope of the connection. 

Connections do not have a TML representation, but can be created and modified via the xref:connections-api.adoc[data connection REST APIs]. 

Connections *must have unique names* within the entire ThoughtSpot server. Connections do have GUIDs, but *only name is necessary in TML* files due to this uniqueness constraint. 

==== Tables
Table objects represent an actual table (or view) within a database. 

Within ThoughtSpot, the display names for tables *do not have uniqueness constraints*. You can create or import tables with the same display names. 

When importing a table through the ThoughtSpot UI, a table's display name will default to the table's name in the data warehouse, but you can change the display name to whatever you'd like. You can specify the display name within the TML document when creating an table via TML import.

==== Join relationships
ThoughtSpot will import join relationships between tables when adding the table through the UI if the relationships are defined within the database. You can also manually define join relationships through the UI or table TML. Joins are defined in table objects. Worksheets can also have join definitions, but these joins modify existing joins between tables.

To define joins, all tables being referenced must exist as table objects in ThoughtSpot. When importing a TML table definition with joins, you must either import all tables at the same time, or remove the `joins_with` section of the tables on initial import, then update the tables with TML files that contain the `joins_with` section.

==== Views
link:https://cloud-docs.thoughtspot.com/complex-search/about-query-on-query.html[Views, window=_blank] transform a saved search into a data source, allowing for analysis that would require complex sub-queries in SQL. Views can be joined with other data objects in a worksheet.

==== Worksheets
Worksheets combine a number of tables into a coherent data model optimized for searches. 

=== Content objects
Content objects are *answers* (saved searches) and *pinboards*. Pinboards are collections of answers organized for display, but the answers on a pinboard are stored completely within the pinboard definition: an answer on a pinboard is not linked in any way to an answer outside of a pinboard. However, the capabilities and definitions for answers stored separately or on a pinboard are identical.

Best practice is to *only connect answers and pinboards to worksheets*. Although they can connect directly to tables, it is far simpler to adjust references within the answer and pinboard TML to worksheets than many individual tables.

== Deployment patterns

=== Copying from one server to another
When moving content from one instance of ThoughtSpot to another, object names can be left exactly as they are from the first environment to the other. Changes like referencing a different *connection* can be achieved by changing the connection name property within the link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/tml.html#syntax-tables[table TML objects, window=_blank]:



=== Dev -> test -> prod
A standard pattern for software development lifecyle (SDLC) is moving content from a development (dev) environment to a test environment then eventually to production (prod) where end customers can see it.

==== "Namespacing" prefixes on content names
The easiest way to avoid name collisions is by adding "dev_" or "test_" before the name of any object. By using a consistent "namespace prefix", deployment scripts an easily find and replace when moving from "dev" to "test", or remove the prefix entirely when copying the content to prod where end customers can see it.

Example:

- dev_Connection A
- test_Connection A
- dev_Table A
- dev_Table B
- dev_Worksheet 1

Using this namespace prefix scheme, you can export the TML files related to "dev_Connection A" and simply update any name references by replacing "dev_" with "test_".


==== Access control
Dev and test content should be shared only to specific groups designed to give access to the correct app developer users.

==== Change tracking / source control
In the development phase, most content creation and updates will occur within the ThoughtSpot web application. Changes can be made directly to TML files and uploaded, but ThoughtSpot's interface is designed for creating new searches and pinboards with maximum speed and control. This presents the question of when and how to track content changes for content in the "development environment".

=== Single-tenant databases deployment model
As described in the multi-tenancy best practices article, the single-tenant databases model requires separate connections for each tenant, along with replicas of all other standardized objects. In this model, there is one additional tier of deployment: dev, test, prod template, and prod tenant content.

Prod template content is the finalized data model and other content for a given prod release, prior to being published out to each tenant with the necessary changes to their tenant connection.

==== Namespacing in the single-tenant databases model

- dev_
- test_
- prod_

Each prod tenant copy will have the same name so that each tenant will not see their own customer name / ID listed out. Access control through sharing will ensure they never have any awareness of the other objects that exist with the same name for the other tenants.
