= Visual Embed Playground
:toc: true

:page-title: Visual Embed Playground
:page-pageid: dev-playground
:page-description: Use the Visual Embed Playground to explore the embedding workflows with the Visual Embed SDK APIs, play with the code, and preview results.

The *Playground* allows developers to try Visual Embed APIs, play with the code, and view results instantly.

You can explore the following SDK components in the Playground.

* xref:developer-playground.adoc#playground-search[Search]
* xref:developer-playground.adoc#playground-liveboard[Liveboards]
* xref:developer-playground.adoc#playground-visualization[Visualizations]
* xref:developer-playground.adoc#playground-fullapp[Full application]

[#playground-search]
== Search
To explore the Search embed function:

. Go to *Playground* > *Search*.
. Select a data source or a saved Answer.
. Try using any of the following customization settings and click *Run* to preview the result.

[width="100%"]
|====
a|**Collapse data panel**

Minimizes the data panel on the left navigation bar.

++++
<a href="{{previewPrefix}}/playground/search?collapseDataSources=true" id="preview-in-playground" target="_blank">Try it out</a>
++++


a|**Hide data panel**

Hides the default data panel. You can use this function to create a custom data panel when embedding the search module in your application.

++++
<a href="{{previewPrefix}}/playground/search?hideDataSources=true" id="preview-in-playground" target="_blank">Try it out</a>
++++

a|**Hide chart or table**

Hides the charts and tables that appear beneath the search bar by default. For example, if you want to create a custom visualization using raw data from an existing Answer, you can enable this checkbox.

++++
<a href="{{previewPrefix}}/playground/search?hideResults=true" id="preview-in-playground" target="_blank">Try it out</a>
++++

a|**Modify available actions**

include::{path}/modify-available-actions.adoc[]

a|**Add search tokens**

Allows constructing a TML-based search query string to set search tokens and execute search.

The following example shows how to create a search a `searchTokenString` and execute search:

[source, Javascript]
----
searchOptions: {
    searchTokenString: '[product][sales][date].daily',
    executeSearch: true,
}
----
 
++++
<a href="{{previewPrefix}}/playground/search/searchOptions=true" id="preview-in-playground" target="_blank">Try it out</a>
++++

|*Handle custom actions*

Allows you to view the code for a custom action event. If the embedded instance has a custom action, use this checkbox to view the event generated by the custom action and send ThoughtSpot data as a payload.
|====

[#playground-visualization]
== Visualization
To explore the visualization embedding function:

. Go to *Playground* > *Visualization*.
. Select a Liveboard or visualization.
. Try using any of the following customization settings and click *Run* to preview the result.


[width="100%"]
|====

a|*Modify available actions*

include::{path}/modify-available-actions.adoc[]

a|**Set runtime filters**

Enables Runtime Filters.

Runtime filters provide the ability to filter data at the time of retrieval.
To apply Runtime Filters, pass the `columnName`, `operator`, and `value` parameters in the `runtimeFilters` attribute.

[source,JavaScript]
----
runtimeFilters: [{
    columnName: 'color',
    operator: RuntimeFilterOp.EQ,
    values: ['red']
}]
----

++++
<a href="{{previewPrefix}}/playground/answer?runtimeFilters=true" id="preview-in-playground" target="_blank">Try it out</a>
++++

For more information, see xref:runtime-filters.adoc[Runtime filters].

|**Handle custom actions**

Allows you to view the code for a custom action event. If the embedded instance has a custom action, use this checkbox to view the event generated by the custom action and send ThoughtSpot data as a payload.

|**Enable Search Assist**

Enables the Search Assist feature that provides a custom onboarding experience for users searching data on an embedded instance. With Search Assist, data engineers and Worksheet owners can create a set of questions to assist users with the search.

++++
<a href="{{previewPrefix}}/playground/search?enableSearchAssist=true" id="preview-in-playground" target="_blank">Try it out</a>
++++

|====

[#playground-liveboard]
== Liveboard
To explore the Liveboard embedding SDK functions:

. Go to *Playground* > *Liveboard*.
. Select a Liveboard.
. Try using any of the following customization settings and click *Run* to preview the result.

[width="100%"]
|====

a|**Full Height**

Dynamically resizes the embedded Liveboard frame according to the height of the Liveboard.

If the embedded Liveboard does not fit vertically within your application page, a second scroll bar may appear. When **Full Height** is selected, the embedded Liveboard container is automatically adjusted according to the height of the Liveboard.

++++
<a href="{{previewPrefix}}/playground/liveboard?fullHeight=true" id="preview-in-playground" target="_blank">Try it out</a>
++++


a|**Modify available actions **

include::{path}/modify-available-actions.adoc[]

a|**Set runtime filters**

Enables Runtime Filters on a visualization in a Liveboard.

Runtime filters provide the ability to filter data at the time of retrieval.
To apply Runtime Filters, pass the `columnName`, `operator`, and `value` parameters in the `runtimeFilters` attribute.

[source,JavaScript]
----
runtimeFilters: [{
    columnName: 'Revenue',
    operator: RuntimeFilterOp.EQ,
    values: [100000]
}]
----

++++
<a href="{{previewPrefix}}/playground/liveboard?runtimeFilters=true" id="preview-in-playground" target="_blank">Try it out</a>
++++

For more information, see xref:runtime-filters.adoc[Runtime filters].

|*Handle custom actions*

Allows you to view the code for a custom action event. If the embedded instance has a custom action, use this checkbox to view the event generated by the custom action and send ThoughtSpot data as a payload.
|====

[#playground-fullapp]
== Full application
To explore the full ThoughtSpot embedding function:

. Go to *Playground* > *Full app*.
. Select a tab to set a default page view for embedded application users.
. Try using any of the following customization settings and click *Run* to preview the result.

|====
a|**Modify available actions**

include::{path}/modify-available-actions.adoc[]

a|*Show navigation bar*

Displays the ThoughtSpot top navigation bar. By default, the navigation bar is hidden.

++++
<a href="{{previewPrefix}}/playground/fullApp?showNavBar=true" id="preview-in-playground" target="_blank">Try it out</a>
++++
|**Navigate to URL**

Allows you to define a specific URL path for loading a ThoughtSpot application page. If a particular ThoughtSpot page is set as a homepage in  the `pageID` attribute and the URL path is also defined in the `path` attribute, the path definition takes precedence.

a|**Set runtime filters**

Enables Runtime Filters on a visualization in a Liveboard.

Runtime filters provide the ability to filter data at the time of retrieval.
To apply Runtime Filters, pass the `columnName`, `operator`, and `value` parameters in the `runtimeFilters` attribute.

[source,JavaScript]
----
runtimeFilters: [{
    columnName: 'Revenue',
    operator: RuntimeFilterOp.EQ,
    values: [100000]
}]
----

++++
<a href="{{previewPrefix}}/playground/fullApp?runtimeFilters=true" id="preview-in-playground" target="_blank">Try it out</a>
++++

For more information, see xref:runtime-filters.adoc[Runtime filters].

|**Handle custom actions**

Allows you to view the code for a custom action event. If the embedded instance has a custom action, use this checkbox to view the event generated by the custom action and send ThoughtSpot data as a payload.
|====

== Related information

* xref:embed-search.adoc[Embed ThoughtSpot Search]
* xref:embed-a-viz.adoc[Embed a visualization]
* xref:embed-pinboard.adoc[Embed a Liveboard]
* xref:full-embed.adoc[Embed full application]

////
+
Disable Search Assist::
Disables the Search Assist feature. Search Assist allows you to create a custom onboarding experience for your users by demonstrating how to search data from the example queries created on your Worksheet.
+

////
