= Embed ThoughtSpot in a React app
:toc: true
:toclevels: 2

:page-title: Embed ThoughtSpot components in a React app
:page-pageid: react-app-embed
:page-description: You can use visual embed SDK to embed ThoughtSpot search, Liveboard, visualizations, or the full app in a React application

If you are building an app using ReactJS and want to embed ThoughtSpot search, Liveboard, visualization, or full ThoughtSpot experience in your React app, you can use the Visual Embed SDK and ThoughtSpot React components.

== Get started

Before you begin embedding ThoughtSpot, make sure you have installed React framework and its dependencies in your development environment. 

. Check if NPM and Node.js are installed on your setup.
. If you do not have a React app created for ThoughtSpot integration, create a React app and install its dependencies.

+
----
npm install -g create-react-app
----
+
For information about installing React framework on Windows, see  link:https://docs.microsoft.com/en-us/windows/dev-environment/javascript/react-on-windows[Install React directly on Windows, windows=_blank].

. If you want to build an app with TypeScript, you can either create a new React app in TypeScript or add TypeScript to your existing React app project. For more information, see link:https://create-react-app.dev/docs/adding-typescript/[Adding TypeScript, window=_blank].

. Initialize the app. 
+
----
npm init react-app ts-data-app
----
+
In the above example, the React app for embedding ThoughtSpot is named as `ts-data-app`.

. Make sure a React app directory with the initial project structure is created.


== Add Visual Embed SDK to your project

You can install the Visual Embed SDK from NPM.

----
npm i @thoughtspot/visual-embed-sdk
----

== Get the GUIDs

You will require GUIDs of the following objects to embed ThoughtSpot components.

* The saved answer or data source GUIDs to embed search and run a search query
* Liveboard GUID to embed a Liveboard
* Liveboard and visualization GUIDs to embed a visualization from a Liveboard 

You can find the GUIDs of these objects in the UI, the developer Playground on your ThoughtSpot instance, or through the REST API endpoints, such as xref:metadata-api.adoc#metadata-list[metadata/list] and xref:metadata-api#object-header[metadata/listobjectheaders].

== Embed ThoughtSpot search 

To embed ThoughtSpot search, complete the following steps:

=== Create a search component

In your React app project, go to the **Components ** folder in your app directory and add a page for the embedded search object; for example, `search.tsx`. 

. Import the React library: 
+ 
[source,Typescript]
----
import React from 'react'
import { AuthType, init, EmbedEvent, HostEvent } from '@thoughtspot/visual-embed-sdk';
import { SearchEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/react';
----
+
If you are using Webpack 4, which is the default when using `create-react-app v4`, import the React components as shown in this example:

+ 
[source,Typescript]
----
import { SearchEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/lib/src/react';
----
+
Optionally, you can use an event logger component to log and track events. 

+ 
[source,Typescript]
----
import { useEventLogger } from "../../utils/utils";
----

. Initialize the SDK and specify the authentication method. 
+
In the following example, the `authType` is set to `SSO` to use SSO authentication for the embedded app users.

+
[source,Typescript]
----
init({
    thoughtSpotHost: 'https://<hostname>:<port>',
    authType: AuthType.SSO,
});
---- 
+
For more information about supported authentication methods and login attributes, see xref:embed-authentication.adoc[Authentication].

. Add constructor options as props and register event listeners. 

+
The following example adds the `Search` function  with a data source ID and registers a custom action event. 

+
[source,Typescript]
----
const Search = ({ dataSources }) => {
    const embedRef = useEmbedRef();
    const onCustomAction = (actionEvent) => {
        // Do something with actionEvent.
    };

    return (
        <SearchEmbed
            dataSources={["cd252e5c-b552-49a8-821d-3eadaa049cca"]}
            onCustomAction={onCustomAction}
        />
    );
};
----
+
This example shows how to trigger a `load` event when the search component loads in the embedded app.

+
[source,Typescript]
----
const Search = ({ dataSources }) => {
 const embedRef = useEmbedRef();
 const logEvent = useEventLogger();
 const onLoad = () => {
 embedRef.current.trigger(EmbedEvent.Load, {});
  };
 return (
        <SearchEmbed
            dataSources={["cd252e5c-b552-49a8-821d-3eadaa049cca"]}
            onLoad={logEvent(EmbedEvent.Load)}
        />
    );
 };
----


. Render the app
+
----
ts-data-app> npm start
----

=== Test your app

* Load your application.
* Perform a search operation and verify the results.
* Verify if the actions are disabled or hidden as configured in the app.
* Check if the registered events are emitted and logged.

=== Code sample for Search embed

[source,Typescript]
----
const Search = () => {
  const embedRef = useEmbedRef();
  const logEvent = useEventLogger();
  const changeSearch = () => {
    embedRef.current.trigger(HostEvent.Search, {
      searchQuery: "[sales] by [item type]",
      dataSources: ["cd252e5c-b552-49a8-821d-3eadaa049cca"],
    });
  };
  const triggerDrill = () => {};
  const onLoad = () => {
    embedRef.current.trigger(EmbedEvent.load, {});
  };

  return (
    <SearchEmbed
      frameParams={{
        height: 600,
      }}
      ref={embedRef}
      searchOptions={{
        searchTokenString: "[quantity purchased] [region]",
        executeSearch: true,
      }}
      dataSources={["cd252e5c-b552-49a8-821d-3eadaa049cca"]}
      collapseDataSources={true}
      disabledActions=["Action.Pin","Action.ShowUnderlyingData"]
      disabledActionReason="Contact your administrator"
      onLoad={logEvent(EmbedEvent.Load)}
      onQueryChanged={logEvent}
      onData={logEvent}
    />
  );
};
----

== Embed a Liveboard 

To embed a ThoughtSpot Liveboard, complete the following steps:

=== Create a Liveboard component

In your React app project, go to the **Components ** directory and add a new page for Liveboard in your app directory; for example, `liveboard.tsx`. 

. Import the React library: 
+ 
[source.Typescript]
----
import React from "react";
import { Action, init, EmbedEvent, HostEvent } from "@thoughtspot/visual-embed-sdk";
import { LiveboardEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/react';
----
+
If you are using Webpack 4, which is the default when using `create-react-app v4`, import the React components as shown in this example:

+ 
[source,Typescript]
----
import { LiveboardEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/lib/src/react';
----
+
Optionally, you can use an event logger component to log and track events. 

+ 
[source,Typescript]
----
import { useEventLogger } from "../../utils/utils";
----
. Initialize the SDK and specify the authentication method. 
+
In the following example, the `authType` is set to `SSO` to use SSO authentication for the embedded app users.

+
[source,Typescript]
----
init({
    thoughtSpotHost: 'https://<hostname>:<port>',
    authType: AuthType.SSO,
});
---- 
+
For more information about supported authentication methods and login attributes, see xref:embed-authentication.adoc[Authentication].

. Add constructor options as props and register event listeners.

+
The following example adds the `Liveboard` function with a Liveboard ID and registers the `UpdateRuntimeFilters` event listener. 

+
[source,Typescript]
----
const Liveboard = () => {
  const embedRef = useEmbedRef();
  const logEvent = useEventLogger();
  const [fullHeight, setFullHeight] = React.useState(false);
  const applyFilter = () => {
    embedRef.current.trigger(HostEvent.UpdateRuntimeFilters, [
      {
        columnName: "state",
        operator: "EQ",
        values: ["michigan"]
      }
    ]);
  };
  return (
          <LiveboardEmbed
            frameParams={{
              height: 400
            }}
            ref={embedRef}
            fullHeight={fullHeight}
            liveboardId="d084c256-e284-4fc4-b80c-111cb606449a"
            onInit={logEvent(EmbedEvent.Init)}
            onLoad={logEvent(EmbedEvent.Load)}
            onVizPointDoubleClick={applyFilter}
          />
    );
};
----
+
This example shows how to trigger the `SetVisibleVizs` event when the Liveboard is rendered in the embedded app.

+
[source,Typescript]
----
const Liveboard = () => {
    const embedRef = useEmbedRef();
    const onLiveboardRendered = () => {
        embedRef.current.trigger(HostEvent.SetVisibleVizs, ['3f84d633-e325-44b2-be25-c6650e5a49cf', '28b73b4a-1341-4535-ab71-f76b6fe7bf92']);
    };

    return (
        <LiveboardEmbed
            ref={embedRef}
            liveboardId="<liveboard-guid>"
            onLiveboardRendered={onLiveboardRendered}
        />
    );
};
----

. Render the app

+
----
ts-data-app> npm start
----

=== Test your app

* Load the embedded Liveboard in your app.
* Verify if embedded visualizations are rendered correctly.
* Verify if the actions are disabled or hidden as configured in your app.  
* Check if the registered events are emitted and logged.

=== Code sample for Liveboard embed

[source,Typescript]
----
export const Liveboard = () => {
  const logEvent = useEventLogger();
  const embedRef = useEmbedRef();
  const [fullHeight, setFullHeight] = React.useState(false);
  const applyFilter = () => {
    embedRef.current.trigger(HostEvent.UpdateRuntimeFilters, [
      {
        columnName: "state",
        operator: "EQ",
        values: ["california"],
      },
    ]);
  };
  const selectVizs = () => {
    embedRef.current.trigger(HostEvent.SetVisibleVizs, [
      "3f84d633-e325-44b2-be25-c6650e5a49cf",
      "28b73b4a-1341-4535-ab71-f76b6fe7bf92",
    ]);
  };

  return (
    <LiveboardEmbed
      frameParams={{
        height: 400,
      }}
      ref={embedRef}
      disabledActions=["Action.Share","Action.Delete"]
      disabledActionReason="Contact your administrator"
      fullHeight={fullHeight}
      liveboardId="d084c256-e284-4fc4-b80c-111cb606449a"
      onInit={logEvent(EmbedEvent.Init)}
      onLoad={logEvent(EmbedEvent.Load)}
      onLiveboardRendered={selctVizs}
      onVizPointDoubleClick={applyFilter}
    />
  );
};
----

== Embed a visualization

To embed a ThoughtSpot Liveboard, complete the following steps:

=== Create a visualization component

In your React app project, go to the **Components ** folder in your app directory and add a new page for visualization; for example, `viz.tsx`. 

. Import the React library: 
+ 
[source.Typescript]
----
import React from "react";
import { Action, init, EmbedEvent, HostEvent } from "@thoughtspot/visual-embed-sdk";
import { LiveboardEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/react';
----
+
If you are using Webpack 4, which is the default when using `create-react-app v4`, import the React components as shown in this example:

+ 
[source,Typescript]
----
import { LiveboardEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/lib/src/react';
----
+
Optionally, you can use an event logger component to log and track events. 

+ 
[source,Typescript]
----
import { useEventLogger } from "../../utils/utils";
----

. Pass the constructor options as props and add event listeners. 

+
The following example adds the `viz` function with the Liveboard and visualization IDs, and registers a custom action event to set visible visualizations on a Liveboard. 

+
[source,Typescript]
----
const viz = () => {
  const embedRef = useEmbedRef();
  const onCustomAction = (e) => {
    if (e.id === "only-this-viz") {
      embedRef.current.trigger(HostEvent.SetVisibleVizs, [
        "6d39225c-8845-44b4-b105-910981cdbba8","3f84d633-e325-44b2-be25-c6650e5a49cf"
      ]);
      console.log(JSON.parse(e.data));
    }
  };

  return (
    <LiveboardEmbed
      frameParams={{
        height: 400,
      }}
      ref={embedRef}
      liveboardId="d084c256-e284-4fc4-b80c-111cb606449a"
      vizId="3f84d633-e325-44b2-be25-c6650e5a49cf"
      onCustomAction={onCustomAction}
    />
  );
};
----

. Render the app

+
----
ts-data-app> npm start
----

=== Test your app

* Verify if the embedded visualization is rendered correctly.
* Verify if the actions are disabled or hidden as configured in your app.  
* Check if the registered events are emitted and logged.

=== Code sample for visualization embed

[source,Typescript]
----
const viz= () => {
  const logEvent = useEventLogger();
  const embedRef = useEmbedRef();
  const applyFilter = () => {
    embedRef.current.trigger(HostEvent.UpdateRuntimeFilters, [
      {
        columnName: "state",
        operator: "EQ",
        values: ["michigan"],
      },
    ]);
  };

  return (
    <LiveboardEmbed
      frameParams={{
        height: 400,
      }}
      ref={embedRef}
      disabledActions=["Action.ShareViz","Action.Delete"]
      disabledActionReason="Contact your administrator"
      liveboardId="d084c256-e284-4fc4-b80c-111cb606449a"
      vizId="3f84d633-e325-44b2-be25-c6650e5a49cf"
      onInit={logEvent(EmbedEvent.Init)}
      onLoad={logEvent(EmbedEvent.Load)}
      onLiveboardRendered={selectVizs}
      onVizPointDoubleClick={applyFilter}
    />
  );
};
----

== Embed full app

To full ThoughtSpot application, complete the following steps:

=== Create a full app component

In your React app project, go to the **Components ** folder in your app directory and add a new page for full application embed: for example, `fullApp.tsx`. 

. Import the React library: 
+
[source,Typescript]
----
import React from "react";
import {
  Action,
  init,
  EmbedEvent,
  HostEvent,
  Page
} from "@thoughtspot/visual-embed-sdk";
import { AppEmbed, useEmbedRef } from @thoughtspot/visual-embed-sdk/react';
----
+
If you are using Webpack 4, which is the default when using `create-react-app v4`, import the React components as shown in this example:

+ 
[source,Typescript]
----
import { AppEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/lib/src/react';
----
+
Optionally, you can use an event logger component to log and track events. 

+ 
[source,Typescript]
----
import { useEventLogger } from "../../utils/utils";
----
 
 
+
Note that the import includes `Page`. The `Page` enumeration is required to set a specific ThoughtSpot page as a home tab when the application loads.

. Initialize the SDK and specify the authentication method. 
+
In the following example, the `authType` is set to `SSO` to use SSO authentication for the embedded app users.

+
[source,Typescript]
----
init({
    thoughtSpotHost: 'https://<hostname>:<port>',
    authType: AuthType.SSO,
});
---- 
+
For more information about supported authentication methods and login attributes, see xref:embed-authentication.adoc[Authentication].

. Add constructor options as props and register event listeners. 
+
The following example adds the `FullApp` function with a pageID and registers the `DialogOpen` and `DialogClose` events. 

+
[source,Typescript]
----
const FullApp = () => {
  const logEvent = useEventLogger();
  const embedRef = useEmbedRef();
  const [page, setPage] = React.useState(Page.Home);
  const onDialogOpen = (e) => {
    logEvent(e);
  };
  const onDialogClose = (e) => {
    logEvent(e);
  };

  return (
    <AppEmbed
      frameParams={{
        height: 600,
      }}
      ref={embedRef}
      pageId={page}
      onDialogOpen={onDialogOpen}
      onDialogClose={onDialogClose}
    />
  );
};
----


. Render the app
+
----
ts-data-app> npm start
----

=== Test your app

* Load your application.
* Verify if the page you set as the active tab opens when you load the application.
* If you have disabled a menu item on a ThoughtSpot application page, verify if the menu command is disabled.
* Check if the registered events are emitted and logged.

=== Code sample for full application embed

[source,Typescript]
----
const FullApp = () => {
  const logEvent = useEventLogger();
  const embedRef = useEmbedRef();
  const [page, setPage] = React.useState(Page.Home);
  const onDialogOpen = (e) => {
    logEvent(e);
  };
  const onDialogClose = (e) => {
    logEvent(e);
  };

  const onCustomAction = (e) => {
    if (e.id === "only-this-viz") {
      embedRef.current.trigger(HostEvent.SetVisibleVizs, [
        "6d39225c-8845-44b4-b105-910981cdbba8",
      ]);
      console.log(JSON.parse(e.data));
    }
  };

  return (
    <AppEmbed
      frameParams={{
        height: 600,
      }}
      ref={embedRef}
      pageId={page}
      disabledActions=["Action.Save","Action.Edit"]
      disabledActionReason="Contact your administrator"
      onInit={logEvent(EmbedEvent.Init)}
      onLoad={logEvent(EmbedEvent.Load)}
      onCustomAction={onCustomAction}
      onDialogOpen={onDialogOpen}
      onDialogClose={onDialogClose}
      onRouteChange={logEvent}
    />
  );
};

----

== Add routes for navigation

If your app has multiple pages and you have created a new page for the embedded ThoughtSpot component, make sure you add a route in your app for navigation.  

The following example shows a route for the Liveboard page.

[source,Javascript]
----
import { Route, Routes} from "react-router-dom";
import { Liveboard } from './components/liveboard'

function App() {
 return (
   <div className="App">
     <Routes>
       <Route path="/" element={<h1>Home</h1>} />
       <Route path="/liveboard" element={<Liveboard />} />
       <Route path="/about" element={<About />} />
     </Routes>
   </div>
 );
}
export default App;
----
 
== Additional resources

* For Javascript code examples, see link:https://github.com/thoughtspot/quickstarts/tree/main/react-starter-app[Code samples, windows=_blank].
* For information about events, see xref:embed-events.adoc[Interact with events].
* For information about Action enumerations, see xref:embed-actions.adoc[Show or hide UI actions].
* For more information about the SDK APIs and attributes, see xref:sdk-reference.adoc[Visual Embed SDK Reference].
