= Interact with events
:toc: true
:toclevels: 1

:page-title: Embed events
:page-pageid: events
:page-description: You can subscribe to events emitted by the embedded objects and the host application.

ThoughtSpot supports a range of events that your app can listen to and respond to with appropriate actions. The embedded ThoughtSpot components emit events when they initialize and load, and when a user executes an action inside these components. The host application can also trigger events within the embedded ThoughtSpot objects, causing an alert or other action.

== Types of events

The events in the Visual Embed SDK library are classified as:

* `HostEvent`
+
Events triggered by the host application in which ThoughtSpot components are embedded. 

* `EmbedEvent`
+ 
Events emitted by the embedded ThoughtSpot components. 

== Import event library

Before you begin, make sure you import the events library from the Visual Embed SDK package.

[source,javascript]
----
import { EmbedEvent, HostEvent } from '@thoughtspot/visual-embed-sdk';
----

To trigger events on ThoughtSpot components embedded in a React app, import the `useEmbedRef` hook.

[source,javascript]
----
import { LiveboardEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/react';
----

[#host-events]
== Register, handle, and trigger host events

The following host events are triggered by the host application, which the embedded ThoughtSpot app can register. 
The host events are part of the *HostEvent* object; for example, `HostEvent.SetVisibleVizs`. 
Host events use the `.trigger()` method to send the event message to embedded ThoughtSpot components. The events are sent in the  `.trigger(hostEvent, data)` format.

[div tableContainer]
--
[width="100%" cols="1,2,2,5"]
[options='header']
|======
|Event| Available from|SDK package| Description
|`DrillDown`| [version noBackground]#V1.5.0# | `SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed`
a|
Triggers a drill down event when a user clicks on a specific point in a column. 
[source,javascript]
----
searchEmbed.trigger(HostEvent.DrillDown, {
        points: clickedPointData,
        autoDrillDown: true,
    });
----
In this example, the `VizPointDoubleClick` event is used for triggering the `DrillDown` event when an area or specific data point on a table or chart is double-clicked.

[source,javascript]
----
searchEmbed.on(EmbedEvent.VizPointDoubleClick, (data) => {
    const {
        payload: clickedPointData
    } = data;
    console.log('>>> called', clickedPointData);
    embed.trigger(HostEvent.DrillDown, {
        points: clickedPointData,
        autoDrillDown: true,
    });
})
----

|`Search`| [version noBackground]#V1.1.0#| `SearchEmbed` +
`AppEmbed`  a|

Is triggered when search is executed. The event returns the data source GUID and search query details. +
 
[source,javascript]
----
searchEmbed.trigger(HostEvent.Search)
----
 
|`SetVisibleVizs`| [version noBackground]#V1.6.0#| `LiveboardEmbed` +
`AppEmbed` a|
Sets specific visualizations as visible objects on a Liveboard. The visualization IDs that are not passed in the parameter are hidden on the Liveboard. 

[source, javascript]
----
liveboardEmbed.trigger(HostEvent.SetVisibleVizs, ['viz1', 'viz2'])
----
|`UpdateRuntimeFilters`|[version noBackground]#V1.8.0# | `LiveboardEmbed` +
`AppEmbed` a|
Triggers an event to update runtime filters. The following example shows how to register an event handler to trigger an event when the runtime filters are updated.

[source, javascript]
----
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [{
    columnName: "state",
    operator: "EQ",
    values: ["michigan"]
}]);
----
|======
--

[#embed-events]
== Register, handle, and trigger embed events

The embed events are generated by the embedded ThoughtSpot application components. All embed events are part of the `EmbedEvent` object; for example, `EmbedEvent.Init`.

Embed events are triggered when ThoughtSpot components initialize and load, and when users interact with these components. The `EmbedEvent` library also includes events that can be triggered when an action is initiated in the embedded view. For example, you can register an event handler to trigger `EmbedEvent.Save` when a user clicks the `Save` action on the answer page in the embedded UI. For some of these action-triggered events, you can register event handlers to emit events when the corresponding action starts and ends.  


[div tableContainer]
--
[width="100%" cols="1,2,2,5"]
[options='header']
|======
|Event|Available from|
SDK package|Description
|`ALL` 
 +
|[version noBackground]#V1.11.0#|
 `SearchEmbed` +
 `LiveboardEmbed` +
 `AppEmbed` + 
a|
Triggers all embed events. 

[source, javascript]
----
appEmbed.on(EmbedEvent.ALL, payload => {
    console.log('Embed Events', payload)
})
----
a|`AddRemoveColumns` +
|[version noBackground]#V1.10.0# 
 |
`SearchEmbed` +
`AppEmbed` a|
Is triggered when one or more columns are selected when passing search tokens in a search query. +
Returns the GUIDs of the selected columns. 

[source,Javascript]
----
appEmbed.on(EmbedEvent.AddRemoveColumns, payload => {
    console.log('AddRemoveColumns', payload);
})
----
|`Alert` +
|[version noBackground]#V1.1.0# +
|
`SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` 
a|

Is triggered when the embedded object sends an alert. 
[source]
----
searchEmbed.on(EmbedEvent.Alert)
---- 
|`AnswerChartSwitcher`|[version noBackground]#V1.11.0#| `SearchEmbed` +
`AppEmbed` 

a|Is triggered when a user switches to the chart or table view on the answer page.

[source,Javascript]
----
appEmbed.on(EmbedEvent.AnswerChartSwitcher, payload => {
    console.log('switch view', payload);
})
----

|`AnswerDelete`|[version noBackground]#V1.11.0#| `SearchEmbed` +
`AppEmbed` 

a|Is triggered when the `Delete` action clicked on the answer page.

[source,Javascript]
----
 //trigger when action starts
appEmbed.on(EmbedEvent.AnswerDelete, payload => {
    console.log('delete answer', payload)}, {start: true })
 //trigger when action is completed
appEmbed.on(EmbedEvent.AnswerDelete, payload => {
    console.log('delete answer', payload)})
----

|`AuthInit` +
|[version noBackground]#V1.1.0# |`SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` a| 

Is emitted when authentication is initiated. Returns user GUID as data.  
You can also subscribe to the `AuthInit` event to be notified when user authentication is successful, and `AuthExpire` to trigger an alert when an authenticated session expires.


[source,javascript]
----
appEmbed.on(EmbedEvent.AuthInit, payload => {
    console.log('AuthInit', payload);
})
----
|`AuthExpire` +
|[version noBackground]#V1.4.0#   |`SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed`
a|
Indicates if an authenticated session has expired. +
In this example, the `AuthExpire` event calls the `showAuthExpired` function to show a banner when an authenticated session expires. +
[source,javascript]
----
appEmbed.on(EmbedEvent.AuthExpire, showAuthExpired)
  //show auth expired banner
function showAuthExpired() {
    document.getElementById("authExpiredBanner");
}
----
|`CopyAEdit`|[version noBackground]#V1.11.0# | `AppEmbed` a|
Is triggered when a user clicks *Copy and edit* on a saved answer. +
[source,javascript]
----
 //trigger when action starts
appEmbed.on(EmbedEvent.CopyAEdit, payload => {
  console.log('Copy and edit', payload)}, {start: true })
 //trigger when action ends
appEmbed.on(EmbedEvent.CopyAEdit, payload => {
  console.log('Copy and edit', payload)})  
----
|`CopyToClipboard`|[version noBackground]#V1.11.0# | `SearchEmbed` +
`AppEmbed` a|
Is triggered when a user selects the table cells of an answer and selects *Copy to clipboard* from the context menu. +
[source,javascript]
----
seachEmbed.on(EmbedEvent.CopyToClipboard, payload => {
    console.log('copy to clipboard', payload);
})
----
|`CustomAction` |[version noBackground]#V1.1.0# 
|`SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed`  a|
Is triggered when a custom action is initiated. +
Returns the custom action ID and the response payload with the answer or Liveboard data.
For more information, see xref:embed-events.adoc##customAction[Custom action events]. 
----
appEmbed.on(EmbedEvent.customAction, payload => {
    const data = payload.data;
    if (data.id === 'insert Custom Action ID here') {
        console.log('Custom Action event:', data.embedAnswerData);
    }
})
----
|`Data` |[version noBackground]#V1.1.0# |`SearchEmbed` +
`AppEmbed` + a|
Is triggered when data pertaining to an answer or Liveboard object is received. +
[source, javascript]
----
searchEmbed.on(EmbedEvent.Data, payload => {
    console.log('data', payload);
})
----
|`DataSourceSelected` |[version noBackground]#V1.1.0#
|`SearchEmbed` +
`AppEmbed`  a|
Is triggered when one or more data sources are selected. 
Returns the GUIDs of the data sources selected. 
[source, javascript]
----
searchEmbed.on(EmbedEvent.DataSourceSelected, payload => {
    console.log('DataSourceSelected', payload);
})
----
|`DialogOpen` | [version noBackground]#V1.6.0#
| `SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` a|
Is triggered when a modal dialog is opened.
[source, javascript]
----
appEmbed.on(EmbedEvent.DialogOpen, payload => {
    console.log('dialog open', payload);
})
----
|`DialogClose` |[version noBackground]#V1.6.0# 

| `SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` a| Is triggered when a modal dialog is closed. 
[source, javascript]
----
appEmbed.on(EmbedEvent.DialogClose, payload => {
    console.log('dialog close', payload);
})
----
|`Download`|[version noBackground]#V1.11.0# |`SearchEmbed` +
`AppEmbed` a|
Is triggered when the *Download* action is initiated on a Liveboard or answer and on download completion. +
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.Download, payload => {
    console.log('download', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.Download, payload => {
    console.log('download', payload)})
----
|`DownloadAsCSV`|[version noBackground]#V1.11.0# |`SearchEmbed` +
`AppEmbed` a|
Is triggered when the *Download As CSV* action is initiated on a Liveboard or answer and on download completion. +
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsCSV, payload => {
    console.log('download CSV', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsCSV, payload => {
    console.log('download CSV', payload)})
----
|`DownloadAsPDF`|[version noBackground]#V1.11.0# |`SearchEmbed` +
`AppEmbed` a|
Is triggered when a Liveboard or answer object is downloaded as a PDF file and on download completion. +

[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsPDF, payload => {
    console.log('download PDF', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsPDF, payload => {
    console.log('download PDF', payload)})
----
|`DownloadAsXlsx`|[version noBackground]#V1.11.0# |`SearchEmbed` +
`AppEmbed` a|
Is triggered when the Liveboard or answer data is downloaded as an Excel file and on download completion. +

[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsXlsx, payload => {
    console.log('download Xlsx', payload)}, { start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsXlsx, payload => {
    console.log('download Xlsx', payload)})
----
|`Drilldown` | [version noBackground]#V1.1.0# 
| `SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` a|
Is triggered when the *Drill down* action is executed. +
Returns the IDs of the column on which the drill down operation was performed, any additional filters applied during the operation, and the columns that were not filtered. 

[source,javascript]
----
searchEmbed.on(EmbedEvent.Drilldown, payload => {
    console.log('Drilldown', payload);
})
----
|`DrillExclude`|[version noBackground]#V1.11.0# | `SearchEmbed` +
`AppEmbed` a| 
Is triggered when a filter is applied to exclude a data point in the drilled down view. +
Returns the IDs of the column and the filters applied during the operation. 
[source,javascript]
----
appEmbed.on(EmbedEvent.DrillExclude, payload => {
    console.log('Drill exclude', payload);
})
----
|`DrillInclude`|[version noBackground]#V1.11.0# | `SearchEmbed` +
`AppEmbed` a| 
Is triggered when a filter is applied to include a data point in the drilled down view. +
Returns the IDs of the column and the filters that were applied during the operation. 
[source,javascript]
----
appEmbed.on(EmbedEvent.DrillInclude, payload => {
    console.log('Drill include', payload);
})
----
|`EditTML`|[version noBackground]#V1.11.0#| `SearchEmbed` +
`AppEmbed` a|
Is triggered when a user clicks the *Edit TML* action on the answer page.
[source,javascript]
----
appEmbed.on(EmbedEvent.EditTML, payload => {
    console.log('Edit TML', payload);
})
----
|`ExportTML`|[version noBackground]#V1.11.0# |`SearchEmbed` +
`AppEmbed` a|
Is triggered when a user clicks *Export TML* action on the answer page. 
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.ExportTML, payload => {
    console.log('Export TML', payload)}, { start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.ExportTML, payload => {
    console.log('Export TML', payload)})
----
|`Error` |[version noBackground]#V1.1.0# 
|`SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` a| 
Indicates that an error has occurred. 
[source,javascript]
----
SearchEmbed.on(EmbedEvent.Error, showErrorMsg)
//show error messaage
function showErrorMsg() {
    document.getElementById("error");

----
|`Init` |[version noBackground]#V1.1.0# 
|`SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` a| 
Is triggered when the embedded object rendering initializes. In this example, a showLoader function is called to show a loader when the `Init` event is emitted.

[source,javascript]
----
liveboardEmbed.on(EmbedEvent.Init, showLoader)
  //show a loader
function showLoader() {
    document.getElementById("loader");
}
----

|`LiveboardRendered` |[version noBackground]#V1.9.1#
| `LiveboardEmbed` +
`AppEmbed` a|
Is emitted when a Liveboard has completed rendering. This event can be used as a hook to trigger other events on a rendered Liveboard.
[source,Javascript]
----
liveboardEmbed.on(EmbedEvent.LiveboardRendered, payload => {
    console.log('Liveboard is rendered', payload);
})
----
The following example shows how to trigger `SetVisibleVizs` event using `LiveboardRendered` embed event:

[source, Typescript]
----
const embedRef = useEmbedRef();
const onLiveboardRendered = () => {
embedRef.current.trigger(HostEvent.SetVisibleVizs, ['viz1', 'viz2']);
};
----
|`Load` |[version noBackground]#V1.1.0#
 | `SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` a| 
Indicates if the embedded ThoughtSpot object has loaded.
[source]
----
liveboardEmbed.on(EmbedEvent.Load, hideLoader)
 //hide loader
function hideLoader() {
  document.getElementById("loader");
}
----

|`NoCookieAccess` |[version noBackground]#V1.2.0#
| `SearchEmbed` +
`LiveboardEmbed` +
`AppEmbed` a| 
Is emitted when third-party cookies are blocked by a user's browser. +
In this example, the `NoCookieAccess` event calls the `showCookieSettingsMsg` function to show a message about setting cookies.
[source,javascript]
----
appEmbed.on(EmbedEvent.NoCookieAccess, showCookieSettingsMsg)
----
 
|`Pin`|[version noBackground]#V1.11.0# | `SearchEmbed` +
`AppEmbed` a|

[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.Pin, payload => {
    console.log('pin', payload)
}, {
    start: true
})
 //trigger when action ends
searchEmbed.on(EmbedEvent.Pin, payload => {
    console.log('pin', payload)
})
----
|`QueryChanged` |[version noBackground]#V1.4.0# 
| `SearchEmbed` +
`AppEmbed` a|
Is triggered when a search query is updated.
[source,javascript]
----
searchEmbed.on(EmbedEvent.QueryChanged, payload => console.log('data', payload))
----
|`RouteChange` |[version noBackground]#V1.7.0#
| `AppEmbed` a|
Is triggered when a user navigates from one page to another in the embedded ThoughtSpot app. This event logs the application page URL accessed by a user. 
[source,javascript]
----
searchEmbed.on(EmbedEvent.RouteChange, payload => console.log('data', payload))
----
|`Save` |[version noBackground]#V1.11.0#
| `SearchEmbed`  +
`AppEmbed`
a| 
Is triggered when an answer is saved in the embedded view. 

[source,javascript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.Save, payload => {
    console.log('Save', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.Save, payload => {
    console.log('Save', payload)
})
----
|`SaveAsView`|[version noBackground]#V1.11.0#|
`AppEmbed` a|
Is triggered when Create view action is clicked on an answer page.

|`Share`|[version noBackground]#V1.11.0# |`SearchEmbed` +
`AppEmbed` a|
Is triggered when a user clicks the *Share* icon on the answer page.
[source,javascript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.Share, payload => {
    console.log('Share', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.Share, payload => {
    console.log('Share', payload)
})
----
|`SpotIQAnalyze`|[version noBackground]#V1.11.0#|`SearchEmbed` +
`AppEmbed` a| 
Is triggered when the *SpotIQ Analyze* action is clicked on an answer page.

[source,javascript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.SpotIQAnalyze, payload => {
    console.log('SpotIQAnalyze', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.SpotIQAnalyze, payload => {
    console.log('SpotIQ analyze', payload)
})
----
|`VizPointClick`|[version noBackground]#V1.11.0# |  `SearchEmbed` +
`AppEmbed` a|
Is triggered when an area or data point on a chart is clicked.
[source,javascript]
----
searchEmbed.on(EmbedEvent.VizPointClick, payload => {
    console.log('VizPointClick', payload)
})
----
|`VizPointDoubleClick` |[version noBackground]#V1.5.0#
| `SearchEmbed` +
`AppEmbed` a|
Is triggered when an area or data point on a chart or table is double-clicked.
[source,javascript]
----
searchEmbed.on(EmbedEvent.VizPointDoubleClick, payload => {
    console.log('VizPointDoubleClick', payload)
})
----
|======
--

[#customAction]
== Handle custom action events

If you have added a xref:customize-actions-menu.adoc[custom action], you must register an event handler to send data in a payload when the custom action is triggered:

[source, javascript]
----
searchEmbed.on(EmbedEvent.customAction, payload => {
    const data = payload.data;
    if (data.id === 'insert Custom Action ID here') {
        console.log('Custom Action event:', data.embedAnswerData);
    }
})
----

== Unsubscribe from an event

The following example shows how to unsubscribe from an event:

[source, javascript]
----
appEmbed.off(EmbedEvent.AuthInit)
----

////
== Embed events

The embed events are generated by the embedded ThoughtSpot application components. All embed events are part of the *EmbedEvent* object; for example,  `EmbedEvent.AuthInit`.

[width="100%" cols="2,7,3,3"]
[options='header']
|====
|Event| Description |SDK version| SDK version and Embed package
|`AddRemoveColumns`| Is triggered when a column is selected. The event returns the GUIDs of the selected columns.|Version 1.10.0 or later|
`SearchEmbed`

`LiveboardEmbed`

`AppEmbed`
|`Alert`
|Is triggered when the embedded object sends an alert.|Version 1.1.0 or later | `SearchEmbed`

`LiveboardEmbed`

`AppEmbed` 

|`AuthInit`
| Indicates if a user authentication has either succeeded or failed. The event returns the `IsLoggedIn` attribute with a boolean value.| Version 1.1.0 or later |`SearchEmbed`

`LiveboardEmbed`

`AppEmbed`
|`AuthExpire`|Indicates if an authenticated session has expired. | Version 1.4.0 or later| `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`


|`CustomAction` |Is triggered when a custom action is initiated. The event returns the custom action ID and the response payload with the answer or Liveboard data.| Version 1.1.0 or later | `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`
|`Data`| Indicates that the answer data or Liveboard object is received. | Version 1.1.0 or later| `SearchEmbed`

`AppEmbed`

|`DataSourceSelected`|Is triggered when one or more data sources are selected. The event returns the GUIDs of the data sources selected.| Version 1.1.0 or later | `SearchEmbed`

`AppEmbed`
|`Drilldown`|Is triggered when the drill down action is executed. The event returns the IDs of the column on which the drill down operation was performed, any additional filters applied during the operation, and the columns that were not filtered.|Version 1.1.0 or later| `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`

|`DialogOpen`|Is triggered when a modal dialog is opened.|Version 1.6.0 or later | `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`

|`DialogClose`|Is triggered when a modal dialog is closed.|Version 1.6.0 or later | `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`

|`Error`|Indicates that an error has occurred. |Version 1.1.0 or later | `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`
|`Init`|Indicates if the embedded object rendering has initialized.| Version 1.1.0 or later| `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`
|`Load`|Indicates if the embedded ThoughtSpot object has loaded. | Version 1.1.0 or later| `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`

|`LiveboardRendered`|Is emitted when a Liveboard has completed rendering. This event can be used as a hook to trigger other events on a rendered Liveboard.|Version 1.9.1 or later | `LiveboardEmbed` 

`AppEmbed`

|`NoCookieAccess`|Is emitted when third-party cookies are blocked by a user's browser.|Version 1.2.0 or later| `SearchEmbed`

`LiveboardEmbed`

`AppEmbed`

|`QueryChanged`|Is triggered when a search query is updated. | Version 1.4.0 or later | `SearchEmbed`

`AppEmbed`
|`RouteChange`|Is triggered when a user navigates from one page to another in the embedded ThoughtSpot app. This event logs the application page URL accessed by a user. | Version 1.7.0 or later| `AppEmbed`

|`VizPointDoubleClick`|Indicates that a double-click event has been triggered on a table or chart. |Version 1.5.0 or later| `LiveboardEmbed`

`AppEmbed`

|====
////

== Related resources

* For a complete list of event types that you can register, see  link:{{visualEmbedSDKPrefix}}/enums/embedevent.html[EmbedEvent, window=_blank] and link:{{visualEmbedSDKPrefix}}/enums/HostEvent.html[HostEvent, window=_blank].
* For information about triggering events on React components, see xref:embed-ts-react-app.adoc[Embed ThoughtSpot in a React app].