= Events and app integration
:toc: true
:toclevels: 2

:page-title: Events and app integration
:page-pageid: events-app-integration
:page-description: Events allow the embedding application to send and receive messages from embedded ThoughtSpot components.

ThoughtSpot supports a range of events that your app can listen to and respond to with appropriate actions. The embedded ThoughtSpot components emit events when they initialize and load, and when a user executes an action inside these components. The host application can also trigger events within the embedded ThoughtSpot objects, causing an alert or other action.

== Types of events

The events in the Visual Embed SDK library are classified as:

* `HostEvent` +
Events triggered by the host application in which ThoughtSpot components are embedded.
+
Host events use the `.trigger()` method to send the event message to embedded ThoughtSpot components. The events are sent in the  `.trigger(hostEvent, data)` format.

* `EmbedEvent` +
Events emitted by the embedded ThoughtSpot components.
+
You can define a *listener* for an EmbedEvent with a callback function to handle the event response via the `.on(embedEvent, eventHandlerCallbackFunction)` format.

== Events library

You can import the event library from the Visual Embed SDK package.

[source,javascript]
----
import { EmbedEvent, HostEvent } from '@thoughtspot/visual-embed-sdk';
----

To trigger events on ThoughtSpot components embedded in a React app, import the `useEmbedRef` hook.

[source,javascript]
----
import { LiveboardEmbed, useEmbedRef } from '@thoughtspot/visual-embed-sdk/react';
----
[#use-cases]
== Common use cases

=== Handle load and errors for embed components

A common workflow is to use an overlay `div` element to hide the embed content until you know that SSO has completed, and the content is fully loaded. If an error occurs in the process, you may prefer to display your own custom message to the end user rather than showing embedded ThoughtSpot content in an error state.

Embed events fire at points within the loading process. The following events are related to the load process:

. `Init`
+
Fires at the beginning of the loading process.
. `NoCookieAccess`

+
Some browsers (Safari in particular) default to strict settings on cookie origins that prohibit the standard SSO process. This event fires if cookies are restricted by a user's browser.

. `AuthExpire`
+
Fires if SSO does not complete and if the ThoughtSpot session times out at some point. Listen to the `AuthExpire` event in the load process to determine when it is safe to show the ThoughtSpot content, and listen to it after loading to hide the ThoughtSpot login screen if the session expires for some reason.

. `AuthInit` 
+
Fires when the SSO process has completed correctly. The event does not fire when an SSO process fails, instead `AuthExpire` fires in that situation. The logged-in user GUID is available in the response of the `AuthInit` event.

. `Error` 

+
Fires if any other error occurs in the Visual Embed SDK process. Does not fire for errors within the embedded ThoughtSpot content

. `Load`
+
Fires as soon as the area for embedding is created, not when the content has begun or finished loading.

. `Data`
+
Fires only on `SearchEmbed` components. Does not fire on a `LiveboardEmbed` component.

. `LiveboardRendered`
+
Fires only on `LiveboardEmbed` components, after all visualizations have completed loading.


`AuthExpire` and `AuthInit` can be used together to determine if the SSO process is completed correctly. To determine if `AuthExpire` is firing because SSO did not complete or if the ThoughtSpot session has timed out, you can set a variable to act as a flag to determine if SSO is completed. When `AuthInit` fires, set the flag to *true*. You can also associate a callback function to `AuthExpire` to look up the flag to determine which state change has caused the `AuthExpire` event to fire. In the following example, the `tsLoggedIn` flag is set to indicate the SSO login state. 

[source,javascript]
----
// Instantiate class for embedding a Liveboard
const embed = new LiveboardEmbed("#thoughtspot-embed", {
    liveboardId: '<Liveboard-guid>',
});
let tsLoggedIn = false;
embed
    .on(EmbedEvent.Init, showLoader)
    .on(EmbedEvent.NoCookieAccess, showCookieSettingsMsg)
    .on(EmbedEvent.AuthInit, (response) => {
        // Set that AuthInit has fired
        tsLoggedIn = true;
        // authInit returns object -> {type: 'authInit', data: {userGuid: <guid>} } }
        let userGUID = response.data.userGuid;
    })
    .on(EmbedEvent.AuthExpire, (response) => {
        // Handle if session dies while content shows
        if (tsLoggedIn == true) {
            tsSessionTimeoutCleanup();
        } else {
            // Display custom message if SSO issues
            showSSOFailedMsg();
        }
    })
    .on(EmbedEvent.Error, showGenericErrorMsg)
    .on(EmbedEvent.LiveboardRendered, hideLoader)
    .render()
----

=== Filters in embedded UI
xref:runtime-filters.adoc[Runtime filters] can be set programmatically before loading the embedded ThoughtSpot content in the `options` object set in the `LiveboardEmbed` component constructor.

Runtime filters can be updated after load time by triggering the `HostEvent.UpdateRuntimeFilters` event. You can build the filter UI in the embedding app, which triggers the `UpdateRuntimeFilters` event when changed or with the click of an `apply` button.

==== Filtering from selection
Filtering from a selection on a chart or table can be implemented by combining the `EmbedEvent.VizPointClick` or `EmbedEvent.VizPointDoubleClick` events with the `HostEvent.UpdateRuntimeFilters` event.

The callback function from the `VizPointClick` event will need to read the response, parse out the attributes from the response that will be sent to the Runtime Filters, and then send the attributes and their target fields in the format used by `UpdateRuntimeFilters`.

==== ThoughtSpot filters overview
ThoughtSpot Liveboards have four levels of filters. 

Row-level security (RLS) rules::
Tied to the logged-in user and their group memberships. Completely secure and cannot be altered by the logged-in user.
Runtime filters::
Set via the Visual Embed SDK or URL parameters. Runtime filters do not display as UI filter components.
Answer filters::
Established via the search definition, not visible as UI filter components on a Liveboard, but can be viewed in **Explore** or *Edit* modes.
Liveboard filters::
Visible as UI components at the top of a Liveboard, affecting all visualizations on the Liveboard.

=== Modify SearchEmbed behavior
The `hideResults` parameter in the options object of a `SearchEmbed` constructor blocks the *GO* button from displaying the chart or table results. When this option is *true*, you can listen to the `QueryChanged` event to perform actions based on the user's interaction within the `SearchEmbed` component.

==== SearchEmbed Events
There are several events that fire only on the SearchEmbed component:

* `DataSourceSelected`
+
Fires when a change occurs in the data sources, including the initial load of the `SearchEmbed` component. Can be used to hide a loader screen. Return object contains an array of the selected column GUIDs (accessible using `LOGICAL_COLUMN` type within metadata REST API commands).

* `QueryChanged`
+
Fires when a change occurs in the search bar, including the initial load of the `SearchEmbed` component. The returned object includes a `data.search` property with the TML search query from the search box.

[#customAction]
== Handle custom action events

If you have added a xref:customize-actions-menu.adoc[custom action] set as a xref:custom-action-callback.adoc[callback action], you must register an event handler to send data in a payload when the custom action is triggered:

[source, javascript]
----
searchEmbed.on(EmbedEvent.customAction, payload => {
    const data = payload.data;
    if (data.id === 'insert Custom Action ID here') {
        console.log('Custom Action event:', data.embedAnswerData);
    }
})
----

== Related resources
* For a complete list of host and embed events, see xref:events-ref.adoc[Events reference].
* For a complete list of event types, see  link:{{visualEmbedSDKPrefix}}/enums/EmbedEvent.html[EmbedEvent, window=_blank] and link:{{visualEmbedSDKPrefix}}/enums/HostEvent.html[HostEvent, window=_blank] SDK documentation.
* For information about triggering events on React components, see xref:embed-ts-react-app.adoc[Embed ThoughtSpot in a React app].
