= Event subscription and handling
:toc: true
:toclevels: 1

:page-title: Embed events
:page-pageid: events
:page-description: ThoughtSpot Events 

ThoughtSpot supports a range of events that your app can listen to and respond with an appropriate action. The embedded ThoughtSpot components emit events when they initialize and load, and when a user executes an action inside these components. The embedded ThoughtSpot objects can also listen to the events triggered by their host application and trigger an alert or action. 

== How to register and handle events

Before you begin, make sure you import the events library from the Visual Embed SDK package.

[source,javascript]
----
import { EmbedEvent } from '@thoughtspot/visual-embed-sdk';
----

The following code snippet shows how to register the `Init` event for the embedded ThoughtSpot pinboards. 

[source, javascript]
----
pinboardEmbed.on(EmbedEvent.Init, showLoader)
----

The `Init` event is generated when the embedded object rendering initializes. In the above example, a `showLoader` function is called to show a loader when the `Init` event triggers. 

You can also subscribe to the `AuthInit` event to be notified when user authentication is successful, and `AuthExpire` to trigger an alert when an authenticated session expires.

[source, javascript]
----
appEmbed.on(EmbedEvent.AuthInit)
---- 

In the following example, the `AuthExpire` calls the `showAuthExpired` function to show a banner when an authenticated session expires.

[source, javascript] 
---- 
appEmbed.on(EmbedEvent.AuthExpire, showAuthExpired)
----

=== Custom action events

If you have added a xref:customize-actions-menu.adoc[custom action], you must register an event handler to send data in a payload when the custom action is triggered:

[source, javascript]
----
 searchEmbed.on(EmbedEvent.customAction, payload => {
	const data = payload.data;
	if(data.id === 'insert Custom Action ID here') {
		console.log('Custom Action event:', data.embedAnswerData);
	}
})
----

== Unsubscribe from an event

The following example shows how to unsubscribe from an event:

[source, javascript] 
---- 
appEmbed.off(EmbedEvent.AuthInit)
----

== Embed events

The embed events are generated by the embedded ThoughtSpot application components. 

[width="100%" cols="1,4"]
[options='header']
|===
|Event| Description
|`Alert` 
|Is triggered when the embedded object sends an alert.
|`AuthInit` 
| Indicates if a user authentication has either succeeded or failed. The event returns the `IsLoggedIn` attribute with a boolean value.
|`AuthExpired`|Indicates if an authenticated session has expired.
|`CustomAction` |Is triggered when a custom action is initiated. The event returns the custom action ID and the response payload with the answer or pinboard data.
|`Data`| Indicates that the answer data or pinboard object is received.
|`DataSourceSelected`|Is triggered when one or more data sources are selected. The event returns the GUIDs of the data sources selected.
|`Drilldown`|Is triggered when a drilldown action is executed. The event returns the IDs of the column on which the drill down operation was performed, any additional filters applied during the operation, and the columns that were not filtered.
|`Error`|Indicates that an error has occurred.
|`Init`|Indicates if the embedded object rendering has initialized.
|`Load`|Indicates if the embedded ThoughtSpot object has loaded.
|`QueryChanged`|Is triggered when a search query is updated. 
|`NoCookieAccess`|Is emitted when third-party cookies are blocked by a user's browser.
|===

== Host events

The host events are triggered by the host application that the embedded ThoughtSpot app can register.

[width="100%" cols="2,4"]
[options='header']
|===
|Event| Description
|`Search`| Triggers search. The event returns the data source GUID and search query details.
|`DrillDown`| Triggers a drill down event when a user clicks on specific points in a column.
|===

== Related resources

For a complete list of event types that you can register, see  link:{{visualEmbedSDKPrefix}}/enums/embedevent.html[EmbedEvent, window=_blank].
