== Embed ThoughtSpot Search
:toc: true

:page-title: Embed Search
:page-pageid: search-embed
:page-description: Embed Search

This topic provides instructions for embedding the ThoughtSpot search function. The embedded Search API enables external applications to search for data from one or several data sources.

=== Import the JavaScript library
In your .html page, include the JavaScript file in the `<script>` tag under `<head>`:
[source,javascript]
----
<script type="text/javascript" src="<file-location>/<file-name>.js"></script>
----
=== Import the SearchEmbed package
Import the SearchEmbed SDK library to your application environment:

[source,javascript]
----
import { init, SearchEmbed } from "ts-embed-sdk";
----
=== Import styles
[source,javascript]
----
import "./styles.css"
----
=== Add the embed domain

To allow your client application to connect to ThoughtSpot:

. Configure the URL with ThoughtSpot hostname or IP address.
. Specify the authentication method to use for authenticating application users.
+
[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: "SSO"
    });
----
+
thoughtSpotHost::
_String_. Hostname or IP address of the ThoughtSpot application.
+
---

authType::
[horizontal]
SSO::
SAML SSO authentication method. Users accessing the embedded content are authenticated with SAML SSO.
AuthServer::
Trusted authentication method. The trusted authentication method enables applications to exchange secure tokens and grant access to the embedded content. If this authentication method is used, define the `authEndpoint`  attribute.
+
authEndpoint::
_String_. The endpoint URL of the authentication server.
None::
Requires no authentication. The user must already be logged in to ThoughtSpot before interacting with the embedded content.
+
This approach is used only for testing client applications. Do not use this in production environments.

---
=== Create an instance of the search object
Create an instance of the SearchEmbed object and customize your search page view.

[source,javascript]
----
const SearchEmbed = new SearchEmbed(
    document.getElementById('ts-embed'), {
    frameParams: {
        width: '100%',
        height: '100%'
    },
    collapseDataSources:false,
    hideDataSources: true,
    hideResults: false,
    enableSearchAssist: true,
    disabledActions: [],
    });

----
==== Search Page UI Attributes
frameParams:: Sets the `width` and `height` dimensions to render the iframe in the web browser.
---
collapseDataSources [small]*_optional_*::
_Boolean_. When set to true, collapses the list of data sources on the Data Source panel.

---
 hideDataSources [small]_optional_::
_Boolean_. When set to true, it hides the Data Source panel.

---
hideResults [small]_optional_::
_Boolean_. When set to true, it hides charts and tables in search answers.

---
enableSearchAssist [small]_optional_::
_Boolean_. When set to true, it enables search assistance.

---
disabledActions [small]_optional_::
_String_. Disables the specified menu item from the list of actions in the search answer page.
+
For example, to hide the *Show underlying data* action from the (*...*) menu, add `showUnderlyingData` to the  `disabledActions` attribute.

---
disabledActionReason [small]_optional_::
_String_. Indicates the reason for disabling an action from the search answer page view.

---

=== Construct the URL and render the embedded search
Construct the URL of the embedded ThoughtSpot search object to load in the iframe.
Render the embedded search and pass parameters such as data source ID.
[source, javascript]
----
searchEmbed.render({
    dataSources,
    searchQuery,
    answerId,
  }: SearchRenderOptions = {}): SearchEmbed {
     super.render();
     const src = this.getIFrameSrc(answerId, dataSources, searchQuery);
    this.renderIFrame(src, this.viewConfig.frameParams);
 return this;
    }

----
==== Attributes for rendering search
dataSources::
_String_. The Global Unique Identifier (GUID) of the data sources for searching data.

---
answerID::
_String_. The GUID of the search answers saved in a user a profile.

---
searchQuery::
_String_. The search query string to use when the application loads.

---

=== Subscribe to events
Register event handlers to subscribe to events triggered by the ThoughtSpot Search function:
[source, javascript]
----
 search.on("init", showLoader)
 search.on("load", hideLoader)
 search.on("answerPageLoading", payload =>
    console.log("message received from embedded view" + JSON.stringify(payload))

// Functions to show or hide a loader while the iframe loads.
 function showLoader() {
    document.getElementById("loader").style.display = "block";
    }

 function hideLoader() {
    document.getElementById("loader").style.display = "none";
    }
----
////
==== Event Type
init::
The search iframe is initiaized.
load::
The search iframe is loaded.
queryChanged::
The search query is modified.
dataSourceSelected::
The data source for searching data is selected.
////

=== Test the embedded workflow

To verify the ThoughtSpot Search integration, perform the following tasks:

* Load your application.
* Search for data from a data source.
* Verify if the page view parameters, such as hiding or showing the data source panel, function as expected.
* If you have disabled a menu item from the search visualizations page, verify if the menu command is disabled.

=== Code sample

++++
<a href="{{tshost}}/#/everywhere/playground/search">Preview in Playground</a>
++++

