= Embed user authentication
:toc: true
:toclevels: 1

:page-title: Embed authentication
:page-pageid: embed-auth
:page-description: Embed authentication

You can use any of the following authentication methods to authenticate your application users and allow access to the embedded ThoughtSpot content.

* xref:embed-authentication.adoc#saml-sso-embed[SAML SSO authentication]
* xref:embed-authentication.adoc#trusted-auth-embed[Trusted authentication]
* xref:embed-authentication.adoc#basic-auth-embed[Basic authentication with ThoughtSpot login API]
* xref:embed-authentication.adoc#no-auth-embed[No authentication]

[IMPORTANT]
====
ThoughtSpot recommends that you use the SAML SSO or trusted authentication method to authenticate embed users in production environments.
====

== Authentication methods

[#saml-sso-embed]
=== SAML SSO authentication
To allow federated users to sign in to ThoughtSpot with their SSO credentials, you can enable SAML authentication on ThoughtSpot. With SSO, you can use your host application or an external service as the identity provider, and allow authenticated users to access ThoughtSpot content.

==== Prerequisites
To use SAML SSO authentication, the ThoughtSpot administrator must enable SAML authentication and add the SAML redirect domains to the allowed list. For more information, see xref:configure-saml.adoc[SAML SSO].

==== Enable SSO authentication in Visual Embed SDK

To configure SAML SSO authentication for embed users, set the `authType` attribute to `SSO`. 

[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: AuthType.SSO,
    });

----

If you want the SAML SSO authentication workflow to open in a pop-up window, instead of refreshing the application page to show the SAML login page, you can set the `noRedirect` parameter to `true`.

[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: AuthType.SSO,
        noRedirect: true,
        
    });

----

[#trusted-auth-embed]
=== Trusted authentication

This method requires you to xref:trusted-authentication.adoc#trusted-auth-enable[enable trusted authentication] on ThoughtSpot. In this method, ThoughtSpot users are required to obtain an authentication token to access ThoughtSpot content. 
 
==== Key attributes

* Secret key
+
When ThoughtSpot administrator enables trusted authentication in the *Develop* > *Customization* > *Security Settings* page, ThoughtSpot server obtains a `secret_key` from the authentication server. Administrators can use this key to obtain an authentication token for a ThoughtSpot user. 

* Authentication endpoint
+
The URL endpoint of the server that provides the authentication token.

* Username
+
The `username` of the user for which the token must be obtained.  

==== Configure trusted authentication method in Visual Embed SDK

To configure trusted authentication method in the Visual Embed SDK, set the `authType` attribute as `AuthServer`. You can either use the `authEndpoint` attribute or the `getAuthToken` function to get token.

If `authEndpoint` is defined, a GET request is sent to the specified authentication endpoint URL. The authentication server sends the token as a plain text in response.

[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: AuthType.AuthServer,
	    username: "<username>",
        authEndpoint: "https://authenticator-server:<port>/endpoint",
    });
----

You can also use the `getAuthToken` function, which invokes the trusted authentication endpoint and returns a `Promise` string that resolves to the authentication token. 

[source,javascript]
----
getAuthToken: () => Promise.resolve(token) 
----

[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: AuthType.AuthServer,
	    username: "<username>",
        getAuthToken: () => Promise.resolve(token),
    });
----

After obtaining the token, a GET request to the `/tspublic/v1/session/login/token` endpoint is sent with the `username` and authentication token. If the request is successful, the SDK renders the embedded content. 

[#basic-auth-embed]
=== Basic authentication with ThoughtSpot login API

In this method, users can log in to ThoughtSpot by sending a POST request to `xref:session-api.adoc#session-login[/tspublic/v1/session/login]` API endpoint. Users can pass their `username` and `password` in the API `POST` request to authenticate and access ThoughtSpot content.  `/tspublic/v1/session/login` API. For more information, see xref:session-api.adoc[Session API]. 

To enable basic authentication method in the Visual Embed SDK, set the `authType` attribute to `Basic` as shown here:

[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: AuthType.Basic,
    });

----

[WARNING]
You can use this authentication method for initial development and testing. ThoughtSpot does not recommend this authentication method for production environments.

[#no-auth-embed]
=== No authentication
You can choose to specify no authentication method for your users. The local ThoughtSpot users  who are already logged into your application can access the embedded ThoughtSpot content.   

To allow your logged-in application users to access ThoughtSpot content without any authentication, set the `authType` attribute to `None` as shown here:

[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: AuthType.None,
    });

----

[WARNING]
====
Do not use this authentication method in production environments.
====

[#embed-session-sec]
== Session security

include::{path}/embed-config.adoc[]