= Embed Pinboards
:toc: true

:page-title: Embed Pinboards
:page-pageid: embed-pinboard
:page-description: Embed Pinboards


This page explains, through an example, how to embed a ThoughtSpot Pinboard in your Web page, portal, or application.
////
To build this sample, you must have access to a text editor and a ThoughtSpot instance with a visualization.
Experience working with Javascript also helps.
////
=== Import the JavaScript library
In your .html page, include the JavaScript file in the `<script>` tag under `<head>`:
[source,javascript]
----
<script type="text/javascript" src="<file-location>/<file-name>.js"></script>
----
=== Import the PinBoardEmbed package
Import the pinboard SDK library to your application environment:

[source,javascript]
----
import { init, PinboardEmbed } from "ts-embed-sdk";
----
=== Import styles
[source,javascript]
----
import "./styles.css"
----

=== Add the embed domain

To allow your client application to connect to ThoughtSpot:

. Configure the URL with ThoughtSpot hostname or IP address.
. Specify the authentication method to use for authenticating application users.
+
[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: "SSO"
    });
----
+
thoughtSpotHost::
_String_. Hostname or IP address of the ThoughtSpot application.

+
---
authType::
[horizontal]
SSO::
Enables SAML SSO authentication method.
AuthServer::
Trusted authentication method. The trusted authentication method enables applications to exchange secure tokens and grant access to the embedded content. If this authentication method is used, define the `authEndpoint`  attribute.
authEndpoint::
_String_. The endpoint URL of the authentication server.
None::
Requires no authentication. The user must already be logged in to ThoughtSpot before interacting with the embedded content.
+
This approach is used only for testing client applications. Do not use this in production environments.

---
=== Construct the embed content
[source,JavaScript]
----
 const embed = new PinboardEmbed("#embed", {
	frameParams: {
		width: 1280,
		height: 720
	},
	disabledActions: [],
	hiddenActions: [],
});
----
==== Pinboard Page UI Attributes
frameParams:: Sets the `width` and `height` dimensions to render the iframe containing the pinboard.

---
fullHeight:: 
_Boolean_. Sets the pinboard page to full height.

---
disabledActions:: 
_String_. Menu items from the list of actions to be disabled on the Pinboards  page. 
+
For example, to disable the *Present* action from the (*...*) menu, add `present` to the  `disabledActions` attribute.

---
hiddenActions::
_String_. Menu items from the list of actions to be hidden on the Pinboards  page.
+
For example, to hide *Add filters* action from the  (*...*) menu, add `Add filters` to the `hiddenActions` attribute.

---
disabledActionReason::
_String_. Reason for disabling an action on the Pinboards page.

---
=== Render the embedded pinboard
Costruct the URL for the embedded pinboard and render the embedded content:
[source,JavaScript]
----
  PinboardEmbed.render({
        pinboardId,
        vizId,
        runtimeFilters,
    }: PinboardRenderOptions): PinboardEmbed {
        super.render();
        
        const src = this.getIFrameSrc(pinboardId, vizId, runtimeFilters);
        this.renderV1Embed(src);

        return this;
    }
----
==== Attributes for rendering pinboards
pinboardId::
_String_. The GUID of the pinboard.

---
vizId [small]_optional_:: 
_String_. The Global Unique Identifier (GUID) of the visualizations added to the pinboard.

---
runtimeFilters [small]_optional_::
Runtime filters to be applied when the Pinboard page loads.
+ 
Runtime filters provide the ability to filter data at the time of retrieval. Runtime filters allow you to apply a filter to a visualization in a pinboard and pass filter specifications in the URL query parameters. 
+
For example, to sort values equal to `red` in the `Color` column for a visualization in a pinboard, you can pass the runtime filter in the URL query parameters as shown here:
+
----
http://<thoughtspot_server>:<port>/
?col1=<column_name\>&op1=EQ>&val1=red#/pinboard/<pinboardId>/<vizId>
----
Runtime filters have several operators you can use to filter your embedded visualizations.
+
[width="100%" cols="1,2,1"]
[options='header']
|===
|Operator |Description  |Number of Values

| `EQ`
| equals
| 1

| `NE`
| does not equal
| 1

| `LT`
| less than
| 1

| `LE`
| less than or equal to
| 1

| `GT`
| greater than
| 1

| `GE`
| greater than or equal to
| 1

| `CONTAINS`
| contains
| 1

| `BEGINS_WITH`
| begins with
| 1

| `ENDS_WITH`
| ends with
| 1

| `BW_INC_MAX`
| between inclusive of the higher value
| 2

| `BW_INC_MIN`
| between inclusive of the lower value
| 2

| `BW_INC`
| between inclusive
| 2

| `BW`
| between non-inclusive
| 2
|===

---
=== Subscribe to events
Register event handlers and subscribe to events triggered by the embedded pinboard:
[source, javascript] 
----
  //register event listeners for initializing pinboard loading event
  
  embed.on("init", showLoader)
  embed.on("load", hideLoader)
----
////
==== Event Types
init::
The visualization iframe is initiaized.
load::
The visualization iframe is loaded.
filtersChanged::
New filters applied for the visualization
drilldown::
Visualization drilldown is initiated.
////

=== Test the embedded workflow

* Load the client application. 
* Try accessing a pinboard embedded in your application.
* Verify the iframe rendition.
* If you have disabled a menu item, verify if the menu command is disabled on the Pinboards page.
* Verify the runtime filters.

=== Code sample

++++

<a href="{{tshost}}/#/everywhere/playground/pinboard" id="preview-in-playground">Preview in Playground</a>

++++
