= Embed Liveboards without the Visual Embed SDK

:page-title: Embed Liveboards without Visual Embed SDK
:page-pageid: embed-without-sdk
:page-description: Embed Liveboards without the Visual Embed SDK

The Visual Embed SDK is the most convenient way to embed all of the different types of ThoughtSpot content, but there are certain situations where the system you want to embed into does not have a way to use the Visual Embed SDK JavaScript library.

In these situations, you can embed ThoughtSpot Liveboards or individual visualizations from a Liveboard using a directly created iframe tag.

== Construct URL for direct iframe embed
The pattern for the URL to embed a Liveboard is:

`https://{thoughtspotserver}/?embedApp=true#/embed/viz/{Liveboard_id}`

If you want to embed an individual visualization from a Liveboard, use the following URL pattern:

`https://{thoughtspotserver}/?embedApp=true#/embed/viz/{Liveboard_id}/{visualization_id}`

You can specify link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/about-runtime-filters.html[runtime filters, window=_blank] in the URL.


== SSO considerations
When doing a direct embed, xref:configure-saml.adoc[SAML] is typically the only SSO mechanism that can be implemented.

If you cannot use the Visual Embed SDK, this typically means the environment you are embedding ThoughtSpot within has restrictions on using JavaScript, which limits the ability to use the xref:trusted-authentication.adoc[Trusted Authentication] method for SSO. Any sign-in method to ThoughtSpot creates a session, stored in the browser cookies, so if your platform has a way to complete the trusted authentication flow at some point, even on a different page from where the direct iframe embed of a Liveboard is, then it may be a viable SSO mechanism.

== Simple embedding in Salesforce
If you have configured ThoughtSpot to use the same SAML provider as a Salesforce instance, you can create a simple Visualforce page that can embed ThoughtSpot Liveboards or individual visualizations.

First, as a developer, choose 'Create a New Visualforce Page'.

The following code example can be used to define the new page. It defines the iframe, with the ThoughtSpot URL using a runtime filter to personalize the results to the Salesforce user:

[source, xml]
----
<apex:page standardController="Account" tabStyle="Account">
<apex:pageBlock title="ThoughtSpot">
<apex:iframe src="https://{thoughtspot-server}/?embedApp=true#/embed/viz/{Liveboard_id}/{visualization_id}/?col1={field_name}&op1=EQ&val1={!account.Name}" frameborder="0" height="690" width="100%">
</apex:iframe>
</apex:pageBlock>
</apex:page>
----

Note that the `{!account.Name}` is a Salesforce APEX variable. The other curly braces represent permanent values from your ThoughtSpot instance that you would hardcode into the APEX page.

More complex integrations to Salesforce, utilizing the Visual Embed SDK, can be achieved using Lightning components. Please contact your ThoughtSpot team if you are interested in additional integration beyond what is described on this page.

== Mobile apps
Rather than using a direct iframe embed, it is easier on mobile devices to use the xref:pinboarddata.adoc[pinboarddata REST API] to pull only the data values and then render them using a table or charting library native to the mobile platform.
