= Authentication
:toc: true
:toclevels: 2

:page-title: Embed authentication
:page-pageid: embed-auth
:page-description: Define the authentication method in the Visual Embed SDK to authenticate users of an embedded instance.

Visual Embed SDK supports several authentication options to authenticate and authorize the users of an embedded ThoughtSpot view.

== Supported authentication methods

You can use one of the following authentication methods to authenticate your application users and allow them to access the embedded ThoughtSpot content. 

* xref:embed-authentication.adoc#no-auth-embed[No authentication] 
* xref:embed-authentication.adoc#basic-auth-embed[Basic authentication]
* xref:embed-authentication.adoc#saml-sso-embed[SAML SSO authentication]
* xref:embed-authentication.adoc#trusted-auth-embed[Trusted authentication]
* xref:embed-authentication.adoc#oidc-auth[OpenID Connect authentication]

[IMPORTANT]
====
If you are developing or testing code for embedding ThoughtSpot in your host app, you might want to use basic authentication with `username` and `password`, or no authentication. For production environments, ThoughtSpot strongly recommends using SAML SSO, OIDC, or trusted authentication. 
====

[#no-auth-embed]
=== No authentication

In development and testing environments, you can choose not to use any authentication method. To allow your logged-in application users to access ThoughtSpot content without any authentication, set the `authType` attribute to `None` as shown here:

[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.None,
});
----

[WARNING]
====
Do not use this authentication method in production environments.
====

[#basic-auth-embed]
=== Basic authentication

The basic authentication option in the SDK sends a `POST` request with the `username` and `password` of the user to the `xref:session-api.adoc#session-login[/tspublic/v1/session/login]` API endpoint. This option allows users to log in to the embedded ThoughtSpot view  with their `username` and `password`.

To enable basic authentication method in the Visual Embed SDK, set the `authType` attribute to `Basic` as shown here:

[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.Basic,
});
----

[WARNING]
====
ThoughtSpot does not recommend this authentication method for production environments.
====

[#saml-sso-embed]
=== SAML SSO authentication
If your organization uses an identity provider (IdP) and SAML SSO to authenticate your application users, you can configure the `SAML` auth type to authenticate ThoughtSpot users. With SAML SSO, you can allow federated users to access ThoughtSpot content with their SSO credentials.

To use SAML SSO authentication, the administrator must enable SAML authentication on ThoughtSpot and add the SAML redirect domains to the allowed list. For more information, see xref:configure-saml.adoc[SAML SSO].

==== Enable SSO authentication in Visual Embed SDK

To configure SAML SSO authentication for embed users, set the `authType` attribute to `SAML`.

[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.SAML,
});
----

The SAML authentication workflow occurs when the actual ThoughtSpot content is loaded into the iframe generated by the Visual Embed SDK.  If the user is not logged into the IdP, the IdP presents its login page. When the user enters SSO credentials, the IdP sends the assertion to ThoughtSpot.

The user should have already gone through the SAML flow when entering the embedding application before accessing any ThoughtSpot content. For the SSO experience to be completely seamless, the user must already have a valid session with the IdP, so that the IdP automatically sends a SAML assertion back to ThoughtSpot.

==== SAML redirection

If you want the SAML SSO authentication workflow to terminate on a specific path on the host origin, you can set the redirect path in the `redirectPath` attribute. For example, when a user's attempt to sign on using SSO fails, you might want to redirect your users to the main page or a specific application page, instead of showing your application in an error state. 

[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.SAML,
    redirectPath: "/dashboard",
});
----

If you want the SAML SSO authentication page to open as a pop-up window, instead of refreshing the application page to show the SAML login page, you can set the `noRedirect` parameter to `true`.

[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.SAML,
    noRedirect: true,
});
----

[#oidc-auth]
=== OpenID Connect SSO authentication 

If your app supports OAuth 2.0 protocol and requires OIDC authentication framework, you can enable the OpenID Connect authentication on your embedded ThoughtSpot instance.

Before you enable the OIDC authentication type, make sure your ThoughtSpot instance is xref:configure-oidc.adoc[integrated with the OpenID provider and set up for OIDC authentication]. 

[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.OIDC,
});
----

Optionally, you can configure a `redirectPath` string to redirect embed users to a specific application page. 

----
redirectPath: "/dashboard"
----

[#trusted-auth-embed]
=== Trusted authentication

In the trusted authentication method, a security token is required to authenticate users who request access to the embedded ThoughtSpot content. For token-based authentication, you will require an authenticator server or service, which can securely authenticate your application users. 

For token-based authentication, the following attributes are required:

* Secret key
+
The token-based authentication requires you to xref:trusted-authentication.adoc#trusted-auth-enable[enable trusted authentication] on ThoughtSpot to ensure that your authenticator server has access to a ThoughtSpot secret key. This secret key allows the authenticator server to request a login token __for any user__ on the ThoughtSpot Server. The login token is then sent to the user's web browser, where it is used in the login process.

* Username
+
The `username` of the user for whom the token is required.  

* Authentication endpoint
+
The URL endpoint of the server that provides the authentication token.

==== Configure token-based authentication method in Visual Embed SDK

To configure the token-based authentication method in the Visual Embed SDK, set the `authType` attribute as `AuthServer`. 

To obtain authentication tokens, you can either set the `authEndPoint` attribute or call the `getAuthToken` method:  

* `**authEndpoint**`
+
Specify the authentication endpoint URL from which you want to obtain the authentication token. When a `GET` request is sent to the specified endpoint URL to obtain the token, the authentication server sends the token as plain text.  

+
[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.AuthServer,
    username: "<username>",
    authEndpoint: "https://authenticator-server:<port>/endpoint",
});
----

* `**getAuthToken**` +

+
You can call the `getAuthToken` function to invoke your login endpoint. The login endpoint then returns a `Promise` string that resolves to an authentication token.

+
[NOTE]
====
The generated authentication token is valid for only five minutes. Make sure the `getAuthToken` function returns a fresh token for each re-login. 
Using older tokens to renew a user session will lead to authentication failure. 
====

+
[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.AuthServer,
    username: "<username>",
    getAuthToken: () => Promise.resolve(token),
});
----

+
After obtaining the token, a GET request to the `/tspublic/v1/session/login/token` endpoint is sent with the `username` and authentication token. If the request is successful, the SDK renders the embedded content.

When a user session expires, the embedded app redirects its users to the login page. To refresh a user session and automatically log in a user to the embedded app, you can set the `disableLoginRedirect` and `autoLogin` attributes to `true`.

----
disableLoginRedirect: true,
autoLogin: true,
----

Unlike the SAML workflow, the trusted authentication workflow logs in via AJAX requests that are not visible to the end-user, even if they fail. Use the event emitter returned by the `init` call to listen to the login failure events. You can also register an event handler to trigger the xref:embed-events.adoc[AuthInit event] to detect and respond to errors in the login process.

== Authentication errors and event handling

The user authentication may fail due to an incomplete SSO login process, expired user session, SDK initialization error, or if the browser has blocked third-party cookies. 

The `init` method returns an event emitter, which you can use to listen to `AuthStatus` such as authentication failure, success, or user logout, and respond to these events with a message or corrective action.

[source,Typescript]
----
authStatus = init(embedConfig); authStatus.on(AuthStatus.FAILURE, (reason) => { 
console.log('Authentication failed');
});
----

[NOTE]
====
The `EventEmitter` returned from `init` supports listening to only authentication status events such as `AuthStatus.SUCCESS`, `AuthStatus.FAILURE`, and `AuthStatus.LOGOUT`.
====

If you want to display a message in the embedded UI when a user login fails, include the `loginFailedMessage` property in your `init` call.
By default, the attribute displays the `Not logged in` message in the embedded UI. To customize this message, define a string with custom text or markup as shown here:

----
loginFailedMessage: "Authentication failed! Please try again."  
----

----
loginFailedMessage: "<div> <h3> Please enable third-party cookies</h3> <img src='<image url'> </div>"
----

You can also register event handlers to trigger the following events:

* `NoCookieAccess` 
+
Emitted if cookies are restricted by a user's browser. 

* `AuthExpire`
+
Emitted if the SSO does not complete and if the ThoughtSpot session times out at some point.

* `AuthInit` 
+
Emitted when the authentication is completed. 

For more information about triggering these events, see xref:embed-events.adoc[Interact with events].

== User logout

To log out embed users, you can use the `Logout` method to call the `xref:session-api.adoc#session-logout[/callosum/v1/session/logout]` API endpoint.

[source,Typescript]
----
import { logout } from "@thoughtspot/visual-embed-sdk";

 // call this somewhere
logout();
----

The `logout` function returns a promise that resolves when the user is logged out of ThoughtSpot. When you call `logout`, the `autoLogin` attribute is set to `false` to prevent the SDK from automatically logging in the user again. If you do not want to disable `autoLogin`, set the `doNotDisableAutoLogin` parameter to `false`.

You can also call `init` again with the `autoLogin` property set to `true` to re-login a user.

[#embed-session-sec]
== Session security and login attributes

include::{path}/embed-config.adoc[]