= Events Reference
:toc: true
:toclevels: 2

:page-title: Events and app integration
:page-pageid: events
:page-description: Events allow the embedding application to send and receive messages from embedded ThoughtSpot components.

This article lists the `HostEvent` and `EmbedEvent` enumeration members. For information about the common use cases and general guidelines for using events on embedded ThoughtSpot instances, see xref:embed-events.adoc[Events and app integration].

[#host-events]
== Host events
The following host events are triggered by the host application, which the embedded ThoughtSpot app can register.
The host events are part of the *HostEvent* object; for example, `HostEvent.SetVisibleVizs`.
Host events use the `.trigger()` method to send the event message to embedded ThoughtSpot components. The events are sent in the  `.trigger(hostEvent, data)` format.

==== CreateMonitor

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Create alert* action to create a threshold-based alert for KPI charts. +
Requires the `vizId` key.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.CreateMonitor {
    vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== CopyLink

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Copy link* action on a Liveboard or visualization on a Liveboard. +
To trigger the *Copy link* action on a specific visualization on a Liveboard, pass the `vizId` key.

[div divider]
--
.Example
[%collapsible]
====
The following example triggers the `CopyLink` action on a Liveboard.

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.CopyLink,  {
    vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--


==== Delete
Available with  `LiveboardEmbed`,  and `AppEmbed` in `v1.19.0` or later. +
Triggers the Delete action on embedded visualization or search Answer. +
Requires `vizID` key for embedded Liveboards.

[div divider]
--
.Example
[%collapsible]
====
The following example triggers the `Delete` action on an embedded Liveboard.

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Delete,
{vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== Download

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `v1.19.0` or later. +
Triggers the *Download* action on a visualization or Answer in the Chart view mode.  +
Requires the `vizId` key for event trigger on a Liveboard.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Download, {vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== DownloadAsPDF

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Download PDF* action on a Liveboard.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.DownloadAsPDF)
----
====
--

==== DownloadAsCSV

Available with `SearchEmbed`, LiveboardEmbed`, and `AppEmbed` in `v1.19.0` or later. +
Triggers the *Download As CSV* action on a Liveboard visualization or Answer in the table view mode.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.DownloadAsCsv, {vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== DownloadAsXLSX

Available with `SearchEmbed`, LiveboardEmbed`, and `AppEmbed` in `v1.19.0` or later. +
Triggers the *Download As XLXS* action on a Liveboard visualization or Answer in the table view mode.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.DownloadAsXlsx, {vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== DrillDown
Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `v1.5.0` or later. +
Triggers a drill-down event on certain points of the specified column.  +
Includes the following parameters:

* `points` +
An object containing `selectedPoints` or `clickedPoints` to drill down to. For example, `{ selectedPoints: []}`.
* `columnGuid`  __Optional__ +
__String__. GUID of the column to drill by.
* `autoDrillDown`  __Optional__ +
__Boolean__. When set to `true`, automatically drills down to the selected points on the configured column.

[div divider]
--
.Examples
[%collapsible]
====
[source,JavaScript]
----
searchEmbed.trigger(HostEvent.DrillDown, {
    points: {
        clickedPoint,
        selectedPoints: selectedPoint
    },
    autoDrillDown: true,
})
----
In this example, the `VizPointDoubleClick` event is used for triggering the `DrillDown` event when an area or specific data point on a table or chart is double-clicked.

[source,JavaScript]
----
searchEmbed.on(EmbedEvent.VizPointDoubleClick, (payload) => {
    console.log(payload);
    const clickedPoint = payload.data.clickedPoint;
    const selectedPoint = payload.data.selectedPoints;
    console.log('>>> called', clickedPoint);
    embed.trigger(HostEvent.DrillDown, {
        points: {
            clickedPoint,
            selectedPoints: selectedPoint
        },
        autoDrillDown: true,

    })
})
----
====
--

==== Edit

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Edit* action on a Liveboard or visualization in a Liveboard.  +
To trigger the *Edit* action for a specific visualization on a Liveboard, pass the `vizId` key.

[div divider]
--
.Example
[%collapsible]
====
The following example triggers the `Edit` action on a Liveboard.

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Edit)
----

The following example triggers the `Edit` action on the specified visualization in a Liveboard.
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Edit,  {
    vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----

If you have embedded only chart or table visualization, you can trigger the `Edit` action on the object.
[source,JavaScript]
----
vizEmbed.trigger(HostEvent.Edit)
----

====
--

==== EditTML

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Edit TML* action on a Liveboard. +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.EditTML)
----
====
--

==== Explore

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Explore* action for a Liveboard visualization. +
Requires the `vizId` key.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Explore, {
    vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== ExportTML

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Export TML* action on a Liveboard. +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.ExportTML)
----
====
--

==== getExportRequestForCurrentPinboard
Available with `LiveboardEmbed` in v1.13.0 or later. +
Fires when a user triggers the Liveboard export workflow with the `getExportRequestForCurrentPinboard` method in the browser fetch request to download a Liveboard in its current state, including unsaved changes if any.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.getExportRequestForCurrentPinboard)
.then(data => {
console.log('Liveboard Data:', data);
})
----
====
--


==== GetTML
Available with `SearchEmbed`, and `AppEmbed` in v1.18.0 or later. +

Gets TML of the visualization or answer object.

////
when a user on the *Show underlying data* action on a Liveboard visualization or answer. +

////

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
searchEmbed.trigger(HostEvent.GetTML)
----
====
--

==== LiveboardInfo

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Show Liveboard details*  action on a Liveboard. +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.LiveboardInfo)
----
====
--

==== MakeACopy

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Make a copy*  action on a Liveboard. +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.MakeACopy)
----
====
--

==== ManageMonitor
Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Manage alert*  action on a Liveboard visualization. This action is available for KPI visualizations that support threshold-based alerts.  +
Requires the `vizId` key: +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.ManageMonitor, {
vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== ManagePipelines

Available with `LiveboardEmbed` and `AppEmbed` in `v1.19.0` or later. +
Triggers the *ManagePipelines* action on a Liveboard visualization or saved Answer. +
Requires the `vizId` key for event trigger on Liveboard visualizations:


[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.ManagePipelines, {
vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== Navigate

Available with `AppEmbed` in `v1.12.0` or later. +
Triggers navigation to the specified application page without triggering a reload +
Requires the following parameters: +

* `path`  +
__String__ |__Integer__. The application path to navigate to.
* `noReload` +
__Boolean__. When set to `true`, the user is navigated to the specified application page.

[NOTE]
====
You can also use the `appEmbed.navigateToPage(path, true)` function for page navigation within the embedded ThoughtSpot app.
====

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
appEmbed.trigger(HostEvent.Navigate, {
path: 'saved-answer/3da14030-11e4-42b2-8e56-5ee042a8de9e',
noReload: true
});
----
--

==== Pin

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Pin* action on a Liveboard visualization.  +
Requires the `vizId` key.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Pin, {
vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== Present

Available with `LiveboardEmbed` and `AppEmbed` in `v1.15.0` or later. +
Triggers the *Present* action on a Liveboard or visualization on a Liveboard.  +

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Present)
----

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Present, {
vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== Remove

Available with `AppEmbed` in `v1.15.0` or later. +
Triggers the *Remove* action for a Liveboard in the embedded ThoughtSpot app.  +

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
appEmbed.trigger(HostEvent.Remove)
----
====
--

==== Save

Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `v1.19.0` or later. +
Triggers the *Save* action on a Liveboard or Answer.

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Save)
----
====
--

==== Search
Available with `SearchEmbed`  and  `AppEmbed` in `v1.1.0` or later. +
Triggers a search query. +
Requires the following parameters: +

* `searchQuery` +
__String__. Query string with search tokens

* `dataSourceIds` +
__String__. Data source GUIDs

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
searchEmbed.trigger(HostEvent.Search {
searchQuery: "[sales] by [item type]"
dataSourceIds: ["cd252e5c-b552-49a8-821d-3eadaa049cca"]
})
----
====
--

==== Schedule

Available with `AppEmbed` in `v1.15.0` or later. +
Triggers the *Schedule* action for scheduling a Liveboard job.  +

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Schedule)
----
====
--

==== ScheduleList

Available with `AppEmbed` in `v1.15.0` or later. +
Triggers the *Manage schedules* action to manage Liveboard job schedules.  +

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.ScheduleList)
----
====
--

==== SetVisibleVizs
Available with `LiveboardEmbed` and `AppEmbed` in `v1.6.0` or later. +
Sets specific visualizations as visible objects on a Liveboard.
You can specify an array of Visualization GUIDs set as visible objects. The visualization IDs not included in the array are hidden on the Liveboard. +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.SetVisibleVizs, ['730496d6-6903-4601-937e-2c691821af3c','d547ec54-2a37-4516-a222-2b06719af726'])
----
====
--

==== Share

Available with `LiveboardEmbed` `SearchEmbed` and `AppEmbed` in `v1.19.0` or later.
Triggers the `*Share*` action on visualization, Answer, or Worksheet.

[div divider]
--
.Examples
[%collapsible]
====

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.Share)
----
--


==== ShowUnderlyingData

Available with `LiveboardEmbed` `SearchEmbed` and `AppEmbed` in `v1.19.0` or later. +
Triggers the *ShowUnderlyingData* action on visualization or Answer. +
Requires the `vizId` key for event trigger on a Liveboard.

[div divider]
--
.Examples
[%collapsible]
====

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.ShowUnderlyingData,
{vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
--

==== SpotIQAnalyze

Available with `AppEmbed`, `SearchEmbed`, and `LiveboardEmbed` in `v1.19.0` or later. +
Triggers the *SpotIQAnalyze* action on a Liveboard visualization, search result, or saved Answer. +
Requires `vizId` key for event trigger on Liveboards.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.SpotIQAnalyze,
{vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--


==== SyncToSheets

Available with `LiveboardEmbed` and `AppEmbed` in `v1.19.0` or later. +
Triggers the *SyncToSheets* action on a saved Answer or visualization. +
Requires `vizId` key for event trigger on Liveboards.

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.SyncToSheets,
{vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== SynToOtherApps

Available with `LiveboardEmbed` and `AppEmbed` in `v1.19.0` or later. +
Triggers the *SyncToOherApps* action on a saved Answer or visualization. +
Requires `vizId` key for event trigger on Liveboards.

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.SyncToOtherApps,
{vizId: '730496d6-6903-4601-937e-2c691821af3c'})
----
====
--

==== UpdateRuntimeFilters
Available with `LiveboardEmbed` and `AppEmbed` in `v1.8.0` or later. +
Updates runtime filters applied on Liveboard, visualization, or answer object. You can specify an array of runtime filters with the following attributes:

* `columnName`  +
__String__. The name of the column to filter on.

* `operator` +
Runtime filter operator to apply. For information about supported operators, see xref:runtime-filters.adoc#runtimeFilterOp[Runtime filter operators].

* `values` +
The list of operands. The value can be an array of strings, integer, or boolean. Some operators such as `EQ`, `LE` allow a single value, whereas operators such as `BW` and `IN` accept multiple operands.

The following example shows how to register an event handler to trigger an event to update runtime filters.


[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [{
        columnName: "state",
        operator: "EQ",
        values: ["michigan"]
    },
    {
        columnName: "item type",
        operator: "EQ",
        values: ["Jackets"]
    }
])
----
====
--

==== UpdateTML

Available with `AppEmbed` in `v1.15.0` or later. +
Triggers the *Update TML* action for a Liveboard object.  +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateTML)
----
====
--

[#embed-events]
== Embed events

The embed events are generated by the embedded ThoughtSpot application components. All embed events are part of the `EmbedEvent` object; for example, `EmbedEvent.Init`.

Embed events are triggered when ThoughtSpot components initialize and load, and when users interact with these components. The `EmbedEvent` library also includes events that can be triggered when an action is initiated in the embedded view. For example, you can register an event handler to trigger `EmbedEvent.Save` when a user clicks the *Save* action on the answer page in the embedded UI. For some of these action-triggered events, you can register event handlers to emit events when the corresponding action starts and ends.

==== ALL
Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `v1.11.0` or later. +
Triggers all embed events. +
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
appEmbed.on(EmbedEvent.ALL, payload => {
console.log('Embed Events', payload)
})
----
====

--

==== AddRemoveColumns
Available with `SearchEmbed` and `AppEmbed` in `v1.10.0` or later. +
Is emitted when one or more columns are selected or removed during a search operation. +
Returns the GUIDs of the selected columns. +
[div divider]
--
.Example
[%collapsible]
====
[source,Javascript]
----
appEmbed.on(EmbedEvent.AddRemoveColumns, payload => {
console.log('AddRemoveColumns', payload);
})
----
====
--

==== Alert

Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `v1.1.0` or later. +
Is triggered when the embedded object sends an alert.  +
Returns an alert object or message.
[div divider]
--
.Example
[%collapsible]
====
[source]
----
searchEmbed.on(EmbedEvent.Alert)
----
====

--

==== AnswerChartSwitcher

Available with `SearchEmbed` and `AppEmbed` in `v1.11.0` or later. +
Is triggered when a user switches to the chart or table view on the answer page. +
[div divider]
--
.Example
[%collapsible]
====
[source,Javascript]
----
appEmbed.on(EmbedEvent.AnswerChartSwitcher, payload => {
console.log('switch view', payload);
})
----
====

--

==== AnswerDelete

Available with `SearchEmbed` and `AppEmbed` in `v1.11.0` or later. +
[div divider]
--
.Example
[%collapsible]
====
[source,Javascript]
----
 //trigger when action starts
appEmbed.on(EmbedEvent.AnswerDelete, payload => {
    console.log('delete answer', payload)}, {start: true })
 //trigger when action is completed
appEmbed.on(EmbedEvent.AnswerDelete, payload => {
    console.log('delete answer', payload)})
----
====

--

==== AuthInit

Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `v1.1.0` or later. +
Is emitted when authentication is initiated. Returns user GUID as data. +
Returns the `isLoggedIn` boolean to indicate if authentication was successful.

You can register the `AuthInit` event to be notified about the authentication status, and `AuthExpire` to trigger an alert when an authenticated session expires.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
appEmbed.on(EmbedEvent.AuthInit, payload => {
    console.log('AuthInit', payload);
})
----
====
--

==== AuthExpire

Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `v1.4.0` or later. +
Indicates if an authenticated session has expired. +

[div divider]
--
.Example
[%collapsible]
====
In this example, the `AuthExpire` event calls the `showAuthExpired` function to show a banner when an authenticated session expires. +

[source,JavaScript]
----
appEmbed.on(EmbedEvent.AuthExpire, showAuthExpired)
  //show auth expired banner
function showAuthExpired() {
    document.getElementById("authExpiredBanner");
}
----
====

--

==== CopyAEdit

Available with `AppEmbed` in `v1.11.0` or later. +
Is triggered when a user clicks *Copy and edit* on a saved answer. +
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
 //trigger when action starts
appEmbed.on(EmbedEvent.CopyAEdit, payload => {
  console.log('Copy and edit', payload)}, {start: true })
 //trigger when action ends
appEmbed.on(EmbedEvent.CopyAEdit, payload => {
  console.log('Copy and edit', payload)})
----
====

--

==== CopyToClipboard

Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when a user selects the table cells of an answer and selects *Copy to clipboard* from the context menu. +
[source,JavaScript]

[div divider]
--
.Example
[%collapsible]
====
----
seachEmbed.on(EmbedEvent.CopyToClipboard, payload => {
    console.log('copy to clipboard', payload);
})
----
====
--

==== CustomAction

Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `v1.1.0` or later. +
Is triggered when a custom action is initiated. +
Returns the custom action ID and response payload with the answer or Liveboard data.
For more information, see xref:embed-events.adoc#customAction[Custom action events].

[div divider]
--
.Example
[%collapsible]
====
----
appEmbed.on(EmbedEvent.customAction, payload => {
    const data = payload.data;
    if (data.id === 'insert Custom Action ID here') {
        console.log('Custom Action event:', data.embedAnswerData);
    }
})
----
====
--

==== Data

Available with `SearchEmbed` and `AppEmbed` in `v1.1.0` or later. +
Is triggered when the answer or Liveboard object data is received. +
Returns the answer or Liveboard data.

[source,JavaScript]
[div divider]
--
.Example
[%collapsible]
====
----
searchEmbed.on(EmbedEvent.Data, payload => {
    console.log('data', payload);
})
----
====

--
==== DataSourceSelected

Available with `SearchEmbed`  and  `AppEmbed` in `v1.1.0` or later. +
Is triggered when one or more data sources are selected. +
Returns the GUIDs of the data sources selected.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
searchEmbed.on(EmbedEvent.DataSourceSelected, payload => {
    console.log('DataSourceSelected', payload);
})
----
====

--

==== DialogOpen

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `v1.6.0` or later. +
Is triggered when a modal dialog is opened.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
appEmbed.on(EmbedEvent.DialogOpen, payload => {
    console.log('dialog open', payload);
})
----
====

--

==== DialogClose

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `v1.6.0` or later. +
Is triggered when a modal dialog is closed.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
appEmbed.on(EmbedEvent.DialogClose, payload => {
    console.log('dialog close', payload);
})
----
====

--

==== Download

Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when the *Download* action is initiated on a Liveboard or answer, and on download completion. +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.Download, payload => {
    console.log('download', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.Download, payload => {
    console.log('download', payload)})
----
====

--

==== DownloadAsCSV

Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when the *Download As CSV* action is initiated on a Liveboard or answer and on download completion. +
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsCSV, payload => {
    console.log('download CSV', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsCSV, payload => {
    console.log('download CSV', payload)})
----
====

--

==== DownloadAsPDF

Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when a Liveboard or answer object is downloaded as a PDF file and on download completion. +

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsPDF, payload => {
    console.log('download PDF', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsPDF, payload => {
    console.log('download PDF', payload)})
----
====

--

==== DownloadAsXlsx

Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when the Liveboard or answer data is downloaded as an Excel file and on download completion. +
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsXlsx, payload => {
    console.log('download Xlsx', payload)}, { start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsXlsx, payload => {
    console.log('download Xlsx', payload)})
----
====

--

==== Drilldown

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `v1.1.0` or later. +
Is triggered when the *Drill down* action is executed. +
Returns the following data:  +

* Drill columns +
The GUIDs of the columns on which the `Drill down` action was applied.

* Additional filters +
Additional filters applied during the operation

* Non-filtered columns +
The GUIDs of the columns that were excluded from filter application.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
searchEmbed.on(EmbedEvent.Drilldown, payload => {
    console.log('Drilldown', payload);
})
----
====
--

==== DrillExclude

Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when a filter is applied to exclude a data point in the drilled-down view. +
Returns the IDs of the column and the filters applied during the operation.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
appEmbed.on(EmbedEvent.DrillExclude, payload => {
    console.log('Drill exclude', payload);
})
----
====

--


==== DrillInclude

Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when a filter is applied to include a data point in the drilled-down view. +
Returns the IDs of the column and the filters that were applied during the operation.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
appEmbed.on(EmbedEvent.DrillInclude, payload => {
    console.log('Drill include', payload);
})
----
====

--

==== EditTML
Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when a user clicks the *Edit TML* action on the answer page.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
appEmbed.on(EmbedEvent.EditTML, payload => {
    console.log('Edit TML', payload);
})
----
====

--

==== ExportTML

Available with `SearchEmbed`  and  `AppEmbed` in `v1.11.0` or later. +
Is triggered when a user clicks the *Export TML* action on the answer page.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.ExportTML, payload => {
    console.log('Export TML', payload)}, { start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.ExportTML, payload => {
    console.log('Export TML', payload)})
----
====
--

==== Error

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `v1.1.0` or later. +
Indicates that an error has occurred. +
Returns an error object or message.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
SearchEmbed.on(EmbedEvent.Error, showErrorMsg)
//show error messaage
function showErrorMsg() {
    document.getElementById("error");

----
====

--

==== Init

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `v1.1.0` or later. +
Is triggered when the embedded object rendering initializes. +
Returns the timestamp of the event.

[div divider]
--
.Example
[%collapsible]
====

In this example, a showLoader function is called to show a loader when the `Init` event is emitted.

[source,JavaScript]
----
liveboardEmbed.on(EmbedEvent.Init, showLoader)
  //show a loader
function showLoader() {
    document.getElementById("loader");
}
----
====
--

==== LiveboardRendered

Available with `LiveboardEmbed`, `AppEmbed` in `V1.9.1` or later. +
Is emitted when a Liveboard container loads. You can use this event as a hook to trigger other events on a rendered Liveboard.

[NOTE]
====
The `LiveboardRendered` event is triggered when the Liveboard container loads. The data on the Liveboard visualizations are loaded asynchronously and may not be loaded fully when the event is emitted.
====

[div divider]
--
.Examples
[%collapsible]
====
[source,Javascript]
----
liveboardEmbed.on(EmbedEvent.LiveboardRendered, payload => {
    console.log('Liveboard is rendered', payload);
})
----
The following example shows how to trigger `SetVisibleVizs` event using `LiveboardRendered` embed event:

[source, Typescript]
----
const embedRef = useEmbedRef();
const onLiveboardRendered = () => {
embed.trigger(HostEvent.SetVisibleVizs, ['viz1', 'viz2']);
};
----
====

--

==== Load

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.1.0` or later. +
Is triggered when an embedded ThoughtSpot object loads. +
Returns the timestamp of the event.

[div divider]
--
.Example
[%collapsible]
====
[source]
----
liveboardEmbed.on(EmbedEvent.Load, hideLoader)
 //hide loader
function hideLoader() {
  document.getElementById("loader");
}
----
====
--

==== NoCookieAccess

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.2.0` or later. +
Is emitted when third-party cookies are blocked by a user's browser. +

[div divider]
--
.Example
[%collapsible]
====
In this example, the `NoCookieAccess` event calls the `showCookieSettingsMsg` function to show a message about setting cookies.

[source,JavaScript]
----
appEmbed.on(EmbedEvent.NoCookieAccess, showCookieSettingsMsg)
----
====

--

==== Pin

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user tries to pin an answer to a Liveboard.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.Pin, payload => {
    console.log('pin', payload)
}, {
    start: true
})
 //trigger when action ends
searchEmbed.on(EmbedEvent.Pin, payload => {
    console.log('pin', payload)
})
----
====
--

==== QueryChanged

Available with `SearchEmbed`  and  `AppEmbed` in `V1.4.0` or later. +
Is triggered when a search query is updated.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
searchEmbed.on(EmbedEvent.QueryChanged, payload => console.log('data', payload))
----
====
--

==== RouteChange
Available with `SearchEmbed`  and  `AppEmbed` in `V1.7.0` or later. +
Is triggered when a user navigates from one page to another in the embedded ThoughtSpot app. This event logs the application page URL accessed by a user.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
searchEmbed.on(EmbedEvent.RouteChange, payload => console.log('data', payload))
----
====
--
==== Save

Available with `SearchEmbed` and  `AppEmbed` in `V1.11.0` or later, and with `LiveboardEmbed` in 1.15.0 or later versions. +

Is triggered when an answer or Liveboard (new Liveboard experience only) is saved in the embedded view. +

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.Save, payload => {
    console.log('Save', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.Save, payload => {
    console.log('Save', payload)
})
----

[source,JavaScript]
----
  //trigger when action starts
liveboardEmbed.on(EmbedEvent.Save, payload => {
    console.log('Save', payload)
}, {
    start: true
})
  //trigger when action ends
liveboardEmbed.on(EmbedEvent.Save, payload => {
    console.log('Save', payload)
})
----

====
--


==== SaveAsView

Available with `AppEmbed` in `V1.11.0` or later. +
Is triggered when *Create view* action is initiated on an answer page.

[div divider]
--
--

==== Share

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user clicks the *Share* icon on the answer page.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.Share, payload => {
    console.log('Share', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.Share, payload => {
    console.log('Share', payload)
})
----
====

--

==== SpotIQAnalyze

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when the *SpotIQ Analyze* action is initiated on an answer page.
[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.SpotIQAnalyze, payload => {
    console.log('SpotIQAnalyze', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.SpotIQAnalyze, payload => {
    console.log('SpotIQ analyze', payload)
})
----
====
--

==== VizPointClick

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.11.0` or later. +
Is triggered when an area or data point on a chart is clicked. +
Returns the data point that was clicked.

[div divider]
--
.Example
[%collapsible]
====
[source,JavaScript]
----
searchEmbed.on(EmbedEvent.VizPointClick, payload => {
    console.log('VizPointClick', payload)
})
----
====
--

==== VizPointDoubleClick

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.5.0` or later. +
Is triggered when an area or data point on a chart is double-clicked. +
Returns the data point that was double-clicked.

[div divider]
--
.Example
[%collapsible]
====

[source,JavaScript]
----
searchEmbed.on(EmbedEvent.VizPointDoubleClick, payload => {
    console.log('VizPointDoubleClick', payload)
})
----
====
Sometimes, when a user double-clicks on a chart, both `VizPointClick` and `VizPointDoubleClick` events are triggered. Because the double-click action involves two clicks, the `VizPointClick` event is triggered for each click. To distinguish between a single-click and double-click event and avoid firing `VizPointClick` events when a user double-clicks on a chart, define a timeout function as shown in this example:

[source,javascript]
----
let vizPointClickTimer;
// Register an event handler
searchEmbed.on(EmbedEvent.VizPointClick, payload => {
   // Delay the click handlers by 400 milliseconds
   vizPointClickTimer = setTimeout(() => {
      onVizPointClick(payload);
   }, 400);
})
searchEmbed.on(EmbedEvent.VizPointDoubleClick, payload => {
   // If a double-click action is registered, clear the single-click timer
   clearTimeout(vizPointClickTimer);
   onVizPointDoubleClick(payload);
})
----
--

== Unsubscribe from an event

The following example shows how to unsubscribe from an event:

[source,JavaScript]
----
appEmbed.off(EmbedEvent.AuthInit)
----

== Related resources

* For information about common use cases and how to use events for app integration, see xref:embed-events.adoc[Events and app integration].
* For information about triggering events on React components, see xref:embed-ts-react-app.adoc[Embed ThoughtSpot in a React app].
* See also the link:{{visualEmbedSDKPrefix}}/enums/EmbedEvent.html[EmbedEvent, window=_blank] and link:{{visualEmbedSDKPrefix}}/enums/HostEvent.html[HostEvent, window=_blank] SDK documentation.

