= Events Reference
:toc: true
:toclevels: 1

:page-title: Events and app integration
:page-pageid: events
:page-description: Events allow the embedding application to send and receive messages from embedded ThoughtSpot components.

This article lists the `HostEvent` and `EmbedEvent` enumeration members. For information about the common use cases and general guidelines for using events on embedded ThoughtSpot instances, see xref:embed-events.adoc[Events and app integration].

[#host-events]
== Host events
The following host events are triggered by the host application, which the embedded ThoughtSpot app can register.
The host events are part of the *HostEvent* object; for example, `HostEvent.SetVisibleVizs`.
Host events use the `.trigger()` method to send the event message to embedded ThoughtSpot components. The events are sent in the  `.trigger(hostEvent, data)` format.

==== DrillDown
Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.5.0` or later. +
Triggers a drill down event when a user clicks on a specific point in a column.  +

[div divider]
--
.Examples
[%collapsible]
====
[source,javascript]
----
searchEmbed.trigger(HostEvent.DrillDown, {
        points: clickedPointData,
        autoDrillDown: true,
    });
----
In this example, the `VizPointDoubleClick` event is used for triggering the `DrillDown` event when an area or specific data point on a table or chart is double-clicked.

[source,javascript]
----
searchEmbed.on(EmbedEvent.VizPointDoubleClick, (data) => {
    const {
        payload: clickedPointData
    } = data;
    console.log('>>> called', clickedPointData);
    embed.trigger(HostEvent.DrillDown, {
        points: clickedPointData,
        autoDrillDown: true,
    });
})
----
====
--

==== Navigate

Available with `AppEmbed` in `V1.12.0` or later. +
Is triggered when a user navigates to an application page without reloading the page. +

[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
appEmbed.trigger(HostEvent.Navigate, {
   path: 'saved-answer/3da14030-11e4-42b2-8e56-5ee042a8de9e',
   noReload: true
});
----
--

==== Search
Available with `SearchEmbed`  and  `AppEmbed` in `V1.1.0` or later. +
Is triggered when a search operation is executed. The event returns the data source GUID and search query details. +
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
searchEmbed.trigger(HostEvent.Search)
----
====
--

==== SetVisibleVizs
Available with `LiveboardEmbed` and `AppEmbed` in `V1.6.0` or later. +
Sets specific visualizations as visible objects on a Liveboard. The visualization IDs that are not passed in the parameter are hidden on the Liveboard. +

[div divider]
--
.Example
[%collapsible]
====
[source, javascript]
----
liveboardEmbed.trigger(HostEvent.SetVisibleVizs, ['viz1', 'viz2'])
----
====
--


==== UpdateRuntimeFilters
Available with `LiveboardEmbed` and `AppEmbed` in `V1.8.0` or later. +
Triggers an event to update runtime filters. The following example shows how to register an event handler to trigger an event when the runtime filters are updated. +
[div divider]
--
.Example
[%collapsible]
====
[source, javascript]
----
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [{
    columnName: "state",
    operator: "EQ",
    values: ["michigan"]
}]);
----
====
--

[#embed-events]
== Embed events

The embed events are generated by the embedded ThoughtSpot application components. All embed events are part of the `EmbedEvent` object; for example, `EmbedEvent.Init`.

Embed events are triggered when ThoughtSpot components initialize and load, and when users interact with these components. The `EmbedEvent` library also includes events that can be triggered when an action is initiated in the embedded view. For example, you can register an event handler to trigger `EmbedEvent.Save` when a user clicks the *Save* action on the answer page in the embedded UI. For some of these action-triggered events, you can register event handlers to emit events when the corresponding action starts and ends.

==== ALL
Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `V1.11.0` or later. +
Triggers all embed events. +
[div divider]
--
.Example
[%collapsible]
====
[source, javascript]
----
appEmbed.on(EmbedEvent.ALL, payload => {
    console.log('Embed Events', payload)
})
----
====

--

==== AddRemoveColumns
Available with `SearchEmbed` and `AppEmbed` in `V1.10.0` or later. +
Is emitted when one or more columns are selected or removed during a search operation. +
Returns the GUIDs of the selected columns. +
[div divider]
--
.Example
[%collapsible]
====
[source,Javascript]
----
appEmbed.on(EmbedEvent.AddRemoveColumns, payload => {
    console.log('AddRemoveColumns', payload);
})
----
====

--

==== Alert

Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `V1.1.0` or later. +
Is triggered when the embedded object sends an alert.
[div divider]
--
.Example
[%collapsible]
====
[source]
----
searchEmbed.on(EmbedEvent.Alert)
----
====

--

==== AnswerChartSwitcher

Available with `SearchEmbed` and `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user switches to the chart or table view on the answer page. +
[div divider]
--
.Example
[%collapsible]
====
[source,Javascript]
----
appEmbed.on(EmbedEvent.AnswerChartSwitcher, payload => {
    console.log('switch view', payload);
})
----
====

--

==== AnswerDelete

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
[div divider]
--
.Example
[%collapsible]
====
[source,Javascript]
----
 //trigger when action starts
appEmbed.on(EmbedEvent.AnswerDelete, payload => {
    console.log('delete answer', payload)}, {start: true })
 //trigger when action is completed
appEmbed.on(EmbedEvent.AnswerDelete, payload => {
    console.log('delete answer', payload)})
----
====

--

==== AuthInit

Available with `SearchEmbed`, `LiveboardEmbed`,  `AppEmbed` in `V1.1.0` or later. +
Is emitted when authentication is initiated. Returns user GUID as data.
You can also subscribe to the `AuthInit` event to be notified when user authentication is successful, and `AuthExpire` to trigger an alert when an authenticated session expires.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
appEmbed.on(EmbedEvent.AuthInit, payload => {
    console.log('AuthInit', payload);
})
----
====
--

==== AuthExpire

Available with `SearchEmbed`, `LiveboardEmbed`,  `AppEmbed` in `V1.4.0` or later. +
Indicates if an authenticated session has expired. +

[div divider]
--
.Example
[%collapsible]
====
In this example, the `AuthExpire` event calls the `showAuthExpired` function to show a banner when an authenticated session expires. +

[source,javascript]
----
appEmbed.on(EmbedEvent.AuthExpire, showAuthExpired)
  //show auth expired banner
function showAuthExpired() {
    document.getElementById("authExpiredBanner");
}
----
====

--

==== CopyAEdit

Available with `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user clicks *Copy and edit* on a saved answer. +
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
 //trigger when action starts
appEmbed.on(EmbedEvent.CopyAEdit, payload => {
  console.log('Copy and edit', payload)}, {start: true })
 //trigger when action ends
appEmbed.on(EmbedEvent.CopyAEdit, payload => {
  console.log('Copy and edit', payload)})
----
====

--

==== CopyToClipboard

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user selects the table cells of an answer and selects *Copy to clipboard* from the context menu. +
[source,javascript]

[div divider]
--
.Example
[%collapsible]
====
----
seachEmbed.on(EmbedEvent.CopyToClipboard, payload => {
    console.log('copy to clipboard', payload);
})
----
====
--

==== CustomAction

Available with `SearchEmbed`, `LiveboardEmbed`, and `AppEmbed` in `V1.1.0` or later. +
Is triggered when a custom action is initiated. +
Returns the custom action ID and the response payload with the answer or Liveboard data.
For more information, see xref:embed-events.adoc#customAction[Custom action events].

[div divider]
--
.Example
[%collapsible]
====
----
appEmbed.on(EmbedEvent.customAction, payload => {
    const data = payload.data;
    if (data.id === 'insert Custom Action ID here') {
        console.log('Custom Action event:', data.embedAnswerData);
    }
})
----
====
--

==== Data

Available with `SearchEmbed`  and  `AppEmbed` in `V1.1.0` or later. +
Is triggered when data pertaining to an answer or Liveboard object is received. +
[source, javascript]
[div divider]
--
.Example
[%collapsible]
====
----
searchEmbed.on(EmbedEvent.Data, payload => {
    console.log('data', payload);
})
----
====

--
==== DataSourceSelected

Available with `SearchEmbed`  and  `AppEmbed` in `V1.1.0` or later. +
Is triggered when one or more data sources are selected. +
Returns the GUIDs of the data sources selected.
[div divider]
--
.Example
[%collapsible]
====
[source, javascript]
----
searchEmbed.on(EmbedEvent.DataSourceSelected, payload => {
    console.log('DataSourceSelected', payload);
})
----
====

--

==== DialogOpen

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.6.0` or later. +
Is triggered when a modal dialog is opened.
[div divider]
--
.Example
[%collapsible]
====
[source, javascript]
----
appEmbed.on(EmbedEvent.DialogOpen, payload => {
    console.log('dialog open', payload);
})
----
====

--

==== DialogClose

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.6.0` or later. +
Is triggered when a modal dialog is closed.
[div divider]
--
.Example
[%collapsible]
====
[source, javascript]
----
appEmbed.on(EmbedEvent.DialogClose, payload => {
    console.log('dialog close', payload);
})
----
====

--

==== Download

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when the *Download* action is initiated on a Liveboard or answer and on download completion. +
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.Download, payload => {
    console.log('download', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.Download, payload => {
    console.log('download', payload)})
----
====

--

==== DownloadAsCSV

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when the *Download As CSV* action is initiated on a Liveboard or answer and on download completion. +
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsCSV, payload => {
    console.log('download CSV', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsCSV, payload => {
    console.log('download CSV', payload)})
----
====

--

==== DownloadAsPDF

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a Liveboard or answer object is downloaded as a PDF file and on download completion. +

[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsPDF, payload => {
    console.log('download PDF', payload)}, {start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsPDF, payload => {
    console.log('download PDF', payload)})
----
====

--

==== DownloadAsXlsx

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when the Liveboard or answer data is downloaded as an Excel file and on download completion. +
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.DownloadAsXlsx, payload => {
    console.log('download Xlsx', payload)}, { start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.DownloadAsXlsx, payload => {
    console.log('download Xlsx', payload)})
----
====

--

==== Drilldown

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.1.0` or later. +
Is triggered when the *Drill down* action is executed. +
Returns the IDs of the column on which the drill down operation was performed, any additional filters applied during the operation, and the columns that were not filtered.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
searchEmbed.on(EmbedEvent.Drilldown, payload => {
    console.log('Drilldown', payload);
})
----
====

--

==== DrillExclude

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a filter is applied to exclude a data point in the drilled down view. +
Returns the IDs of the column and the filters applied during the operation.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
appEmbed.on(EmbedEvent.DrillExclude, payload => {
    console.log('Drill exclude', payload);
})
----
====

--


==== DrillInclude

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a filter is applied to include a data point in the drilled down view. +
Returns the IDs of the column and the filters that were applied during the operation.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
appEmbed.on(EmbedEvent.DrillInclude, payload => {
    console.log('Drill include', payload);
})
----
====

--

==== EditTML
Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user clicks the *Edit TML* action on the answer page.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
appEmbed.on(EmbedEvent.EditTML, payload => {
    console.log('Edit TML', payload);
})
----
====

--

==== ExportTML

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user clicks *Export TML* action on the answer page.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.ExportTML, payload => {
    console.log('Export TML', payload)}, { start: true })
 //trigger when action ends
searchEmbed.on(EmbedEvent.ExportTML, payload => {
    console.log('Export TML', payload)})
----
====
--

==== Error

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.1.0` or later. +
Indicates that an error has occurred.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
SearchEmbed.on(EmbedEvent.Error, showErrorMsg)
//show error messaage
function showErrorMsg() {
    document.getElementById("error");

----
====

--

==== Init

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.1.0` or later. +

[div divider]
--
.Example
[%collapsible]
====
Is triggered when the embedded object rendering initializes. In this example, a showLoader function is called to show a loader when the `Init` event is emitted.

[source,javascript]
----
liveboardEmbed.on(EmbedEvent.Init, showLoader)
  //show a loader
function showLoader() {
    document.getElementById("loader");
}
----
====
--

==== LiveboardRendered

Available with `LiveboardEmbed`, `AppEmbed` in `V1.9.1` or later. +
Is emitted when a Liveboard has completed rendering. This event can be used as a hook to trigger other events on a rendered Liveboard.
[div divider]
--
.Examples
[%collapsible]
====
[source,Javascript]
----
liveboardEmbed.on(EmbedEvent.LiveboardRendered, payload => {
    console.log('Liveboard is rendered', payload);
})
----
The following example shows how to trigger `SetVisibleVizs` event using `LiveboardRendered` embed event:

[source, Typescript]
----
const embedRef = useEmbedRef();
const onLiveboardRendered = () => {
embedRef.current.trigger(HostEvent.SetVisibleVizs, ['viz1', 'viz2']);
};
----
====

--

==== Load

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.1.0` or later. +
Indicates if the embedded ThoughtSpot object has loaded.
[div divider]
--
.Example
[%collapsible]
====
[source]
----
liveboardEmbed.on(EmbedEvent.Load, hideLoader)
 //hide loader
function hideLoader() {
  document.getElementById("loader");
}
----
====
--

==== NoCookieAccess

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.2.0` or later. +
Is emitted when third-party cookies are blocked by a user's browser. +

[div divider]
--
.Example
[%collapsible]
====
In this example, the `NoCookieAccess` event calls the `showCookieSettingsMsg` function to show a message about setting cookies.

[source,javascript]
----
appEmbed.on(EmbedEvent.NoCookieAccess, showCookieSettingsMsg)
----
====

--

==== Pin

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user tries to pin an answer to a Liveboard.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
 //trigger when action starts
searchEmbed.on(EmbedEvent.Pin, payload => {
    console.log('pin', payload)
}, {
    start: true
})
 //trigger when action ends
searchEmbed.on(EmbedEvent.Pin, payload => {
    console.log('pin', payload)
})
----
====
--

==== QueryChanged

Available with `SearchEmbed`  and  `AppEmbed` in `V1.4.0` or later. +
Is triggered when a search query is updated.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
searchEmbed.on(EmbedEvent.QueryChanged, payload => console.log('data', payload))
----
====
--

==== RouteChange
Available with `SearchEmbed`  and  `AppEmbed` in `V1.7.0` or later. +
Is triggered when a user navigates from one page to another in the embedded ThoughtSpot app. This event logs the application page URL accessed by a user.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
searchEmbed.on(EmbedEvent.RouteChange, payload => console.log('data', payload))
----
====
--
==== Save

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when an answer is saved in the embedded view.
[div divider]
--
.Example
[%collapsible]
====

[source,javascript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.Save, payload => {
    console.log('Save', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.Save, payload => {
    console.log('Save', payload)
})
----
====
--

==== SaveAsView

Available with `AppEmbed` in `V1.11.0` or later. +
Is triggered when *Create view* action is initiated on an answer page.

[div divider]
--
--

==== Share

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when a user clicks the *Share* icon on the answer page.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.Share, payload => {
    console.log('Share', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.Share, payload => {
    console.log('Share', payload)
})
----
====

--

==== SpotIQAnalyze

Available with `SearchEmbed`  and  `AppEmbed` in `V1.11.0` or later. +
Is triggered when the *SpotIQ Analyze* action is initiated on an answer page.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
  //trigger when action starts
searchEmbed.on(EmbedEvent.SpotIQAnalyze, payload => {
    console.log('SpotIQAnalyze', payload)
}, {
    start: true
})
  //trigger when action ends
searchEmbed.on(EmbedEvent.SpotIQAnalyze, payload => {
    console.log('SpotIQ analyze', payload)
})
----
====
--

==== VizPointClick

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.11.0` or later. +
Is triggered when an area or data point on a chart is clicked.
[div divider]
--
.Example
[%collapsible]
====
[source,javascript]
----
searchEmbed.on(EmbedEvent.VizPointClick, payload => {
    console.log('VizPointClick', payload)
})
----
====
--

==== VizPointDoubleClick

Available with `SearchEmbed`, `LiveboardEmbed`,  and `AppEmbed` in `V1.5.0` or later. +
Is triggered when an area or data point on a chart is double-clicked.
[div divider]
--
.Example
[%collapsible]
====

[source,javascript]
----
searchEmbed.on(EmbedEvent.VizPointDoubleClick, payload => {
    console.log('VizPointDoubleClick', payload)
})
----
====
--

== Unsubscribe from an event

The following example shows how to unsubscribe from an event:

[source, javascript]
----
appEmbed.off(EmbedEvent.AuthInit)
----

== Related resources

* For information about common use cases and how to use events for app integration, see xref:embed-events.adoc[Events and app integration].
* For information about triggering events on React components, see xref:embed-ts-react-app.adoc[Embed ThoughtSpot in a React app].
* See also the link:{{visualEmbedSDKPrefix}}/enums/EmbedEvent.html[EmbedEvent, window=_blank] and link:{{visualEmbedSDKPrefix}}/enums/HostEvent.html[HostEvent, window=_blank] SDK documentation.
