= Feature matrix and license types
:toc: true

:page-title: Feature matrix and license types
:page-pageid: license-feature-matrix
:page-description: Choose the license model as per your embedding requirements.

The following table lists the features available with ThoughtSpot Analytics and embedding licenses:

[div tableContainer]
--

[width="100%" cols="7,5,5,5,5,5"]
[options='header']
|=====
|Feature|ThoughtSpot Analytics license|ThoughtSpot Analytics with Embed Add-on license| ThoughtSpot Everywhere License +
|Free Trial account +

(Evaluation only) |Developer Playground on public instance +
(Evaluation only)

|Access to **Develop** tab +
__Requires developer or admin  privileges__ |[tag greenBackground]#✓# 2*| [tag greenBackground]#✓# |[tag greenBackground]#✓#  |[tag greenBackground]#✓#
| Visual Embed Playground|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greenBackground]#✓#| [tag greenBackground]#✓#
|REST API Playground |[tag greenBackground]#✓#  2*| [tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓#
|Embedding with Visual Embed SDK +
|[tag greyBackground]#–# 2*|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greyBackground]#–#

5+|*Authentication and security* + |

|Basic authentication + |[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#

|SAML SSO |[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#|[tag greyBackground]#–#
|OIDC authentication |[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#|[tag greyBackground]#–#
|Trusted authentication |[tag greyBackground]#–#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#|[tag greyBackground]#–#

|CSP, CORS, and SAML redirect allowlists| [tag greyBackground]#–#  2*| [tag greenBackground]#✓# | [tag greyBackground]#–# | [tag greyBackground]#–#

5+|*REST APIs* + |

a|Embedding Liveboards and charts using data APIs +
|[tag greyBackground]#–#  +
2*|[tag greenBackground]#✓# |[tag greenBackground]#✓#  +
|[tag greyBackground]#–#

a|REST API v1 endpoints

|[tag greenBackground]#✓#  2*|[tag greenBackground]#✓#
| [tag greenBackground]#✓#  | [tag greyBackground]#–#

a|REST API v2.0 endpoints |[tag greenBackground]#✓#
 2*|[tag greenBackground]#✓#  + |[tag greenBackground]#✓#  |[tag greyBackground]#–#

5+|*REST API authentication options* + |

|Basic authentication + |[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#
|Bearer token authentication (REST API v2.0 only)|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#
|Trusted authentication |[tag greyBackground]#–#|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#|[tag greyBackground]#–#

5+|*Custom actions* + |
|URL-based custom actions|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greyBackground]#–#|[tag greyBackground]#–#
|Callback custom actions|[tag greyBackground]#–# 2*|[tag greenBackground]#✓# |[tag greyBackground]#–#|[tag greyBackground]#–#
5+|*Custom styles* + |
|Style customization via UI|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greyBackground]#–# |[tag greyBackground]#–#
|CSS customization |[tag greyBackground]#–# 2*|[tag greenBackground]#✓# |[tag greyBackground]#–# |[tag greyBackground]#–#
|CSP overrides for fonts, styles, and images|[tag greyBackground]#–#  2*| [tag greenBackground]#✓# | [tag greyBackground]#–# | [tag greyBackground]#–#
5+|*Link settings* + |
|Custom link format|[tag greyBackground]#–# 2*|[tag greenBackground]#✓# |[tag greyBackground]#–# |[tag greyBackground]#–#
|=====
--
////

a|Runtime filters

(Available on embedded ThoughtSpot instances only) | [tag greenBackground]#✓# REST APIs

(Basic authentication only)

|[tag greenBackground]#✓# REST APIs

[tag greenBackground]#✓#  Visual Embed SDK

|[tag greenBackground]#✓# REST APIs

[tag greenBackground]#✓#  Visual Embed SDK

(Basic authentication only)
| [tag greenBackground]#✓# REST APIs

[tag greenBackground]#✓#  Visual Embed SDK

(Basic authentication only)

////

== REST API v1 operations

[div tableContainer]
--
[width="100%" cols="8,4,4,4,4,4"]
[options='header']
|=====
|REST API v1 endpoints|ThoughtSpot Analytics license|ThoughtSpot Analytics with Embed Add-on license|ThoughtSpot Everywhere license|Free Trial account +

(Evaluation only) |API Playground on public instance +
(Evaluation only)

a| xref:user-api.adoc[User API endpoints] +
////
__Require `ADMINISTRATION` privilege__
////
2*|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greyBackground]#–# |[tag greyBackground]#–#

a| xref:group-api.adoc[Group API endpoints] +
////
__Require `ADMINISTRATION` privilege__
////
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greyBackground]#–# |[tag greyBackground]#–# +

a|xref:session-api.adoc[Session API endpoints] +

////
* __The API calls to `/tspublic/v1/session/auth/token` and  `/tspublic/v1/session/login/token` require ThoughtSpot Everywhere license__ +
* __The home Liveboard CRUD operations require view or edit access to Liveboard objects__
////
|[tag greenBackground]#✓# +

__The xref:api-auth-session.adoc#_obtain_a_token_for_trusted_authentication[`session/auth/token`] and xref:api-auth-session.adoc#_authenticate_and_log_in_with_a_token_trusted_authentication[`session/login/token`] endpoints are not available__ 2*|[tag greenBackground]#✓#
 |[tag greenBackground]#✓#|[tag greenBackground]#✓# +

__Session information and home Liveboard APIs only__
a|xref:connections-api.adoc[Connection API endpoints] +

////
__Require `DATAMANAGEMENT` privilege__
////
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greyBackground]#–#
a|xref:metadata-api.adoc[Metadata API endpoints] +
////
* __Require at least view access to metadata objects__ +

* __ `POST` requests require edit access to metadata objects__
////

|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓#

__Query APIs only__

a|xref:tml-api.adoc[TML API endpoints] +

////
__Require `DATAMANAGEMENT` privilege__
////
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greyBackground]#–#

a|xref:admin-api.adoc[System administration API endpoints] +

////
* __Require `ADMINISTRATION` privilege__ +
* __Custom action APIs require `ADMINISTRATOR` or `DEVELOPER` privilege__ +
* __Custom action association requires at least edit access to the visualization or saved answer__ +
////
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greyBackground]#–# |[tag greyBackground]#–#

a|xref:admin-api.adoc#_supported_operations[Custom action API endpoints] +

////
* __Require `ADMINISTRATION` privilege__ +
* __Custom action APIs require `ADMINISTRATOR` or `DEVELOPER` privilege__ +
* __Custom action association requires at least edit access to the visualization or saved answer__ +
////
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greenBackground]#✓# |[tag greenBackground]#✓#

__Query APIs only__
a|xref:dependency-apis.adoc[Dependency API endpoints] +

////
__Require view access to metadata objects__
////

|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#
a|Data API endpoints +

* xref:search-data-api.adoc[Search data API endpoint] +
* xref:pinboarddata.adoc[Liveboard data AI endpoint] +
* xref:pinboard-export-api.adoc[Liveboard Export API endpoint] +

////
__Require at least view access to metadata objects__
////
|
[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓#

a|xref:security-api.adoc[Security API endpoints] +

////
__Require edit access to metadata objects to share and view permission details__
////
|
[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greyBackground]#–#

a|xref:logs-api.adoc[Audit logs API endpoint] +

////
__Requires `ADMINISTRATION` privilege__
////
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#|
|=====
--

== REST API v2.0 operations

[div tableContainer]
--
[width="100%" cols="8,8,4,4,4,4"]
[options='header']
|=====
|REST API v2.0 endpoints |ThoughtSpot Analytics license|ThoughtSpot Analytics with Embed Add-on license| ThoughtSpot Everywhere License|Free Trial account +
(Evaluation only) |API Playground on public instance +
(Evaluation only)
a|xref:rest-api-v2-reference.adoc#_authentication[Authentication API endpoints] +

a|[tag greenBackground]#✓# +

__The token generation option with `username` and `secret_key` and the JIT user provisioning parameters in `auth/token/object` and `auth/token/full` endpoints require an embedding license__.

2*|[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greenBackground]#✓# +
__Session information API only__
a|xref:rest-api-v2-reference.adoc#_users[User API endpoints]

|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greyBackground]#–# |[tag greyBackground]#–#
a|xref:rest-api-v2-reference.adoc#_system[System API endpoints]

|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greyBackground]#–# |[tag greyBackground]#–#
a|xref:rest-api-v2-reference.adoc#_orgs[Org API endpoints]

|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓# |[tag greyBackground]#–# |[tag greyBackground]#–#
a|xref:rest-api-v2-reference.adoc#_metadata[Metadata API endpoints]
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greenBackground]#✓# |[tag greenBackground]#✓# +
__Query APIs only__

a|xref:rest-api-v2-reference.adoc#_reports[Report API endpoints]
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greenBackground]#✓# |[tag greenBackground]#✓# +
__Query APIs only__

a|xref:rest-api-v2-reference.adoc#_security[Security API endpoints]
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greyBackground]#–# |[tag greyBackground]#–#

a|xref:rest-api-v2-reference.adoc#_data[Data API endpoints]
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greenBackground]#✓#  |[tag greenBackground]#✓#

a|xref:rest-api-v2-reference.adoc#_data[Log API endpoints]
|[tag greenBackground]#✓# 2*|[tag greenBackground]#✓#|[tag greyBackground]#–# |[tag greyBackground]#–#
|=====
--



== REST API v2 [beta betaBackground]^Beta^ operations

Starting from 9.0.0.cl, the REST API v2 [beta betaBackground]^Beta^ API endpoints are deprecated and removed from the REST API v2 Playground. The APIs remain functional until further notice. However, we recommend using the new REST API 2.0 endpoints that are currently available in the REST API Playground.

////
=== Supported operations
[div tableContainer]
--
[width="100%" cols="8,4,4,4,4"]
[options='header']
|=====
|REST API v2.0 endpoints[beta betaBackground]^Beta^ |ThoughtSpot Enterprise Cloud Service|ThoughtSpot Everywhere Edition License|Free Trial account +
(Evaluation only) |Developer Playground on public instance +
(Evaluation only)
a|Session API endpoints +

* __The API calls to `/tspublic/rest/v2/session/gettoken` require ThoughtSpot Everywhere license__  +
* __The home Liveboard CRUD operations require view or edit access to Liveboard objects__
__Require view or edit access to Liveboard objects__|[tag greenBackground]#✓# |[tag greenBackground]#✓#|[tag greenBackground]#✓#|[tag greyBackground]#–#
a|User API endpoints +
* __Require `ADMINISTRATION` privilege__ +
* __The `/tspublic/rest/v2/user/changepassword` endpoint is available to all users__.
|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greyBackground]#–# |[tag greyBackground]#–#
a| Group API endpoints +
__Require `ADMINISTRATION` privilege__|[tag greenBackground]#✓# |[tag greenBackground]#✓#|[tag greyBackground]#–# |[tag greyBackground]#–#
a|Metadata API endpoints +

* __Require at least view access to metadata objects__ +
* __ `POST` and `PUT` requests require edit access to metadata objects__ +
* __The import and export TML API endpoints require `DATAMANAGEMENT` privilege.__  |
[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓# +

(Query APIs only)
a|Connection API endpoints +
__Require `DATAMANAGEMENT` privilege__|[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greyBackground]#–#
a|Data API endpoints +
__Require at least view access to metadata objects__ |
[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓#
a|Report API endpoints +
__Require `DATADOWNLOADING` privilege__|
[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓#
a|Admin API endpoints +
__Require `ADMINISTRATION` privilege__|[tag greenBackground]#✓# |[tag greenBackground]#✓#|[tag greyBackground]#–# |[tag greyBackground]#–#
a|Custom action API endpoints +

* __Require `ADMINISTRATION` or `DEVELOPER` privilege__ +
* __Require edit access to saved Answer or Liveboard visualization object to associate custom action__ |[tag greenBackground]#✓# |[tag greenBackground]#✓#|[tag greyBackground]#–# |[tag greyBackground]#–#
a|Security API endpoints +
__Require edit access to metadata objects to share and view permission details__ |
[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greenBackground]#✓# |[tag greyBackground]#–#
a|Audit logs API endpoint +
__Requires `ADMINISTRATION` privilege__|[tag greenBackground]#✓# |[tag greenBackground]#✓#|[tag greyBackground]#–# |[tag greyBackground]#–#|
|=====
--
////



== Additional resources

* xref:get-started-tse.adoc[Get started with embedding]
* link:https://www.thoughtspot.com/pricing[License options and pricing, window=_blank]
