= Embed Full Application
:toc: true

:page-title: Embed Full Application
:page-pageid: full-embed
:page-description: Embed Full Application


Full embedding allows you to integrate the full ThoughtSpot content in an application.

== Full application embedding overview

Full embedded ThoughtSpot content gives your users the ability to perform many essential tasks:

* create Answers and Pinboards
* share objects with other users
* upload data, and refresh uploaded data
* relate uploaded data to existing worksheets

=== Limitations
Users in a fully  embedded application cannot perform the following tasks:

* create worksheets or views
* modify profiles
* view the Help Center


=== Browser support
Note the following support across browsers:

Supported desktop browsers::
Chrome, Edge, Firefox, and Opera
Supported mobile browsers::
Android webview, Chrome for Android, Firefox for Android, Opera for Android, and Samsung Internet
NOT supported desktop browsers::
Internet Explorer, Safari
NOT supported mobile browser::
Safari on iOS

=== Error messages and full embed

In ThoughtSpot, you can disable error messages within the ThoughtSpot `iframe`.
We provide APIs so you can access error messages and display them in your application UI appropriately.

This approach suppressing error messages inside the `<iframe>`, and uses the `window.postMessage` function to passes them through to the parent application, which acts as the listener.

You can view these 'hidden' messages in the console logs.
Contact ThoughtSpot Support to enable this feature.

== Full application embedding workflow

=== Import the JavaScript library
In your .html page, include the JavaScript file in the `<script>` tag under `<head>`:
[source,javascript]
----
<script type="text/javascript" src="<file-location>/<file-name>.js"></script>
----
=== Import the AppEmbed package
Import the AppEmbed SDK library to your application environment:

[source,javascript]
----
import { init, AppEmbed } from "ts-embed-sdk";
----
=== Import styles
[source,javascript]
----
import "./styles.css"
----
=== Add the embed domain

To allow your client application to connect to ThoughtSpot:

. Configure the URL with ThoughtSpot hostname or IP address.
. Specify the authentication method to use for authenticating application users.
+
[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: "SSO"
    });
----
+
thoughtSpotHost::
_String_. Hostname or IP address of the ThoughtSpot application.


+

---
authType::
[horizontal]
SSO::
SAML SSO authentication method. Users accessing the embedded content are authenticated with SAML SSO. 
AuthServer::
Trusted authentication method. The trusted authentication method enables applications to exchange secure tokens and grant access to the embedded content. If this authentication method is used, define the `authEndpoint`  attribute.
+
authEndpoint::
_String_. The endpoint URL of the authentication server.
None::
Requires no authentication. The user must already be logged in to ThoughtSpot before interacting with the embedded content.
+
This approach is used only for testing client applications. Do not use this in production environments.

---
=== Create an instance of the AppEmbed object
Create an instance of the AppEmbed object and pass the iframe parameters for the application pages.

[source,javascript]
----
const embed = new AppEmbed("#embed", {
  frameParams: {
    width: '100%',
    height: '100%'
  },
});
----
frameParams:: Sets the `width` and `height` dimensions to render the iframe in the web browser.

=== Construct the URL and render the application
Construct the URL of the embedded ThoughtSpot application to load in the iframe.
Render the embedded content and pass the `pageID` parameter for setting a page as an active tab when the application loads.
[source, javascript] 
----
embed.render({ pageId }: AppRenderOptions): AppEmbed {
        super.render();

        const pageRoute = this.getPageRoute(pageId);
        const src = this.getIFrameSrc(pageRoute);
        this.renderV1Embed(src);

        return this;
    }
    
----

pageId::
The unique identifier for the ThoughtSpot application page. The following values are valid.

[horizontal]
Page.Search:: 
Displays the search answers page when the application loads.
---
Page.Answers:: Displays the saved search answers (*Answers*) page when the application loads. 
Page.Pinboards:: Displays the *Pinboards* page when the application loads.
Page.Data:: Displays the *Data* page when the application loads.
Page.Home:: Displays the *Home* page when the application loads.

--- 

=== Subscribe to events
Register event handlers to subscribe to events triggered by the ThoughtSpot Search function:
[source, javascript] 
----
 embed.on("init", showLoader)
 embed.on("load", hideLoader)
  
// Functions to show or hide a loader while the iframe loads. 
 function showLoader() {
    document.getElementById("loader").style.display = "block";
    }
    
 function hideLoader() {
    document.getElementById("loader").style.display = "none";
    }
----
////
==== Event Type
init::
The search iframe is initiaized.
load::
The search iframe is loaded.
queryChanged::
The search query is modified.
dataSourceSelected::
The data source for searching data is selected. 
////

=== Test the embedded workflow

To verify the ThoughtSpot application integration, perform the following tasks:

* Load your application. 
* Verify if the page you set as the active tab opens when you load the application.
* Verify if the tabs are displayed correctly.
* Verify if the page view parameters, such as hiding or showing the data source panel, function as expected.
* If you have disabled a menu item from the search visualizations page, verify if the menu command is disabled.

////


=== Framework support for full screen embedding

Additionally, consider the following framework factors:
+++<dlentry>+++allowfullscreen::::
This attribute is the legacy precursor of `allow="fullscreen"`, and may still work with some browsers.
+ Set to `true` if the `<iframe>` can activate fullscreen mode by calling the `requestFullscreen()` method.
+ We strongly recommend that you update your embedding scripts to use the new approach inside the `<iframe>` tag.+++</dlentry>++++++<dlentry>+++Spring MVC::::  This framework supports the `allowfullscreen="true"` parameter inside the `iframe` tag.+++</dlentry>++++++<dlentry>+++React::::  This framework is case sensitive, and uses the attribute `allowFullScreen` inside the `iframe` tag.+++</dlentry>+++

== Hide the ThoughtSpot navigation bar

To hide the primary navigation, configure these:

* Ensure the app is in an `<iframe/>` .
* Set the `embedApp` flag to `true` to specify that the application is embedded.
* Set the `primaryNavHidden` flag to `true` (the default) to specify that navigation visibility is off.

If either flag is `false`, primary navigation appears.
////

////
== Additional notes

Here are some additional notes about the full embed feature:

* Call `thoughtspot.<customerURL>.com/#/answer` and use that to access the search functionality.
* Call `thoughtspot.<customerURL>.com/#/pinboards` and use that to access saved pinboards.
* Use SAML for authentication against ThoughtSpot within the `<iframe>`.

The function `updateIframeUrl(id)` contains the logic to change the src URL of the `<iframe>` when your users click  navigation buttons.
////

=== Code sample
[source,javascript]
----
import { AppEmbed, Page, AuthType, init } from '@thoughtspot/embed-sdk';

init({
    thoughtSpotHost: '<%=tshost%>',
    authType: "SSO", 
});

const appEmbed = new AppEmbed(
    document.getElementById('ts-embed'),
    {
        frameParams: {
            width: '100%',
            height: '100%',
        },
    });

appEmbed.render({
    Page.Data
});
----

++++
<a href="{{tshost}}/#/everywhere/playground/fullApp" id="preview-in-playground">Preview in Playground</a>
++++

=== Additional resources
For more information on pinboardVizEmbed SDK reference, see xref:sdk-reference.adoc[Visual Embed SDK Reference].
