= Embed full application
:toc: true

:page-title: Embed Full Application
:page-pageid: full-embed
:page-description: Embed Full Application


Full embedding allows you to integrate the full ThoughtSpot content in an application.

== Full application embedding

The full embedded ThoughtSpot content gives your users the ability to perform many essential tasks:

* create answers and pinboards
* share objects with other users
* upload data, and refresh uploaded data
* relate uploaded data to existing worksheets
* Use search answers
* Use SpotIQ


=== Limitations
Users in a fully  embedded application cannot perform the following tasks:

* create worksheets
* create views
* modify profiles
* view the Help Center

////
=== Error messages and full embed

In ThoughtSpot, you can disable error messages within the ThoughtSpot embedded context.
We provide APIs so you can access error messages and display them in your application UI appropriately.

This approach of suppressing error messages inside the `<iframe>` uses the `window.postMessage` function to pass them through to the parent application, which acts as the listener.

You can view these 'hidden' messages in the console logs.
Contact ThoughtSpot Support to enable this feature.
////
== Full application embedding workflow

=== Import the AppEmbed package
Import the AppEmbed SDK library to your application environment:

[source,javascript]
----
import { AppEmbed, Page, AuthType, init } from '@thoughtspot/visual-embed-sdk';
----

=== Add the embed domain

To allow your client application to connect to ThoughtSpot:

. Configure the URL with ThoughtSpot hostname or IP address.
. Specify the authentication method to use for authenticating application users.
+
[source,javascript]
----
init
    ({
        thoughtSpotHost:"https://<hostname>:<port>",
        authType: AuthType.SSO,
    });
----
+
thoughtSpotHost::
_String_. Hostname or IP address of the ThoughtSpot application.

+
authType::
_String_. Authentication type. You can set the `authType` attribute to one of the following values:

* `*Basic*`
+
Allows authenticating and logging in a user using the ThoughtSpot `/tspublic/v1/session/login` API. The API request passes `username` and `password` parameters to obtain an authentication token. For more information, see xref:session-api.adoc[Session API].

+
[WARNING]
Do not use this authentication method in production environments.

* `*SSO*`
+
Sets SAML SSO as the authentication method. Federated users can authenticate with their SSO credentials to access the embedded ThoughtSpot content.

* `*None*`
+
Requires no authentication. The user must already be logged in to ThoughtSpot before interacting with the embedded content.

+
[WARNING]
Do not use this authentication method in production environments.

+
* `*AuthServer*`

+
+
Enables trusted authentication method. To use the trusted authentication method, specify the  trusted authentication server in the `authEndpoint` attribute or use the `getAuthToken` method. 

+

** `*authEndpoint*` _Optional_
+
_String_. The endpoint URL of the authentication server. When the `authEndPoint` attribute is defined, a GET request is sent to the authentication endpoint, which returns the authentication token as plaintext in its API response. This attribute is not required if `getAuthToken` is used.

** `*getAuthToken*` _Optional_
+
A function that invokes the trusted authentication endpoint and returns a `Promise` string that resolves to the authentication token. This attribute is not required if `authEndpoint` is used.

** `*username*`
+
The username for trusted authentication.

=== Create an instance of the AppEmbed object
Create an instance of the AppEmbed object and pass the iframe parameters for the application pages.

[source,javascript]
----
 const appEmbed = new AppEmbed(
 document.getElementById('ts-embed'), {
     frameParams: {
         width: '100%',
         height: '100%',
    
     },
     showPrimaryNavbar: true,
     page: Page.Data,
     path: '<url-string>',
  },
  });
----
frameParams:: Sets the `width` and `height` dimensions to render the pages in the web application.

showPrimaryNavbar::
_Boolean_. Shows or hides the ThoughtSpot navigation bar.

+
++++
<a href="{{origin}}/playground/fullApp?showNavBar=true" id="preview-in-playground" target="_parent">Preview in Playground</a>
++++
path::
_String_. The URL path of the ThoughtSpot application page to embed. 

[NOTE]
When both `path` and `PageId` attributes are defined, the path definition takes precedence.

pageId::
The unique identifier for the ThoughtSpot application page. The following values are valid.
* `*Page.Search*`
+
Displays the search answers page when the application loads.

* `*Page.Answers*`
+
Displays the saved search answers (*Answers*) page when the application loads.

* `*Page.Pinboards*`
+
Displays the *Pinboards* page when the application loads.

* `*Page.Data*`
+ 
Displays the *Data* page when the application loads.

* `*Page.Home*`
+
Displays the *Home* page when the application loads.

+
++++
<a href="{{origin}}/playground/fullApp?pageId=search" id="preview-in-playground" target="_parent">Preview in Playground</a>
++++


=== Construct the URL and render the application
Construct the URL of the embedded ThoughtSpot application to load within the web page.
Render the embedded content and pass the `pageID` parameter for setting a page as an active tab when the application loads.
[source, javascript]
----
 appEmbed.render();
----


=== Subscribe to events
Register event handlers to subscribe to events triggered by the ThoughtSpot Search function:
[source, javascript]
----
 appEmbed.on(EventType.init, showLoader)
 appEmbed.on(EventType.load, hideLoader)
----

If you have added a xref:customize-actions-menu.adoc[custom action], register event handler to manage the events triggered by the custom action:

[source, javascript]
----
    pinboardEmbed.on(EmbedEvent.customAction, payload => {
    const data = payload.data;
    if (data.id === 'insert Custom Action ID here') {
        console.log('Custom Action event:', data.columnsAndData);
    }
    })
----
For a complete list of event types that you can register, see the link:https://docs.thoughtspot.com/visual-embed-sdk/typedoc/enums/embedevent.html[EmbedEvent reference page, window=_blank].

=== Test the embedded workflow

To verify the ThoughtSpot application integration, perform the following tasks:

* Load your application.
* Verify if the page you set as the active tab opens when you load the application.
* Verify if the tabs are displayed correctly.
* Verify if the page view parameters, such as hiding or showing the data source panel, function as expected.
* If you have disabled a menu item from the search visualizations page, verify if the menu command is disabled.


== Code sample
[source,javascript]
----
import { AppEmbed, Page, AuthType, init } from '@thoughtspot/visual-embed-sdk';

init({
    thoughtSpotHost: '<%=tshost%>',
    authType: AuthType.None,
});

const appEmbed = new AppEmbed(
    document.getElementById('ts-embed'),
    {
        frameParams: {
            width: '100%',
            height: '100%',
        },
        path: '<url-string>',
        Page.Data,
        },
    });

appEmbed.render();
----


++++
<a href="{{origin}}/playground/fullApp" id="preview-in-playground" target="_parent">Preview in Playground</a>
++++

== Additional resources
For more information on AppEmbed SDK reference, see xref:sdk-reference.adoc[Visual Embed SDK Reference].
