= Get Started
:toc: true
:linkattrs:
:sectanchors:


:page-title: Getting Started
:page-pageid: getting-started
:page-description: Getting Started

The ThoughtSpot Visual Embed SDK is a JavaScript library that enables you to embed ThoughtSpot components in web pages. The library provides modular packages for embedding ThoughtSpot functions such as search, visualizations, Liveboards, and the full ThoughtSpot application.

This section lists the tasks you need to complete before embedding ThoughtSpot content in your applications.

== Prerequisites

* Verify if the ThoughtSpot admin has enabled the authentication service.
+
ThoughtSpot supports xref:configure-saml.adoc[SAML SSO] and xref:trusted-authentication.adoc[trusted authentication] services.

* Verify if your host application domain is xref:security-settings.adoc[whitelisted for CORS and CSP].
* If you want to rebrand and white-label the embedded content or add custom actions to the embedded visualizations, you will require access to the ThoughtSpot Developer portal. Make sure you have administrator or developer  privileges to access the *Customizations* menu in the *Develop* tab.

== Prepare your project environment
The Visual Embed SDK is available for installation as a Node Package Manager (NPM) package. Make sure the link:https://www.npmjs.com/get-npm[NPM is installed, window=_blank] in your environment.

You can also access Visual Embed SDK, including information about how to install from NPM or run from a web repository, in the link:https://github.com/thoughtspot/visual-embed-sdk[ThoughtSpot Visual Embed SDK GitHub repository, window=_blank].

== Install the Visual Embed SDK
The latest version of the Visual Embed SDK is available at link:https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk[https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk, window=_blank].

To install the SDK, run the following command at the command line:
[source,console]
----
npm install @thoughtspot/visual-embed-sdk
----

== Import the embed package

Based on integration requirements, import any of the following embed modules and build your code.

SearchEmbed::

Use this package to xref:embed-search.adoc[embed the ThoughtSpot search] functionality.

+
The **SearchEmbed** component can be loaded up blank with a specified data source and no existing search, with a specified data source and a set of example search tokens, or with an existing saved answer.

+
In all cases, the search bar will appear along with full capabilities to edit and modify the search and the resulting chart or table.

LiveboardEmbed::

Use this package to embed ThoughtSpot xref:embed-a-viz.adoc[visualizations] and xref:embed-pinboard.adoc[Liveboards].

+
You can use the **LiveboardEmbed** component to embed a full Liveboard with multiple answers, as well as a specific answer on a Liveboard without the search bar. These answers are referred to as Liveboard visualizations.
+
Although you can use a saved answer as a data source in SearchEmbed, ThoughtSpot does not support embedding a saved answer. However, you can embed a specific visualization from a Liveboard using the `liveboardId` and `vizId` properties of LiveboardEmbed.

AppEmbed::

Use this package to embed xref:full-embed.adoc[the full ThoughtSpot application].

[#initSdk]
== Initialize the SDK

After importing the package, specify the hostname or IP address of your ThoughtSpot application instance and the authentication type.

[source,javascript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.SSO,
});
----
thoughtSpotHost::
_String_. Hostname or IP address of the ThoughtSpot application.

include::{path}/embed-auth-config.adoc[]

=== Prefetch static resources (Optional)

To prefetch static resources and load your application fast, set the `callPrefetch` attribute to `true`.

For more information, see xref:prefetch-and-cache.adoc[Prefetch static resources].

=== Configure security and login parameters (Optional)

include::{path}/embed-config.adoc[]

== Embed objects

After you initialize the SDK, create embed object classes and define object properties. +
For more information about embedding ThoughtSpot app and its objects using SDK, see the following pages:

* xref:embed-search.adoc[Embed Search]
* xref:embed-pinboard.adoc[Embed a Liveboard]
* xref:embed-a-viz.adoc[Embed a Liveboard visualization]
* xref:full-embed.adoc[Embed full ThoughtSpot app]

== Related resources

* link:{{visualEmbedSDKPrefix}}/modules.html[Visual Embed SDK Reference Guide, window=_blank] 
* link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/README.md[Visual Embed SDK GitHub repository, window=_blank]
* link:https://github.com/thoughtspot/ts_everywhere_resources[ThoughtSpot Everywhere Resources on GitHub, window=_blank]
* link:https://developers.thoughtspot.com/guides[Visual Embed Tutorials]
