= Get Started
:toc: true

:page-title: Getting Started
:page-pageid: getting-started
:page-description: Getting Started

The ThoughtSpot Visual Embed SDK is a JavaScript library that enables you to embed ThoughtSpot components in web pages. The library provides modular packages for embedding ThoughtSpot functions such as search, visualizations, pinboards, and the full ThoughtSpot application.

This section lists the tasks you need to complete before embedding ThoughtSpot content in your applications.

== Prerequisites

* Verify if the ThoughtSpot admin has enabled the authentication service.
+
ThoughtSpot supports SAML SSO and trusted authentication services.

* Verify if your host application domain is xref:security-settings.adoc[whitelisted for CORS and CSP].
* Verify if the same-site cookie setting is set to `none`.
* If you want to rebrand and white-label the embedded content or add custom actions to the embedded visualizations, you will require access to ThoughtSpot Developer Hub. Make sure you have administrator or developer  privileges to access the *Customizations* menu in the *Develop* tab.

== Prepare your project environment
The Visual Embed SDK is available for installation as a Node Package Manager (NPM) package.

If NPM is not installed, link:https://www.npmjs.com/get-npm[install NPM, window=_blank].

== Install the Visual Embed SDK
The latest version of the Visual Embed SDK is available at link:https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk[https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk, window=_blank].

To install the SDK, run the following command at the command line:
[source,console]
----
npm install @thoughtspot/visual-embed-sdk
----

== Import the embed package

Based on integration requirements, import any of the following embed modules and build your code.

* *SearchEmbed*
+
To xref:embed-search.adoc[embed the ThoughtSpot search] functionality.
* *PinboardEmbed*
+
To embed ThoughtSpot xref:embed-a-viz.adoc[visualizations] and xref:embed-pinboard.adoc[pinboards].
* *AppEmbed*
+
To embed xref:full-embed.adoc[the full ThoughtSpot application].
