= Group APIs

:page-title: Group API
:page-pageid: group-api
:page-description: Group API

The Group APIs allow you to set or remove a privilege to or from a group.

[width="100%" cols="2,3"]
|===
|`xref:group-api.adoc#add-privilege[**POST** /tspublic/v1/group/addprivilege]`|Allows you to assign the data upload and download privileges to a user group.
|`xref:group-api.adoc#remove-privilege[**POST** /tspublic/v1/group/removeprivilege]`|Allows you to remove the  privileges assigned to a group.
|===

[#add-privilege]
== Add a privilege

Use this API to add the following privileges to a group.

* `DATADOWNLOADING`
+
Allows users to download data from search results and pinboards. When the `DATADOWNLOADING` privilege is applied, users can download all the data sources that a group can access.

* `USERDATAUPLOADING`
+
Allows users to upload their data to ThoughtSpot.

[NOTE]
ThoughtSpot also has a default group called `ALL_GROUP`. When you create new users in ThoughtSpot, they are automatically assigned to the `ALL_GROUP` group. By default, the members of `ALL_GROUP` do not have the permission to download or upload data. You can use this API to add these privileges to the `ALL_GROUP` group.

=== Resource URL
----
POST /tspublic/v1/group/addprivilege
----
=== Request parameters
[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|The type of privilege to add. Valid values are `DATADOWNLOADING` and `USERDATAUPLOADING`.

|`groupNames`|string|A JSON array of group names to which you want to add the privilege. To add a privilege to all user groups, specify `ALL_GROUP`.
|====

=== Example request

.cURL

[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=DATADOWNLOADING&groupNames=ALL_GROUP' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/group/addprivilege'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/group/addprivilege
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**|Privilege added
|**204**|Successful operation
|**401**|Failure/Unauthorized request
|===

[#remove-privilege]
== Remove a privilege

Use this API to delete the `DATADOWNLOADING` or `USERDATAUPLOADING` privilege from the system default `ALL_GROUP` group.

=== Resource URL
----
POST /tspublic/v1/group/removeprivilege
----
=== Request parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|Type of the privilege to delete. Valid values are `DATADOWNLOADING` and `USERDATAUPLOADING`.

|`groupNames`|string|A JSON array of group names. To remove the privilege from all user groups, specify `ALL_GROUP`.
|====

=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=USERDATAUPLOADING&groupNames=ALL_GROUP' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/group/removeprivilege'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/group/removeprivilege
----

=== Response codes
[options="header", cols="1,2"]
|===
|HTTP Code|Description
|**200**|Privilege removed
|**204**|Successful operation
|**401**|Failure/Unauthorized request
|===
