= Group API
:toc: true

:page-title: Group API
:page-pageid: group-api
:page-description: Group API


The Group APIs enable you to set or remove a privilege to or from a group or multiple groups.

== Add a privilege

Use this API to add a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege to the system default `ALL_GROUP` group.
All users in the system are always a part of the `ALL_GROUP` group.
By default, this group does not have permission to download or upload data.

All the data sources that the `ALL_GROUP` group can access are downloadable when `DATADOWNLOADING` is applied.

=== Resource URL
----
POST /tspublic/v1/group/addprivilege
----
=== Request parameters
[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|Specifies a privilege type to add. Valid values are `DATADOWNLOADING` or`USERDATAUPLOADING` privilege.

|`groupNames`|string|Specifies a group name to add the privilege to. Valid value is `ALL_GROUP` group. 

|====

=== Example request

.cURL

[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=DATADOWNLOADING&groupNames=ALL_GROUP' 'https://<base-uri>/callosum/v1/tspublic/v1/group/addprivilege'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/group/addprivilege
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description 
|**200**|No response was specified 
|**204**|Success
|**401**|Failure/Unauthorized
|===

== Remove a privilege

Use this API to delete a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege from the system default ``ALL_GROUP``group.

=== Resource URL
----
POST /tspublic/v1/group/removeprivilege
----
=== Request parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|Specifies a privilege type to delete. Valid values are `DATADOWNLOADING` or `USERDATAUPLOADING` privilege.

|`groupNames`|string|Specifies a group name to delete the privilege to. Valid value is `ALL_GROUP` group. 

|====

=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=USERDATAUPLOADING&groupNames=ALL_GROUP' 'https://<base-uri>/callosum/v1/tspublic/v1/group/removeprivilege'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/group/removeprivilege
----

=== Response codes
[options="header", cols="1,2"]
|===
|HTTP Code|Description 
|**200**|No response was specified
|**204**|Success 
|**401**|Failure/Unauthorized 
|===


////
## Error Codes

<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
    <tr> <td><code>10003</code></td>  <td>Authentication token of type could not be authenticated by any configured realms.  Use valid realm that can authenticate these tokens.</td> <td><code>401</code></td></tr>

  </tbody>
</table>
////
