= Group API
:toc: true

:page-title: Group API
:page-pageid: group-api
:page-description: Group API

The Group APIs allow you to set or remove a privilege to or from a group.

== Add a privilege
Use this API to add the following privileges to a group.

* `DATADOWNLOADING` 
+
Allows users to download data from search results and pinboards. When `DATADOWNLOADING` privilege is applied, the users can download all the data sources that a group can access.

* `USERDATAUPLOADING` 
+
Allows users to upload their own data to ThoughtSpot.
Each user group in ThoughtSpot assigns a set of privileges for its users. 

ThoughtSpot also has a default group called `ALL_GROUP`, which includes every user in ThoughtSpot. When you create a new user, they will be added to the `ALL_GROUP` group automatically. By default, the members of `ALL_GROUP` do not have permission to download or upload data. You can use this API to add these privileges to the `ALL_GROUP` group.

 
=== Resource URL
----
POST /tspublic/v1/group/addprivilege
----
=== Request parameters
[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|Specifies a privilege type to add. Valid values are `DATADOWNLOADING` or `USERDATAUPLOADING` privilege.

|`groupNames`|string|Specifies a group name to which you want to add the privilege. The default value is `ALL_GROUP` group. 

|====

=== Example request

.cURL

[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=DATADOWNLOADING&groupNames=ALL_GROUP' 'https://<base-uri>/callosum/v1/tspublic/v1/group/addprivilege'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/group/addprivilege
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description 
|**200**|Privilege added
|**204**|Success
|**401**|Failure/Unauthorized request
|===

== Remove a privilege

Use this API to delete a `DATADOWNLOADING` or `USERDATAUPLOADING` privilege from the system default ``ALL_GROUP``group.

=== Resource URL
----
POST /tspublic/v1/group/removeprivilege
----
=== Request parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`privilege`|string|Specifies a privilege type to delete. Valid values are `DATADOWNLOADING` or `USERDATAUPLOADING` privilege.

|`groupNames`|string|Specifies a group name to delete the privilege to. The valid value is `ALL_GROUP` group. 

|====

=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'privilege=USERDATAUPLOADING&groupNames=ALL_GROUP' 'https://<base-uri>/callosum/v1/tspublic/v1/group/removeprivilege'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/group/removeprivilege
----

=== Response codes
[options="header", cols="1,2"]
|===
|HTTP Code|Description 
|**200**|Privilege removed
|**204**|Success 
|**401**|Failure/Unauthorized request
|===


////
## Error Codes

<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
    <tr> <td><code>10003</code></td>  <td>Authentication token of type could not be authenticated by any configured realms.  Use valid realm that can authenticate these tokens.</td> <td><code>401</code></td></tr>

  </tbody>
</table>
////
