= Integrate ThoughtSpot content with your UI
:toc: true
:toclevels: 1

:page-title: Integrate with embedding application UI
:page-pageid: integrate-with-app-ui
:page-description: You can use Visual Embed SDK and REST API capabilities to integrate embedded ThoughtSpot with your application's UI

This article describes how to integrate the embedded ThoughtSpot content with your application's UI elements. 

== Dynamic lists of ThoughtSpot objects

The more dynamic your content creation process is, the more likely you will want to automate the retrieval of lists of content a user can see. All ThoughtSpot content is referenced by GUIDs, which you can obtain directly from the URLs of the ThoughtSpot UI or via REST API calls. Once the user session is established in the browser via SSO, you can call any REST API for the logged-in user if you xref:api-auth-session.adoc[include the credentials in the request].

=== Get object names and GUIDs

To generate menu or selection box items with ThoughtSpot objects, you will require the names and GUIDs of the objects. You can obtain this data by making a REST API call to xref:metadata-api.adoc#metadata-list[metadata/list] or xref:metadata-api#object-header[metadata/listobjectheaders]. The `metadata/list` endpoint provides more information about tags than `metadata/listobjectheaders`. Both calls are scoped to the user and will only show the objects the user has access to.

In your REST API calls to the xref:metadata-api.adoc#metadata-list[metadata/list] and  xref:metadata-api#object-header[metadata/listobjectheaders] endpoints, you must specify the object type; that is, `PINBOARD_ANSWER_BOOK` for Liveboards, `QUESTION_ANSWER_BOOK` for answers, and `LOGICAL_TABLE` for data objects. You can also specify an additional `subtype` parameter to limit your query specifically to ThoughtSpot tables, worksheets or views. 

Both endpoints include parameters for sorting and a `category` parameter that can filter the response to show only the objects created or marked as favorites by the logged-in user.

When your application user selects or clicks on an item in the embedded UI, the GUID(s) must pass to the appropriate parameter in the options object of the Embed constructor:

* `liveboardId` for a xref:embed-pinboard.adoc[Liveboard] in a `LiveboardEmbed` object
* `liveboardId` and `vizId` for an xref:embed-a-viz.adoc[individual visualization] from a Liveboard through the `LiveboardEmbed` object
* `datasources` array for a xref:embed-search.adoc[SearchEmbed]
* `answerId` for loading a xref:embed-search.adoc[saved Answer] in a `SearchEmbed`

== Filters in the embedded UI

xref:runtime-filters.adoc[Runtime filters] can be tied into the embedding application, since they are set programmatically before loading the embedded ThoughtSpot content. If you want users to set filter values outside of the embedded ThoughtSpot content, display some type of filter UI in the embedding application, then set those values in the runtime filters section of the constructor of the *LiveboardEmbed* object.

ThoughtSpot Liveboards have four levels of filters:

Row-level security (RLS) rules::
Tied to the logged-in user and their group memberships.
Runtime filters::
Set via the Visual Embed SDK or URL parameters. Runtime filters do not display as UI filter components.
Answer filters::
Established via the search definition, not visible as UI filter components on a Liveboard, but can be viewed in **Explore** or *Edit* modes.
Liveboard filters::
Visible as UI components at the top of a Liveboard, affecting all visualizations on the Liveboard.

RLS rules are only affected by the SSO process, which makes them the appropriate layer for secure data filtering. The other filter types can all be adjusted by the end user in the browser.

Embedded search operations are always filtered by RLS rules. The end user can create their own UI filters via search within the embedded search component.

== Size and placement of LiveboardEmbed object

The first argument of the constructors of each of the Embed classes in the Visual Embed SDK (xref:search-embed.adoc[SearchEmbed], xref:embed-pinboard.adoc[LiveboardEmbed]) is a *div* element in the embedding page, where the embedded ThoughtSpot content will load.

The second argument of the constructors is a JavaScript object of options, several of which control how the embedded content fills the `div`.

`frameParams` is an object with `width` and `height` attributes. If `frameParams` is not included, the embedded ThoughtSpot will fill the `div` entirely, and resize automatically if the `div` adjusts in size. This is equivalent to `width: '100%', height: '100%'`. When `width` and `height` are set to percentages, the embedded area will be adjusted according to the proportion of the embedded div. When set to exact pixel sizes, the size of the embedded area stays fixed regardless of what happens to the `div`.

When `fullHeight` is set to `true`, the scrollbar within the embedded Liveboard area does not appear.

[source,javascript]
----
{
    frameParams: {
        'width': '100%',
        'height': '100%'
    },
    fullHeight: false
}
----

== Handle load and errors for embedded Liveboard objects

A common workflow is to use an overlay `div` element to hide the embed content until you know that SSO has completed and the content is fully loaded. If an error occurs in the process, you may prefer to display your own custom message to the end user rather than showing embedded ThoughtSpot content in an error state.

The Visual Embed SDK provides xref:embed-events.adoc[events] to take action at various places within the loading process. The following events are related to the load process:

. `Init`
+
Fires at the beginning of the loading process.
. `NoCookieAccess` 

+
Some browsers (Safari in particular) default to strict settings on cookie origins that prohibit the standard SSO process. This event fires if cookies are restricted by a user's browser.

. `AuthExpire`
+
Fires if SSO does not complete and if the ThoughtSpot session times out at some point. Listen to the `AuthExpire` event in the load process to determine when it is safe to show the ThoughtSpot content, and listen to it after loading to hide the ThoughtSpot login screen if the session expires for some reason.

. `AuthInit` 
+
Fires when the SSO process has completed correctly. The event does not fire when an SSO process fails, instead `AuthExpire` fires in that situation. The logged-in user GUID is available in the response of the `AuthInit` event.

. `Error` 

+
Fires if any other error occurs in the Visual Embed SDK process. Does not fire for errors within the embedded ThoughtSpot content

. `Load`
+
Fires as soon as the area for embedding is created, not when the content has begun or finished loading.

. `Data`
+
Fires only on `SearchEmbed` components. Never fires with a `LiveboardEmbed` component.

The full list events are defined in the link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts[types.ts, window=_blank] file of the Visual Embed SDK source.

`AuthExpire` and `AuthInit` can be used together to determine if the SSO process is completed correctly. To determine if `AuthExpire` is firing because SSO did not complete or if the ThoughtSpot session has timed out, you can set a variable to act as a flag to determine if SSO is completed. When `AuthInit` fires, set the flag to *true*. You can also associate a callback function to `AuthExpire` to look up the flag to determine which state change has caused the `AuthExpire` event to fire. In the following example, the `tsLoggedIn` flag is set to indicate the SSO login state. 

[source,javascript]
----
// Instantiate class for embedding a Liveboard
const embed = new LiveboardEmbed("#thoughtspot-embed", {
    liveboardId: '<Liveboard-guid>',
});
let tsLoggedIn = false;
embed
    .on(EmbedEvent.Init, showLoader)
    .on(EmbedEvent.NoCookieAccess, showCookieSettingsMsg)
    .on(EmbedEvent.AuthInit, (response) => {
        // Set that AuthInit has fired
        tsLoggedIn = true;
        // authInit returns object -> {type: 'authInit', data: {userGuid: <guid>} } }
        let userGUID = response.data.userGuid;
    })
    .on(EmbedEvent.AuthExpire, (response) => {
        // Handle if session dies while content shows
        if (tsLoggedIn == true) {
            tsSessionTimeoutCleanup();
        } else {
            // Display custom message if SSO issues
            showSSOFailedMsg();
        }
    })
    .on(EmbedEvent.Error, showGenericErrorMsg)
    .render()
----

=== Custom actions and interaction events

xref:custom-action-intro.adoc[Custom actions] fire an event when a user clicks on a menu item when set as  xref:custom-action-callback.adoc[callback actions]. The event provides the custom action identifier, the data from the visualization and additional information depending on the configuration.

Custom actions provide a way for interaction within the ThoughtSpot components to trigger further workflows within the embedding application.

There are other xref:embed-events.adoc#embed-events[events] that fire as the user interacts with the `SearchEmbed` and `LiveboardEmbed` components:

* `Drilldown`
* `VizPointDoubleClick`

See below for additional events that fire only on the SearchEmbed component.

== Control SearchEmbed component behavior

There are three general ways to use the xref:embed-search.adoc[SearchEmbed] component:

. Load with no datasources selected
. Load with particular datasources
. Load an existing saved answer

In cases 1 and 2, you can also define the items to appear in the search bar using the `searchOptions` object. The `searchOptions` object has two properties:

* `searchTokenString`
* `executeSearch`

When `executeSearch` is *true*, the search component will load the chart or table automatically. If `executeSearch` is *false*, the search bar will display the terms from `searchTokenString`, but the user must click the *GO* button to execute the search.

The `forceTable` option causes the search to load in table mode rather than with the automatically chosen visualization.

`collapseDataSources` and `hideDataSources` control the data source pane on the left side of the search component. When `hideDataSources` is *true*, there is no way for the user to see the data source pane, while `collapseDataSources` loads to only an icon which can be used to expand the pane.

=== Use search bar without displaying results

The `hideResults` parameter in the options object blocks the *GO* button from displaying the chart or table results. When this option is *true*, you can listen to the `QueryChanged` event to capture the TML search string from the search bar, then use that query string in the xref:search-data-api.adoc[search data REST API].

=== SearchEmbed Events
There are several events that fire only on the SearchEmbed component:

* `DataSourceSelected`
+
Fires when a change occurs in the data sources, including initial load of the `SearchEmbed` component. Can be used to hide a loader screen. Return object contains an array of the selected column GUIDs (accessible using `LOGICAL_COLUMN` type within metadata REST API commands).

* `QueryChanged`
+
Fires when a change occurs in the search bar, including the initial load of the SearchEmbed component. Returned object includes a `data.search` property with the TML search query from the search box.


== Additional Resources

link:https://github.com/thoughtspot/ts_everywhere_resources/blob/master/apis/rest-api.js[Example implementation of REST API calls in JavaScript, window=_blank]


