= Integrate ThoughtSpot content with your UI
:toc: true
:toclevels: 1

:page-title: Integrate with embedding application UI
:page-pageid: integrate-with-app-ui
:page-description: You can use Visual Embed SDK and REST API capabilities to integrate embedded ThoughtSpot with your application's UI


This article describes how to integrate the embedded ThoughtSpot content with your application's UI elements. 

== Navigation to ThoughtSpot objects
You can use the ThoughtSpot REST API to create navigation elements in the form of navigation pages, menus, or drop-down selectors. 

This allows you to give dynamic navigation to objects to your users with full control of the display.

All REST API requests from the browser are scoped to the signed-in user and will only show the objects the user has access to.

=== REST API request
The ThoughtSpot web application UI uses the xref:metadata-api.adoc#metadata-list[metadata/list REST API endpoint] in rendering the Answers, Liveboards, and Data pages. 

The endpoint can only request one object type at a time: `PINBOARD_ANSWER_BOOK` for Liveboards, `QUESTION_ANSWER_BOOK` for answers, and `LOGICAL_TABLE` for data objects. Data objects can be filtered using an additional `subtype` parameter to limit the query specifically to ThoughtSpot tables, worksheets or views. 

There are additional parameters for sorting and a `category` parameter that can filter the response to show only the objects created or marked as favorites by the logged-in user.

REST API calls are by nature asynchronous. The following is an example function returning the response as a JSON object using *fetch()*:
[source,javascript]
----
    async function metadataListRestApiCall(args){
        // args = { 'type', 'category', 'sortOn', 'sortAsc', 'tagnames' }
        let type = args['type'].toLowerCase();
        const publicApiUrl = 'callosum/v1/tspublic/v1/';
        let endpoint = 'metadata/list';
        
        // Easy type names match ThoughtSpot UI names for objects
        const typesToApiType = { 
            'liveboard': 'PINBOARD_ANSWER_BOOK',
            'answer': 'QUESTION_ANSWER_BOOK',
            'datasource' : 'LOGICAL_TABLE', // datasource doesn't distinguish sub-types
            'table' : 'ONE_TO_ONE_LOGICAL',
            'view' : 'AGGR_WORKSHEET',
            'worksheet' : 'WORKSHEET'
        }

        // batchsize = -1 gives all results
        let apiParams = { 'batchsize' : '-1'};
        console.log(type);
        // The three datasource types can be specified using 'subtype'
        if (type == 'table' || type == 'view' || type == 'worksheet'){
            let subtype = [typesToApiType[type]];
            apiParams['type'] = 'LOGICAL_TABLE';
            apiParams['subtypes'] = `["${subtype}"]`;
        }
        else {
            apiParams['type'] = typesToApiType[type];
        }

        // Category arguments
        let category = 'ALL';
        if ('category' in args){
            if ( args['category'] == 'MY' || args['category'] == 'ALL' || args['category'] == 'FAVORITE'){
                category = args['category'];
                apiParams['category'] = category;
            }
        }

        // Sort arguments
        if ('sortOn' in args){
            if (args['sortOn'] !== null){
                apiParams['sort'] = args['sortOn'];
            }
        }

        if ('sortAsc' in args){
            if (args['sortAsc'] === true){
                apiParams['sortascending'] = 'true';
            }
            if (args['sortAsc'] === false){
                apiParams['sortascending'] = 'false';
            }
        }

        console.log(apiParams);
        const searchParams = new URLSearchParams(apiParams);
        const apiFullEndpoint = tsURL + publicApiUrl + endpoint + "?" + searchParams.toString();
        console.log(apiFullEndpoint);
        return await fetch(
            apiFullEndpoint, {
            method: 'GET',
            headers: {
                "Accept": "application/json",
                "X-Requested-By": "ThoughtSpot"
            },
            credentials: "include"
            })
        .then(response =>  response.json())
        .then(data => data['headers'])  // metadata/list info is really in the 'headers' property returned
        .catch(error => {
        console.error("Unable to get the metadata/list response: " + error)
        });
    }
----

The results of this REST API request can be directed into a rendering function using `.then()`:

[source,javascript]
----
metadataListRestApiCall(
    {
        'type': 'liveboard', 
        'sortOn': 'NAME', 
        'sortAsc' : true, 
        'category': 'ALL'
    })
.then(
    (listResponse) => renderNavigationFromResponse(listResponse) // Use your own rendering function here
);
----

=== Render navigation elements
The response from the function above is an array of headers objects, which can be parsed to render navigation. 

The `name` and `id` property will be used in almost navigation you build (`id` is the GUID necessary to load any ThoughtSpot object). Additional properties of interest:

* `description` : text description added to content by creator 
* `authorDisplayName`: display name of the object creator or current owner
* `authorName`: username of the object creator or current owner
* `created` : object creation timestamp (to milliseconds)
* `modified`: last edit timestamp (to milliseconds)
* `tags`: array of tag objects, each with a `name` property among other details

==== Navigation pages
If you want to render something very close to the 'Answers' or 'Pinboards' page within the ThoughtSpot UI, your rendering function will grab the `name`, `id`, `tags`, `modified` and `authorDisplayName` properties and make a table in that order (feel free to leave out any undesired elements):

[source,javascript]
----
    function tableFromList(listResponse){
        console.log(listResponse);
        let t = document.createElement('table');

        // Make table headers 
        let thead = document.createElement('thead');
        t.append(thead);
        let thr = document.createElement('tr');
        thead.append(thr);
        let headers = ['Name', 'Tags', 'Modified', 'Author'];
        for (let i=0, len=headers.length; i < len; i++){
            let th = document.createElement('th');
            th.innerText = headers[i];
            thr.append(th);
        }

        // Go through response and build rows
        for (let i=0, len=listResponse.length; i < len; i++){
            let tr = document.createElement('tr');
            
            // Name Column
            let name_td = document.createElement('td');
            name_td.innerHTML = '<a href="#" onclick="loadContent("' + listResponse[i]['id'] + '")>' +  listResponse[i]['name'] +  '</a>';
            //name_td.append(name_text);
            console.log(name_td);
            tr.append(name_td);
            
            // Tags column
            let tags_td = document.createElement('td');
            console.log(listResponse[i]['tags']);
            // Tags is an Array of Tag objects, with properties ('name' being the important one)
            if (listResponse[i]['tags'].length > 0){
                let tagNames = [];
                for(let k = 0, len = listResponse[i]['tags'].length; k<len; k++){
                    let tagName = listResponse[i]['tags'][k]['name'];
                    tagNames.push(tagName);
                }
                tags_td.innerText = tagNames.join(', ');
            }
            tr.append(tags_td);

            // Modified Date column
            let modified_td = document.createElement('td');
            modified_td.innerText = listResponse[i]['modified'];
            tr.append(modified_td);

            let author_td = document.createElement('td');
            author_td.innerText = listResponse[i]['authorDisplayName'];
            tr.append(author_td);

            t.append(tr);

        }

        return t;
    }
----

The above function merely creates the table, it does not place it into the page. You can continue chaining using `.then()` to place the table in the appropriate place in your web application page :

[source,javascript]
----
metadataListRestApiCall(
    {
        'type': 'liveboard', 
        'sortOn': 'NAME', 
        'sortAsc' : true, 
        'category': 'ALL'
    })
.then(
    (response) => tableFromList(response)
).then(
    (table) => document.getElementById('main-content-div').append(table)
);
----

Also note the `loadContent()` function referenced in the anchor tag created for the name column in the function above is is a placeholder representing whatever is necessary to load that type of ThoughtSpot content in the web application. Loading content is discussed in the next section, but the actual design you choose for your application will determine the code you need to go from the navigation component to loading the ThoughtSpot content.

=== Load ThoughtSpot content in embed components
However you have rendered the navigation element, when the user selects the object, the GUID of the object must pass to the appropriate parameter in the options object of the Embed constructor for one of the embed components:

* `liveboardId` for a xref:embed-pinboard.adoc[Liveboard] in a `LiveboardEmbed` object
* `liveboardId` and `vizId` for an xref:embed-a-viz.adoc[individual visualization] from a Liveboard through the `LiveboardEmbed` object
* `datasources` array for a xref:embed-search.adoc[SearchEmbed]
* `answerId` for loading a xref:embed-search.adoc[saved Answer] in a `SearchEmbed`

In general, most web applications will put the ThoughtSpot GUID into the URL in a way that allows the page to be bookmarked: `{domain.com}/analytics/dashboard/{liveboardGUID}` would be an example of a 'true' URL, while `{domain.com}/analytics/\#dashboard/{liveboardGUID}` is an alternative example often seen in single-page style apps where the fragment specifying the object type and GUID can be read within the page's JavaScript to command different content to be loaded without going to an actual different page.

=== Load individual visualizations from a Liveboard
Individual visualizations on a Liveboard can be loaded using the LiveboardEmbed component by supplying both the `liveboardId` and the `vizId`. 

The display of a visualization from a Liveboard differs from a saved answer object, which are loaded via the SearchEmbed component and always display the ThoughtSpot search bar and other editing UI. Visualizations display with a minimal amount of UI and control over all menu items that will appear in the `...` menu.

The xref:metadata-api.adoc#viz-header[get visualization headers REST API endpoint] is used to retrieve a list of visualizations from a given Liveboard. 

[source,javascript]
----
async function metadataGetVizHeadersRestApiCall(liveboardGuid){
    // args = { 'type', 'category', 'sortOn', 'sortAsc', 'tagnames' }
    let type = args['type'].toLowerCase();
    const publicApiUrl = 'callosum/v1/tspublic/v1/';
    let endpoint = 'metadata/listvizheaders';

    // batchsize = -1 gives all results
    let apiParams = { 'id' : liveboardGuid};
    const searchParams = new URLSearchParams(apiParams);
    const apiFullEndpoint = tsURL + publicApiUrl + endpoint + "?" + searchParams.toString();
    console.log(apiFullEndpoint);
    return await fetch(
        apiFullEndpoint, {
        method: 'GET',
        headers: {
            "Accept": "application/json",
            "X-Requested-By": "ThoughtSpot"
        },
        credentials: "include"
        })
    .then(response =>  response.json())
    // 
    .then(data => data)  // metadata/list info is really in the 'headers' property returned
    .catch(error => {
    console.error("Unable to get the metadata/listvizheaders response: " + error)
    });
}
----

== Filters in the embedded UI

xref:runtime-filters.adoc[Runtime filters] can be tied into the embedding application, since they are set programmatically before loading the embedded ThoughtSpot content. If you want users to set filter values outside of the embedded ThoughtSpot content, display some type of filter UI in the embedding application, then set those values in the runtime filters section of the constructor of the *LiveboardEmbed* object.

ThoughtSpot Liveboards have four levels of filters:

Row-level security (RLS) rules::
Tied to the logged-in user and their group memberships.
Runtime filters::
Set via the Visual Embed SDK or URL parameters. Runtime filters do not display as UI filter components.
Answer filters::
Established via the search definition, not visible as UI filter components on a Liveboard, but can be viewed in **Explore** or *Edit* modes.
Liveboard filters::
Visible as UI components at the top of a Liveboard, affecting all visualizations on the Liveboard.

RLS rules are only affected by the SSO process, which makes them the appropriate layer for secure data filtering. The other filter types can all be adjusted by the end user in the browser.

Embedded search operations are always filtered by RLS rules. The end user can create their own UI filters via search within the embedded search component.

== Size and placement of LiveboardEmbed object

The first argument of the constructors of each of the Embed classes in the Visual Embed SDK (xref:search-embed.adoc[SearchEmbed], xref:embed-pinboard.adoc[LiveboardEmbed]) is a *div* element in the embedding page, where the embedded ThoughtSpot content will load.

The second argument of the constructors is a JavaScript object of options, several of which control how the embedded content fills the `div`.

`frameParams` is an object with `width` and `height` attributes. If `frameParams` is not included, the embedded ThoughtSpot will fill the `div` entirely, and resize automatically if the `div` adjusts in size. This is equivalent to `width: '100%', height: '100%'`. When `width` and `height` are set to percentages, the embedded area will be adjusted according to the proportion of the embedded div. When set to exact pixel sizes, the size of the embedded area stays fixed regardless of what happens to the `div`.

When `fullHeight` is set to `true`, the scrollbar within the embedded Liveboard area does not appear.

[source,javascript]
----
{
    frameParams: {
        'width': '100%',
        'height': '100%'
    },
    fullHeight: false
}
----

== Handle load and errors for embedded Liveboard objects

A common workflow is to use an overlay `div` element to hide the embed content until you know that SSO has completed and the content is fully loaded. If an error occurs in the process, you may prefer to display your own custom message to the end user rather than showing embedded ThoughtSpot content in an error state.

The Visual Embed SDK provides xref:embed-events.adoc[events] to take action at various places within the loading process. The following events are related to the load process:

. `Init`
+
Fires at the beginning of the loading process.
. `NoCookieAccess`

+
Some browsers (Safari in particular) default to strict settings on cookie origins that prohibit the standard SSO process. This event fires if cookies are restricted by a user's browser.

. `AuthExpire`
+
Fires if SSO does not complete and if the ThoughtSpot session times out at some point. Listen to the `AuthExpire` event in the load process to determine when it is safe to show the ThoughtSpot content, and listen to it after loading to hide the ThoughtSpot login screen if the session expires for some reason.

. `AuthInit` 
+
Fires when the SSO process has completed correctly. The event does not fire when an SSO process fails, instead `AuthExpire` fires in that situation. The logged-in user GUID is available in the response of the `AuthInit` event.

. `Error` 

+
Fires if any other error occurs in the Visual Embed SDK process. Does not fire for errors within the embedded ThoughtSpot content

. `Load`
+
Fires as soon as the area for embedding is created, not when the content has begun or finished loading.

. `Data`
+
Fires only on `SearchEmbed` components. Does not fire on a `LiveboardEmbed` component.

The full list events are defined in the link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts[types.ts, window=_blank] file of the Visual Embed SDK source.

`AuthExpire` and `AuthInit` can be used together to determine if the SSO process is completed correctly. To determine if `AuthExpire` is firing because SSO did not complete or if the ThoughtSpot session has timed out, you can set a variable to act as a flag to determine if SSO is completed. When `AuthInit` fires, set the flag to *true*. You can also associate a callback function to `AuthExpire` to look up the flag to determine which state change has caused the `AuthExpire` event to fire. In the following example, the `tsLoggedIn` flag is set to indicate the SSO login state. 

[source,javascript]
----
// Instantiate class for embedding a Liveboard
const embed = new LiveboardEmbed("#thoughtspot-embed", {
    liveboardId: '<Liveboard-guid>',
});
let tsLoggedIn = false;
embed
    .on(EmbedEvent.Init, showLoader)
    .on(EmbedEvent.NoCookieAccess, showCookieSettingsMsg)
    .on(EmbedEvent.AuthInit, (response) => {
        // Set that AuthInit has fired
        tsLoggedIn = true;
        // authInit returns object -> {type: 'authInit', data: {userGuid: <guid>} } }
        let userGUID = response.data.userGuid;
    })
    .on(EmbedEvent.AuthExpire, (response) => {
        // Handle if session dies while content shows
        if (tsLoggedIn == true) {
            tsSessionTimeoutCleanup();
        } else {
            // Display custom message if SSO issues
            showSSOFailedMsg();
        }
    })
    .on(EmbedEvent.Error, showGenericErrorMsg)
    .render()
----

=== Custom actions and interaction events

xref:custom-action-intro.adoc[Custom actions] fire an event when a user clicks on a menu item when set as  xref:custom-action-callback.adoc[callback actions]. The event provides the custom action identifier, the data from the visualization and additional information depending on the configuration.

Custom actions provide a way for interaction within the ThoughtSpot components to trigger further workflows within the embedding application.

There are other xref:embed-events.adoc#embed-events[events] that fire as the user interacts with the `SearchEmbed` and `LiveboardEmbed` components:

* `Drilldown`
* `VizPointDoubleClick`

See below for additional events that fire only on the SearchEmbed component.

== Control SearchEmbed component behavior

There are three general ways to use the xref:embed-search.adoc[SearchEmbed] component:

. Load with no datasources selected
. Load with particular datasources
. Load an existing saved answer

In cases 1 and 2, you can also define the items to appear in the search bar using the `searchOptions` object. The `searchOptions` object has two properties:

* `searchTokenString`
* `executeSearch`

When `executeSearch` is *true*, the search component will load the chart or table automatically. If `executeSearch` is *false*, the search bar will display the terms from `searchTokenString`, but the user must click the *GO* button to execute the search.

The `forceTable` option causes the search to load in table mode rather than with the automatically chosen visualization.

`collapseDataSources` and `hideDataSources` control the data source pane on the left side of the search component. When `hideDataSources` is *true*, there is no way for the user to see the data source pane, while `collapseDataSources` loads to only an icon which can be used to expand the pane.

=== Use search bar without displaying results

The `hideResults` parameter in the options object blocks the *GO* button from displaying the chart or table results. When this option is *true*, you can listen to the `QueryChanged` event to capture the TML search string from the search bar, then use that query string in the xref:search-data-api.adoc[search data REST API].

=== SearchEmbed Events
There are several events that fire only on the SearchEmbed component:

* `DataSourceSelected`
+
Fires when a change occurs in the data sources, including initial load of the `SearchEmbed` component. Can be used to hide a loader screen. Return object contains an array of the selected column GUIDs (accessible using `LOGICAL_COLUMN` type within metadata REST API commands).

* `QueryChanged`
+
Fires when a change occurs in the search bar, including the initial load of the SearchEmbed component. Returned object includes a `data.search` property with the TML search query from the search box.


== Additional Resources

link:https://github.com/thoughtspot/ts_everywhere_resources/blob/master/apis/rest-api.js[Example implementation of REST API calls in JavaScript, window=_blank]


