= Introduction to ThoughtSpot objects and terminology

ThoughtSpot is different from other BI tools, because ThoughtSpot Search is the core of the ThoughtSpot system. Before you look at the rest of the developer documentation, please review this page to understand how ThoughtSpot works relative to other tools you may be familiar with.

== Data modeling
You must create a data model comprising at least a *connection* with one *table* to begin using *Search Data* to create content. Most often there will be multiple *tables*, with a variety of *joins* defined in ThoughtSpot, with a *worksheet* bringing those tables together into a presentable analytic data model for the end-users.

*Tables* can have *Row Level Security (RLS)* rules that filter the data results based on the signed in *username* or the *ThoughtSpot groups* the user belongs to, and those rules apply to any *worksheet* that uses the *table*.

=== Data modeling workflow
1. Make *connection* to cloud data warehouse
2. Import *tables* from the *connection*
3. Create *worksheets* (analytic data models) based on *tables*
4. Create ThoughtSpot *views* or *SQL views* as necessary

== Content creation
The best practice workflow for content creation is:

1. Use *Search Data* to build visualizations/widgets from *worksheets* as data source
2. Save the search as an "answer" or pin the search to a "Liveboard"

ThoughtSpot Search Data creates a single table or chart view based on the Search Bar and other settings. 

*Liveboards* combine together many visualizations. You do not create the visualizations on a Liveboard directly; they are created from Search Data then *pinned to a Liveboard*. You can create a new Liveboard from the Liveboards page then go to Search Data, or create a new Liveboard when pinning from Search Data.

Search Data serves the role of report builder / widget designer, while a Liveboard serves the role of dashboards in other tools. 

A single saved search is an *answer* object.
 
You can pin any number of searches to a *Liveboard* object as a "visualization". Once pinned, that *visualization only exists within the Liveboard*, there is no connection between a Liveboard object and any separate answer object. 

Each time you pin from Search Data, it will create a new separate visualization on the Liveboard.

To edit a *visualization* on a Liveboard, go to the Liveboard then click the *More (...)* menu in the top left of a visualization and choose *Edit*.

*Visualizations* on a Liveboard have their own GUIDs, but the visualization objects do not exist separately from the Liveboard object.

== Access control (sharing)
ThoughtSpot's access control model works by an *author* or *admin* *sharing* objects to ThoughtSpot *groups* or other indvidual users: 

* The creator of an object is the *author*
* The *author* can *share* the object to *groups* with the *Shareable* property that the *author* belongs to
* The *author* can *share* the object to other users in *Shareable groups* that the *author* belongs to, if the other *user* is also marked *Shareable*

An *admin user* can share any object to any group or user with no restrictions.

== Tags
Tags can be added to objects for organization and searching. 

Tags exist as separate objects that are defined, visible, and assignable by every user.

Tag search is always an *OR* operation where allowed: filtering on multiple tags results in all objects with any of the tags, not just those with all of the specified tags. 

== API properties

* `id`: GUID of the object. Unique within a given ThoughtSpot instance
* `author`: GUID of user who created / uploaded the object, or had the object transfered to them
* `owner`: GUID representing relationship between hierarchical objects (for example, a *column* would have the GUID of a *table* or *worksheet* as owner)
* `created`: 
* `modified`: 
* `modifiedBy`: 
* `tags`: 

== API object names


Column objects with their own GUIDs do exist within the ThoughtSpot instance, but they are connected to *tables* or *worksheets* or other data objects and are never seen or modified separately.
