= ThoughtSpot Everywhere
:toc: true

:page-title: Embedded Analytics with ThoughtSpot
:page-pageid: embed-analytics
:page-description: Embedded Analytics with ThoughtSpot

ThoughtSpot Everywhere provides a low-code embedded analytics platform for developers and product owners to build interactive data apps and incorporate ThoughtSpot functions and services directly into their apps, products, or services. Using ThoughtSpot Everywhere, you can embed search-driven analytics, infuse insights into your application, and enrich your website, portal, or product with ThoughtSpot's analytical capabilities.

The ThoughtSpot Everywhere platform provides your developers with the Visual Embed SDK to programmatically embed search-driven analytics, pinboards, visualizations, and even the entire ThoughtSpot application. ThoughtSpot also provides REST API services to programmatically query data, manage users and user sessions, push data to an external application, and automate deployments. 

== Embedding methods
You can use one of the following methods to embed ThoughtSpot into your host application:

Using Visual Embed SDK::
You can install the Visual Embed SDK, import the Javascript library, and programmatically integrate ThoughtSpot application and its components.
The Visual Embed SDK includes separate libraries for embedding ThoughtSpot content, such as search, visualizations, pinboards, and the full application.

+
For more information, see xref:visual-embed-sdk.adoc[Visual Embed SDK].

Using REST APIs::
You can use the REST APIs to programmatically query data from the ThoughtSpot application. You can also use REST APIs to manage users and perform other key functions.
+
For more information, see xref:about-rest-apis.adoc[REST APIs].

== ThoughtSpot Developer portal
To facilitate faster application integration and assist developers, ThoughtSpot provides the Developer portal. The portal includes a playground for application developers to learn and explore the Visual Embed SDK components. Developers can interact with the embed modules, try integrating ThoughtSpot content in their applications, and view results instantly.

The portal provides customization settings to customize and rebrand the look and feel of your application. You can also add custom actions that can be invoked from the embedded  UI and trigger your application or a URL with ThoughtSpot data as a payload. 

You can access the Developer portal either from the ThoughtSpot website, or by using the *Develop* tab in the ThoughtSpot application. To access the *Develop* tab in the ThoughtSpot application, you need administrator or developer user privileges.

For more information, see xref:spotdev-portal.adoc[ThoughtSpot Developer portal].

////
== Types of embedding
ThoughtSpot supports embedding the full application or its individual components into your business solution.
Based on your business needs and integration environment, you can use one of the following embedding approaches:

Full application embedding::
You can embed the entire ThoughtSpot application into your host application or portal. The full application embedding allows your users to access ThoughtSpot tabs and pages within the context of your application.

Page-level embedding::
You can embed a ThoughtSpot page and hide  the navigation bar, help, and profile links. The host application can allow page-to-page navigation.
Object-level embedding::
You can embed a specific ThoughtSpot component such as the search functionality, pinboards, or charts.
////


== UI customization and rebranding
If you have embedded the ThoughtSpot application in your host application, you can customize the look and feel of ThoughtSpot UI to match your organization's branding guidelines.

You can customize the ThoughtSpot application UI by using the style customization settings in the Developer portal.

For more information, see xref:customize-style.adoc[Style customization].

== Custom actions
ThoughtSpot allows you to add custom actions to the embedded  pinboards and visualizations.

For example, you can add a button to the ThoughtSpot UI that will trigger a workflow in your parent application.  

For more information, see xref:customize-actions-menu.adoc[Actions customization].

== Custom link format

When a user shares an object with another user or follows a pinboard to receive periodic notifications, ThoughtSpot generates links to access objects, such as pinboards, visualizations, and search answers. If you have embedded ThoughtSpot in your application, you might want to generate these links in the format that preserves your host application context.

ThoughtSpot allows you to customize the format of the links in the Developer portal. The *Link Settings* page in the Developer portal allows you to customize the link format for various resource URLs and the *unsubscribe* link sent in email notifications.

For more information, see xref:customize-links.adoc[Customize links].
