= ThoughtSpot Everywhere for embedded analytics
:toc: true

:page-title: Embedded Analytics with ThoughtSpot Everywhere
:page-pageid: embed-analytics
:page-description: Embedded Analytics with ThoughtSpot

ThoughtSpot Everywhere provides a low-code embedded analytics platform for developers and product owners to build interactive data apps and incorporate ThoughtSpot functions and services directly into their apps, products, or services. Using ThoughtSpot Everywhere, you can embed search-driven analytics, infuse insights into your application, and enrich your website, portal, or product with ThoughtSpot's capabilities.

ThoughtSpot Everywhere provides the Visual Embed SDK to embed search-driven analytics, Liveboards, visualizations, and even the entire ThoughtSpot experience in your application. ThoughtSpot also supports REST API services to programmatically query data, manage users and user sessions, push data to an external application, and automate deployments.

== Embedding methods
You can use one of the following methods to embed ThoughtSpot into your host application:

Using Visual Embed SDK::
You can install the Visual Embed SDK, import the Javascript library, and programmatically integrate ThoughtSpot application and its components.
The Visual Embed SDK includes separate libraries for embedding ThoughtSpot content, such as search, visualizations, Liveboards, and the full application.

+
For more information, see xref:visual-embed-sdk.adoc[Visual Embed SDK].

Using REST APIs::
You can use the REST APIs to programmatically query data from the ThoughtSpot application. You can also use REST APIs to manage users and perform other key functions.
+
For more information, see xref:about-rest-apis.adoc[REST APIs].

== ThoughtSpot Developer portal

To allow your application developers to experiment with the Visual Embed APIs, ThoughtSpot provides the Developer portal. The portal includes a playground for developers to learn and explore the Visual Embed SDK components. Developers can interact with the embed modules, try integrating ThoughtSpot content in a fictional app, and view results instantly.

If you want to try the Developer playground and evaluate ThoughtSpot embedding experience, you can access the Playground from the link:https://developers.thoughtspot.com/[ThoughtSpot Developers website, window=_blank].

If you are a ThoughtSpot user, you can access this portal by clicking the *Develop* tab in your ThoughtSpot application instance. To access the portal, you need administrator or developer privileges.  For authenticated users, the portal provides a set of customization controls to rebrand the look and feel of your application, insert custom buttons and actions, customize link format and URLs, and so on.

== UI customization and rebranding
If you have embedded the ThoughtSpot application in your host application, you can customize the look and feel of ThoughtSpot UI to match your organization's branding guidelines.

You can customize the ThoughtSpot application UI by using the style customization settings in the Developer portal.

For more information, see xref:customize-style.adoc[Customize styles and layout].

== Custom actions

ThoughtSpot allows you to add custom actions to embedded Liveboards and visualizations.

For example, you can add a button to the ThoughtSpot UI that will trigger a workflow in your parent application.

For more information, see xref:custom-actions.adoc[Custom actions].

== Custom link format

When a user shares an object with another user, ThoughtSpot generates a link to the shared object and sends it in email notifications. ThoughtSpot also generates system notifications when a user schedules a Liveboard job or runs SpotIQ analysis. If you have embedded ThoughtSpot in your application, you might want to generate these links in the format that preserves your host application context.

ThoughtSpot allows you to customize the format of the links in the Developer portal. The *Links settings* page in the Developer portal allows you to customize the link format for various resource URLs and the *unsubscribe* link sent in email notifications.

For more information, see xref:customize-links.adoc[Customize links].
