= ThoughtSpot Everywhere
:toc: true

:page-title: ThoughtSpot Everywhere
:page-pageid: embed-analytics
:page-description: Embedded Analytics with ThoughtSpot

ThoughtSpot Everywhere provides a low-code embedded analytics platform for developers and product owners to build interactive data apps and integrate ThoughtSpot functions and services directly into their apps, products, or services. Using ThoughtSpot Everywhere, you can embed search-driven analytics, infuse insights, and enrich your product with ThoughtSpot's capabilities.

ThoughtSpot Everywhere offers a robust API framework with Visual Embed SDK and REST APIs to embed and customize ThoughtSpot components, and automate deployments. You can explore these APIs and preview the coding experience in the interactive developer playgrounds.

[IMPORTANT]
====
We recommend using ThoughtSpot Everywhere to embed ThoughtSpot in your app starting from the 8.4.0-sw release. To enable ThoughtSpot Everywhere on your instance and get access to Visual Embed SDK, developer playground, security settings, and customization capabilities, contact ThoughtSpot Support.
====

== Visual embed SDK

The Visual Embed SDK provides Javascript-based embed packages and client libraries to embed and customize ThoughtSpot components in your web application. The SDK package includes separate libraries for embedding Search, Liveboard, full ThoughtSpot application, or a single visualization. To explore the Visual Embed APIs, navigate to the *Develop* tab and click *Visual Embed Playground*.

For more information, see xref:visual-embed-sdk.adoc[Visual Embed SDK].

== Using REST API
ThoughtSpot REST API v1 framework allows your client applications to query data, add and modify ThoughtSpot objects, and perform administrative tasks.

The REST API v2 Playground and SDK playground[beta blueBackground]^BETA^ feature offers language-specific SDK libraries and packages, using which  you can call REST APIs from your clients and programmatically manage ThoughtSpot objects.

For more information, see xref:about-rest-apis.adoc[REST APIs].

== Developer portal

ThoughtSpot Everywhere users with Developer or admin privilege can access the *Develop* tab and use the developer playgrounds and customization features. The Visual Embed Playground allows you to explore the embedding options available with the SDK, try integrating ThoughtSpot content in a fictional app, and view results instantly.

The *Develop* tab also provides separate playgrounds for Rest API v1 and REST v2 and several customization controls.

For more information, see xref:spotdev-portal.adoc[ThoughtSpot Developer portal].

== Customization controls

UI customization and rebranding::
If you want to customize the look and feel of ThoughtSpot UI to match your organization's branding guidelines, you can use the style customization settings in the *Develop* tab.
+
For more information, see xref:customize-style.adoc[Customize styles and layout].

Custom actions::
If you want to add a custom action to an embedded visualization or saved answer, use the *Custom actions* menu.
+
For more information, see xref:custom-actions.adoc[Custom actions].

Custom link format::

To customize the host URL and resource path in the system-generated links, use the *Link settings* menu. For example, when your application user shares an embedded Liveboard with another user or group, ThoughtSpot can generate a link with your host application URL and resource path specified in *Link settings*.

For more information, see xref:customize-links.adoc[Customize links].

== Security settings

If you are embedding ThoughtSpot in your application, you must add the domain URL of your application as a xref:security-settings.adoc[CSP and CORS host]. These settings are available on the *Security settings*  page. This page also allows you to enable xref:trusted-authentication.adoc[trusted authentication] and xref:configure-saml.adoc[add redirect domains for SAML SSO authentication].