= Set locale and display language
:toc: true
:toclevels: 1

:page-title: Set locale
:page-pageid: set-locale
:page-description: You can change the locale settings of your embedded app to display the UI elements in your preferred language

The display language of the embedded ThoughtSpot UI is determined by the user's system locale.
If your browser locale matches one of the locale options supported by ThoughtSpot, the ThoughtSpot UI automatically changes to that locale. If your browser locale is not supported by ThoughtSpot, the embedded UI is displayed in US English by default.  For example, if your browser locale is an unsupported Central American locale, such as Spanish (Mexico) (es-MX), ThoughtSpot launches in en-US. If your browser doesn't allow you to change the locale, ThoughtSpot launches in the OS locale.

Note that if your organization manages your browser settings, and your administrator or developer has already set your browser locale, ThoughtSpot automatically defaults to that locale. In the full application embed mode, users can override locale by updating their language preference in profile settings.

== Locale settings for embedded ThoughtSpot app

If you have embedded the full ThoughtSpot app, your application users can set the locale on their profile settings page. The profile settings page will be visible to your users only when the `disableProfileAndHelp` attribute is set to `false` and `showPrimaryNavbar` set to `true` in the SDK. 

To set the locale on the profile settings page:

. In the embedded app, click the user icon in the navigation bar.
. Click *View my profile*.
. Next to *Preferences*, click *Edit*.
. Select the drop-down menu icon to set the locale to your preferred language. 
. Refresh your browser page.

You can also use the `/tspublic/v1/user/updatepreference` REST API endpoint to change a user's locale preference. For more information, see xref:user-api.adoc#updatepreference-api[User API].

=== Locale configuration in the SDK

If you want to set your embedded app view to a specific locale for your application users, you can configure the `locale` attribute in the SDK. 

ThoughtSpot supports the following locale identifiers in the `locale` string:

[width="60%", cols="1,2"]
[options="header"]
|====================
| Locale | Language
| `da-DK` | Dansk
| `de-DE` | Deutsch
| `en-AU` | English (Australia)
| `en-CA` | English (Canada)
| `en-IN` | English (India)
| `en-GB` | English (United Kingdom)
| `en-US` | English (United States)
| `es-US` | Español (Latinoamérica)
| `es-ES` | Español (España)
| `fr-CA` | Français (Canada)
| `fr-FR` | Français (France)
| `it-IT` | Italiano
| `nl-NL` | Nederland
| `nb-NO` | Norsk
| `pt-BR` | Português (Brasil)
| `pt-PT` | Português (Portugal)
| `fi-FI` | Suomi
| `sv-SE` | Svenska
| `zh-CN` | 中文(简体)
| `zh-HANT`| 中文 (繁體)
| `ja-JP` | 日本語
|====================

This example sets the locale of the embedded ThoughtSpot app to Español. 

[source,Javascript]
----
const appEmbed = new AppEmbed(document.getElementById('ts-embed'), {
    frameParams: {
        width: '100%',
        height: '100%',
    },
    locale: 'es-ES',
});
----


The following example sets the display language of Liveboard and visualization pages to Deutsch. 

[source,Javascript]
----
const liveboardEmbed = new LiveboardEmbed(document.getElementById('ts-embed'), {
    frameParams: {
        width: '100%',
        height: '100%',
    },
    liveboardId: '<%=liveboardGUID%>',
    vizId: '<%=vizGUID%>',
    locale: 'de-DE',
});
----

== Limitations

* ThoughtSpot _does not_ translate column names, object titles, description text, formulas, or metadata entered by the user. For example, if you name a visualization **Sales performance** in any variant of English and subsequently change the locale to Español, the name of the visualization remains **Sales performance**. +
* If you specify a currency when uploading data, that currency format does not change when the locale changes. +
* ThoughtSpot translates keywords, operators, and error messages. See  link:https://docs.thoughtspot.com/cloud/latest/keywords[Keyword reference] for all supported languages. +

