= Metadata API
:toc: true

:page-title: Get metadata
:page-pageid: metadata-api
:page-description: Metadata API

The metadata API service allows you to fetch metadata details for various objects in the ThoughtSpot system.

For example, you may want to see the visualization headers of a particular visualization or a pinboard.

---
== Get visualization headers

Use this API to get a list of visualization headers from the ThoughtSpot system.
The output includes a list of objects, each with information about the visualizations in a given pinboard or a search answer.

=== Resource URL
----
GET /tspublic/v1/metadata/listvizheaders
----
=== Request parameters
[width="100%" cols="1,2,3"]
[options='header']
|====
|Query Parameter|Data Type|Description
|`id`|string|ID of a particular answer or a pinboard.
|====
=== Example request

.cURL
[source, cURL]
----
curl -X GET --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/metadata/listvizheaders?id=97begg839e-71b6-42ad-a980-20c38b4d6db5'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/metadata/listvizheaders?id=97be839e-71b6-42ggad-a980-20c38b4d6db5
----

=== Example response

[source,JSON]
----
[
  {
    "id": "dd7f5467-99c3-4278-998b-6dd0c4346cd4",
    "name": "Headline Viz answer book guid max timestamp answer book guid != {null} sort by max timestamp descending today last 180 days",
    "author": "67e15c06-d153-4924-a4cd-ff615393b60f",
    "created": 1536179170172,
    "modified": 1536179170172,
    "modifiedBy": "67e15c06-d153-4924-a4cd-ff615393b60f",
    "owner": "ec718bc5-4608-4ea9-93e2-c1f82e9f2b31"
  },
  {
    "id": "fcb65fdb-3965-4f56-8bda-e5e3c2a127a7",
    "name": "Filter Viz answer book guid max timestamp answer book guid != {null} sort by max timestamp descending today last 180 days Row: 1",
    "author": "67e15c06-d153-4924-a4cd-ff615393b60f",
    "created": 1536179170172,
    "modified": 1536179170172,
    "modifiedBy": "67e15c06-d153-4924-a4cd-ff615393b60f",
    "owner": "ec718bc5-4608-4ea9-93e2-c1f82e9f2b31"
  },
  {
    "id": "0f6e7220-5088-4a0e-8122-50b637c356fc",
    "name": "Table Viz answer book guid max timestamp answer book guid != {null} sort by max timestamp descending today last 180 days",
    "author": "67e15c06-d153-4924-a4cd-ff615393b60f",
    "created": 1536179170172,
    "modified": 1536179170172,
    "modifiedBy": "67e15c06-d153-4924-a4cd-ff615393b60f",
    "owner": "ec718bc5-4608-4ea9-93e2-c1f82e9f2b31"
  }
]
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**|Successful retrieval of the visualization headers list
|**400**|Invalid pinboard GUID
|===

---
== Get object headers

Use this API to fetch a comprehensive list of metadata headers of a specific object type in the Thoughtspot system.

=== Resource URL
----
GET /tspublic/v1/metadata/listobjectheaders
----
=== Request parameters
[width="100%" cols="1,1,4"]
[options='header']
|====
|Query Parameter|Data Type|Description
|`type`|string a|Specifies the metadata object type.
 Valid values are:

* `QUESTION_ANSWER_BOOK`
* `PINBOARD_ANSWER_BOOK`
* `QUESTION_ANSWER_SHEET`
* `PINBOARD_ANSWER_SHEET`
* `LOGICAL_COLUMN`
* `LOGICAL_TABLE`
* `LOGICAL_RELATIONSHIP`
* `TAG`
* `DATA_SOURCE`
|`subtypes`|string a|Specifies the sub-types of a metadata object. Valid values are:

* `ONE_TO_ONE_LOGICAL`
* `WORKSHEET`
* `PRIVATE_WORKSHEET`
* `USER_DEFINED`
* `AGGR_WORKSHEET`

Note: This parameter only applies to the `LOGICAL_TABLE`.
|`category`|string a|Specifies the metadata object category. Valid values are:

* `ALL`
* `MY`
* `FAVORITE`
* `REQUESTED`
|`sort`|string a|Sort order of returned headers. Valid values are:

* `DEFAULT`
* `NAME`
* `DISPLAY_NAME`
* `AUTHOR`
* `CREATED`
* `MODIFIED`
|`sortascending`| boolean a|A flag to specify the sort order. A null value defines the default order.

* To set an ascending order, specify `true`.
* To set a descending order, specify `false`.
|`offset`|integer|The batch offset to fetch the page headers. The system default is  `-1`, which  implies first page.
|`batchsize`|integer|The batch size of the object. A value of `-1` implies no pagination.
|`tagname`|string|A JSON array containing a set of tag names to filter headers by.
|`pattern`|string|A pattern to match object name. Use `%`for wildcard match.
|`skipids`|string|IDs of metadata objects to exclude.
|`fetchids`|string|IDs of metadata objects to fetch.
|`auto_created`| boolean|A flag that indicates whether to list only the auto-created objects. A value of null returns all objects.
|====
=== Example request

.CURL
[source,cURL]
----
curl -X GET --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/metadata/listobjectheaders?type=PINBOARD_ANSWER_BOOK&subtypes=WORKSHEET&category=ALL&sort=CREATED&offset=-1'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/metadata/listobjectheaders?type=PINBOARD_ANSWER_BOOK&subtypes=WORKSHEET&category=ALL&sort=CREATED&offset=-1
----

=== Example response

[source, JSON]
----
[
  {
    "id": "7752fa9e-db22-415e-bf34-e082c4bc41c3",
    "name": "Basic Pinboard 1",
    "description": "This pinboard contains one TPCH based visualization",
    "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "created": 1450823023991,
    "modified": 1504281997165,
    "modifiedBy": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "owner": "7752fa9e-db22-415e-bf34-e082c4bc41c3",
    "isAutoCreated": false,
    "isAutoDelete": false
  },
  {
    "id": "6715f768-8930-4180-9a3d-1efdbfaa8e7f",
    "name": "Headline Pinboard",
    "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "created": 1519940021267,
    "modified": 1519945210514,
    "modifiedBy": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "owner": "6715f768-8930-4180-9a3d-1efdbfaa8e7f",
    "isAutoCreated": false,
    "isAutoDelete": false
  },
  {
    "id": "601be8e5-140e-477c-8812-843795306438",
    "name": "Pinboard Filter - datatypes",
    "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "created": 1519943239150,
    "modified": 1519944533160,
    "modifiedBy": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "owner": "601be8e5-140e-477c-8812-843795306438",
    "isAutoCreated": false,
    "isAutoDelete": false
  }
]
----
=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**|Successful retrieval of metadata headers
|===

---
[#headers-metadata-users]
== Get metadata objects for a user or user group

Use the `/tspublic/v1/metadata/listas` API to get a list of metadata objects available for a user or user group. 

=== Resource URL
----
GET /tspublic/v1/metadata/listas
----
=== Request parameters
[width="100%" cols="1,2,3"]
[options='header']
|====
|Query Parameter|Data Type|Description
|`offset` __Optional__|integer| The batch offset value that indicates the first item to return in a page of headers. The system default is -1, which implies first page.
|`batchsize` __Optional__|integer|The batch size of the objects. A value of `-1` implies no pagination.
|`pattern` __Optional__|string|The pattern to match object names. Use `%` for a wildcard match.
|`principalid` __Optional__|string a|ID of the user or user group. 

* If you specify a userID and set the `type` parameter to `USER`, the API returns metadata objects associated with the user ID. 
* If you specify a user group ID and set the type parameter to `USER_GROUP`, the API returns metadata objects for all the users mapped to the specified user group.
* If the `principalID` parameter is not defined, but the `type` attribute is set to `USER`, the API returns metadata objects for the current logged-in user.
* If the `principalID` parameter is not defined, but the `type` attribute is set to `USER_GROUP`, the API returns metadata objects for all user groups.
* If both `principalID` and `type` parameters are not defined, the API returns headers for all users.

|`minimumaccesslevel`__Optional__|string a| Minimum access level that the specified user or user group has. 
Valid values are:

* `NO_ACCESS`
* `READ_ONLY` 
* `MODIFY`

The default value is `NO_ACCESS`.
|`type` __Optional__|string|Type of principal. The allowed values are `USER` and `USER_GROUP`.
|====
 
=== Example request

.cURL
[source, cURL]
----
curl -X GET --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/metadata/listas?offset=-1&pattern=%25&principalid=13bb9aec-aad0-4075-adb9-bd0569351393&minimumaccesslevel=READ_ONLY&type=USER'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/metadata/listas?offset=-1&pattern=%25&principalid=13bb9aec-aad0-4075-adb9-bd0569351393&minimumaccesslevel=READ_ONLY&type=USER
----

=== Example response

The following example shows the headers for user groups:

[source,JSON]
----
{
  "headers": [
    {
      "id": "eea322db-2b8c-4bb7-922d-a80807a0ba94",
      "indexVersion": 5,
      "generationNum": 1471,
      "name": "Stats and Trends for Search on Answers",
      "description": "This pinboard describes how users are searching for existing answers.",
      "author": "67e15c06-d153-4924-a4cd-ff615393b60f",
      "authorName": "system",
      "authorDisplayName": "System User",
      "created": 1604579772176,
      "modified": 1618858656671,
      "modifiedBy": "67e15c06-d153-4924-a4cd-ff615393b60f",
      "owner": "eea322db-2b8c-4bb7-922d-a80807a0ba94",
      "isDeleted": false,
      "isHidden": false,
      "isAutoCreated": false,
      "isAutoDelete": false,
      "tags": [],
      "isExternal": false,
      "isDeprecated": false
    },
    {
      "id": "9d789a9e-12a7-4b00-91de-e558b590d192",
      "indexVersion": 1217,
      "generationNum": 1217,
      "name": "test table 2",
      "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
      "authorName": "tsadmin",
      "authorDisplayName": "Administrator",
      "created": 1618463063893,
      "modified": 1618463113058,
      "modifiedBy": "59481331-ee53-42be-a548-bd87be6ddd4a",
      "owner": "9d789a9e-12a7-4b00-91de-e558b590d192",
      "isDeleted": false,
      "isHidden": false,
      "isAutoCreated": false,
      "isAutoDelete": false,
      "tags": [],
      "isExternal": false,
      "isDeprecated": false
    }
  ],
  "isLastBatch": true,
  "debugInfo": {}
}
----

The following example shows the headers returned for a user:

[source,JSON]
----
{
  "headers": [
    {
      "id": "b27d4ce9-0220-4238-b0b0-917ee18147df",
      "indexVersion": 1494,
      "generationNum": 1494,
      "name": "Sales Performance",
      "description": "",
      "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
      "authorName": "tsadmin",
      "authorDisplayName": "Administrator",
      "created": 1614677491805,
      "modified": 1619648685627,
      "modifiedBy": "59481331-ee53-42be-a548-bd87be6ddd4a",
      "owner": "b27d4ce9-0220-4238-b0b0-917ee18147df",
      "isDeleted": false,
      "isHidden": false,
      "isAutoCreated": false,
      "isAutoDelete": false,
      "tags": [],
      "isExternal": false,
      "isDeprecated": false
    },
    {
      "id": "8161e7ab-8ada-43ae-9627-f9b76dd85d27",
      "indexVersion": 1490,
      "generationNum": 1490,
      "name": "Copy of Sales Performance",
      "description": "",
      "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
      "authorName": "tsadmin",
      "authorDisplayName": "Administrator",
      "created": 1619644750652,
      "modified": 1619644750652,
      "modifiedBy": "59481331-ee53-42be-a548-bd87be6ddd4a",
      "owner": "8161e7ab-8ada-43ae-9627-f9b76dd85d27",
      "isDeleted": false,
      "isHidden": false,
      "isAutoCreated": false,
      "isAutoDelete": false,
      "tags": [],
      "isExternal": false,
      "isDeprecated": false
    },
    {
      "id": "eea322db-2b8c-4bb7-922d-a80807a0ba94",
      "indexVersion": 5,
      "generationNum": 1471,
      "name": "Stats and Trends for Search on Answers",
      "description": "This pinboard describes how users are searching for existing answers. It provides what users are searching for, where users are successful and where they are not.",
      "author": "67e15c06-d153-4924-a4cd-ff615393b60f",
      "authorName": "system",
      "authorDisplayName": "System User",
      "created": 1604579772176,
      "modified": 1618858656671,
      "modifiedBy": "67e15c06-d153-4924-a4cd-ff615393b60f",
      "owner": "eea322db-2b8c-4bb7-922d-a80807a0ba94",
      "isDeleted": false,
      "isHidden": false,
      "isAutoCreated": false,
      "isAutoDelete": false,
      "tags": [],
      "isExternal": false,
      "isDeprecated": false
    },
 
    {
      "id": "7e4071e5-6223-4ccd-a839-2621e5d8201e",
      "indexVersion": 1230,
      "generationNum": 1470,
      "name": "Sales Breakdown",
      "description": "",
      "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
      "authorName": "tsadmin",
      "authorDisplayName": "Administrator",
      "created": 1618469015915,
      "modified": 1618469413741,
      "modifiedBy": "59481331-ee53-42be-a548-bd87be6ddd4a",
      "owner": "7e4071e5-6223-4ccd-a839-2621e5d8201e",
      "isDeleted": false,
      "isHidden": false,
      "isAutoCreated": false,
      "isAutoDelete": false,
      "tags": [],
      "isExternal": false,
      "isDeprecated": false
    },
   
  ],
  "isLastBatch": true,
  "debugInfo": {}
}
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**|Successful retrieval of the metadata headers
|**401**| Unauthorized request
|**404**|The requested resource could not be found
|===


////
## Error Codes
<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
    <tr> <td><code>10002</code></td>  <td>Bad request. Invalid parameter values i.e., wrong pinboard ID.</td> <td><code>400</code></td></tr>
  </tbody>
</table>
////
