= Organization APIs
:toc:
:toclevels: 1

:page-title: Organization APIs
:page-pageid: orgs-api
:page-description: Use organization APIs to create and manage tenant organizations on your ThoughtSpot instance

The organization API endpoints allow creating and managing multiple tenant-specific containers on a ThoughtSpot instance. Each organization object is independent of and isolated from other organization objects to support data protection and privacy.

== Required permissions

To create and manage an organization on a multi-tenant ThoughtSpot instance, you must have Cluster administrator privileges. By default, the administrator of the primary org (Org 0) is set as a  cluster administrator.

To perform CRUD operations on organization objects, the cluster administrator must switch to the `All org` scope using the `POST /tspublic/v1/session/org/` API endpoint.

== Supported operations

include::{path}/org-api-list.adoc[]

[#createOrg]
== Create an organization object
To create an organization object on a ThoughtSpot instance programmatically, send a `POST` request to the `/tspublic/v1/org/` API endpoint.

=== Resource URL
----
POST /tspublic/v1/org/
----

=== Request parameters

[width="100%" cols="1,4"]
[options='header']
|===
|Form parameter|Description
|`name` |__String__. Name of the organization. The organization name string must be unique.
|`description`|__String__. Description of the organization.
|===

=== Example request

.cURL

[source,cURL]
----
curl -X POST \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
-d 'name=OrgA&description=This%20org%20is%20for%20A' \
'http://172.19.228.189:8088/callosum/v1/tspublic/v1/org/'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/
----

=== Example response

If the organization object is successfully created in ThoughtSpot, the API returns the Org ID with the following JSON response:

[source,JSON]
----
{
  "orgId": 1,
  "orgName": "OrgA",
  "description": "This org is for A",
  "allGroupUserId": "ebff8c6b-3a12-4ec8-86ff-ad1362cfab32",
  "defaultAdminUserGroupId": "0e6a2056-ccd9-48bf-a4e3-815d97185cd8",
  "active": true,
  "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
  "deleted": false,
  "created": 1658904338487,
  "modified": 1658904338487
}
----

=== Response codes
[width="100%" cols="2,4"]
[options='header']
|===
|HTTP status code|Description
|**200**| Successful operation
|**400**| Name string is not unique
|**403**| Unauthorized request
|===

[#editOrg]
== Edit an organization  object
To modify an organization object on a ThoughtSpot instance programmatically, send a `PUT` request to the `/tspublic/v1/org/` API endpoint. This API request allows editing organization object properties, enabling or disabling on organization on a ThoughtSpot instance.

=== Resource URL
----
PUT /tspublic/v1/org/
----

=== Request parameters

[width="100%" cols="1,4"]
[options='header']
|===
|Form parameter|Description
|`id`|__Integer__. The ID of the Organization object that you want to edit.
|`name` |__String__. Name of the organization.
|`description`|__String__. Description text associated with the organization.
|`active`|__Boolean__. Enables or disables the organization object.
|===

=== Example request

.cURL

[source,cURL]
----
curl -X PUT \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
-d 'id=5&name=OrgB&description=This%20is%20Org%20B&active=true' \
'http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/
----

=== Example response

If the organization object is successfully modified, the API returns the updated information in the JSON response:

[source,JSON]
----
{
  "orgId": 1,
  "orgName": "OrgB",
  "description": "This is Org B",
  "allGroupUserId": "ebff8c6b-3a12-4ec8-86ff-ad1362cfab32",
  "defaultAdminUserGroupId": "0e6a2056-ccd9-48bf-a4e3-815d97185cd8",
  "active": true,
  "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
  "deleted": false,
  "created": 1658904338487,
  "modified": 1658904959065
}
----

=== Response codes
[width="100%" cols="2,4"]
[options='header']
|===
|HTTP status code|Description
|**200**| Successful operation
|**400**| Name string is not unique
|**403**| Unauthorized request
|===

[#getOrg]
== Get an organization object
To get the details of a specific org object, send a `GET` request to the `/tspublic/v1/org/` API endpoint. You must specify the org `Id` or `name` in the API request to retrieve the organization  details.

=== Resource URL
----
GET /tspublic/v1/org/
----

=== Request parameters

[width="100%" cols="1,4"]
[options='header']
|===
|Query parameter|Description
|`id`|__Integer__. The ID of the Organization object that you want to edit.
|`name` |__String__. Name of the organization.
|===

=== Example request

.cURL
[source,cURL]
----
curl -X GET \
--header 'Accept: application/json' \
'http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/?id=2'
----

.Request URL
----
http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/?id=2
----

=== Example response

If the GET operation is successful, the API returns org details in the JSON response:

[source,JSON]
----
{
  "orgId": 2,
  "orgName": "test-org1",
  "description": "",
  "allGroupUserId": "02de36d9-8d59-43b5-bcad-aa956638a859",
  "defaultAdminUserGroupId": "2fb4b690-ea81-4c6a-a9ad-ecdd773783f4",
  "active": true,
  "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
  "deleted": false,
  "created": 1658822918525,
  "modified": 1658822918525
}
----

=== Response codes
[width="100%" cols="2,4"]
[options='header']
|===
|HTTP status code|Description
|**200**| Successful operation
|**400**| Invalid parameter
|**403**| Unauthorized request
|===

[#getOrgs]
== Get all organization objects
To get the details of all Org objects on a ThoughtSpot instance, send a `POST` request to the `/tspublic/v1/org/search` API endpoint. If you do not specify the `id` or `name` of the organization object, the API returns details of all organization objects on the ThoughtSpot instance.

=== Resource URL
----
POST /tspublic/v1/org/search
----

=== Request parameters

[width="100%" cols="1,4"]
[options='header']
|===
|Form parameter|Description
|`id`|__Integer__. The ID of the organization object that you want to edit.
|`name` |__String__. Name of the organization.
|`showinactive`|__Boolean__. Allows including or excluding inactive organization objects in the API response.
|===

=== Example request

.cURL
[source,cURL]
----
curl -X POST \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
-d 'showinactive=true' \
'http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/search'
----

.Request URL
----
http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/?id=2
----

=== Example response

If the request is successful, the API returns the org details in the JSON response:

[source,JSON]
----
[
  {
    "orgId": 0,
    "orgName": "Master",
    "description": "Master Org",
    "allGroupUserId": "b25ee394-9d13-49e3-9385-cd97f5b253b4",
    "defaultAdminUserGroupId": "d0326b56-ef23-4c8a-8327-a30e99bcc72b",
    "active": true,
    "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "deleted": false,
    "created": 1658822907382,
    "modified": 1658822907382
  },
  {
    "orgId": 1,
    "orgName": "Org A",
    "description": "This org is for A",
    "allGroupUserId": "7aa17f2d-e15a-4f82-9d91-ea1a5809fcab",
    "defaultAdminUserGroupId": "59c3b1c4-947a-4c56-a41d-ae4684d87437",
    "active": true,
    "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "deleted": false,
    "created": 1658904526488,
    "modified": 1658904526488
  },
  {
    "orgId": 2,
    "orgName": "OrgB",
    "description": "This is Org B",
    "allGroupUserId": "ebff8c6b-3a12-4ec8-86ff-ad1362cfab32",
    "defaultAdminUserGroupId": "0e6a2056-ccd9-48bf-a4e3-815d97185cd8",
    "active": true,
    "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "deleted": false,
    "created": 1658904338487,
    "modified": 1658904959065
  },
  {
    "orgId": 3,
    "orgName": "test-org2",
    "description": "Test org 2",
    "allGroupUserId": "ad6ba0c3-1dcd-49cc-b1af-9aebc1d1b385",
    "defaultAdminUserGroupId": "dcf67a1d-5b3a-4606-b80b-96a3f0c12027",
    "active": true,
    "author": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "deleted": false,
    "created": 1658835691052,
    "modified": 1658835691052
  }
]
----

=== Response codes
[width="100%" cols="2,4"]
[options='header']
|===
|HTTP status code|Description
|**200**| Successful operation
|**400**| Invalid parameter
|**403**| Unauthorized request
|===

[#deleteOrg]
== Delete an organization object
To programmatically delete an organization object, send a `DELETE` request to the `/tspublic/v1/org/` API endpoint. You must specify at least the org `Id` or `name` in the API request to delete the org object.

[NOTE]
----
ThoughtSpot does not allow deleting the primary organization (Org 0).
----

=== Resource URL
----
DELETE /tspublic/v1/org/
----

=== Request parameters

[width="100%" cols="1,4"]
[options='header']
|===
|Form parameter|Description
|`id`|__Integer__. The ID of the organization object that you want to edit.
|`name` |__String__. Name of the organization.
|===

=== Example request

.cURL
[source,cURL]
----
curl -X DELETE \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
-d 'id=5' \
'http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/'
----

.Request URL
----
http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/org/
----

=== Example response

If the DELETE operation is successful, the API returns the 204 response code.

----
Response Code
204
----

=== Response codes
[width="100%" cols="2,4"]
[options='header']
|===
|HTTP status code|Description
|**200**| Successful operation
|**400**| Invalid parameter
|**403**| Unauthorized request
|===