= Org administration and management via REST API
:toc:
:toclevels: 1

:page-title: Org administration and management via REST API
:page-pageid: orgs-api-op
:page-description: You can administer Orgs on your mult-tenant cluster using REST API

To administer and manage Orgs, you can use the link:https://docs.thoughtspot.com/cloud/latest/orgs-overview[UI workflows, window=_blank] or REST API v1 endpoints. This article describes the REST API operations available for Org provisioning and management.

[#_create_and_manage_orgs]
== Org CRUD operations

To create an Org on a multi-tenant ThoughtSpot instance, you need cluster administrator privileges. By default, ThoughtSpot sets the administrator of the `Primary Org` as a cluster administrator. Only cluster administrators are allowed to perform CRUD operations on Org objects.

=== REST API v1 endpoints

For Orgs CRUD operations, use the xref:org-api.adoc[`/tspublic/v1/org/`] endpoints. To access Org API endpoints, you must log in to ThoughtSpot as a cluster administrator:

Note that for all Org operations, you must set the org scope to `ALL` in your API request and pass it as a query parameter in the request URL.

* To create an Org, send a xref:org-api.adoc#createOrg[`POST` request to the `/tspublic/v1/org/` endpoint] with the Org name and description text in the request body.
+
If the API operation is successful, ThoughtSpot creates an Org and assigns a system-generated number as Org ID.
* To view the Orgs configured on a ThoughtSpot instance, use the xref:org-api.adoc#getOrgs[`/tspublic/v1/org/search`] or xref:org-api.adoc#getOrg[`GET /tspublic/v1/org/`] API endpoint.
* To edit the properties of an Org object, use the xref:org-api.adoc#editOrg[`PUT /tspublic/v1/org/`] endpoint.
+
The `PUT` request allows modifying the name and description properties of an Org object and setting its status as active or inactive.
* To delete an Org object, send a `DELETE` request to the xref:org-api.adoc#deleteOrg[`/tspublic/v1/org/` endpoint] with Org ID or name in the request body.

=== REST API v2.0 endpoints

For Orgs CRUD operations, you can also use the following REST API v2.0 Org endpoints:

* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/create-org" target="_blank"><code>/api/rest/2.0/orgs/create</code></a>+++
* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/search-orgs" target="_blank"><code> /api/rest/2.0/orgs/search</code></a>+++
* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/update-org" target="_blank"><code>/api/rest/2.0/orgs/{org_identifier}/update </code></a>+++
* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/tags/delete-tag"  target="_blank"><code> /api/rest/2.0/orgs/{org_identifier}/delete</code></a>+++

== Manage users and groups

On a multi-tenant instance, the cluster and Org administrators can create users and associate these users to Orgs and groups within these Orgs. The cluster administrator can perform CRUD operations on Org objects at the All Orgs level and assign users, whereas the Org administrator can create users and groups within the context of their Org workspace.

[NOTE]
====
The xref:session-api.adoc#orgSwitch[`/tspublic/v1/session/orgs`] REST API v1 endpoint allows administrators to switch between Org contexts. For REST API v2 operations, the Org context is determined based on the authentication token used by the user in their API requests. Users must log in to the appropriate Org context from which they want to send API requests.
====

[width="100%" cols="5,8,7"]
[options='header']
|=====
|Operation type|REST API v1 endpoints|REST API v2 endpoints

|Authentication a|
**Basic authentication** +
To log in to a specific Org context with basic authentication, specify the Org ID in the xref:session-api.adoc#session-login[`/tspublic/v1/session/login`] API request.

**Token-based authentication** +
For xref:trusted-authentication.adoc[trusted authentication], use the xref:session-api.adoc#session-authToken[`/tspublic/v1/session/auth/token`] API endpoint. If a user is mapped to a specific org, you can pass the `orgid` in the API request to obtain an authentication token to log in the user to the relevant Org context. +
You can also create a user just-in-time and assign Orgs, groups, and privileges in this API call.

For more information, see xref:api-auth-session.adoc[REST API v1 authentication].

a| **Basic authentication** +
To log in to a specific Org context with basic authentication, specify the Org ID in the +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/login" target="_blank"> <code>/api/rest/2.0/auth/session/login </code> </a>+++ API request.

**Token-based authentication** +
Use the following API endpoints:

* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/get-object-access-token" target="_blank"> <code> /api/rest/2.0/auth/token/object </code> </a>+++
* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/get-full-access-token" target="_blank"><code> /api/rest/2.0/auth/token/full </code></a>+++

These above endpoints also support just-in-time provisioning of users to Orgs and groups. For more information, see xref:authentication.adoc[REST API v2 authentication].

|User provisioning a|To create users, use the xref:user-api.adoc#create-user[`POST /tspublic/v1/user/`] API endpoint. This endpoint also allows assigning a user to Orgs. +

To add multiple users to an Org in bulk, use the xref:user-api.adoc#addOrg[`/tspublic/v1/user/addtoorg`] API endpoint. +

To remove a user from an Org, use the xref:user-api.adoc#delete-user[`DELETE /tspublic/v1/user/{userid}`] endpoint. If a user belongs only to the Org specified in the `DELETE` request, the user will be deleted from the Org and ThoughtSpot system. If the user belongs to more than one Org, the `DELETE` operation removes the user from only the Org specified in the API request. To remove the user from the ThoughtSpot system and all Orgs, you must set the `orgid` to `-1` in your API request.
|To create users and assign users to one or several Orgs, use the +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/create-user" target="_blank"> <code> /api/rest/2.0/users/create </code> </a>+++ API endpoint. +

To assign an existing user to new Orgs or remove a user from an Org, use the +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/update-user" target="_blank"> <code>/api/rest/2.0/users/{user_identifier}/update </code> </a>+++ API endpoint.

|Group provisioning a|To create a group in an Org, log in to the Org context or xref:session-api.adoc#orgSwitch[switch to the Org context] and send an API request to the xref:group-api.adoc#create-group[`/tspublic/v1/group/`] endpoint.
a|To create a group in an Org, use the +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/groups/create-user-group" target="_blank"> <code>/api/rest/2.0/groups/create </code></a>+++ API endpoint.

|Fetching Orgs a| * To get a list of Orgs for the currently logged-in user, use the xref:session-api.adoc#getOrgs[/tspublic/v1/session/orgs] API endpoint. +

* To get Orgs for a specific user, use the xref:session-api.adoc#getOrgsForUser[/tspublic/v1/session/orgs/users/{userid}] endpoint. Set the Org scope to `ALL` to get all Orgs for a given user.
a| The REST API v2 endpoints allow you to perform query operations to get Org details:

* To get a list of all Orgs on the cluster, use +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/search-orgs" target="_blank"><code>/api/rest/2.0/orgs/search </code></a>+++  (Requires cluster administrator privileges)

* To get Org details for a user, use +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/search-users  target="_blank"><code>/api/rest/2.0/users/search</code></a>+++
* To get Org details for a group, use +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/search-users  target="_blank"><code>/api/rest/2.0/groups/search</code></a>+++
|=====

