= Add a custom action for in-app navigation
:toc: true

:page-title: Customize page navigation
:page-pageid: in-app-navigation
:page-description: Customized page navigation

To provide quick access to a related report or saved answer within the context of an embedded pinboard or visualization, you might want to add a custom action that navigates your users to a specific page in your app.  
The Visual Embed SDK simplifies this process by allowing you to define a URL path in the `navigateToPage` function and assign it to an action or button event in the UI.  

To add a custom action for in-app navigation, follow these steps:

. xref:custom-actions-callback.adoc[Add a custom action].
. Register the callback in the Visual Embed SDK
. Define the page path 
 
In this example, the **view-report ** action on a pinboard page calls the `navigateTo` method to open a specific saved answer page when a user clicks the **View report** button in the embedded app. 

[source,javascript]
----
pinboardEmbed.on(EmbedEvent.CustomAction, async (payload: any) => {
    if (payload.payload.id === 'view-report') {
        pinboardEmbed.navigateToPage(
            'saved-answer/3da14030-11e4-42b2-8e56-5ee042a8de9e'
        );
    }
})
----
