= Restrict access to a Liveboard
:toc: true
:toclevels: 2

:page-title: User access to embedded objects
:page-pageid: Liveboard-access
:page-description: You can define user access to view or edit embedded Liveboards and related workflows.

If you have Classic Answer Experience enabled on your ThoughtSpot instance, you can use the *Cannot create or update Liveboards* privilege to restrict user access to a Liveboard. This privilege allows `Read-only` access and restricts users from performing the following actions:

* Sharing a Liveboard with another user
* Pinning a visualization to a Liveboard
* Downloading a Liveboard
* Editing a Liveboard
* Copying a Liveboard
* Copying the Liveboard link

=== Before you begin

* make sure you have admin privilege.
* make sure the *Cannot create or update Liveboards* checkbox is visible on the Group configuration page. If it is not available, contact ThoughtSpot Support.

To limit user access to Liveboards, follow these steps:

* Log in to ThoughtSpot. 
* Go to *Admin* > *Groups*.
* Click *Add Group* to create a read-only user group.
* Select the *Cannot create or update Liveboards* privilege.
* Save changes.
* Go to *Admin* > *Users*. 
* Select the users to whom you want to assign this privilege, and then click *Add users to groups*.
* Select the user group for which you enabled the *Cannot create or update Liveboards* privilege.
* Click *Add*.
