
= Pinboard data API
:toc: true

:page-title: Get Pinboard Data
:page-pageid: pinboard-api
:page-description: Pinboard Data API

To retrieve data related to a pinboard or visualization from the ThoughtSpot system, you can use the pinboard data API.

Using this API, you can fetch the following information:

* All the visualization objects on a pinboard.
* A specific or a group of visualizations on a pinboard.

== Request URL
----
POST /tspublic/v1/pinboarddata
----
== Request Parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Query Parameter|Data Type|Description
|`id`|string|The pinboard id in the system.
|`vizid`|string|(Optional) The visualization id(s) on a pinboard. Use this parameter to fetch a specific visualization on a pinboard. The syntax is:
         `4fdf9d2c-6f34-4e3b-9fa6-bd0ca69676e1`, "\...\...
|`batchsize`|integer|The batch size for loading pinboard objects. The system default is -1.
|`pagenumber`|integer|The system default is -1.
|`offset`|integer|The system default is -1. Alternately, set the offset using the following code:
         `1-based indexingOffset = (pageNumber - 1)` * batchSize
|`formattype`|string|Valid values are `COMPACT` or `FULL JSON`. The system default is `COMPACT`.
|====


== Example request

.CURL
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/pinboarddata?id=f4533461-caa5-4efa-a189-13815ab86770&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/pinboarddata?id=f4533461-caa5-4efa-a189-13815ab86770&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT
----

== Example response

----
{
  "4fdf9d2c-6f34-4e3b-9fa6-bd0ca69676e1": {
    "name": "Sample Name",
    "columnNames": [
      "Opportunity Stage",
      "Opportunity Owner Name",
      "Total Amount"
    ],
    "data": [
      [
        "s3 alignment with eb",
        "jeff cameron",
        1102272
      ],
      [
        "s4 validation",
        "brian mcquillan",
        59150
      ]
    ],
    "samplingRatio": 1,
    "totalRowCount": 14,
    "rowCount": 14,
    "pageSize": 10,
    "offset": 0
  }
}
----
=== Response codes

[options="header", cols="1,2"]
|===
|HTTP Code|Description
|**200**|Successful retrieval of pinboard or visualization data
|**400**|Invalid pinboard ID
|===
////
## Error Codes

<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
    <tr> <td><code>10002</code></td>  <td>Bad request. Invalid parameter values.</td> <td><code>400</code></td></tr>
    <tr> <td><code>10000</code></td>  <td>Internal server error. Malformed JSON Exception.</td><td><code>500</code></td></tr>
  </tbody>
</table>
////
