= Prefetch static resources
:toc: true

:page-title: Prefetch static resources
:page-pageid: prefetch
:page-description: Prefetch static resources before loading an application.

By default, the SDK fetches application resources when the embedded content loads. For optimal performance and faster loading of embedded objects, we recommend prefetching static resources and serving static assets from the local cache of user's browser.

The `prefetch` method in the SDK allows your web browsers to prefetch static resources from a given URL before the embedded objects load. You can define the prefetch URL and specify the embed feature components for which they want to prefetch resources and call the prefetch function in the `init` method by setting `callPrefetch` attribute to `true`. You must call the prefetch function before the user login and cache static assets early on. The prefetched resources can then be served from the user's local disk to load your application content fast.

[source,javascript]
----
import {
    SearchEmbed,
    AuthType,
    init,
    prefetch,
    PrefetchFeatures
}
from '@thoughtspot/visual-embed-sdk';
init
    ({
        thoughtSpotHost: "https://<hostname>:<port>",
        authType: AuthType.None,
        callPrefetch: true,
    });
----
