= Prefetch static resources
:toc: true

:page-title: Prefetch static resources
:page-pageid: prefetch
:page-description: Prefetch static resources before loading an application.

By default, the SDK fetches application resources when the embedded content loads. For optimal performance and faster loading of embedded objects, we recommend prefetching static resources and serving static assets from the local cache of the user's browser.

To prefetch static resources, use one of these options:

* Use the `prefetch` method (Recommended)
+
The `prefetch` method in the SDK allows your web browsers to prefetch static resources from a given URL before initiating authentication and loading an embedded object. You can define the prefetch URL and specify the embed feature components for which you want to prefetch resources in the `prefetch` method. To improve application response time, call the `prefetch` method before calling the `init` method and initiating authentication.
+

[source,javascript]
----
import {
   LiveboardEmbed,
   AuthType,
   init,
   prefetch,
   PrefetchFeatures
}
from '@thoughtspot/visual-embed-sdk';
prefetch
   ({
      url: "https://<hostname>:<port>",
      prefetchFeatures: [PrefetchFeatures.LiveboardEmbed,PrefetchFeatures.VizEmbed]
   });
init
   ({
      thoughtSpotHost: "https://<hostname>:<port>",
      authType: AuthType.None,
   });
----

* Call prefetch in `init`
+
You can call prefetch in the `init` method by setting `callPrefetch` attribute to `true`.

+
[source,javascript]
----
import {
   LiveboardEmbed,
   AuthType,
   init,
   prefetch,
}
from '@thoughtspot/visual-embed-sdk';
init
   ({
      thoughtSpotHost: "https://<hostname>:<port>",
      authType: AuthType.None,
      callPrefetch: true
   });
----