= REST API v1 Reference 
:toc: true

:page-title: REST API Reference Guide
:page-pageid: rest-api-reference
:page-description: REST API Reference


[div tableContainer]
--
[width="100%" cols="2,1"]
[options='header']
|=====
|API endpoint| Available from
|`xref:metadata-api.adoc#assign-tag[*POST* /tspublic/v1/metadata/assigntag]` +
Assigns tags to a metadata object, such as a Liveboard, search answer, table, worksheet, or view.|ThoughtSpot Cloud [version noBackground]#ts7.jun.cl# +
ThoughtSpot Software [version noBackground]#7.1.1#
|`xref:metadata-api.adoc#unassign-tags[*POST* /tspublic/v1/metadata/unassigntag]` +
Removes tag associations to metadata objects.|ThoughtSpot Cloud [version noBackground]#ts7.sep.cl# +
ThoughtSpot Software [version noBackground]#7.2.1#
|`xref:metadata-api.adoc#metadata-details[**GET** /tspublic/v1/metadata/details]` +
Gets metadata details for a specific data object such as a Liveboard, answer, or a worksheet.|ThoughtSpot Cloud [version noBackground]#ts7.jun.cl# +
ThoughtSpot Software [version noBackground]#7.1.1#
|`xref:metadata-api.adoc#metadata-list[**GET** /tspublic/v1/metadata/list]` +
Gets a list of all metadata objects from the ThoughtSpot resource repository.|ThoughtSpot Cloud [version noBackground]#ts7.sep.cl# +
ThoughtSpot Software [version noBackground]#7.2.1#
|`xref:metadata-api.adoc#headers-metadata-users[**GET** /tspublic/v1/metadata/listas]` +
Gets a list of metadata objects that are available to a user or user group.|ThoughtSpot Cloud [version noBackground]#ts7.may.cl# +
ThoughtSpot Software [version noBackground]#7.1.1#
|`xref:metadata-api.adoc#object-header[**GET** /tspublic/v1/metadata/listobjectheaders]` +
Lists metadata object headers in the repository.|ThoughtSpot Cloud [version noBackground]#ts7.may.cl# +
ThoughtSpot Software [version noBackground]#6.0.x#
|`xref:metadata-api.adoc#viz-header[**GET** /tspublic/v1/metadata/listvizheaders]` +
Gets visualization headers from the ThoughtSpot system.|ThoughtSpot Cloud [version noBackground]#ts7.may.cl# +
ThoughtSpot Software [version noBackground]#6.0.x#
|`xref:metadata-api.adoc#set-favorite[**POST** /tspublic/v1/metadata/markunmarkfavoritefor]` +
Adds objects to favorites for a given user account.|ThoughtSpot Cloud [version noBackground]#ts7.jun.cl# +
ThoughtSpot Software [version noBackground]#7.1.1#
|`xref:metadata-api.adoc#del-object-fav[**DELETE** /tspublic/v1/metadata/markunmarkfavoritefor]` +
Removes the objects from a user's favorites list.|ThoughtSpot Cloud [version noBackground]#ts7.jun.cl# +
ThoughtSpot Software [version noBackground]#7.1.1#
|=====
--


[div announcementBlock]
--
Starting from the ThoughtSpot Cloud ts8.nov.cl and ThoughtSpot Software 8.4.0-sw (Limited Availability) releases, pinboards are rebranded as Liveboards in ThoughtSpot UI, documentation, and learning materials.
However, for backward compatibility, the REST API v1 endpoints URLs and request and response workflows will continue to use the `pinboard` terminology.
--


== User management

include::{path}/user-api-list.adoc[]

== Groups and privileges

include::{path}/group-api-list.adoc[]

== Session management

include::{path}/session-api-list.adoc[]

== Metadata management

include::{path}/metadata-api-list.adoc[]

== Configuration management

include::{path}/admin-api-list.adoc[]

== Data connections 

include::{path}/data-connection-apis.adoc[]

== TML objects

include::{path}/tml-api-list.adoc[]

== Liveboard data

include::{path}/pinboard-api-list.adoc[]

== Search data

`xref:search-data-api.adoc#search-data-api-ref[**POST** /tspublic/v1/searchdata]`

+++<p class="divider">Allows searching for data from a specific data source in the ThoughtSpot application.</p>+++

== Dependent objects

include::{path}/dependency-api-list.adoc[]

== Security

include::{path}/security-api-list.adoc[]

== Log Streaming Service

`xref:logs-api.adoc[**GET** /tspublic/v1/logs/topics/{topic}]`

+++<p class="divider">Gets security audit logs from the ThoughtSpot system.</p>+++

--