= REST API v2.0 Reference
:toc: true


:page-title: REST API Reference Guide
:page-pageid: rest-apiv2-reference
:page-description: REST API Reference

This API Reference page lists the REST API v2.0 endpoints and provides basic information about the resource URLs and supported operations. If you want to try out these APIs, view detailed documentation, and download code samples, visit the +++<a href="{{previewPrefix}}/api/rest/playgroundV2" target="_blank">REST API v2.0 Playground</a>+++.

[NOTE]
====
Access to ThoughtSpot data is controlled based on xref:api-user-management.adoc#group-privileges[user privileges] and xref:configure-user-access.adoc#_object_level_permissions[object-level permissions]. Some operations are available to all users and may require at least view access to the metadata object. ThoughtSpot users are assigned access privileges based on the group to which they belong. Additionally, object owners can control access to a metadata object using `MODIFY` (*Can edit*), `READ_ONLY` (*Can view*), or `NO_ACCESS` permission when sharing an object with other users and groups.
====

== Authentication

[div divider]
--
+++<h4> Get current user information</h4>+++

`GET /api/rest/2.0/auth/session/user` +

Gets session information for the currently logged-in user.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Login</h4>+++

`POST /api/rest/2.0/auth/session/login` +

Creates a login session for a ThoughtSpot user.

If the login is successful, a user session is established.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Get authentication token</h4>+++

* `POST /api/rest/2.0/auth/token/object`
+
Gets an authentication token from ThoughtSpot, which allows access to a specific metadata object in ThoughtSpot. The token obtained from this API call provides only view access to the object specified in the API request.
+
** To obtain a bearer token, specify the username, password, and object ID in the API request.
** To obtain a token on behalf of a user, specify the username, secret key, and object ID.
+
__Requires administrator privileges__.


* `POST /api/rest/2.0/auth/token/full`
+
Gets an authentication token from ThoughtSpot, which provides access to full application.
+
** To obtain a bearer token, specify the username and password in the API request.
** To obtain a token on behalf of a user, specify the username and secret key.
+
__Requires administrator privileges__.

[NOTE]
====
You can copy the `secret key` from *Develop* > *Customizations* > *Security Settings* page if xref:trusted-authentication.adoc#trusted-auth-enable[Trusted authentication] is enabled on your instance.
====

+++ <h5>Just-in-time user provisioning</h5> +++

The `/api/rest/2.0/auth/token/object` and `/api/rest/2.0/auth/token/full` API endpoints also let you provision a user just-in-time (JIT) and assign the new user to Orgs and groups. If a user is not available in ThoughtSpot, administrators can create a user profile by setting `auto_create` to `true`, and provision the user to an Org and groups in an Org.

For more information, see xref:authentication.adoc[REST API v2.0 authentication].

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Logout</h4>+++

`POST /api/rest/2.0/auth/session/logout` +

Logs out the currently logged-in user.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Revoke token</h4>+++

`POST /api/rest/2.0/auth/token/revoke` +

Revokes authentication token granted for a user.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Users

[div divider]
--
+++<h4>Search users</h4>+++

`POST /api/rest/2.0/users/search`

Gets user details. You can get the details of a specific user or all user objects available in the ThoughtSpot system.
You can also filter the API output based on groups, Org ID, visibility, account status, user type, and user preference settings.

__Available to all users. Does not require administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create a user</h4>+++

`POST /api/rest/2.0/users/create`

Creates a user in ThoughtSpot. This API also supports the following operations: +

* add the email address of the user
* add the user to xref:orgs.adoc[Orgs] and groups.
* set account status
* define sharing visibility
* set a default Liveboard for the user
* add Liveboard, Answer, and Worksheet objects to the user's favorites list
* set user preferences to start or stop onboarding walkthrough, and receive an email notification when another user shares an object

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update a user</h4>+++

`POST /api/rest/2.0/users/{user_identifier}/update`

Allows modifying the properties of a user object.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete a user</h4>+++

`POST /api/rest/2.0/users/{user_identifier}/delete`

Deletes a user from ThoughtSpot.

[NOTE]
====
In the current release, deleting a user removes the user from ThoughtSpot. If you want to remove a user from a specific Org, update the group and Org mapping properties of the user object via a `POST` API call to the `/api/rest/2.0/users/{user_identifier}/update` endpoint.
====
__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Import users</h4>+++

`POST /api/rest/2.0/users/import`

Allows importing user data from external databases into ThoughtSpot.

__Requires administrator privileges__.

During this operation:

* If the specified users are not available in ThoughtSpot, the users are created and assigned a default password. The `default_password` definition in the API request is optional.
* If the `delete_unspecified_users` property is set to `true`, users not specified in the API request, excluding `tsadmin`, `guest`, `system` and `su` users, are deleted.
* If the specified user objects are already available in ThoughtSpot, the object properties of these users are modified and synchronized as per the input data in the API request.

A successful API call returns the object that represents the changes made in the ThoughtSpot system.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Change password</h4>+++

`POST /api/rest/2.0/users/change_password`

Allows ThoughtSpot users to change the password of their account. Administrators can also change the password on behalf of a user.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Reset password</h4>+++

`POST /api/rest/2.0/users/reset_password`

Resets a user's password.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Force logout</h4>+++

`POST /api/rest/2.0/users/force_logout`

Forces logout on user sessions.

[WARNING]
* Use this API with caution as it may invalidate active user sessions and force users to re-login.
* Make sure you specify the usernames or GUIDs. If you pass null values in the API call, all user sessions on your cluster become invalid, and the users are forced to re-login.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== System

[div divider]
--
+++<h4>Get system information</h4>+++

`GET /api/rest/2.0/system`

Gets system information of your current logged-in cluster.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Get System Config</h4>+++

`GET /api/rest/2.0/system`

Gets details of the current configuration running on your cluster.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Orgs

You can perform CRUD operations on Org objects if the Orgs feature is enabled on your cluster. For Org operations, cluster administration privileges are required.

[NOTE]
====
In the current release, REST API v2.0 Playground is accessible only in the primary Org (Org 0) context. However, REST clients can call the REST API v2 endpoints via a Web browser, Postman, or other such tools.
====

[div divider]
--
+++<h4>Search Orgs</h4>+++

`POST /api/rest/2.0/orgs/search`

Gets Org objects from ThoughtSpot. To filter the API output based on Org status, visibility, and user association, set `visibility`, `status`, and `user_identifiers` properties in your API request.

__Requires cluster administration privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create an Org</h4>+++

`POST /api/rest/2.0/orgs/create`

Creates an Org object.

__Requires cluster administration privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update an Org</h4>+++

`POST /api/rest/2.0/orgs/{org_identifier}/update`

Modifies the object properties of an Org.

__Requires cluster administration privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete an Org</h4>+++

`POST /api/rest/2.0/orgs/{org_identifier}/delete`

Deletes an Org object from ThoughtSpot.

__Requires cluster administration privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Tags

API endpoints for CRUD operations on tag objects and metadata association.

[div divider]
--
+++<h4>Search tags</h4>+++

`POST /api/rest/2.0/tags/search`

Gets details of tag objects from ThoughtSpot.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create a tag</h4>+++

`POST /api/rest/2.0/tags/create`

Creates a tag object in ThoughtSpot.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update a tag</h4>+++

`POST /api/rest/2.0/tags/{tag_identifier}/update`

Modifies the object properties of a tag.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete a tag</h4>+++

`POST /api/rest/2.0/tags/{tag_identifier}/delete`

Deletes a tag object from ThoughtSpot.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Assign a tag</h4>+++

`POST /api/rest/2.0/tags/assign`

Assigns a tag to metadata objects.

__Requires edit access to the metadata object (Liveboard, saved Answer, or the Worksheet)__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Unassign a tag</h4>+++

`POST /api/rest/2.0/tags/unassign`

Removes the tag assigned to a metadata object.

__Requires edit access to the metadata object (Liveboard, saved Answer, or the Worksheet)__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


== Groups

API endpoints for CRUD operations on groups objects and groups data import from external databases.

[div divider]
--
+++<h4>Search groups</h4>+++

`POST /api/rest/2.0/groups/search`

Gets the details of group objects from ThoughtSpot. You can get the details of a specific group or all groups available in the ThoughtSpot system. You can also filter the API output based on user association, privileges, Org ID, visibility, and group type.

__Available to all users. Does not require administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create a group</h4>+++

`POST /api/rest/2.0/groups/create`

Creates a user in ThoughtSpot. This API also supports the following operations: +

* assign privileges
* add users
* define sharing visibility
* add sub-groups
* set a default Liveboard for the users in a group

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update a group</h4>+++

`POST /api/rest/2.0/groups/{group_identifier}/update`

Allows modifying the object properties of a group. You can also use this API to add or remove users, groups, and privileges.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete a group</h4>+++

`POST /api/rest/2.0/users/{user_identifier}/delete`

Deletes a group from ThoughtSpot.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Import groups</h4>+++

`POST /api/rest/2.0/groups/import`

Allows importing group objects from external databases into ThoughtSpot.

__Requires administrator privileges__.

During this operation:

* If the specified group is not available in ThoughtSpot, it will be added to ThoughtSpot.
* If the `delete_unspecified_groups` property is set to `true`, the groups not specified in the API request, excluding administrator and system user groups, are deleted.
* If the specified groups are already available in ThoughtSpot, the object properties of these groups are modified and synchronized as per the input data in the API request.

A successful API call returns the object that represents the changes made in the ThoughtSpot system.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Metadata

API endpoints for querying metadata objects, importing and exporting TML representation of metadata objects, and deleting metadata objects.

[div divider]
--
+++<h4>Search metadata objects</h4>+++

`POST /api/rest/2.0/metadata/search`

Gets details of metadata objects from ThoughtSpot.

__Requires at least view access to metadata objects. The `USER` and `USER_GROUP` metadata object queries require administrator privileges__.

* To fetch data for a metadata object, specify the object ID and type.
* To fetch data for a specific object type, for example, Liveboard or saved Answer, specify an object type from the `type` list:

** `LIVEBOARD` for Liveboards
** `ANSWER` for saved Answer object
** `CONNECTION` for data connections
** `TAG` for tag objects
** `USER` for user objects
** `USER_GROUP` for groups
** `LOGICAL_TABLE` for worksheets, tables and views.
** `LOGICAL_COLUMN` for a column of any data object such as tables, worksheets, or views.
** `LOGICAL_RELATIONSHIP` for table and worksheet joins

[NOTE]
====
Searching by metadata sub-types such as `CALENDAR_TYPE` and `FORMULA` is not supported in REST API v2.0.
====

The search metadata API allows you to define several parameters to filter the output. For example, you can filter objects created or modified by specific users, or based on the tags assigned to an object. Similarly, you can exclude or include dependent, hidden, and incomplete objects in the output.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Fetch SQL query details for a Liveboard</h4>+++

`POST /api/rest/2.0/metadata/liveboard/sql`

Gets SQL query data for the visualizations on a Liveboard.

__Requires at least view access to Liveboard__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Fetch SQL query details for an Answer</h4>+++

`POST /api/rest/2.0/metadata/answer/sql`

Gets SQL query data for a saved Answer.

__Requires at least view access to the Answer object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Import metadata objects</h4>+++

`POST /api/rest/2.0/metadata/tml/import`

Imports TML representation of the metadata objects into ThoughtSpot.

__Requires data management privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Export metadata objects</h4>+++

`POST /api/rest/2.0/metadata/tml/export`

Exports TML representation of the metadata objects from ThoughtSpot in JSON or YAML format.

__Requires data management privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete metadata objects</h4>+++

`POST /api/rest/2.0/metadata/delete`

Deletes a metadata object from ThoughtSpot.

__Requires edit access to metadata objects__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Reports

API endpoints to download Liveboard or Answer from ThoughtSpot.

[div divider]
--
+++<h4>Download a Liveboard report</h4>+++

`POST /api/rest/2.0/report/liveboard`

Downloads a Liveboard and its visualizations as a PDF, CSV, XLSX, or PNG file.

__Requires data download privileges and at least view access to the Liveboard object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Download an Answer report</h4>+++

`POST /api/rest/2.0/report/answer`

Downloads the Answer data in PDF, CSV, PNG, or XLSX format.

__Requires data download privileges and at least view access to the Answer object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Security

API endpoints that let you share objects and fetch permission details for metadata objects.

[NOTE]
====
By default, the JSON response from the `api/rest/2.0/security/principals/fetch-permissions` and `/api/rest/2.0/security/metadata/fetch-permissions` API calls show `group_permissions` as a null object. To allow ThoughtSpot to return group permission details in the API response, the `groupWisePermissionEnabled` flag must be enabled on your instance. For more information, contact ThoughtSpot Support.
====

[div divider]
--
+++<h4>Fetch object permission details for users or groups</h4>+++

`POST /api/rest/2.0/security/principals/fetch-permissions`

Gets a list of objects that a user or group has access to. You can also specify the metadata type to fetch user permission details for Liveboards, Worksheets, or Answers.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Fetch permission details for metadata objects </h4>+++

`POST /api/rest/2.0/security/metadata/fetch-permissions`

Fetches access permission details for metadata objects. To get object access details for a user or group, specify the user or group identifiers.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Transfer object ownership and assign author</h4>+++

`POST /api/rest/2.0/security/metadata/assign`

Assigns a new author or changes the author of a metadata object.

__Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Share metadata objects</h4>+++

`POST /api/rest/2.0/security/metadata/share`

Allows sharing metadata objects, such as Liveboards, saved Answers, and Worksheets with another user or group in ThoughtSpot.

__Requires administrator privileges and at least view access to the metadata object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Data

API endpoints to search data from a data source, fetch Liveboard and Answer data.

[div divider]
--
+++<h4>Search data</h4>+++

`POST /api/rest/2.0/searchdata`

Allows searching data from a data source by passing query strings in the API request.

__Requires data download privileges and at least view access to the data source object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Fetch Liveboard data</h4>+++

`POST /api/rest/2.0/metadata/liveboard/data`

Gets Liveboard and visualization data from ThoughtSpot.

__Requires data download privileges and at least view access to the Liveboard object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Fetch Answer data</h4>+++

`POST /api/rest/2.0/metadata/answer/data`

Gets Answer data from ThoughtSpot. You can fetch data for saved Answers only.

__Requires data download privileges and at least view access to the Answer object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


== Logs

[div divider]
--
+++<h4>Fetch audit logs</h4>+++

`POST /api/rest/2.0/logs/fetch`

Gets security audit logs from the ThoughtSpot system.

--Requires administrator privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">View in Playground</a>+++
--



////
== Session

--
`**GET** /tspublic/rest/v2/session`

Gets details of the current session for the logged-in user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/session/get-session-info" id="preview-in-playground" target="_blank">View in Playground</a>
++++
+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/session/login`

Signs in a user to ThoughtSpot.

+++<p class="divider"> </p>+++

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/session/login" id="preview-in-playground" target="_blank">View in Playground</a>
++++



`**POST** /tspublic/rest/v2/session/gettoken`

Gets an OAuth access token for a ThoughtSpot client. You must send this token in the `Authorization` header to authorize your API requests.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/session/get-token" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/session/revoketoken`

Revokes an existing access token assigned to a ThoughtSpot client. To make API calls, you must obtain a new access token.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/session/revoke-token" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/session/logout`

Logs out a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/session/logout" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Users
--

`*POST* /tspublic/rest/v2/user/create`

Creates a user object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/user/create-user" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`GET /tspublic/rest/v2/user`

Gets details of a specific user. You must provide the username or the GUID of the user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/user/get-user" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/user/update`

Modifies the properties of a user object. You must specify a username or the GUID of the user. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/user/update-user" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`DELETE /tspublic/rest/v2/user/delete`

Deletes a user object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/user/delete-user" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/user/addgroup`

Assigns a user to groups. If the assigned groups have privileges configured, the user inherits these privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/user/add-user-to-groups" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/user/removegroup`

Removes the groups assigned to a user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/user/remove-user-from-groups" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/user/changepassword`

Allows changing a ThoughtSpot user's password.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/user/change-password-of-user" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/user/search`

Gets a list of users available in the ThoughtSpot system. To filter your query, you can specify the user type, group, privileges, sharing visibility, and other such attributes.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/user/search-users" id="preview-in-playground" target="_blank">View in Playground</a>
++++

--

== Groups

--
`*GET* /tspublic/rest/v2/group`

Gets details of a specific group.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/get-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/group/create`

Creates a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/create-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/group/update`

Modifies the properties of a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/update-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/tspublic/rest/v2/group/addprivilege`

Assigns privileges to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/add-privileges-to-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/tspublic/rest/v2/group/removeprivilege`

Removes privileges assigned to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/remove-privileges-from-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**DELETE** /tspublic/rest/v2/group/delete`

Deletes a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/delete-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/group/adduser`

Assigns users to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/add-users-to-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/tspublic/rest/v2/group/removeuser`

Removes one or several users assigned to a group. Requires administrator privileges.


++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/remove-users-from-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/group/addgroup`

Adds a group to another group object. This API request creates a hierarchy of groups. The subgroups inherit the privileges assigned to the parent group.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/add-groups-to-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/group/removegroup`

Removes a group from the parent group.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/remove-groups-from-group" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/group/search`

Gets a list of groups created in the ThoughtSpot system. To filter your query, you can specify the group type, group name, privileges, sharing visibility, users, and other such attributes.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/group/search-groups" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Admin

--
`**GET ** /tspublic/rest/v2/admin/configuration`

Gets details of the current configuration of a ThoughtSpot cluster.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/admin/get-cluster-config" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/admin/configuration/overrides`

Gets details of configuration overrides.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2??apiResourceId=/http/api-endpoints/admin/get-cluster-config-overrides" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/tspublic/rest/v2/admin/configuration/update`

Updates configuration settings of the ThoughtSpot cluster.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/admin/update-cluster-config" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/admin/resetpassword`

Resets the password of a user account.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/admin/reset-user-password" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/admin/syncprincipal`

Synchronizes user account and group properties from an external database with ThoughtSpot.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/admin/sync-principal" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/admin/changeauthor`

Transfers the ownership of objects from one user to another.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/admin/change-author-of-objects" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/admin/assignauthor`

Assigns ownership to one or several objects to a specific user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/admin/assign-author-to-objects" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/admin/forcelogout` +

Logs out specified users from ThoughtSpot.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/admin/force-logout-users" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--



== Metadata

--
`*GET* /tspublic/rest/v2/metadata/tag`

Gets details for the specified tag. You must specify the tag name or the GUID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/get-tag" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/tag/create`

Creates a tag object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/create-tag" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/metadata/tag/update`

Modifies the properties of a tag object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/update-tag" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/metadata/tag/assign`

Assigns a tag to one or several metadata objects. You can assign a tag to a Liveboard, answer, data object, and data connection objects.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/assign-tag" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/metadata/tag/unassign`

Removes the tag assigned to an object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/unassign-tag" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*DELETE* /tspublic/rest/v2/metadata/tag/delete`

Deletes the specified tag.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/delete-tag" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/metadata/favorite/assign`

Adds an object such as Liveboards and answers to a user's favorites list.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/assign-favorite" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT ** /tspublic/rest/v2/metadata/favorite/unassign`

Removes the specified object from the user's favorites list.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/unassign-favorite" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**GET** /tspublic/rest/v2/metadata/homeliveboard`

Gets the details of the Liveboard that is set as a default Liveboard for the ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/get-home-liveboard" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/metadata/homeliveboard/assign`

Assigns a Liveboard as a default Liveboard for a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/assign-home-liveboard" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/metadata/homeliveboard/unassign`

Removes the default home Liveboard setting for a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/unassign-home-liveboard" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/metadata/incomplete`

Gets a list of objects with incomplete metadata.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/get-incomplete-objects" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/metadata/header`

Gets header details for a specific metadata object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/get-object-header" id="preview-in-playground" target="_blank">View in Playground</a>
++++


+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/metadata/details`

Gets details of a specific metadata object. To filter your query, specify the metadata object type and the ID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/get-object-detail" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/metadata/vizheaders`

Gets a list of visualization headers associated with a Liveboard.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/get-object-visualization-header" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/header/search`

Gets a list of all metadata objects in the ThoughtSpot system. To filter your query, specify the metadata object type, access level, and other such attributes.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/search-object-header" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/detail/search`

Gets details of one or several metadata objects of a specific type.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/search-object-detail" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*DELETE* /tspublic/rest/v2/metadata/delete`

Deletes the specified metadata object. You can delete answers, Liveboards, tags, worksheets, views, tables, columns, and table joins. +
Note that the endpoint does not support deleting the connection, user, and group objects. To delete these objects, use the following endpoints:

* `DELETE /tspublic/rest/v2/connection/delete`
* `DELETE /tspublic/rest/v2/user/delete`
* `DELETE /tspublic/rest/v2/group/delete`

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/delete-object" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/dependency`

Gets a list of dependent metadata objects.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/get-object-dependency" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/tml/export`

Exports a TML object and associated metadata.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/export-object-tml" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/metadata/tml/import`

Imports one or several TML objects and object associations.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/metadata/import-object-tml" id="preview-in-playground" target="_blank">View in Playground</a>
++++

--

== Connections

--
`*GET* /tspublic/rest/v2/connection`

Gets details of a specific data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/get-connection" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**GET** /tspublic/rest/v2/connection/database`

Gets details of the databases associated with a connection ID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/get-connection-database" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/connection/table`

Gets details of the tables associated with a connection ID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/get-connection-tables" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/connection/tablecoloumn`

Gets details of the columns of the tables associated with a connection ID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/get-connection-table-columns" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/connection/create`

Creates a data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/create-connection" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/connection/update`

Updates an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/update-connection" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

*DELETE* /tspublic/rest/v2/connection/delete

Deletes a data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/delete-connection" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/connection/addtable`

Adds a table to an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/add-table-to-connection" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/connection/removetable`

Removes a table from an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/remove-table-from-connection" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/connection/search`

Gets details of all data connections. You can also query data for a specific connection type.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/connection/search-connection" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Data

--
`**POST** /tspublic/rest/v2/data/search`

Allows constructing a search query string and retrieves data from a search query.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/data/search-query-data" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/data/answer`

Gets data from a saved search answer.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/data/answer-data" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/data/liveboard`

Gets data from the specified Liveboard and visualization.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/data/liveboard-data" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/data/answer/querysql`

Retrieves SQL for an answer object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/data/answer-query-sql" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/data/liveboard/querysql`

Retrieves SQL for a visualization on a Liveboard.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/data/liveboard-query-sql" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Custom actions

`*GET* /tspublic/rest/v2/customaction`

Gets details of a custom action.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/custom-actions/get-custom-action" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST **/tspublic/rest/v2/customaction/create`

Creates a custom action.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/custom-actions/create-custom-action" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/customaction/update`

Updates a custom action object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/custom-actions/update-custom-action" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**DELETE** /tspublic/rest/v2/customaction/delete`

Deletes a custom action object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/custom-actions/delete-custom-action" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/customaction/search`

Allows searching for custom actions available in ThoughtSpot.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/custom-actions/search-custom-action" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/customaction/association`

Gets metadata association details for a given custom action.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/custom-actions/get-custom-action-association" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/customaction/association/update`

Updates metadata association for a given custom action.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/custom-actions/update-custom-action-association" id="preview-in-playground" target="_blank">View in Playground</a>
++++


+++<p class="divider"> </p>+++

`**DELETE **/tspublic/rest/v2/customactions/association/delete`

Removes custom action association to a user, group or metadata object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/custom-actions/delete-custom-action-association" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

== Log
--
`*GET* /tspublic/rest/v2/logs/events`

Gets security audit logs from the ThoughtSpot system.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/logs/get-log-events" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++
--



== Materialization
--
`*PUT* /tspublic/rest/v2/materialization/refreshview`

Refreshes data in a materialized view. +

This endpoint is applicable to ThoughtSpot Software deployments only.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2?apiResourceId=/http/api-endpoints/materialization/refresh-materialized-view" id="preview-in-playground" target="_blank">View in Playground</a>
++++
+++<p class="divider"> </p>+++
--

== Database

The Database endpoints are applicable to ThoughtSpot Falcon-based Software deployments only.

////