= REST API v1
:toc: true

:page-title: REST API v1
:page-pageid: rest-api-v1
:page-description: ThoughtSpot REST API provides service endpoints for administration, embedding, and data management.

ThoughtSpot REST API v1 endpoints let you programmatically create, access, and manage ThoughtSpot objects and resources. The REST API endpoints support the following operations:

* get Liveboard and visualization data from the ThoughtSpot application
* embed data from visualizations and Liveboards in a web page, portal, or application
* view metadata details for various types of ThoughtSpot objects
* construct a search query to get ThoughtSpot data
* manage ThoughtSpot user profiles and group privileges
* transfer ownership of objects from one user to another
* import, export, and validate scriptable files and automate deployments

== Resource endpoints
ThoughtSpot API components or resources are represented by the URI endpoints. The URI endpoint contains the base URI and resource path to the objects that you want to query or manage.

The base URI of the API endpoints constitutes the following:

* The hostname or IP address of your ThoughtSpot application instance
* Port number
* Name of the ThoughtSpot API service
* The version number

For example, in the `\https://<your-thoughtspot-hostname:port>/callosum/v1/tspublic/v1/session/login` URL

* the base URI is `\https://<your-thoughtspot-hostname:port>/callosum/v1`
* the resource path is `/tspublic/v1/session/login` 

== HTTP request methods

ThoughtSpot REST API endpoints support Create, Read, Update and Delete (CRUD) operations and allow applications to use the standard HTTP verbs in API requests:
 
* `GET` to query information, such as getting a list of users or groups.
* `POST` to create and add new properties to a resource, such as a user, group, Answer, Worksheet, or a data object.
* `PUT` to update the properties of an existing resource, such as modifying the properties of a user or user group. 
* `DELETE` to remove an object or object association.

== Data format

The REST APIs allow you to send and receive data in JSON format. To embed this data in your application, you can import or extract the data from the JSON file. You can also use scriptable files in ThoughtSpot Modeling Language (TML) to represent objects in a reusable, editable, and easy-to-read format. ThoughtSpot allows you to export, validate, and import these scriptable files.

== Related information

* xref:rest-api-getstarted.adoc[Get started with REST API v1]
* xref:api-auth-session.adoc[Authentication]
* xref:rest-api-reference.adoc[REST API v1 Reference]
