= Get started
:toc: true

:page-title: Getting started with REST API
:page-pageid: rest-api-getstarted
:page-description: Getting started with REST API

The REST API allows you to query data from ThoughtSpot and embed it in a Web page, portal, or application.
To access REST APIs, you must authenticate through SAML SSO.
For more information on configuring SAML, see xref:configure-saml.adoc[SAML SSO].

== Cross-Origin Resource Sharing

To query and modify ThoughtSpot objects using REST APIs, you must add your client application domain as an allowed domain for CORS. When you add your host domain for CORS, ThoughtSpot adds the `access-control-allow-origin` header in its API responses.
For more information on whitelisting a domain for CORS, see  xref:security-settings.adoc[Security settings].

== Base URI

The base URI for the REST APIs calls includes the following:

* The hostname or IP address of your ThoughtSpot application instance.
* Port number

For example:

----
https://<your-thoughtspot-hostname:port>
----

== API service name and version

For REST API calls, in addition to the base URI, append the API service name and the version number.

For example:

----
https://<your-thoughtspot-hostname:port>/callosum/v1/
----
