= REST API SDK and client libraries 
:toc: true
:toclevels: 2

:page-title: REST API SDK and client libraries
:page-pageid: client-libraries
:page-description: REST API SDK 

REST API V2 client libraries are available to help client applications call REST APIs in a language-specific way.

Client libraries are available for Java, Python and TypeScript. For each language, the client library provides tools and an abstraction layer, letting you construct queries and use response data without having to create HTTP requests or process HTTP responses by hand. Each client library provides classes that correspond to the elements and data types that the API uses.  

== Java

The Java API client library is provided by ThoughtSpot.

[div boxdiv]
--
Quickstart
Reference Guide 
Code samples
--

== Python

The Java API client library is provided by ThoughtSpot.

[div boxdiv]
--
Quickstart
Reference Guide 
Code samples
--

== TypeScript

The Java API client library is provided by ThoughtSpot.

[div boxdiv]
--
Quickstart
Reference Guide 
Code samples
--

