= Get started with REST API v2
:toc: true
:toclevels: 2

:page-title: Getting started with REST API v2
:page-pageid: rest-apiv2-getstarted
:page-description: Get started with REST API v2 to access, create, and manage ThoughtSpot resources programmatically.

To get started with REST API v2 framework



== Access the REST API Playground

If your instance has the REST API v2 Playground and SDK feature enabled, go to **Develop** > **REST API** > **REST Playground v2**. You can view a list of available endpoints on the left pane.


The Playground allows you to make API calls, view the request and response workflows, and and download the samples.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">Visit REST v2 Playground</a>
++++

== Authorize your client

REST API v2 support the OAuth 2.0 Bearer token authentication method to provide secure access to ThoughtSpot resources. 

Before accessing or modifying any ThoughtSpot object, you must obtain an OAuth access token to authorize your client. 

To get an access token, send a `POST` request to the  `/api/rest/v2/session/gettoken` endpoint.

----
POST /api/rest/v2/session/gettoken
----


In the request body, specify your ThoughtSpot user credentials. Optionally, you can set token expiry duration.

[source,curl]
----
  "userName": "tsadmin",
  "password": "123CLOud!",
  "tokenExpiryDuration": "86400"
----

If the request is successful, the server returns an access token in the session login response. 

[source,JSON]
----
{
"userName":"tsadmin"
"token":"dHNhZG1pbjpKSE5vYVhKdk1TUlRTRUV0TWpVMkpEVXdNREF3TUNSRGRVZFRLM2hQUzNKUVNUSm1jMnBsTlRNdmMwVkJQVDBrTmsxeFZYWmhNR2R1TUVabFQzTXZiSE5qTW5ONVdtdG1Zalo0ZFVSTWIyNXZWVmRtTWxGeWEwVnhORDA="
"tokenCreatedTime":"1642662844229"
"tokenExpiryDuration":"1642749244229"
"tokenType":"Bearer"
}
----

Note the access token in the response. You must pass this token in the Authorization HTTP header along with the other headers in the subsequent API requests.

[NOTE]
====
The generated token will be valid for the specified duration. If a request is made with an expired token, the API returns token expired message. You can request for another token to make API calls.  
====

== Make an API call

To make a REST API call, send a request to the endpoint URL and pass the parameters. 

For example, to get a list of metadata objects, send a `GET` request to the `/api/rest/v2/metadata/header/search`.

----
POST /api/rest/v2/metadata/header/search
----


++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">Try it out</a>
++++

=== Request header

Each API call must include the following headers.

* `'Authorization: Bearer {OAUTH}'`
+
The authorization header must include the OAuth token obtained from ThoughtSpot.

* `'Content-Type: application/json'`
+
The header to indicate the content type for request body. 

* `'Accept-Language: application/json'`
+
The `Accept` header for API response format. 


=== Request parameters

Most APIs require you to specify at least one parameter. For example, to view the details of a user object, you can specify either user GUID or the user name. 

The API Playground indicates the required and optional parameters and provides information about the data type and allowed values. For example, to get a list of answers, you must specify the metadata `type` as `Answer`. 

The following example shows the CURL request format to get a list of answers saved in the ThoughtSpot system.

[source,curl]
----
curl -X POST \
  --url '<ThoughtSpot-host>/api/rest/v2/metadata/header/search' \
  -H 'Authorization: Bearer dHNhZG1pbjpKSE5vYVhKdk1TUlRTRUV0TWpVMkpEVXdNREF3TUNRMFEwVXhVVTVpTm05c2FGZEthMFI0VjNJNFdHMW5QVDBrYTFCc1dEaENTMnR5YWtSbE0wSnRibEZ5VkRFclEzTXpRbEpRWkU5allreHNReXN5Y21WT2FtNUZUVDA='\
  -H 'Accept-Language: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "type": "ANSWER"
}'
----

If the API request is successful, ThoughtSpot returns a list of object headers for requested object type.

[source,JSON]
----
{
   "headers":[
      {
         "id":"92f48c07-9c62-4bfa-81ac-55f3049165b4",
         "indexVersion":5,
         "generationNum":705,
         "name":"Credit usage from Charging Records",
         "description":"COPY and EDIT : Username and Timestamp to trace events",
         "author":"67e15c06-d153-4924-a4cd-ff615393b60f",
         "authorName":"system",
         "authorDisplayName":"System User",
         "created":1620803453455,
         "modified":1620804108541,
         "modifiedBy":"67e15c06-d153-4924-a4cd-ff615393b60f",
         "owner":"92f48c07-9c62-4bfa-81ac-55f3049165b4",
         "isDeleted":false,
         "isHidden":false,
         "isAutoCreated":false,
         "isAutoDelete":false,
         "tags":[
            
         ],
         "isExternal":false,
         "isDeprecated":false
      }
   ],
   "isLastBatch":true
}
----

=== 



=== HTTP status codes

For each API request, ThoughtSpot sends a response. The API returns one of the following response codes upon completing a request operation:

* *200*
+
Indicates a successful operation. The API returns a response body.
* *204*
+
Indicates a successful operation. The 204 response code does not include a response body.
* *400*
+
Indicates a bad request. You may have to modify the request before making another call.
* *401*
+
Indicates an unauthorized request. Check if you have the required credentials and object access to send the API request.

* *415*
+
Indicates an unsupported media type. Check the media type specified in the `Content-Type` header.

* *500*
+
Indicates an internal server error. Check if the data format of the request is supported. Verify if the server is available and can process the request.




==== Object IDs
All ThoughtSpot objects and resources are assigned a GUID (Globally Unique Identifier) by default. Most endpoints require you to specify the GUID to access, query, or modify a specific object. You can query the metadata list to get a list of objects of a specific type, and the GUIDs assigned to each of these objects.

For example, you can use the `/tspublic/v1/metadata/listvizheaders` endpoint to get a list of the Liveboards and their GUIDs:

[source,JSON]
----
[
{
   "id":"d084c256-e284-4fc4-b80c-111cb606449a",
   "name":"Sales Performance",
   "description":"",
   "author":"67e15c06-d153-4924-a4cd-ff615393b60f",
   "created":1642560047638,
   "modified":1642560047638,
   "modifiedBy":"67e15c06-d153-4924-a4cd-ff615393b60f",
   "owner":"d084c256-e284-4fc4-b80c-111cb606449a",
   "isAutoCreated":false,
   "isAutoDelete":false
},
{
   "id":"74852035-9624-4fac-b352-200fa8506b14",
   "name":"Object Usage",
   "description":"",
   "author":"67e15c06-d153-4924-a4cd-ff615393b60f",
   "created":1620198465429,
   "modified":1620198473992,
   "modifiedBy":"67e15c06-d153-4924-a4cd-ff615393b60f",
   "owner":"74852035-9624-4fac-b352-200fa8506b14",
   "isAutoCreated":false,
   "isAutoDelete":false
}
]
----

=== HTTP status codes

For each API request, ThoughtSpot sends a response. The API returns one of the following response codes upon completing a request operation:

* *200*
+
Indicates a successful operation. The API returns a response body.
* *204*
+
Indicates a successful operation. The 204 response code does not include a response body.
* *400*
+
Indicates a bad request. You may have to modify the request before making another call.
* *401*
+
Indicates an unauthorized request. Check if you have the required credentials and object access to send the API request.

* *415*
+
Indicates an unsupported media type. Check the media type specified in the `Content-Type` header.

* *500*
+
Indicates an internal server error. Check if the data format of the request is supported. Verify if the server is available and can process the request.

