= REST API v2 Reference
:toc: true

:page-title: REST API Reference Guide
:page-pageid: rest-apiv2-reference
:page-description: REST API Reference

The REST v2 API endpoints[beta blueBackground]^BETA^ are categorized based on the type of object they operate on. The REST v2 framework includes the following resource collections and endpoints.

== Session

--
`**GET** /tspublic/rest/v2/session`

Gets details of the current session for the logged-in user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/session/login`

Signs in a user to ThoughtSpot. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/session/gettoken`

Gets an OAuth access token for a ThoughtSpot client. You must send this token in the `Authorization` header to authorize your API requests.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/session/revoketoken`

Revokes an existing access token assigned to a ThoughtSpot client. To make API calls, you must obtain a new access token.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/session/logout`

Logs out a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Users
--

`*POST* /tspublic/rest/v2/user/create`

Creates a user object. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`GET /tspublic/rest/v2/user`

Gets details of a specific user. You must provide the username or the GUID of the user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/user/update`

Modifies the properties of a user object. You must specify a username or the GUID of the user. Requires administrator privileges. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`DELETE /tspublic/rest/v2/user/delete`

Deletes a user object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/user/addgroup`

Assigns a user to groups. If the assigned groups have privileges configured, the user inherits these privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/user/removegroup`

Removes the groups assigned to a user. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/user/changepassword`

Allows changing a ThoughtSpot user's password.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/user/search`

Gets a list of users available in the ThoughtSpot system. To filter your query, you can specify the user type, group, privileges, sharing visibility, and other such attributes. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

--

== Groups

--
`*GET* /tspublic/rest/v2/group`

Gets details of a specific group.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/group/create`

Creates a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/group/update`

Modifies the properties of a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/tspublic/rest/v2/group/addprivilege`

Assigns privileges to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/tspublic/rest/v2/group/removeprivilege`

Removes privileges assigned to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**DELETE** /tspublic/rest/v2/group/delete`

Deletes a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/group/adduser`

Assigns users to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/tspublic/rest/v2/group/removeuser`

Removes one or several users assigned to a group. Requires administrator privileges.


++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++
 
`*PUT* /tspublic/rest/v2/group/addgroup`

Adds a group to another group object. This API request creates a hierarchy of groups. The subgroups inherit the privileges assigned to the parent group.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/group/removegroup`

Removes a group from the parent group.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/group/search`

Gets a list of groups created in the ThoughtSpot system. To filter your query, you can specify the group type, group name, privileges, sharing visibility, users, and other such attributes. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Admin

--
`**GET ** /tspublic/rest/v2/admin/configuration`

Gets details of the current configuration of a ThoughtSpot cluster.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/admin/configuration/overrides`

Gets details of configuration overrides. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/tspublic/rest/v2/admin/configuration/update`

Updates configuration settings of the ThoughtSpot cluster.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/admin/resetpassword`

Resets the password of a user account.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/admin/syncprincipal`

Synchronizes user account and group properties from an external database with ThoughtSpot.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/admin/changeauthor` [tag orangeBackground]#MODIFIED in 8.4.0.cl#

Transfers the ownership of objects from one user to another.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/admin/assignauthor`

Assigns ownership to one or several objects to a specific user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
+++<p class="divider"> </p>+++
--


== Metadata

--
`*GET* /tspublic/rest/v2/metadata/tag`

Gets details for the specified tag. You must specify the tag name or the GUID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/tag/create`

Creates a tag object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/metadata/tag/update`

Modifies the properties of a tag object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/metadata/tag/assign`

Assigns a tag to one or several metadata objects. You can assign a tag to a Liveboard, answer, data object, and data connection objects.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/metadata/tag/unassign`

Removes the tag assigned to an object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*DELETE* /tspublic/rest/v2/metadata/tag/delete`

Deletes the specified tag.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/metadata/favorite/assign`

Adds an object such as Liveboards and answers to a user's favorites list.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT ** /tspublic/rest/v2/metadata/favorite/unassign`

Removes the specified object from the user's favorites list.  

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**GET** /tspublic/rest/v2/metadata/homeliveboard`

Gets the details of the Liveboard that is set as a default Liveboard for the ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++
 
`**PUT** /tspublic/rest/v2/metadata/homeliveboard/assign`

Assigns a Liveboard as a default Liveboard for a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/metadata/homeliveboard/unassign`

Removes the default home Liveboard setting for a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/metadata/incomplete`

Gets a list of objects with incomplete metadata. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/metadata/header`

Gets header details for a specific metadata object. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++


+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/metadata/details`

Gets details of a specific metadata object. To filter your query, specify the metadata object type and the ID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/metadata/vizheaders`

Gets a list of visualization headers associated with a Liveboard.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/header/search`

Gets a list of all metadata objects in the ThoughtSpot system. To filter your query, specify the metadata object type, access level, and other such attributes.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/detail/search`

Gets details of one or several metadata objects of a specific type.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*DELETE* /tspublic/rest/v2/metadata/delete`

Deletes the specified metadata object. You can delete answers, Liveboards, tags, worksheets, views, tables, columns, and table joins. +
Note that the endpoint does not support deleting the connection, user, and group objects. To delete these objects, use the following endpoints:

* `DELETE /tspublic/rest/v2/connection/delete`
* `DELETE /tspublic/rest/v2/user/delete`
* `DELETE /tspublic/rest/v2/group/delete`

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/dependency`

Gets a list of dependent metadata objects.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/metadata/tml/export`

Exports a TML object and associated metadata.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/metadata/tml/import`

Imports one or several TML objects and object associations.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

--

== Connections 

--
`*GET* /tspublic/rest/v2/connection`

Gets details of a specific data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**GET** /tspublic/rest/v2/connection/database`

Gets details of the databases associated with a connection ID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/connection/table`

Gets details of the tables associated with a connection ID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/connection/tablecoloumn`

Gets details of the columns of the tables associated with a connection ID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/connection/create`

Creates a data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/connection/update`

Updates an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

*DELETE* /tspublic/rest/v2/connection/delete

Deletes a data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/connection/addtable`

Adds a table to an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /tspublic/rest/v2/connection/removetable`

Removes a table from an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/connection/search`

Gets details of all data connections. You can also query data for a specific connection type.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Data

--
`**POST** /tspublic/rest/v2/data/search`

Allows constructing a search query string and retrieves data from a search query.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/data/answer`

Gets data from a saved search answer.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/data/liveboard`

Gets data from the specified Liveboard and visualization.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/data/answer/querysql`

Retrieves SQL for an answer object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/data/liveboard/querysql`

Retrieves SQL for a visualization on a Liveboard.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Report

--
`*POST* /tspublic/rest/v2/report/answer`

Downloads answer data in the specified file format, such as PDF, CSV, PNG, and XLSX. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/report/liveboard`

Downloads a given Liveboard and its visualizations as a PDF, CSV, XLSX, or PNF file.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Security

`*POST* /tspublic/rest/v2/security/share/tsobject`

Allows sharing an object with another user or group in ThoughtSpot.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/security/share/visualization`

Allows sharing a Liveboard visualization  with another user or group in ThoughtSpot.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**GET** /tspublic/rest/v2/security/permission/tsobject`

Gets access permission details for a metadata object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

*GET* /tspublic/rest/v2/security/permission/principal

Gets a list of objects that the specified user or group has access to.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/security/permission/tsobject/search`

Gets permission details for specific object and users and groups who have access to these objects.  

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /tspublic/rest/v2/security/permission/principal/search`

Gets a list objects to which a user or group has `read-only` or `modify` permissions.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++


== Custom actions 

`*GET* /tspublic/rest/v2/customaction`

Gets details of a custom action.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST **/tspublic/rest/v2/customaction/create`

Creates a custom action.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /tspublic/rest/v2/customaction/update`

Updates a custom action object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**DELETE** /tspublic/rest/v2/customaction/delete`

Deletes a custom action object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /tspublic/rest/v2/customaction/search`

Allows searching for custom actions available in ThoughtSpot.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /tspublic/rest/v2/customaction/association`

Gets details of a custom action association to metadata objects, users, and groups.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**DELETE **/tspublic/rest/v2/customactions/association/delete`

Removes custom action association to a user, group or metadata object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

== Log

--
`*GET* /tspublic/rest/v2/logs/events`

Gets security audit logs from the ThoughtSpot system.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--