= REST API SDK and client libraries
:toc: true

:page-title: REST API SDK and client libraries
:page-pageid: client-libraries
:page-description: REST API SDK 

ThoughtSpot provides native SDK libraries to help client applications call REST APIs in a language-specific way.

Client libraries are available for Java, Python, TypeScript, and .NET. For each language, the client library provides tools and APIs to construct queries and process responses programmatically. Each client library includes classes that correspond to the resource elements and data types that the API uses.

== Download the SDK

You can also download the SDK and API libraries from the following public resources:

* link:https://github.com/thoughtspot/rest-api-sdk[GitHub repository, window=_blank]
* TypeScript SDK - link:https://www.npmjs.com/package/@thoughtspot/rest-api-sdk[NPM site, window=_blank]
* Python SDK - link:https://pypi.org/project/thoughtspot-rest-api-sdk/[PyPi, window=_blank]
* Java SDK - link:https://search.maven.org/artifact/io.github.thoughtspot/rest-api-sdk-lib[MVN Package Manager, window=_blank]
* .NET SDK - link:https://www.nuget.org/packages/thoughtspot.rest.api.sdk[NuGet package manager, window=_blank]

== Setup and usage

The Playground provides installation, setup and usage instructions for each language.

. Go to **Develop** > *REST API* > **REST Playground v2**.
. Select a programming language.
. Click *Getting Started* > **Setup and Usage** .


== Additional resources

++++
<div class="row">
    <div class="col-md-3">
       <div class="boxDiv"> <h4 align=center>Java SDK and libraries</h4>
       <a href="https://github.com/thoughtspot/rest-api-sdk/blob/main/Java/README.md" target=_blank> <p align=center>Get started</p></a>
        <a href="https://github.com/thoughtspot/rest-api-sdk/blob/main/Java/doc/README.md" target=_blank> <p align=center>API Reference</p></a>
  
      </div> 
    </div>
    <div class="col-md-3">
       <div class="boxDiv"> <h4 align=center>Python SDK and libraries</h4>
       <a href="https://github.com/thoughtspot/rest-api-sdk/blob/main/Python/README.md" target=_blank> <p align=center>Get started</p></a>
        <a href="https://github.com/thoughtspot/rest-api-sdk/blob/main/Python/doc/README.md" target=_blank> <p align=center>API Reference</a>

      </div> 
    </div>
    <div class="col-md-3">
       <div class="boxDiv"> <h4 align=center>Typescript SDK and libraries</h4>
       <a href="https://github.com/thoughtspot/rest-api-sdk/blob/main/Typescript/README.md" target=_blank> <p align=center> Get started</p></a>
        <a href="https://github.com/thoughtspot/rest-api-sdk/blob/main/Typescript/doc/README.md" target=_blank><p align=center>API Reference</p></a>
      </div> 
      </div>
    <div class="col-md-3">
       <div class="boxDiv"> <h4 align=center>.NET SDK and libraries</h4>
       <a href="https://github.com/thoughtspot/rest-api-sdk/tree/main/DotNet#readme" target=_blank> <p align=center> Get started</p></a>
        <a href="https://github.com/thoughtspot/rest-api-sdk/blob/main/DotNet/doc/README.md" target=_blank><p align=center>API Reference</p></a>
      </div>
      </div>
    </div>
  </div>
<div class="divider"></div>
++++
 
 
 
////
<a href="{{previewPrefix}}/tspublic/rest/playgroundV2" target=_blank> <p align=center>Code samples</p></a>

////
 
