= REST API Playground
:toc: true
:toclevels: 2

:page-title: REST API Playground
:page-pageid: rest-playground
:page-description: Use the REST Playground to explore the REST API endpoints, request and response workflows

The REST API Playground provides an interactive portal to explore REST API v1 and v2.0 endpoints.

* To view the Playground with REST API v1 endpoints, click **REST Playground v1**. +
* To explore REST API v2 endpoints, click **REST Playground v2.0**.

== REST API v1 Playground

The *REST Playground v1* opens the v1 API explorer and displays the available resource collections in the Swagger UI.

To make an API call and view results:

. Click the API service category and view a list of endpoints.
. Click on the endpoint to which you want to send an API request.
. If required, define the attributes.
. Click **Try it out** and verify the API response and HTTP status code.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV1" id="preview-in-playground" target="_blank">Try it out</a>
++++

For more information about REST API v1 endpoints, API request and response workflow, see xref:rest-api-getstarted[Get started with REST API v1].

== REST API v2.0 Playground

The REST API v2.0 Playground displays a list of v2 API endpoints, and a code panel to try out API calls.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2_0" id="preview-in-playground" target="_blank">Try it out</a>
++++

For more information, see xref:rest-api-v2-playground.adoc[REST API v2.0 Playground].
