[[_pinboarddata]]
=== Pinboard Data API

Retrieves data for a pinboard or other visualization from the ThoughtSpot system.

This API lets you fetch the following data:

* All the visualization objects on a pinboard.
* A specific visualization or a group of visualizations on a pinboard.



==== Request URL
....
POST /tspublic/v1/pinboarddata
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Data Type |Default
|**Query**|**batchsize** +
__optional__|The batch size for loading of pinboard objects.|integer (int32)|`-1`
|**Query**|**formattype** +
__optional__|Json format type. Valid values are FULL and COMPACT.|string|`"COMPACT"`
|**Query**|**id** +
__optional__|GUID ID of the pinboard.|string|
|**Query**|**offset** +
__optional__|Offset.|integer (int32)|`-1`
|**Query**|**pagenumber** +
__optional__|PageNumber. Alternate way to set offset. This is 1-based indexingOffset = (pageNumber - 1) * batchSize.|integer (int32)|`-1`
|**Query**|**vizid** +
__optional__|GUID IDs of visualizations. Use this parameter to fetch a specific visualization on a pinboard. |string|
|===

==== Example Request

===== cURL
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<instance>/callosum/v1/tspublic/v1/pinboarddata?id=f4533461-caa5-4efa-a189-13815ab86770&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT'
----

===== Request URL
----
https://<instance>/callosum/v1/tspublic/v1/pinboarddata?id=f4533461-caa5-4efa-a189-13815ab86770&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT
----



==== Responses


===== Example Response 

----
{
  "4fdf9d2c-6f34-4e3b-9fa6-bd0ca69676e1": {
    "name": "Sample Name",
    "columnNames": [
      "Opportunity Stage",
      "Opportunity Owner Name",
      "Total Amount"
    ],
    "data": [
      [
        "s3 alignment with eb",
        "jeff cameron",
        1102272
      ],
      [
        "s4 validation",
        "brian mcquillan",
        59150
      ]
    ],
    "samplingRatio": 1,
    "totalRowCount": 14,
    "rowCount": 14,
    "pageSize": 10,
    "offset": 0
  }
}
----
===== Response Messages

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|gets the data of a pinboard/visualization|string
|**400**|invalid pinboard id|No Content
|===



//==== Produces

//* `application/json`


//==== Tags

//* tspublic/v1


[[_searchdata]]
=== Search API
Search data from a specific data source in thoughtspot system

=== Request URL
....
POST /tspublic/v1/searchdata
....

////
==== Description
Search data from a specific data source in thoughtspot system
////

==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**batchsize** +
__optional__|Batch size|integer (int32)|`-1`
|**Query**|**data_source_guid** +
__optional__|Guid of the data source (ex: worksheet/table|string|
|**Query**|**formattype** +
__optional__|Json format type. Values allowed are FULL and COMPACT|string|`"COMPACT"`
|**Query**|**offset** +
__optional__|Offset|integer (int32)|`-1`
|**Query**|**pagenumber** +
__optional__|PageNumber. Alternate way to set offset. This is 1-based indexingOffset = (pageNumber - 1) * batchSize|integer (int32)|`-1`
|**Query**|**query_string** +
__optional__|Query string|string|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|gets the data from the data source|string
|**400**|invalid query/data source|No Content
|===


[[_listobjectheaders]]
=== Metadata object headers API
List of metadata object headers in the repository

=== Request URL
....
GET /tspublic/v1/metadata/listobjectheaders
....

////
==== Description
List of metadata object headers in the repository
////

==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**auto_created** +
__optional__|List auto created objects only. null signifies return all.|boolean|
|**Query**|**batchsize** +
__optional__|Batch size; Unspecified implies system default; -1 implies no pagination|integer (int32)|
|**Query**|**category** +
__optional__|Category of metadata object. Valid values - ALL, MY, FAVORITE, REQUESTED|string|`"ALL"`
|**Query**|**fetchids** +
__optional__|GUID Ids of metadata objects to fetch|string|
|**Query**|**offset** +
__optional__|Batch offset to fetch page of headers; -1 implies first page|integer (int32)|`-1`
|**Query**|**pattern** +
__optional__|Pattern to match for object names (use '%' for wildcard match|string|
|**Query**|**skipids** +
__optional__|GUID Ids of metadata objects to exclude|string|
|**Query**|**sort** +
__optional__|Sort order of returned headers. Valid values - DEFAULT, NAME, DISPLAY_NAME, AUTHOR, CREATED, MODIFIED|string|`"DEFAULT"`
|**Query**|**sortascending** +
__optional__|Flag for direction of sorting (null signifies default order, true signifies ascending order and false signifies descending order)|boolean|
|**Query**|**subtypes** +
__optional__|List of sub-Types of metadata object. Applies for LOGICAL_TABLE type with valid values - ONE_TO_ONE_LOGICAL, WORKSHEET, PRIVATE_WORKSHEET, USER_DEFINED, AGGR_WORKSHEET|string|
|**Query**|**tagname** +
__optional__|Set of tag names to filter headers by; JSON Array of name Strings|string|
|**Query**|**type** +
__optional__|Type of metadata object. Valid values - QUESTION_ANSWER_BOOK, PINBOARD_ANSWER_BOOK, QUESTION_ANSWER_SHEET, PINBOARD_ANSWER_SHEET, LOGICAL_COLUMN, LOGICAL_TABLE, LOGICAL_RELATIONSHIP, TAG, DATA_SOURCE|string|`"PINBOARD_ANSWER_BOOK"`
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Metadata Headers JSON|string
|===



[[_getvisualizationheaders]]
=== Metadata visualization header API
....
GET /tspublic/v1/metadata/listvizheaders
....


==== Description
Get the visualization headers from the ThoughtSpot system.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Query**|**id** +
__optional__|GUID of the reportbook|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|gets the visualization headers|string
|**400**|invalid pinboard GUID|No Content
|===


==== Produces

* `application/json`


==== Tags

* tspublic/v1/metadata

[[_login]]
=== Session Login
....
POST /tspublic/v1/session/login
....


==== Description
Authenticate and login a user


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**FormData**|**password** +
__optional__|Password|string|
|**FormData**|**rememberme** +
__optional__|Flag to indicate if user session should be remembered|boolean|`"false"`
|**FormData**|**username** +
__optional__|Username|string|
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|No response was specified|No Content
|**204**|Successful login|No Content
|**401**|Login failure/unauthorized|No Content
|===




[[_logout]]
=== Session Logout
....
POST /tspublic/v1/session/logout
....


==== Description
Logout current user


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|No response was specified|No Content
|**204**|Successful logout|No Content
|**401**|Logout failure/unauthorized|No Content
|===


==== Tags

* tspublic/v1/session


[[_list]]
=== Fetch users and groups
....
GET /tspublic/v1/user/list
....


==== Description
Api to get all users, groups and their inter-dependencies


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Description was not specified|string
|===




[[_synchronizeprincipals]]
=== Synchronize Principals
....
POST /tspublic/v1/user/sync
....


==== Description
Api to synchronize principal from external system with ThoughtSpot system


==== Parameters

[options="header", cols=".^2a,.^3a,.^4a,.^2a"]
|===
|Type|Name|Schema|Default
|**FormData**|**applyChanges** +
__optional__|boolean|`"false"`
|**FormData**|**password** +
__optional__|string|
|**FormData**|**principals** +
__optional__|string|
|**FormData**|**removeDeleted** +
__optional__|boolean|`"true"`
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|Description was not specified|string
|===


==== Consumes

* `multipart/form-data`


==== Produces

* `application/json`


==== Tags

* tspublic/v1/user


[[_transferownership]]
=== Transfer ownership of all objects from one user to another
....
POST /tspublic/v1/user/transfer/ownership
....


==== Description
Api to transfer ownership of all objects from one user to another


==== Parameters

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Type|Name|Schema
|**Query**|**fromUserName** +
__optional__|string
|**Query**|**toUserName** +
__optional__|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|if ownership of all objects are successfully transferred|No Content
|**400**|In case of invalid fromName and toName or for given username there is no user present.|No Content
|===




[[_changepassword]]
=== Change password of user
....
POST /tspublic/v1/user/updatepassword
....


==== Description
Api to change password of a user.


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**FormData**|**currentpassword** +
__optional__|Current password of the logged in user|string
|**FormData**|**name** +
__optional__|Name of the user whose password needs to be updated/|string
|**FormData**|**password** +
__optional__|New password of the logged in user|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|If the password of the user is changed successfully.|No Content
|===


[[_addprivilege]]
=== Add Privilege
....
POST /tspublic/v1/group/addprivilege
....


==== Description
Add privilege to groups


==== Parameters

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Type|Name|Schema
|**FormData**|**groupNames** +
__optional__|string
|**FormData**|**privilege** +
__optional__|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|No response was specified|No Content
|**204**|Success|No Content
|**401**|Failure/Unauthorized|No Content
|===



[[_removeprivilege]]
=== Remove Privilege
....
POST /tspublic/v1/group/removeprivilege
....


==== Description
Remove privilege from groups


==== Parameters

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Type|Name|Schema
|**FormData**|**groupNames** +
__optional__|string
|**FormData**|**privilege** +
__optional__|string
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|No response was specified|No Content
|**204**|Success|No Content
|**401**|Failure/Unauthorized|No Content
|===


