= REST API v2.0 Reference
:toc: true


:page-title: REST API Reference Guide
:page-pageid: rest-apiv2-reference
:page-description: REST API Reference

This API Reference page lists the REST API v2.0 endpoints and provides basic information about the resource URLs and supported operations. If you want to try out these APIs, view detailed documentation, and download code samples, visit the +++<a href="{{previewPrefix}}/api/rest/playgroundV2" target="_blank">REST API v2.0 Playground</a>+++.

[NOTE]
====
Access to ThoughtSpot data is controlled based on xref:api-user-management.adoc#group-privileges[user privileges] and xref:configure-user-access.adoc#_object_level_permissions[object-level permissions]. Some operations are available to all users and may require at least view access to the metadata object. ThoughtSpot users are assigned access privileges based on the group to which they belong. Additionally, object owners can control access to a metadata object using `MODIFY` (*Can edit*), `READ_ONLY` (*Can view*), or `NO_ACCESS` permission when sharing an object with other users and groups.
====

== Authentication

[div divider]
--
+++<h4> Get current user information</h4>+++

`GET /api/rest/2.0/auth/session/user` +

Gets session information for the currently logged-in user.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/get-current-user-info" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Login</h4>+++

`POST /api/rest/2.0/auth/session/login`

Creates a login session for a ThoughtSpot user.

Requires `username` and `password`. Users can also specify the ID of the Org to which they want to log in.

If the login is successful, a user session is established.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/login" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Get authentication token</h4>+++

* `POST /api/rest/2.0/auth/token/object`
+
Gets an authentication token from ThoughtSpot, which allows access to a specific metadata object in ThoughtSpot. The token obtained from this API call provides only view access to the object specified in the API request.
+
** To obtain a bearer token, specify the username, password, and object ID in the API request.
** To obtain a token on behalf of a user, specify the username, secret key, and object ID.
+
__Requires access to the `secret_key`. For more information, see xref:trusted-authentication.adoc#trusted-auth-enable[Trusted authentication]__.

+
+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/get-object-access-token" id="preview-in-playground" target="_blank">View in Playground</a>+++

* `POST /api/rest/2.0/auth/token/full`
+
Gets an authentication token from ThoughtSpot, which provides access to the full application.
+
** To obtain a bearer token, specify the username and password in the API request.
** To obtain a token on behalf of a user, specify the username and secret key.
+
__Requires access to the `secret_key`. For more information, see xref:trusted-authentication.adoc#trusted-auth-enable[Trusted authentication]__.

+
+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/get-full-access-token" id="preview-in-playground" target="_blank">View in Playground</a>+++

////
[NOTE]
====
You can copy the `secret key` from *Develop* > *Customizations* > *Security Settings* page if xref:trusted-authentication.adoc#trusted-auth-enable[Trusted authentication] is enabled on your instance.
====
////

+++ <h5>Just-in-time user provisioning</h5> +++

The `/api/rest/2.0/auth/token/object` and `/api/rest/2.0/auth/token/full` API endpoints also let you provision a user just-in-time (JIT) and assign the new user to Orgs and groups. If a user is not available in ThoughtSpot, administrators can create a user profile by setting `auto_create` to `true`, and provision the user to an Org and groups in an Org.

For more information, see xref:authentication.adoc[REST API v2.0 authentication].
--

[div divider]
--
+++<h4>Logout</h4>+++

`POST /api/rest/2.0/auth/session/logout` +

Logs out the currently logged-in user.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/logout" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Get Current User Token</h4>+++

`POST /api/rest/2.0/auth/session/logout` +

Gets authentication token details for the currently logged-in user.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/get-current-user-token" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Revoke token</h4>+++

`POST /api/rest/2.0/auth/token/revoke` +

Revokes authentication token granted for a user.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/revoke-token" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Users

[div divider]
--
+++<h4>Search users</h4>+++

`POST /api/rest/2.0/users/search`

Gets user details. You can get the details of a specific user or all user objects available in the ThoughtSpot system.
You can also filter the API output based on groups, Org ID, visibility, account status, user type, user preference settings, user's favorite objects, or home Liveboard setting.

__Available to all authenticated users__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/search-users" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create a user</h4>+++

`POST /api/rest/2.0/users/create`

Creates a user in ThoughtSpot. This API also supports the following operations: +

* add the email address of the user
* add the user to xref:orgs.adoc[Orgs] and groups.
* set account status
* define sharing visibility
* set a default Liveboard for the user
* add Liveboard, Answer, and Worksheet objects to the user's favorites list
* set user preferences to start or stop onboarding walkthrough, and receive an email notification when another user shares an object

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/create-user" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update a user</h4>+++

`POST /api/rest/2.0/users/{user_identifier}/update`

Allows modifying the properties of a user object.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/update-user" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete a user</h4>+++

`POST /api/rest/2.0/users/{user_identifier}/delete`

Deletes a user from ThoughtSpot.

[NOTE]
====
In the current release, deleting a user removes the user from ThoughtSpot. If you want to remove a user from a specific Org, update the group and Org mapping properties of the user object via a `POST` API call to the `/api/rest/2.0/users/{user_identifier}/update` endpoint.
====
__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/delete-user" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Import users</h4>+++

`POST /api/rest/2.0/users/import`

Allows importing user data from external databases into ThoughtSpot.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

During this operation:

* If the specified users are not available in ThoughtSpot, the users are created and assigned a default password. The `default_password` definition in the API request is optional.
* If the `delete_unspecified_users` property is set to `true`, users not specified in the API request, excluding `tsadmin`, `guest`, `system` and `su` users, are deleted.
* If the specified user objects are already available in ThoughtSpot, the object properties of these users are modified and synchronized as per the input data in the API request.

A successful API call returns the object that represents the changes made in the ThoughtSpot system.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/import-users" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Change password</h4>+++

`POST /api/rest/2.0/users/change_password`

Allows ThoughtSpot users to change the password of their account.

__Available to all authenticated users__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/change-user-password" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Reset password</h4>+++

`POST /api/rest/2.0/users/reset_password`

Resets the password of a user account.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/reset-user-password" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Force logout</h4>+++

`POST /api/rest/2.0/users/force_logout`

Forces logout on user sessions.

[WARNING]
* Use this API with caution as it may invalidate active user sessions and force users to re-login.
* Make sure you specify the usernames or GUIDs. If you pass null values in the API call, all user sessions on your cluster become invalid, and the users are forced to re-login.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/force-logout-users" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== System

[div divider]
--
+++<h4>Get system information</h4>+++

`GET /api/rest/2.0/system`

Gets system information of your current logged-in cluster.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/system/get-system-information" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Get System Config</h4>+++

`GET /api/rest/2.0/system`

Gets details of the current configuration running on your cluster.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/system/get-system-config" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Get System Override Info</h4>+++

`GET /api/rest/2.0/system/config-overrides`

Gets details of the configuration overrides on your cluster.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/system/get-system-override-info" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update System Config</h4>+++

`POST /api/rest/2.0/system/config-update`

Updates the current configuration of your cluster.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/system/update-system-config" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Orgs

You can perform CRUD operations on Org objects if the Orgs feature is enabled on your cluster. For Org operations, cluster administration privileges are required.

[NOTE]
====
To access REST API v2.0 Playground at the Org level, make sure the *Develop* tab is enabled for Orgs on your cluster.
====

[div divider]
--
+++<h4>Search Orgs</h4>+++

`POST /api/rest/2.0/orgs/search`

Gets Org objects from ThoughtSpot. To filter the API output based on Org status, visibility, and user association, set `visibility`, `status`, and `user_identifiers` properties in your API request.

__Requires cluster administration privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/search-orgs" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create an Org</h4>+++

`POST /api/rest/2.0/orgs/create`

Creates an Org object.

__Requires cluster administration privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/create-org" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update an Org</h4>+++

`POST /api/rest/2.0/orgs/{org_identifier}/update`

Modifies the object properties of an Org.

__Requires cluster administration privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/update-org" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete an Org</h4>+++

`POST /api/rest/2.0/orgs/{org_identifier}/delete`

Deletes an Org object from ThoughtSpot.

__Requires cluster administration privileges__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/delete-org" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Tags

API endpoints for CRUD operations on tag objects and metadata association.

[div divider]
--
+++<h4>Search tags</h4>+++

`POST /api/rest/2.0/tags/search`

Gets details of tag objects from ThoughtSpot.

__Available to all authenticated users__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/tags/search-tags" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create a tag</h4>+++

`POST /api/rest/2.0/tags/create`

Creates a tag object in ThoughtSpot.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/tags/create-tag" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update a tag</h4>+++

`POST /api/rest/2.0/tags/{tag_identifier}/update`

Modifies the object properties of a tag.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/tags/update-tag" id="preview-in-playground" target="_blank">View in Playground</a>+++

--

[div divider]
--
+++<h4>Delete a tag</h4>+++

`POST /api/rest/2.0/tags/{tag_identifier}/delete`

Deletes a tag object from ThoughtSpot.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/tags/delete-tag" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Assign a tag</h4>+++

`POST /api/rest/2.0/tags/assign`

Assigns a tag to metadata objects.

__Requires edit access to the metadata object (Liveboard, saved Answer, or Worksheet)__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/tags/assign-tag" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Unassign a tag</h4>+++

`POST /api/rest/2.0/tags/unassign`

Removes the tag assigned to a metadata object.

__Requires edit access to the metadata object (Liveboard, saved Answer, or Worksheet)__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/tags/unassign-tag" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


== Groups

API endpoints for CRUD operations on groups objects and groups data import from external databases.

[div divider]
--
+++<h4>Search groups</h4>+++

`POST /api/rest/2.0/groups/search`

Gets the details of group objects from ThoughtSpot. You can get the details of a specific group or all groups available in the ThoughtSpot system. You can also filter the API output based on user association, privileges, Org ID, visibility, and group type.

__Available to all authenticated users__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/groups/search-user-groups" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create a group</h4>+++

`POST /api/rest/2.0/groups/create`

Creates a group in ThoughtSpot. This API also supports the following operations: +

* assign privileges
* add users
* define sharing visibility
* add sub-groups
* set a default Liveboard for the users in a group

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/groups/create-user-group" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update a group</h4>+++

`POST /api/rest/2.0/groups/{group_identifier}/update`

Allows modifying the object properties of a group. You can also use this API to add or remove users, groups, and privileges.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/groups/update-user-group" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete a group</h4>+++

`POST /api/rest/2.0/users/{user_identifier}/delete`

Deletes a group from ThoughtSpot.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/groups/delete-user-group" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Import groups</h4>+++

`POST /api/rest/2.0/groups/import`

Allows importing group objects from external databases into ThoughtSpot.

During the import operation:

* If the specified group is not available in ThoughtSpot, it will be added to ThoughtSpot.
* If the `delete_unspecified_groups` property is set to `true`, the groups not specified in the API request, excluding administrator and system user groups, are deleted.
* If the specified groups are already available in ThoughtSpot, the object properties of these groups are modified and synchronized as per the input data in the API request.

A successful API call returns the object that represents the changes made in the ThoughtSpot system.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/groups/import-user-groups" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Metadata

API endpoints for querying metadata objects, importing and exporting TML representation of metadata objects, and deleting metadata objects.

[div divider]
--
+++<h4>Search metadata objects</h4>+++

`POST /api/rest/2.0/metadata/search`

Gets details of metadata objects from ThoughtSpot.

* To fetch data for a metadata object, specify the object ID and type.
* To fetch data for a specific object type, for example, Liveboard or saved Answer, specify an object type from the `type` list:

** `LIVEBOARD` for Liveboards
** `ANSWER` for saved Answer object
** `CONNECTION` for data connections
** `TAG` for tag objects
** `USER` for user objects
** `USER_GROUP` for groups
** `LOGICAL_TABLE` for worksheets, tables and views.
** `LOGICAL_COLUMN` for a column of any data object such as tables, worksheets, or views.
** `LOGICAL_RELATIONSHIP` for table and worksheet joins

[NOTE]
====
Searching by metadata sub-types such as `CALENDAR_TYPE` and `FORMULA` is not supported in REST API v2.0.
====

The search metadata API allows you to define several parameters to filter the output. For example, you can filter objects created or modified by specific users, or based on the tags assigned to an object. Similarly, you can exclude or include dependent, hidden, and incomplete objects in the output.

__Requires at least view access to metadata objects. The `USER` and `USER_GROUP` metadata object queries require `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/metadata/search-metadata" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Fetch SQL query details for a Liveboard</h4>+++

`POST /api/rest/2.0/metadata/liveboard/sql`

Gets SQL query data for the visualizations on a Liveboard.

__Requires at least view access to the Liveboard object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/metadata/fetch-liveboard-sql-query" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Fetch SQL query details for an Answer</h4>+++

`POST /api/rest/2.0/metadata/answer/sql`

Gets SQL query data for a saved Answer.

__Requires at least view access to the Answer object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/metadata/fetch-answer-sql-query" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Import metadata objects</h4>+++

`POST /api/rest/2.0/metadata/tml/import`

Imports TML representation of the metadata objects into ThoughtSpot.

__Requires `DATAMANAGEMENT` (**Can manage data**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/metadata/import-metadata" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Export metadata objects</h4>+++

`POST /api/rest/2.0/metadata/tml/export`

Exports TML representation of the metadata objects from ThoughtSpot in JSON or YAML format.

__Requires `DATAMANAGEMENT` (**Can manage data**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/metadata/export-metadata" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete metadata objects</h4>+++

`POST /api/rest/2.0/metadata/delete`

Deletes a metadata object from ThoughtSpot.

__Requires edit access to metadata objects__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/metadata/delete-metadata" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Reports

API endpoints to download Liveboard or Answer from ThoughtSpot.

[div divider]
--
+++<h4>Download a Liveboard report</h4>+++

`POST /api/rest/2.0/report/liveboard`

Downloads a Liveboard and its visualizations as a PDF, CSV, XLSX, or PNG file.

__Requires `DATADOWNLOADING` (**Can download data**) privilege and view access to the Liveboard object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/reports/export-liveboard-report" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Download an Answer report</h4>+++

`POST /api/rest/2.0/report/answer`

Downloads the Answer data in PDF, CSV, PNG, or XLSX format.

__Requires `DATADOWNLOADING` (**Can download data**) privilege and view access to the Answer object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/reports/export-answer-report" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Security

API endpoints that let you share objects and fetch permission details for metadata objects.

[NOTE]
====
By default, the JSON response from the `api/rest/2.0/security/principals/fetch-permissions` and `/api/rest/2.0/security/metadata/fetch-permissions` API calls show `group_permissions` as a null object. To allow ThoughtSpot to return group permission details in the API response, the `groupWisePermissionEnabled` flag must be enabled on your instance. For more information, contact ThoughtSpot Support.
====

[div divider]
--
+++<h4>Fetch object permission details for users or groups</h4>+++

`POST /api/rest/2.0/security/principals/fetch-permissions`

Gets a list of objects that a user or group has access to. You can also specify the metadata type to fetch user permission details for Liveboards, Worksheets, or Answers.

__Requires at least view access to the metadata object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/security/fetch-permissions-of-principals" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Fetch permission details for metadata objects </h4>+++

`POST /api/rest/2.0/security/metadata/fetch-permissions`

Fetches access permission details for metadata objects. To get object access details for a user or group, specify the user or group identifiers.

__Requires at least view access to the metadata object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/security/fetch-permissions-on-metadata" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Transfer object ownership and assign author</h4>+++

`POST /api/rest/2.0/security/metadata/assign`

Assigns a new author or changes the author of a metadata object.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/security/assign-change-author" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Share metadata objects</h4>+++

`POST /api/rest/2.0/security/metadata/share`

Allows sharing metadata objects, such as Liveboards, saved Answers, and Worksheets with another user or group in ThoughtSpot.

__Requires edit access to the metadata object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/security/share-metadata" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Data

API endpoints to search data from a data source, fetch Liveboard and Answer data.

[div divider]
--
+++<h4>Search data</h4>+++

`POST /api/rest/2.0/searchdata`

Allows searching data from a data source by passing query strings in the API request.

__Requires at least view access to the data source object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/data/search-data" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Fetch Liveboard data</h4>+++

`POST /api/rest/2.0/metadata/liveboard/data`

Gets Liveboard and visualization data from ThoughtSpot.

__Requires at least view access to the Liveboard object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/data/fetch-liveboard-data" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Fetch Answer data</h4>+++

`POST /api/rest/2.0/metadata/answer/data`

Gets Answer data from ThoughtSpot. You can fetch data for saved Answers only.

__Requires at least view access to the Answer object__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/data/fetch-answer-data" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Logs

[div divider]
--
+++<h4>Fetch audit logs</h4>+++

`POST /api/rest/2.0/logs/fetch`

Gets security audit logs from the ThoughtSpot system.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/log/fetch-logs" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Version control [beta betaBackground]^Beta^

[div divider]
--
+++<h4>Search config</h4>+++

Gets Git repository connections configured on the ThoughtSpot instance.

`POST /api/rest/2.0/vcs/git/config/search`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/search-config" id="preview-in-playground" target="_blank">View in Playground</a>+++

--

[div divider]
--
+++<h4>Search Commits</h4>+++

Gets Git commit history for a given metadata object.

`POST /api/rest/2.0/vcs/git/commits/search`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/search-commits" id="preview-in-playground" target="_blank">View in Playground</a>+++

--

[div divider]
--
+++<h4>Create Local Config</h4>+++

Allows you to connect a ThoughtSpot instance to a Git repository. Use this API endpoint to connect your ThoughtSpot development and production environments to the development and production branches of a Git repository.

`POST /api/rest/2.0/vcs/git/config/create`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/create-config" id="preview-in-playground" target="_blank">View in Playground</a>+++

--

[div divider]
--
+++<h4>Update Config</h4>+++

Updates the Git repository settings configured on a ThoughtSpot instance.

`POST /api/rest/2.0/vcs/git/config/update`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/update-config" id="preview-in-playground" target="_blank">View in Playground</a>+++

--

[div divider]
--
+++<h4>Delete Config</h4>+++

Removes the connection to the Git repository.

`POST /api/rest/2.0/vcs/git/config/delete`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/delete-config" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Delete Config</h4>+++

Deletes the Git configuration details from the ThoughtSpot instance.

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/delete-config" id="preview-in-playground" target="_blank">View in Playground</a>+++

--

[div divider]
--
+++<h4>Commit branch</h4>+++

Commits the TML files of the metadata objects to the Git branch configured on your instance.

`POST /api/rest/2.0/vcs/git/branches/commit`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/commit-branch" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Revert commit</h4>+++

Reverts TML objects to a previous commit in the Git branch.

`POST /api/rest/2.0/vcs/git/branches/commit`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/revert-commit" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Validate merge</h4>+++

Validates the content of your source branch against the objects in your destination environment.

`POST /api/rest/2.0/vcs/git/branches/commit`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/validate-merge" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Deploy commit</h4>+++

Allows you to deploy a commit and publish TML content to the ThoughtSpot instance.

`POST /api/rest/2.0/vcs/git/branches/commit`

__Requires `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/version-control/deploy-commit" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


== Connections

The `Connections` API endpoints allow you to perform CRUD operations on data connection objects. ThoughtSpot users with `ADMINISTRATION` or `DATAMANAGEMENT` privilege can create a connection to any of the following types of data warehouses and let users search from these external data sources to generate the information they need:

* Amazon Redshift
* Azure Synapse
* Databricks
* Dremio
* Denodo
* Google BigQuery
* Oracle ADW
* Presto
* SAP HANA
* Snowflake
* Starburst
* Teradata
* Trino

[div divider]
--
+++<h4>Search connection</h4>+++

`POST /api/rest/2.0/connection/search`

Gets connection objects from ThoughtSpot.

__Requires `DATAMANAGEMENT` (**Can manage data**) or `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

You can send an API request to fetch details of a specific connection by specifying the connection name or GUID. You can also customize your search to filter the API response by the data warehouse type.

* To fetch details of a connection object, specify the connection object GUID or name. The `name_pattern` attribute allows passing partial text with `%` for a wildcard match.
* To get details of the database, schemas, tables, or columns from a data connection object, specify the `data_warehouse_object_type` attribute.
* To get a specific database, schema, table, or column from a connection object, define the object type in `data_warehouse_object_type` and object properties in the `data_warehouse_objects` array. For example, to search for a column, you must pass the database, schema,  and table names in the API request.
+
```
{
  "connections": [
    {
      "identifier": "b9d1f2ef-fa65-4a4b-994e-30fa2d57b0c2",
      "data_warehouse_objects": [
        {
          "database": "NEBULADEV",
          "schema": "INFORMATION_SCHEMA",
          "table": "APPLICABLE_ROLES",
          "column": "ROLE_NAME"
        }
      ]
    }
  ],
  "data_warehouse_object_type": "COLUMN"
}
```

* To include more details about connection objects in the API response, set `include_details` to `true`.
* You can also sort the output by field names and filter connections by tags.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/connections/search-connection" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Create connection</h4>+++

`POST /api/rest/2.0/connection/create`

Creates a connection to the specified data warehouse. +

__Requires `DATAMANAGEMENT` (**Can manage data**) or `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

The endpoint requires you to define connection metadata in JSON format.  The connection can be created without tables.

[#sampleJSON]
+++<h5>JSON sample for the data_warehouse_config attribute</h4>+++

The `data_warehouse_config` attribute requires you to provide connection metadata input in JSON format. The attributes may vary based on the type of data warehouse for which the connection is being created. For example, to create a connection to a Snowflake data warehouse, the following properties and metadata are required.

.JSON sample without tables
[%collapsible]
====
The following example creates an empty connection without tables. When creating a connection without tables, set the `validate` property to `false`.

[source, JSON]
----
{
   "configuration":{
      "accountName":"thoughtspot_partner",
      "user":"tsadmin",
      "password":"TestConn123",
      "role":"sysadmin",
      "warehouse":"MEDIUM_WH"
   },
   "externalDatabases":[

   ]
}
----
====

.JSON sample with tables
[%collapsible]
====
The following example creates a Snowflake connection with tables. When creating a connection with tables, you can set the `validate` property to `true`.

[source, JSON]
----
{
   "configuration":{
      "accountName":"thoughtspot_partner",
      "user":"tsadmin",
      "password":"TestConn123",
      "role":"sysadmin",
      "warehouse":"MEDIUM_WH"
   },
   "externalDatabases":[
      {
         "name":"AllDatatypes",
         "isAutoCreated":false,
         "schemas":[
            {
               "name":"alldatatypes",
               "tables":[
                  {
                     "name":"allDatatypes",
                     "type":"TABLE",
                     "description":"",
                     "selected":true,
                     "linked":true,
                     "columns":[
                        {
                           "name":"CNUMBER",
                           "type":"INT64",
                           "canImport":true,
                           "selected":true,
                           "isLinkedActive":true,
                           "isImported":false,
                           "tableName":"allDatatypes",
                           "schemaName":"alldatatypes",
                           "dbName":"AllDatatypes"
                        },
                        {
                           "name":"CDECIMAL",
                           "type":"INT64",
                           "canImport":true,
                           "selected":true,
                           "isLinkedActive":true,
                           "isImported":false,
                           "tableName":"allDatatypes",
                           "schemaName":"alldatatypes",
                           "dbName":"AllDatatypes"
                        }
                     ]
                  }
               ]
            }
         ]
      }
   ]
}
----
====

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/connections/create-connection" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Update connection</h4>+++

`POST /api/rest/2.0/connection/update`

Updates a data connection. If you are adding tables to a connection, make sure you set the `validate` property to true.

For information about the JSON input for `data_warehouse_config` attribute, refer to the examples in the  xref:rest-api-v2-reference.adoc#sampleJSON[create connection] section.

__Requires `DATAMANAGEMENT` (**Can manage data**) or `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/connections/update-connection" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Delete connection</h4>+++

`POST /api/rest/2.0/connection/delete`

Deletes a data connection.

Before deleting a connection, check if the connection has dependent objects and remove its association to the other metadata objects in ThoughtSpot.

__Requires `DATAMANAGEMENT` (**Can manage data**) or `ADMINISTRATION` (**Can administer ThoughtSpot**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/connections/delete-connection" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

== Schedules

[div divider]
--
+++<h4>Create Schedule</h4>+++

`POST /api/rest/2.0/schedules/create`

Creates a link:https://docs.thoughtspot.com/cloud/latest/liveboard-schedule[Liveboard schedule job, window=_blank].

* The description text is mandatory.  The description text appears as **Description: <your content>** in the Liveboard schedule email notifications.
* The API endpoint supports exporting Liveboard data to the recipients in CSV or PDF format. If your Liveboard has tables, you can set `file_format` to CSV to send CSV files in the email notification to the recipients. For PDF generation, you can define PDF layout options.
* To include specific visualizations, specify the visualization GUIDs in the `visualization_identifiers` array.
* You can schedule a Liveboard job to run periodically by setting frequency parameters. You can set the schedule to run daily, weekly, monthly or every n minutes or hours. The scheduled job can also be configured to run at a specific time of the day or on specific days of the week or month.
* If the `frequency` parameters are defined, you can set the time zone to a value that matches your server's time zone. For example, `US/Central`, `Etc/UTC`, `CET`. The default time zone is `America/Los_Angeles`.

__Requires at least edit access to Liveboards. To create a schedule on behalf of another user, you need  `ADMINISTRATION` (**Can administer Org**) or `JOBSCHEDULING` (**Can schedule for others**) privilege and edit access to the Liveboard__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/schedules/create-schedule" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Delete Schedule</h4>+++

Deletes a scheduled job.

__Requires at least edit access to Liveboards or `ADMINISTRATION` (**Can administer Org**) privilege__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/schedules/delete-schedule" id="preview-in-playground" target="_blank">View in Playground</a>+++
--

[div divider]
--
+++<h4>Search Schedules</h4>+++

Gets a list of scheduled jobs configured for a Liveboard. To get the details of a specific scheduled job, specify the GUID of the scheduled job.

__Requires at least view access to Liveboards__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/schedules/search-schedule" id="preview-in-playground" target="_blank">View in Playground</a>+++
--


[div divider]
--
+++<h4>Update Schedule</h4>+++

Updates a scheduled job.

The API endpoint allows you to pause a scheduled job, change the status of a paused job, and edit the properties of a schedule, such as the recipient list, frequency of the job, format of the file to send to the recipients in email notifications, PDF options, and time zone settings.

__Requires at least edit access to Liveboards. To update a schedule on behalf of another user, you need  `ADMINISTRATION` (**Can administer Org**) or `JOBSCHEDULING` (**Can schedule for others**) privilege and edit access to the Liveboard__.

+++<a href="{{previewPrefix}}/api/rest/playgroundV2_0??apiResourceId=http/api-endpoints/schedules/update-schedule" id="preview-in-playground" target="_blank">View in Playground</a>+++
--
