= REST API v2.0
:toc: true

:page-title: REST API v2.0
:page-pageid: rest-api-v2
:page-description: ThoughtSpot REST API v2.0 provides service endpoints for user management, group administration, and metadata object queries.

The REST API v2.0 framework is built upon the existing core API functionality and data models but offers several new features and enhancements.

Enhanced usability and developer experience::

With REST API v2.0, ThoughtSpot offers a user-friendly, interactive Playground to explore the endpoints, try out API requests, and view responses. The Playground provides detailed information about how to get started, authenticate to ThoughtSpot, and interact with the endpoints.
+
For more information, see xref:rest-api-v2-playground.adoc[REST Playground v2].
////
The Playground provides dynamic code samples as you switch between different languages. You can also generate code samples, and download the SDK and client libraries in different programming languages.
////

////
Language-specific SDK and client libraries::

ThoughtSpot provides Java, Python, and TypeScript SDK and client libraries. If you want to call REST APIs in a language-specific way, you can download the SDK and libraries and integrate them with your environment.
+
For more information, see xref:rest-api-sdk-libraries.adoc[REST API SDK and client libraries].
////

Token-based authentication and authorization::

To provide secure access to ThoughtSpot resources, REST API v2.0 supports the Bearer token and Trusted authentication methods. You must obtain an access token before making an API call and pass the token in the `Authorization` header in the subsequent API calls.

+
For more information, see xref:authentication.adoc[REST API v2 authentication].

Consistent request and response workflow::

With REST API v2.0, the JSON data structure for request and response payloads is standardized.

+
The REST API v2.0 supports the standard Create, Read, Update, and Delete (CRUD) operations, and the following HTTP verbs in API requests.

* **GET** to query information, such as getting system or session information
* **POST** to create new objects, add, modify, or delete object properties
+

Simplified resource collections and endpoint categories::
+
The resource endpoints are grouped logically based on the objects they operate on. The endpoint URLs are easy to understand and predictable. For example, you can find all metadata resource endpoints, including TML operations, in the `/metadata/` resource collection.

== Feature availability

Starting with 9.0.0.cl release, the REST API v2.0 Playground and API endpoints are generally available (GA) on all ThoughtSpot instances.

If you are not a ThoughtSpot user yet, you can preview the REST API v2.0 endpoints link:https://try-everywhere.thoughtspot.cloud/v2/#/everywhere/[ThoughtSpot API Playground, window=_blank] or sign up for a free trial to evaluate the API and Playground experience.

== Interoperability with REST API v1 and REST API v2[beta betaBackground]^Beta^ version

Authentication tokens generated via `POST` requests to REST API v1 endpoints can be used for authorizing REST API v2.0 requests.

The REST API v2.0 introduces several breaking changes that may affect interoperability between REST API v1 and REST API v2.0, or REST API v2[beta betaBackground]^Beta^ and REST API v2.0 versions.

We recommend using REST API v2.0 API endpoints for development and testing purposes in the initial release. ThoughtSpot will provide migration instructions when REST API v2.0 framework is fully ready to replace the REST API v1 endpoints in a production setup.

== Related information

* xref:rest-api-v2-playground.adoc[REST Playground v2]
* xref:rest-api-v2-getstarted.adoc[Get started with REST API v2]
* xref:rest-api-v2-reference.adoc[REST API v2 Reference]

////
* xref:rest-api-sdk-libraries.adoc[REST API SDK and client libraries]
////
