= REST API v2 Reference
:toc: true

:page-title: REST API Reference Guide
:page-pageid: rest-apiv2-reference
:page-description: REST API Reference

The REST v2 API endpoints[beta orangeBackground]^BETA^ are categorized based on the type of object they operate on. The REST v2 framework includes the following resource collections and endpoints.

== Session

--
`**GET** /api/rest/v2/session`

Gets details of the current session for the logged-in user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/session/login`

Signs in a user to ThoughtSpot. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /api/rest/v2/session/gettoken`

Gets an OAuth access token for a ThoughtSpot client. You must send this token in the `Authorization` header to authorize your API requests.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

`**POST** /api/rest/v2/session/revoketoken`

+++<p class="divider"> </p>+++

Revokes an existing access token assigned to a ThoughtSpot client. To make API calls, you must obtain a new access token.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /api/rest/v2/session/logout`

Logs out a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Users


--

`*POST* /api/rest/v2/user/create`

Creates a user object. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`GET /api/rest/v2/user`

Gets details of a specific user. You must provide the username or the GUID of the user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /api/rest/v2/user/update`

Modifies the properties of a user object. You must specify a username or the GUID of the user. Requires administrator privileges. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`DELETE /api/rest/v2/user/delete`

Deletes a user object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /api/rest/v2/user/search`

Gets a list of users available in the ThoughtSpot system. To filter your query, you can specify the user type, group, privileges, sharing visibility, and other such attributes. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /api/rest/v2/user/addgroup`

Assigns a user to groups. If the assigned groups have privileges configured, the user inherits these privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /api/rest/v2/user/removegroup`

Removes the groups assigned to a user. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Groups

--
`*GET* /api/rest/v2/group`

Gets details of a specific group.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/group/create`

Creates a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /api/rest/v2/group/update`

Modifies the properties of a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/api/rest/v2/group/addprivilege`

Assigns privileges to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/api/rest/v2/group/removeprivilege`

Removes privileges assigned to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**DELETE** /api/rest/v2/group/delete`

Deletes a group object. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /api/rest/v2/group/adduser`

Assigns users to a group. Requires administrator privileges.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT **/api/rest/v2/group/removeuser`

Removes one or several users assigned to a group. Requires administrator privileges.


++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++
 
`*PUT* /api/rest/v2/group/addgroup`

Adds a group to another group object. This API request creates a hierarchy of groups. The subgroups inherit the privileges assigned to the parent group.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**PUT** /api/rest/v2/group/removegroup`

Removes a group from the parent group.


++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/group/search`

Gets a list of groups created in the ThoughtSpot system. To filter your query, you can specify the group type, group name, privileges, sharing visibility, users, and other such attributes. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--

== Metadata


--
`*GET* /api/rest/v2/metadata/tag`

Gets details for the specified tag. You must specify the tag name or the GUID.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/metadata/tag/create`

Creates a tag object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /api/rest/v2/metadata/tag/update`

Modifies the properties of a tag object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/metadata/tag/assign`

Assigns a tag to one or several metadata objects. You can assign a tag to a Liveboard, answer, data object, and data connection objects.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/metadata/tag/unassign`

Removes the tag assigned to an object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*DELETE* /api/rest/v2/metadata/tag/delete`

Deletes the specified tag.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /api/rest/v2/metadata/favorite/assign`

Adds an object such as Liveboards and answers to a user's favorites list.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST ** /api/rest/v2/metadata/favorite/unassign`

Removes the specified object from the user's favorites list.  

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**GET** /api/rest/v2/metadata/homeliveboard`

Gets the details of the Liveboard that is set as a default Liveboard for the ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++
 
`**POST** /api/rest/v2/metadata/homeliveboard/assign`

Assigns a Liveboard as a default Liveboard for a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/metadata/homeliveboard/unassign`

Removes the default home Liveboard setting for a ThoughtSpot user.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /api/rest/v2/metadata/incomplete`

Gets a list of objects with incomplete metadata. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /api/rest/v2/metadata/header` [tag greenBackground]#NEW in 8.1.0.cl#

Gets header details for a specific metadata object. 

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++


+++<p class="divider"> </p>+++

`*GET* /api/rest/v2/metadata/details`

Gets details of the metadata objects. To filter the query, you can specify the metadata object type.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*GET* /api/rest/v2/metadata/vizheaders`

Gets a list of visualization headers associated with a Liveboard.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/metadata/header/search`

Gets a list of all metadata objects in the ThoughtSpot system. To filter your query, specify the metadata object type, access level, and other such attributes.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*DELETE* /api/rest/v2/metadata/delete` [tag greenBackground]#NEW in 8.1.0.cl#

Deletes the specified metadata object.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/metadata/dependency`

Gets a list of dependent metadata objects.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/metadata/tml/export`

Exports a TML object and associated metadata.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`**POST** /api/rest/v2/metadata/tml/import`

Imports one or several TML objects and object associations.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

--

== Connections 

--
`*GET* /api/rest/v2/connection` [tag greenBackground]#NEW in 8.1.0.cl#

Gets details of a specific data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/connection/create` [tag greenBackground]#NEW in 8.1.0.cl#

Creates a data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /api/rest/v2/connection/update` [tag greenBackground]#NEW in 8.1.0.cl#

Updates an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

*DELETE* /api/rest/v2/connection/delete [tag greenBackground]#NEW in 8.1.0.cl#

Deletes a data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /api/rest/v2/connection/addtable` [tag greenBackground]#NEW in 8.1.0.cl#

Adds a table to an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*PUT* /api/rest/v2/connection/removetable` [tag greenBackground]#NEW in 8.1.0.cl#

Removes a table from an existing data connection.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++

+++<p class="divider"> </p>+++

`*POST* /api/rest/v2/connection/search` [tag greenBackground]#NEW in 8.1.0.cl#

Gets details of all data connections. You can also query data for a specific connection type.

++++
<a href="{{previewPrefix}}/api/rest/playgroundV2" id="preview-in-playground" target="_blank">View in Playground</a>
++++
--