= Runtime filters
:toc: true
:toclevels: 2

:page-title: Runtime filters
:page-pageid: runtime-filters
:page-description: Apply filters to visualizations at runtime and pass them as URL parameters

Runtime filters provide the ability to apply filters to data and pass them as URL query parameters at the time of data retrieval. Runtime filters allow you to apply filters to the data returned by the REST APIs, or to the visualization and Liveboard embedded in your host application.

You can use runtime filters in the REST API calls or Visual Embed SDK to dynamically apply filters to the embedded objects in your application.

[IMPORTANT]
====
Runtime filters are passed as URL query parameters in the `GET` request methods. Make sure the filter values are URL encoded before passing them as parameters.
====

== Supported data types

You can use runtime filters on these data types:

* VARCHAR
* BIGINT
* INT
* FLOAT
* DOUBLE
* BOOLEAN
* DATE
* DATE_TIME
* TIME

[IMPORTANT]
====
For the `DATE` and `DATE_TIME` data types, you must provide the date and time values in the Epoch time format. The Epoch time is also referred to as POSIX or Unix time. Epoch time is an integer value representing the number of seconds elapsed since 1 JAN 1970 00:00:00 UTC. You may have to convert time zones to calculate the appropriate timestamp.

For example, if you want to filter data for 2020-05-22, you can specify the date value in the Epoch time format as `1590192000`, or use the following JavaScript method to calculate the timestamp:

----
new Date('2020-05-22').getTime() / 1000
----
====

== How runtime filters work

The runtime filters are specified in the request URL as parameters. To apply runtime filters, you need to embed ThoughtSpot data using one of the following methods:

* xref:visual-embed-sdk.adoc[Embed a visualization or Liveboard] using the Visual Embed SDK
* Use the xref:pinboarddata.adoc[REST API to retrieve a visualization or Liveboard]

=== Embedded Liveboard and visualizations

The Visual Embed SDK allows applying runtime filters on embedded Liveboard, visualization, and answer objects. You can apply runtime filters to answers only in the full app embed mode. In the full app embed mode, ThoughtSpot applies runtime filters on all Liveboard, visualization, and answer objects in the embedded app.

[NOTE]
====
The `SearchEmbed` SDK package does not support runtime filters.
====

The following example shows how to apply runtime filters on an embedded visualization. Here, the runtime filter is operating on the `Revenue` column to filter revenue data matching `100000`.

----
liveboardEmbed.render({
    liveboardId: '133e6c5f-e522-41a0-b0ad-b9c3b066e276',
    vizId: '28b73b4a-1341-4535-ab71-f76b6fe7bf92',
      runtimeFilters: [{
      columnName: 'Revenue',
      operator: RuntimeFilterOp.EQ,
      values: ['100000' ]
      }]
  });
----


=== Apply multiple runtime filters in the SDK

The following examples show how to apply multiple runtime filters on Liveboard visualizations using the SDK:

[#multiRuntimeFilters]
[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
            columnName: 'item type', // eg: color
            operator: RuntimeFilterOp.EQ,
            values: ['Jackets'] // eg: red
        },
        {
            columnName: 'Region',
            operator: RuntimeFilterOp.IN,
            values: ['Midwest', 'East', 'West']
        },
        {
            columnName: 'Date',
            operator: RuntimeFilterOp.EQ,
            values: ['1656680400']
        }
    ]
});
----

===== Example video

The following video shows how to apply multiple runtime filters on a Liveboard.

[div videoContainer]
--
video::./images/runtime-filters.mp4[width=100%,options="autoplay,loop"]
++++
<a href="?pageid=runtime-filters#multiRuntimeFilters"  id="preview-in-playground"> Copy sample code</a>
<a href="{{previewPrefix}}/playground/liveboard?runtimeFilters=true" id="preview-in-playground" target="_blank">Try it out in Playground</a>
</div>
++++
--

[#runtimeFilterOp]
=== Runtime filter operators

[width="100%" cols="3,7"]
[options='header']
|=====
|Operator|Example (Visual Embed SDK)

| `EQ` +
equals +
Number of values allowed: 1

a|

[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'state',
        operator: RuntimeFilterOp.EQ,
        values: ['california']
    }]
});
----

| `NE` +
does not equal +
Number of values allowed: 1
a| [source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'item type',
        operator: RuntimeFilterOp.NE,
        values: ['jackets']
    }]
});
----

| `LT` +
less than +
Number of values allowed: 1

a|
[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'revenue',
        operator: RuntimeFilterOp.LT,
        values: ['1000000']
    }]
});
----

| `LE` +
less than or equal to +
Number of values allowed: 1
a|
[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'revenue',
        operator: RuntimeFilterOp.LE,
        values: ['5000000']
    }]
});
----

| `GT` +
greater than +
Number of values allowed: 1 +
a|
[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'revenue',
        operator: RuntimeFilterOp.GT,
        values: ['1000000']
    }]
});
----
| `GE` +
greater than or equal to +
Number of values allowed: 1 +
a|
[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'revenue',
        operator: RuntimeFilterOp.GE,
        values: ['5000000']
    }]
});
----

| `CONTAINS` +
contains +
Number of values allowed: 1 +
a|
[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'item type',
        operator: RuntimeFilterOp.CONTAINS,
        values: ['Bags']
    }]
});
----

| `BEGINS_WITH` +
begins with +
Number of values allowed: 1 +
a|
[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
     runtimeFilters: [{
          columnName: 'product',
          operator: RuntimeFilterOp.BEGINS_WITH,
          values: ['travel']
     }],

});
----

| `ENDS_WITH` +
ends with +
Number of values allowed: 1 +
a| [source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'item type',
        operator: RuntimeFilterOp.ENDS_WITH,
        values: ['shirts']
    }]
});
----

| `BW_INC_MAX` +
between inclusive of the higher value +
Number of values allowed: 2 +
a| [source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'revenue',
        operator: RuntimeFilterOp.BW_INC_MAX,
        values: ['25','30']
    }]
});
----

| `BW_INC_MIN` +
between inclusive of the lower value +
Number of values allowed: 2 +
a| [source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'revenue',
        operator: RuntimeFilterOp.BW_INC_MIN,
        values: ['25','50']
    }]
});
----

| `BW_INC` +
between inclusive +
Number of values allowed: 2 +
a|
[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'sales',
        operator: RuntimeFilterOp.BW_INC,
        values: ['10','50']
    }]
});
----

| `BW` +
between non-inclusive +
Number of values allowed: 2 +
a|[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'sales',
        operator: RuntimeFilterOp.BW,
        values: ['25','50']
    }]
});
----

|`IN` +
is included in this list of values +
Number of values allowed: multiple
a|[source,javascript]
----
liveboardEmbed.render({
    liveboardId: '543619d6-0015-4667-b257-eff547d13a12',
    runtimeFilters: [{
        columnName: 'item type',
        operator: RuntimeFilterOp.IN,
        values: ['jackets', 'bags', 'shirts']
    }]
});
----
|=====

==== SDK Events

See xref:events-ref.adoc#_updateruntimefilters[UpdateRuntimeFilters] and xref:embed-events.adoc#_filters_in_embedded_ui[Filters in embedded UI].

=== Runtime filters in REST API calls

To add a runtime filter to your API call or the embedded object:

. Construct the URL for embedding the visualization or making a REST API call.
. Paste the URL into a text editor.
. Append the runtime filter to the URL, using the runtime filter operators.

The URL format for applying runtime filters to a Liveboard in a REST API call is:

----
http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/pinboarddata?id=<Liveboard_id>&col1=<column_name\>&op1=<operator\>&val1=<value\>
----

The URL format for applying runtime filters to a Liveboard visualization in a REST API call is:

----
http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/pinboarddata?id=<Liveboard_id>&vizid=%5B<visualization_id>%5D&col1=<column_name\>&op1=<operator\>&val1=<value\>
----

The following example shows the URL to access a Liveboard with a filter. Here the runtime filter is operating on the column `Color` and will only return values that equal (EQ) to `red`.

----
http://<ThoughtSpot-host>/?col1=Color&op1=EQ&val1=red#
/pinboard/e36ee65e-64be-436b-a29a-22d8998c4fae
----

The following example shows the URL for a REST API request URL with a filter. Here the runtime filter is operating on the column `Category` and returning values that are equal to `mfgr%2324`.

----
http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/pinboarddata?
id=e36ee65e-64be-436b-a29a-22d8998c4fae&col1=Category
&op1=EQ&val1=mfgr%2324
----

ThoughtSpot will try to find a matching column from the Liveboard or visualization being accessed, using the `col` field as `name`. You can add any number of filters by incrementing the parameters, for example, `col2`, `op2` and `val2`.

==== Add additional filters

You can add additional filters by incrementing the number at the end of each parameter in the runtime filter for each filter you add, for example, col2, op2, val2, and so on. To add additional filters on a particular column, you can specify multiple values by separating them with an ampersand (&) as shown in the example here:

----
val1=foo&val1=bar
----

You can also use the `IN` operator for multiple values, as shown in this example:

----
col1=<column_name>&op1=IN&val1=<value>&val1=<value>
----

The following example passes multiple variables to a single column as well as multiple columns. It shows that the data values are returned as epochs.

----
col1=region&op1=IN&val1=midwest&val1=south&val1=northeast&col2=date&op2=BET&val2=<epoch_start>&val2=<epoch_end>
----
[NOTE]
====
If the Liveboard or answer you're filtering already has one or more filters applied, the runtime filters will act as an `AND` condition. This means that the data returned must meet the conditions of all filters; those supplied in the runtime filter and those included in the Liveboard or visualization itself.
====

== Limitations of runtime filters

* Runtime filter on `DATE` or `DATE_TIME` must be specified in EPOCH time (Unix or POSIX time).
* Runtime filters do not work directly on top of tables. You must create a worksheet if you want to use runtime filters. This means that the Liveboard or visualization on which you apply a runtime filter must be created on top of a worksheet.
* If the worksheet was created from an answer (it is an aggregated worksheet), runtime filters will only work if the answer was formed using a single worksheet. If the answer from which the worksheet was created includes raw tables or joins multiple worksheets, you won't be able to use runtime filters on it. This is because of the join path ambiguity that could result.
* Runtime filters do not allow you to apply `HAVING` filters in the URL parameters.
* You cannot apply a runtime filter on a Liveboard or visualization built from tables and worksheets that have chasm traps.


