You can use the following operators when applying Runtime filters on a visualization or pinboard.

[width="50%" cols="1,2,1"]
[options='header']
|===
|Operator|Description|Number of Values

| `EQ`
| equals
| 1

| `NE`
| does not equal
| 1

| `LT`
| less than
| 1

| `LE`
| less than or equal to
| 1

| `GT`
| greater than
| 1

| `GE`
| greater than or equal to
| 1

| `CONTAINS`
| contains
| 1

| `BEGINS_WITH`
| begins with
| 1

| `ENDS_WITH`
| ends with
| 1

| `BW_INC_MAX`
| between inclusive of the higher value
| 2

| `BW_INC_MIN`
| between inclusive of the lower value
| 2

| `BW_INC`
| between inclusive
| 2

| `BW`
| between non-inclusive
| 2
|===

==== Supported data types
You can use runtime filters on these data types:

* VARCHAR
* BIGINT
* INT
* FLOAT
* DOUBLE
* BOOLEAN
* DATE
* DATE_TIME
* TIME

[IMPORTANT]
====
The `DATE` and `DATE_TIME` data type requires you to provide the date and time values in the Epoch time format, The Epoch time is also referred POSIX or Unix time. The Epoch timestamp is always in GMT/UTC time. You may have to convert time zones to calculate the appropriate timestamp.

For example, if you want to filter data for 2020-05-22, you can specify the date value in the Epoch time format as `1590192000`, or use the following JavaScript method to calculate the timestamp:

----
new Date('2020-05-22').getTime() / 1000
----
====