= Visual Embed SDK Reference
:toc: true

:page-title: Visual Embed SDK Reference
:page-pageid: js-reference
:page-description: Visual Embed SDK Reference

The ThoughtSpot Visual Embed SDK is an open source Javascript library used for embedding ThoughtSpot visualizations, Liveboards, and the entire application in web applications. The Embed SDK library allows you to connect your applications to the ThoughtSpot embedded components and programmatically import them within your application framework.

== Visual Embed SDK libraries
The link:https://github.com/thoughtspot/visual-embed-sdk[Visual Embed SDK, window=_blank] is available for download as `@thoughtspot/visual-embed-sdk` through link:https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk[NPM, window=_blank]. It exports the following classes:
////
* link:https://visual-embed-sdk.vercel.app/docs/typedoc/classes/appembed.html[AppEmbed^, window=_blank]
* link:https://visual-embed-sdk.vercel.app/docs/typedoc/classes/LiveboardEmbed.html[LiveboardEmbed, window=_blank]
* link:https://visual-embed-sdk.vercel.app/docs/typedoc/classes/searchembed.html[SearchEmbed, window=_blank]

For more specific information on Embed options and functions, see the  link:https://visual-embed-sdk.vercel.app/docs/typedoc/modules.html[Visual Embed SDK Reference Guide, window=_blank].

////
* link:{{visualEmbedSDKPrefix}}/classes/AppEmbed.html[AppEmbed^, window=_blank]
* link:{{visualEmbedSDKPrefix}}/classes/LiveboardEmbed.html[LiveboardEmbed, window=_blank]
* link:{{visualEmbedSDKPrefix}}/classes/SearchEmbed.html[SearchEmbed, window=_blank]

For more specific information on Embed options and functions, see the link:{{visualEmbedSDKPrefix}}/modules.html[Visual Embed SDK Reference Guide, window=_blank].


== Additional resources

For information on how to use the Visual Embed SDK, see xref:getting-started.adoc[Get Started].

Additional examples can be found at link:https://github.com/thoughtspot/ts_everywhere_resources[ThoughtSpot Everywhere Resources on GitHub, window=_blank].
