= Enable Search Assist
:toc: true

:page-title: Enable search assist
:page-pageid: search-assist
:page-description: Search Assist on embedded instances
:description: Enable Search Assist to demonstrate how to get construct your search query and view answers.

The Search Assist feature provides sample scenarios of searching data from a Worksheet. Your application users can use this feature to familiarize themselves with the search experience and get the answers they need.

To enable the Search Assist walkthrough on an embedded instance, the following steps are required:

* Enable Search Assist in the Visual Embed SDK
* Configure Search Assist questions and answers (__Requires `Can manage data` privilege and edit access to a worksheet__)

== Enable Search Assist in the SDK

To enable Search Assist, set the `enableSearchAssist` parameter to `true`. The following example shows how to enable Search Assist in the `SearchEmbed` SDK.

[source,JavaScript]
----
const searchEmbed = new SearchEmbed(document.getElementById('ts-embed'), {
    frameParams: {
        width: '100%',
        height: '100%',
    },
    dataSources: ['<%=datasourceGUID%>'],
    enableSearchAssist: true,
    },
});
----

++++
<a href="{{previewPrefix}}/playground/search?enableSearchAssist=true" id="preview-in-playground" target="_blank">Try it out</a>
++++


== Configure Search Assist content

By default, the Sample Retail link:https://docs.thoughtspot.com/cloud/latest/system-worksheet[system Worksheet, window=_blank] includes a Search Assist lesson with a predefined set of questions and instructions to guide your application users.

To provide Search Assist walkthrough to your users with your own data, you must create a Search Assist lesson on your Worksheet. ThoughtSpot provides sample question templates, using which you can create your own Search Assist content. Any ThoughtSpot user with `Can manage data` privilege and edit access to the Worksheet can configure a Search Assist lesson. For more information about configuring a sample search lesson, see link:https://docs.thoughtspot.com/cloud/latest/search-assist-coach[Search Assist Coach, window=_blank].

////
If Search Assist is enabled on your embedded instance, the sample queries and instructions will appear when your users log in to ThoughtSpot for the first time and go through the onboarding process.
////

== How to use Search Assist

Search Assist walks you through simple search scenarios, using data from the Search Assist lesson created for a Worksheet. If Search Assist is enabled, and your Worksheet has the Search Assist queries configured, the embedded Search page allows you to try sample search scenarios.

For example, if you are searching data from the Sample Retail Worksheet, the initial example asks *_What were Sales by Product in this year?_* and Search Assist guides you to select *_sales_* and press *Enter* on your keyboard. The search then returns the answer as a table, demonstrating your total sales.

Similarly, you can add keywords, such as *_product_* and *_this year_* to your search and press *Enter*  to get an answer with the total sales data for each product in the current year.

== Feature limitations

* Search Assist is available on instances that have ThoughtSpot Search functionality embedded using `SearchEmbed` or `AppEmbed` SDK library.
* Sample search queries and search experience walkthrough are available to users only if a Search Assist lesson is configured at the data source level.
* Search Assist lessons can be configured only on worksheets.
* To configure a Search Assist lesson on a Worksheet, make sure you have embedded the ThoughtSpot *Data* tab in your host app.

== Related resources

* link:https://docs.thoughtspot.com/cloud/latest/search-assist-coach[Search Assist Coach, window=_blank]
* link:https://docs.thoughtspot.com/cloud/latest/search-assist[Search Assist, window=_blank]