= Security settings
:toc: true

:page-title: Security settings
:page-pageid: security-settings
:page-description: Security settings for embedding

Before you integrate ThoughtSpot content into your web application, configure security settings on ThoughtSpot to allow your application users to access the embedded content from web browsers. 
To configure security settings for embedding on the Developer portal, you need administrator or developer privileges. 

[#csp-viz-embed-hosts]
== Add CSP visual embed host domains
To allow your host domain to set the `frame-ancestors` CSP policy header and embed a ThoughtSpot object within your application frame, add your domain as a CSP visual embed host. 

To add a visual embed host:

. Log in to your ThoughtSpot application instance.
. Click the *Develop* tab.
. Go to *Customizations*, click *Security settings*.
. In the *CSP visual embed hosts* text box, add one or several domains that you want to use to set `frame-ancestors` CSP policy header.
+
You can add multiple domains as comma-separated values.
. Click *Save changes*.

[#csp-connect-src]
== Allow domains for CSP connect-src
If you plan to create custom actions with URL targets, you must add these URLs to the `CSP connect-src` list. This allows JavaScript events that the custom action URL triggers when a user clicks the action in the ThoughtSpot UI. 

. Log in to your ThoughtSpot application instance.
. Click the *Develop* tab.
. Go to *Customizations*, click *Security settings*.
. In the *CSP connect-src domains* text box, add one or several domains for the URLs that you want to invoke when triggering custom actions.
+
You can add multiple domains as comma-separated values.
. Click *Save changes*.

[#cors-hosts]
== Allow domains for CORS
When you embed ThoughtSpot into your web pages, your host application calls ThoughtSpot from your Web page, portal, or application. If your host application and ThoughtSpot are in different domains, you must enable Cross-Origin HTTP Requests (CORS) for these domains to allow secure data exchange.

The CORS configuration for your cluster controls which domains can access and modify your embedded content. It also prevents code copying and deployment by unauthorized sites. For example, if your website is hosted on the `example.com` domain, you must enable CORS for that domain to allow your  application users to access the embedded content. Similarly, to test your code locally, you can add the domain for your local server, such as `\http://localhost:8080`. If you have added a localhost server, ThoughtSpot recommends that you disable the localhost access after testing.

To whitelist client application domains for CORS, follow these steps:

. Log in to your ThoughtSpot application instance.
. Click the *Develop* tab.
. Under *Customizations*, click *Security settings*.
. In the *CORS whitelisted domains* text box, add the domains to the CORS whitelist.
+
* You can add multiple domains as comma-separated values.
* If you want to use REST APIs, make sure you add the client application domain from which you want to send API requests.
. Click *Save changes*.

[NOTE]
After you add your domain as a CORS host, the `Access-Control-Allow-Origin` header is added in the API responses sent by the ThoughtSpot application.

== Enable browser support for embedding

ThoughtSpot supports rendering embedded content in the following web browsers: 

* Google Chrome
* Microsoft Edge
* Mozilla Firefox
* Opera
* Safari

As a security measure, most browsers allow cookies only when they originate from the same domain name as the main application URL. Some browsers like Safari and Firefox block cookies from third-party content provider sites by default.

To avoid this issue, you might want to host your embedded ThoughtSpot instance in the same domain as its parent application. To customize the ThoughtSpot domain URL for your instance, contact ThoughtSpot Support. For more information, see xref:custom-domain-configuration.adoc[Custom domain configuration].

[NOTE]
====
Google Chrome 80 or later versions use the `SameSite` cookie attribute to disable the use of third-party content.  
For third-party application integrations that rely on cookies, the `SameSite` cookie attribute must be set to `None`. This setting is enabled by default on ThoughtSpot cloud instances.
====
////
If you do not want to customize your domain, you may need to enable third-party cookies and cross-site tracking on your browser:

 * On Safari, go to *Preferences* > *Privacy* and clear the *Prevent cross-site tracking* checkbox. 
 * On Firefox, go to *Preferences* > *Privacy & Security* > *Enhanced Tracking Protection* and allow cross-site cookies.
 
If the embedded content is not rendered despite these configuration changes, contact ThoughtSpot Support. 
////




 