= Session API
:toc: true

:page-title: Session API
:page-pageid: session-api
:page-description: Session API


The Session APIs enable you to manage the sessions of ThoughtSpot users.

== Log in a user

Use this API to authenticate and log in a user.

=== Resource URL
----
POST /tspublic/v1/session/login
----
=== Request Parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`username`|string|Username of the user account.
|password|string|The password of the user account.
|rememberme|boolean|A flag to remember the user session. The system default is `false`.
|====

=== Example requests

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'username=test&password=fhfh2323bbn&rememberme=false' 'https://<instance>/callosum/v1/tspublic/v1/session/login'
----

.Request URL
----
https://<base-uri>/tspublic/v1/session/login
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description 
|**200**|No response was specified 
|**204**|Successful login 
|**401**|Login failure/unauthorized 
|===

== Log out a user

Use this API to log out a current user from an existing session.
 

=== Resource URL

----
POST /tspublic/v1/session/logout
----

=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<base-uri>/callosum/v1/tspublic/v1/session/logout'
----

.Request URL
----
https://<base-uri>/callosum/v1/tspublic/v1/session/logout
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description 
|**200**|No response was specified 
|**204**|Successful logout 
|**401**|Logout failure/unauthorized 
|===
////
## Error Codes
<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
   <tr> <td><code>10000</code></td>  <td>Internal server error.</td> <td><code>500</code></td></tr>
    <tr> <td><code>10002</code></td>  <td>Bad request. Invalid parameter values.</td> <td><code>400</code></td></tr>
    <tr> <td><code>10003</code></td>  <td>Login or logout failure. Unauthorized.</td><td><code>401</code></td></tr>
  </tbody>
</table>
////
