= Session APIs
:toc:
:toclevels: 1

:page-title: Session API
:page-pageid: session-api
:page-description: To log in to ThoughtSpot and create user sessions, use the session API endpoints

The Session APIs allow ThoughtSpot users to authenticate and manage their sessions.

== Supported operations
include::{path}/session-api-list.adoc[]

=== Required permissions

You require ThoughtSpot login credentials to create a session object and obtain a login token.

[#session-login]
== Sign in as a ThoughtSpot user (Basic authentication)

include::{path}/log-in-api.adoc[]


[#session-logout]
== Log out of a user session

include::{path}/log-out-api.adoc[]


[#session-authToken]
== Obtain a token for trusted authentication

include::{path}/auth-token-api.adoc[]


[#session-loginToken]
== Authenticate and log in with a token (Trusted authentication)
include::{path}/login-token-api.adoc[]


[#session-info]
== Get session information

To get the session information for the current logged-in user on a given ThoughtSpot cluster, send a `GET` request to the `/tspublic/v1/session/info` endpoint.

=== Resource URL
----
GET /tspublic/v1/session/info
----

=== Example request

.cURL
[source, cURL]
----
curl -X GET \
--header 'Accept: application/json' \
--header 'X-Requested-By: ThoughtSpot' \
'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/info'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/info
----

=== Example response

If the operation is successful, the API returns a response with the session information and the current configuration of the cluster.

[source,JSON]
----
{
  "userName": "tsuser1",
  "userDisplayName": "Administrator",
  "userEmail": "tsuser1@thoughtspot.com",
  "userCreatedTime": 1354006445722,
  "userExpirationTime": 1634345144438,
  "userGUID": "59481331-ee53-42be-a548-bd87be6ddd4a",
  "apiVersion": "v1",
  "canChangePassword": true,
  "isSystemUser": false,
  "logicalModelVersion": 401,
  "userGroupMask": 6,
  "privileges": [
    "ADMINISTRATION",
    "USERDATAUPLOADING",
    "DATADOWNLOADING",
    "DATAMANAGEMENT",
    "SHAREWITHALL",
    "A3ANALYSIS"
  ],
  "expirationTime": 1632154574,
  "authToken": "gv4HjljdCZKbN4LMEHNn0p7ct12/4KSaCwKDfu/UVnA=",
  "locale": "en_GB",
  "timezone": "UTC",
  "dateFormat": {
    "formatPattern": "dd/MM/yyyy"
  },
  "timeFormat": {
    "formatPattern": "HH:mm:ss"
  },
  "dateTimeFormat": {
    "formatPattern": "dd/MM/yyyy HH:mm"
  },
  "integerFormat": {},
  "decimalFormat": {},
  "clientState": {
    "preferences": {
      "HOMEPAGE_EUREKA": true,
      "PANEL_STATE": "EXPANDED",
      "sageDataSource": [
        "8eaf2704-9754-4c48-830d-27e5317b2c64",
        "b0248372-5e68-4815-8682-67715456efb2"
      ],
      "OPEN_ANSWER_EDIT_PANEL": "VIZ_EDITOR"
    },
    "tips": {
      "chartConfigChipTip": true
    }
  },
  "configInfo": {
    "highCardinalityMaxDataSize": 20000,
    "fetchPivotSummaryFromBackend": true,
    "vizRenderingQueueTimeoutMS": 30000,
    "enableColumnSummariesByDefault": true,
    "isAnswerV2OnByDefault": false,
    "defaultChartDataSize": 5000,
    "maxFilterValues": 10000,
    "useDomainQualifiedName": true,
    "enableInstantSearch": false,
    "defaultFilterNonCascading": false,
    "pinboardFilterConfiguratorDisabled": false,
    "isAnswerUndoStackEnabled": false,
    "answerV2Experience": true,
    "enablePinboardV2": false,
    "enableCJA": false,
    "blinkHelpConfigList": [
      {
        "enabled": true,
        "title": "Keywords",
        "id": "BLINK_KEYWORDS",
        "url": "https://cloud-docs.thoughtspot.com/{versionNameForLink}/reference/keywords.html",
        "iconFilePath": ""
      },
      {
        "enabled": true,
        "title": "Release notes",
        "id": "BLINK_RELEASE_NOTES",
        "url": "https://cloud-docs.thoughtspot.com/{versionNameForLink}/release/notes.html",
        "iconFilePath": ""
      },
      {
        "enabled": true,
        "title": "Documentation",
        "id": "BLINK_DOCUMENTATION",
        "url": "https://cloud-docs.thoughtspot.com/{versionNameForLink}",
        "iconFilePath": ""
      }
    ],
    "blinkActionConfigList": [],
    "embedActionConfigList": [
      {
        "id": "598450a5-c402-4dcb-a127-8797bcda378f",
        "name": "view report",
        "version": "v2",
        "type": "CALLBACK",
        "detail": {
          "link": "",
          "function": "view-report",
          "authSelect": "NONE",
          "authToken": "",
          "encodeUser": "",
          "apiKey": "X-API-KEY",
          "apiValue": "",
          "additionalUrlHeaders": "{}"
        },
        "actionAssociationMap": {
          "ANSWER": {
            "087f51a0-f352-4497-b39a-e69ea8b4d5a1": {
              "enabled": "true",
              "context": "NONE"
            }
          }
        },
        "context": "NONE",
        "availability": [
          "GLOBAL"
        ]
       },
}
----


=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful operation.
|===



[#orgSwitch]
== Switch between Orgs

If your ThoughtSpot instance has multiple Orgs, you can switch between Orgs by using the `/tspublic/v1/session/orgs` endpoint.

Only the cluster administrator and users that belong to multiple Orgs can switch between the Orgs.

=== Resource URL
----
PUT /tspublic/v1/session/orgs
----

=== Request parameters
[width="100%" cols="1,4"]
[options='header']
|===
|Form parameter|Description
|`orgid` a|__Integer__. ID of the Org object. The org ID `0` indicates `Primary Org`. To switch to another Org, specify the Org ID.   +
To know the Org IDs of the Orgs that you can access, send a GET request to the `/tspublic/v1/session/orgs` endpoint.
|===

=== Example request

.cURL

[source, cURL]
----
curl -X PUT \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
-d 'orgid=-1' \
'http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/orgs'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/orgs
----

=== Example response
If the API request is successful, ThoughtSpot returns the 204 response code:

----
Response Code
204
----

=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**204** | Successful operation
|**400**| Invalid parameter
|**403**| Unauthorized request
|===

[#getOrgs]
== Get Orgs for the logged-in user

To get a list of Orgs for the current logged-in user, send a `GET` request to the `/tspublic/v1/session/orgs` API endpoint. +

* If the logged-in user is a cluster administrator, the API returns all active Orgs. +
* If the logged-in user belongs to more than one Org, the API returns all the active Orgs to which the user belongs.

=== Resource URL
----
GET /tspublic/v1/session/orgs
----

=== Request parameters
[width="100%" cols="1,4"]
[options='header']
|===
|Query parameter|Description
|`batchsize`  __Optional__ |__Integer__. The batch size of the Org objects returned in the API response. The system default is -1. A value of -1 implies all items starting from the offset value.
|`offset` __Optional__ |__Integer__. The batch offset value that indicates the index point starting from which the list of Org objects are retrieved. The system default is -1, which implies the first item in the list.
|===

=== Example request

.cURL
[source, cURL]
----
curl -X GET \
--header 'Accept: application/json' \
'http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/orgs?batchsize=-1&offset=-1'
----

.Request URL
----
http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/orgs?batchsize=-1&offset=-1
----

=== Example response

If the API request is successful, ThoughtSpot returns a list of active Orgs for the logged-in user:

[source,JSON]
----
{
  "orgs": [
    {
      "orgId": 0,
      "orgName": "Primary",
      "description": "Primary Org",
      "allUserGroupId": "b25ee394-9d13-49e3-9385-cd97f5b253b4",
      "defaultAdminUserGroupId": "d0326b56-ef23-4c8a-8327-a30e99bcc72b",
      "isActive": true
    },
    {
      "orgId": 1776311864,
      "orgName": "my-org1",
      "description": "",
      "allUserGroupId": "a4ef5fe2-0f90-4632-bd2c-d447428495b8",
      "defaultAdminUserGroupId": "203182f3-3ae1-422f-ae65-30c72f92b665",
      "isActive": true
    },
    {
      "orgId": 255226812,
      "orgName": "my-org2",
      "description": "",
      "allUserGroupId": "d15f3347-1e3a-48a9-bbb5-c31c368b054e",
      "defaultAdminUserGroupId": "1ce55b07-42f1-434f-b1e5-a71b2f78289d",
      "isActive": true
    },
  ],
  "canAdministerAllOrgs": true,
  "currentOrgId": 0
}
----

=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**204** | Successful operation
|**403**| Unauthorized request
|===

[#getOrgsForUser]
== Get Orgs for a specific user

To get a list of Orgs for a specific user, send a `GET` request to the `tspublic/v1/session/orgs/users/{userid}` API endpoint.


=== Resource URL
----
GET /tspublic/v1/session/orgs/users/{userid}
----

=== Request parameters
[width="100%" cols="1,1,4"]
[options='header']
|===
|Parameter|Type|Description
|`userid` |Path parameter|__String__. GUID of the user.
|`orgScope`|Query|__String__. The Org scope. Specify `ALL` to set the Org scope to all Orgs.
|===

=== Example request

.cURL
[source, cURL]
----
curl -X GET \
--header 'Accept: application/json' \
'http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/orgs/users/59481331-ee53-42be-a548-bd87be6ddd4a?orgScope=ALL'
----

.Request URL
----
http://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/orgs/users/59481331-ee53-42be-a548-bd87be6ddd4a?orgScope=ALL
----

=== Example response

If the API request is successful, ThoughtSpot returns a list of active Orgs for the specified user GUID:

[source,JSON]
----
{
  "orgs": [
    {
      "orgId": 255226812,
      "orgName": "Primary",
      "description": "Primary Org",
      "isActive": true
    }
  ],
  "canAdministerAllOrgs": false,
  "currentOrgId": 255226812
}
----

=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**204** | Successful operation
|**400**| Invalid parameter
|**403**| Unauthorized request
|===

[#set-home-liveboard]
== Set a home Liveboard
To set a Liveboard as a home Liveboard for a user account, send a `POST` request to the `/tspublic/v1/session/homepinboard` API endpoint. If a home Liveboard is configured for a user account, ThoughtSpot displays it as the default home page when the user logs in.

=== Resource URL
----
POST /tspublic/v1/session/homepinboard
----
=== Request parameters
[width="100%" cols="1,4"]
[options='header']
|===
|Form parameter|Description
|`id`|__String__. GUID of the Liveboard to be set as a home Liveboard.
|`userid` __Optional__|__String__. GUID of the user account for which you want to set the home Liveboard. If the `userid` attribute is not defined, ThoughtSpot sets the home Liveboard of the currently logged-in user.
|===
=== Example request

.cURL
[source, cURL]
----
curl -X POST \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
--header 'X-Requested-By: ThoughtSpot' \
-d 'id=7a9a6715-e154-431b-baaf-7b58246c13dd&userid=59481331-ee53-42be-a548-bd87be6ddd4a' \ 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard
----

=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**204**|The specified Liveboard is set as a home Liveboard.
|**403**|The Liveboard with the given ID is not accessible.
|**401**|Unauthorized request or invalid token.
|**404**|The specified Liveboard was not found.
|===

[#get-home-liveboard]
== Get details of the home Liveboard

To get the GUID of Liveboard that is currently set as a `home Liveboard`, send a `GET` request to the `/tspublic/v1/session/homepinboard` API endpoint.

=== Resource URL
----
GET /tspublic/v1/session/homepinboard
----

=== Example request

.cURL
[source, cURL]
----
curl -X GET \
--header 'Accept: text/plain' \
--header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard
----

=== Example response
If the home Liveboard is set in the currently logged-in user's account, the API returns the GUID of the Liveboard set as a home Liveboard:

----
7a9a6715-e154-431b-baaf-7b58246c13dd
----

=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful operation.
|===

[#del-home-liveboard]
== Remove a home Liveboard
To remove the home Liveboard setting from the currently logged-in user's account, send a `DELETE` request to the `/tspublic/v1/session/homepinboard` API endpoint.

=== Resource URL
----
DELETE /tspublic/v1/session/homepinboard
----

=== Example request

.cURL
[source, cURL]
----
curl -X DELETE \
--header 'Accept: application/json' \
--header 'X-Requested-By: ThoughtSpot' \
'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard
----

=== Example response
If the home Liveboard is set in the currently logged-in user's account, the API returns the following response:

----
Response Code
200
----
=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful operation.
|===
