= Session API
:toc: true

:page-title: Session API
:page-pageid: session-api
:page-description: Session API


The Session APIs enable you to manage the sessions of existing users.

== Managing login

Use this API to authenticate and login a user.

=== Resource URL

`post` /tspublic/v1/session/login

=== Request Parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`username`|string|Username of the user.
|password|string|Password of the user.
|rememberme|boolean|A flag to remember the user session. The system default is `false`.
|====

=== Request Example

.cURL
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'username=test&password=fhfh2323bbn&rememberme=false' 'https://<instance>/callosum/v1/tspublic/v1/session/login'
----

.Request URL
----
https://<base-uri>/tspublic/v1/session/login
----

=== Response Example

----
Not applicable
204 - Successful login
----

== Managing logout

Use this API to log a current user out of an existing session.
The user details are captured from the active user session.

=== Resource URL

----
POST /tspublic/v1/session/logout
----

=== Request Example

.cURL
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<instance>/callosum/v1/tspublic/v1/session/logout'
----

.Request URL
----
https://<instance>/callosum/v1/tspublic/v1/session/logout
----

=== Response Example

----
Not applicable
204 - Successful logout
----

////
## Error Codes
<table>
   <colgroup>
      <col style="width:20%" />
      <col style="width:60%" />
      <col style="width:20%" />
   </colgroup>
   <thead class="thead" style="text-align:left;">
      <tr>
         <th>Error Code</th>
         <th>Description</th>
         <th>HTTP Code</th>
      </tr>
   </thead>
   <tbody>
   <tr> <td><code>10000</code></td>  <td>Internal server error.</td> <td><code>500</code></td></tr>
    <tr> <td><code>10002</code></td>  <td>Bad request. Invalid parameter values.</td> <td><code>400</code></td></tr>
    <tr> <td><code>10003</code></td>  <td>Login or logout failure. Unauthorized.</td><td><code>401</code></td></tr>
  </tbody>
</table>
////
