= Session APIs

:page-title: Session API
:page-pageid: session-api
:page-description: Session API

The Session APIs allow ThoughtSpot users to authenticate and manage their sessions.

[width="100%" cols="1,2"]
|===
|`xref:session-api.adoc#session-login[**POST** /tspublic/v1/session/login]`|Signs a user into ThoughtSpot.
|`xref:session-api.adoc#session-logout[**POST** /tspublic/v1/session/logout]`|Logs a user out of the current session. 
|`xref:session-api.adoc#session-authToken[**POST** /tspublic/v1/session/auth/token]`|Returns an authentication token for a given ThoughtSpot user if trusted authentication is enabled. 
|`xref:session-api.adoc#session-loginToken[**GET** /tspublic/v1/session/login/token]`|Logs in an authenticated user.
|`xref:session-api.adoc#set-home-pinboard[**POST** /tspublic/v1/session/homepinboard]`|Sets a a specific pinboard as a home pinboard.
|`xref:session-api.adoc#get-home-pinboard[**GET** /tspublic/v1/session/homepinboard]`|Returns the GUID of the pinboard that is set as a home pinboard for the current logged-in user.
|`xref:session-api.adoc#del-home-pinboard[**GET** /tspublic/v1/session/homepinboard]`|Removes the home pinboard settings for the current logged-in user.
|===

[#session-login]
== Sign in a ThoughtSpot user
If you are a ThoughtSpot user, you can programmatically sign in to ThoughtSpot using the `/tspublic/v1/session/login` API.

=== Resource URL
----
POST /tspublic/v1/session/login
----
=== Request Parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`username`|string|Username of the user account.
|`password`|string|The password of the user account.
|`rememberme`|boolean|A flag to remember the user session. The system default is `false`.
|====

=== Example requests

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'username=test&password=fhfh2323bbn&rememberme=false' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/login'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/login
----
=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|User logged in
|**204**|Successful login
|**401**|Login failure/unauthorized request
|===
[#session-logout]
== Log out a user

To log out of the current user session, use the `/tspublic/v1/session/logout` API.

=== Resource URL
----
POST /tspublic/v1/session/logout
----

=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/logout'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/logout
----

=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|User logged out
|**204**|Successful logout of user
|**401**|Logout failure/unauthorized request
|===
[#session-authToken]
== Obtain an authentication token
ThoughtSpot supports the trusted authentication method, which is also known as token-based authentication. In the trusted authentication method, ThoughtSpot users are authenticated by an external authentication server.
When ThoughtSpot receives a request from a trusted authentication service, it returns an authentication token to allow authenticated users to access ThoughtSpot content.
If you have enabled xref:trusted-authentication.adoc#trusted-auth-enable[trusted authentication] on ThoughtSpot and obtained a secret key, you can use the `/tspublic/v1/session/auth/token` API to get an authentication token for a ThoughtSpot user. 
=== Resource URL
----
POST /tspublic/v1/session/auth/token
----
=== Request parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`secret_key`|string|The secret key string provided by the ThoughtSpot application server. This secret key is generated after you enable trusted authentication in ThoughtSpot.
|`username`|string|The user name of the user configured in ThoughtSpot.
|`access_level`|string a|User access permission. Valid values are:

* `FULL` - Allow full access.
* `REPORT_BOOK_VIEW` - Allow view access to visualizations.
|`id`|string|GUID of the ThoughtSpot object. This parameter is required if the  `access_level` is set to `REPORT_BOOK_VIEW`.
|====

=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/auth/token'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/auth/token
----

=== Example response
If the request parameters are assigned correct values, the API returns an authentication token for the user.

----
JHNoaXJvMSRTSEEtMjU2JDUwMDAwMCRPMFA2S0ZlNm51Qlo4NFBlZUppdzZ3PT0kMnJKaSswSHN6Yy96ZGxqdXUwd1dXZkovNVlHUW40d3FLMVdBT3hYVVgxaz0
----
=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|The authentication token is generated successfully.
|**401**|Unauthorized request or invalid token.
|**500**|Token-based trusted authentication is not enabled on ThoughtSpot.
|===

[#session-loginToken]
== Authenticate and log in a user 
If trusted authentication is enabled on ThoughtSpot, the authentication server obtains an authentication token from ThoughtSpot on a user's behalf. You can use this token to log in a ThoughtSpot user and provide access to the requested content. 
To programmatically log in an authenticated user, use the `/tspublic/v1/session/login/token` API. 

=== Resource URL
----
GET /tspublic/v1/session/login/token
----

=== Request parameters

[width="100%" cols="1,1,4"]
[options='header']
|====
|Query Parameter|Data Type|Description
|`username`|string|The user name of the user who requested access to ThoughtSpot.
|`auth_token`|string a|The authentication token obtained from ThoughtSpot.
|`redirect_url`|string|The URL to which you want to redirect the user after a successful login. This URL is fully encoded and includes the authentication token obtained for the user. 

For example, if the user has requested access to a specific visualization on a pinboard, the redirect URL includes the domains to which the user is redirected, the auth token string obtained for the user, visualization ID, and pinboard ID as shown here. 

`https://<redirect-domain>/?authtoken=<user_auth_token>&embedApp=true&primaryNavHidden=true#/embed/viz/<pinboard_id>/<viz-id>`
|====

=== Example request

.cURL
----
curl -X GET --header 'Accept: text/html' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/login/token?username=tsuser&auth_token=JHNoaXJvMSRTSEEtMjU2JDUwMDAwMCRPMFA2S0ZlNm51Qlo4NFBlZUppdzZ3PT0kMnJKaSswSHN6Yy96ZGxqdXUwd1dXZkovNVlHUW40d3FLMVdBT3hYVVgxaz0&redirect_url=https://<ThoughtSpot-Host>/?embedV2=true#/pinboard/7a9a6715-e154-431b-baaf-7b58246c13dd%2F'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/login/token?username=tsadmin&auth_token=JHNoaXJvMSRTSEEtMjU2JDUwMDAwMCRPMFA2S0ZlNm51Qlo4NFBlZUppdzZ3PT0kMnJKaSswSHN6Yy96ZGxqdXUwd1dXZkovNVlHUW40d3FLMVdBT3hYVVgxaz0&redirect_url=https://<ThoughtSpot-Host>/?embedV2=true#/pinboard/7a9a6715-e154-431b-baaf-7b58246c13dd%2F
----

=== Example response
On successful login, the API returns the application details. 
The following example shows a partial output.
[source, HTML]
----
<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width">
    <meta charset="utf-8">
    <meta name="description" content="">
        <!-- Preloading Fonts -->
        <link rel="preload" href="node_modules/@thoughtspot/radiant/widgets/resources/font/optimo/Plain-Light.otf"
              as="font" crossorigin>
        <link rel="preload" href="node_modules/@thoughtspot/radiant/widgets/resources/font/bb-roller/BB-Roller-Mono-Regular-fontlab.ttf"
              as="font" crossorigin>
        <link rel="preload" href="node_modules/@thoughtspot/radiant/widgets/resources/font/optimo/Plain-Regular.otf"
              as="font" crossorigin>
        <link rel="preload" href="node_modules/@thoughtspot/radiant/widgets/resources/font/optimo/Plain-Medium.ttf"
              as="font" crossorigin>
        <link rel="preload" href="node_modules/@thoughtspot/radiant/widgets/resources/font/optimo/Plain-LightIta.otf"
              as="font" crossorigin>
        <link rel="modulepreload" href="https://cdn.skypack.dev/react">
	<link rel="modulepreload" href="https://cdn.skypack.dev/react-dom">
    <link rel="stylesheet" href='(none)'>
    <style>
        .bk-app-loading-indicator {
    position: absolute;
    height: 100%;
    width: 100%;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    flex-direction: row;
    -ms-flex-direction: row;
    -webkit-flex-direction: row;
    align-items: stretch;
    -webkit-align-items: stretch;
    -ms-flex-align: stretch;
    max-width: 100%;
    box-sizing: border-box;
}
    </style>
</head>
<body>
    <div class="bk-app-loading-indicator">
        <div class="load-wrap">
    <div>
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
    </div>
</div>
    </div>

    <script type="text/javascript" id="app-init">
        // Top level namespace var declaration
        var blink = {};
        // Object to store all CDN related variables
        blink.cdnAutoUpdateConfig = {};
        // Location of Eureka Base URL
        blink.eurekaBasePath = 'https://d2if2nytu6z4ml.cloudfront.net';
        // Keys set in blink.env will override / create flags
        blink.env = {
            dev: false
        };
        blink.commitId = '600e99e3c3ebe1b4d89abd99e920c6939616f54c';
        blink.gitBranch = '(HEAD detached at 600e99e3c3e)';
        blink.buildTimeStamp = 'Thu May 20 2021 09:25:58';
        blink.depsPath = 'node_modules';
        blink.localeSuffix = '.' + blink.commitId;
        blink.metrics = {
            scriptsLoadStartTime: window.performance.now()
        };

        function createNode(tag, attributes) {
            var node = document.createElement(tag);
            Object.keys(attributes).forEach(function (key) {
                return node[key] = attributes[key];
            });
            return node;
        }
        function appendNodesToDom(nodes) {
            var fragment = document.createDocumentFragment();
            nodes.forEach(function (node) {
                return fragment.appendChild(node);
            });
            document.getElementsByTagName('body')[0].appendChild(fragment);
        }
        function fetchAndLoadRelease(rcLink) {
            fetch(rcLink).then(function (response) {
                return response.json()
            }).then(function (releaseJson) {
                blink.cdnAutoUpdateConfig.evaluationMode = true;
                blink.cdnAutoUpdateConfig.currentReleaseVersion = releaseJson.releaseVersion;
                blink.cdnAutoUpdateConfig.cdnBuildTimestamp = releaseJson.buildTimestamp;
                blink.cdnAutoUpdateConfig.cdnBasePath = releaseJson.basePath;
                var nodes = releaseJson.resources.css.map(function (cssScript) {
                    return createNode('link', {
                        type: 'text/css',
                        rel:'stylesheet',
                        href: [blink.cdnAutoUpdateConfig.cdnBasePath, cssScript].join('/')
                    })
                });

                nodes = nodes.concat(releaseJson.resources.js.map(function (script) {
                    return createNode('script', {
                        src: [blink.cdnAutoUpdateConfig.cdnBasePath, script].join('/'),
                        async: false
                    });
                }));
                nodes = nodes
                    .concat(releaseJson.resources.modules.map(function (module, index) {
                        return createNode('script', {
                            async: false,
                            type: 'module',
                            src: [blink.cdnAutoUpdateConfig.cdnBasePath, module].join('/'),
                            id: 'module-script' + index
                        });
                    }));
                nodes = nodes
                    .concat(releaseJson.resources.noModule.map(function (noModule, index) {
                        return createNode('script', {
                            async: false,
                            noModule: true,
                            src: [blink.cdnAutoUpdateConfig.cdnBasePath, noModule].join('/'),
                            id: 'nomodule-script' + index
                        });
                    }));
                appendNodesToDom(nodes);
            }, function (error) {
                appendNodesToDom([createNode('div', {
                    innerText: 'unable to fetch: ' + rcLink +
                    'Link does not exist'
                })]);
            });
        }
        var ua = window.navigator && window.navigator.userAgent;
        var trident = ua && ua.indexOf('Trident/');
        var edge = ua && ua.indexOf('Edge');
        var safari = ua && ua.indexOf('Safari');
        var chrome = ua && ua.indexOf('Chrome');

    </script>
    
        <link type="text/css" rel="stylesheet" href="resources/css/all.min.90630a0a141abec0.css">

        <script src="js/lib.min.bcef417e2b193abd.js"></script>
        <script src="js/templates.133e974a290769f7.js"></script>
        <script src="js/all.min.b4be265ed3041f65.js"></script>
        <script type="module" src="js/module/app-ad896427.js
" id="module-script"></script>
        <script nomodule src="js/nomodule/app.js" id="nomodule-script"></script>
    <app-controller class="bk-app-controller-container"></app-controller>
</body>
</html>
----

=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|The user is logged in successfully.
|**302**|The user is redirected to the specified URL. 
|**401**|Unauthorized request or invalid token.
|===

[#set-home-pinboard]
== Set a pinboard as a home pinboard
To set a pinboard as a home pinboard for a user account, send a `POST` request to the `/tspublic/v1/session/homepinboard` API endpoint. If a home pinboard is configured for a user account, ThoughtSpot displays it as the default home page when the user logs in.  

=== Resource URL
----
POST /tspublic/v1/session/homepinboard
----
=== Request parameters
[width="100%" cols="1,1,4"]
[options='header']
|===
|Form Parameter|Data Type|Description
|`id`|string|GUID of the pinboard to be set as a home pinboard.
|`userid` __Optional__|string|GUID of the user account for which you want to set the home pinboard. If the `userid` attribute is not defined, ThoughtSpot sets the home pinboard of the current logged in user.
|===
=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'id=7a9a6715-e154-431b-baaf-7b58246c13dd&userid=59481331-ee53-42be-a548-bd87be6ddd4a' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard
----

=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful operation.
|**204**|The specified pinboard is set as a home pinboard. 
|**403**|The pinboard with the given ID is not accessible.
|**401**|Unauthorized request or invalid token.
|**404**|The specified pinboard was not found.
|===

[#get-home-pinboard]
== Get details of the home pinboard
To get the pinboard GUID that is set as home pinboard in the current logged in user account, send a GET request to the `/tspublic/v1/session/homepinboard` API endpoint.

=== Resource URL
----
GET /tspublic/v1/session/homepinboard
----

=== Example request

.cURL
[source, cURL]
----
curl -X GET --header 'Accept: text/plain' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard
----

=== Example response
If the home pinboard is set in the current logged-in user's account, the API returns the GUID of the pinboard set as a home pinboard:

----
7a9a6715-e154-431b-baaf-7b58246c13dd
----

=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful operation.
|===

[#del-home-pinboard]
== Remove a home pinboard
To remove the home pinboard setting from current logged-in user's account, send a DELETE request to the `/tspublic/v1/session/homepinboard` API endpoint.

=== Resource URL
----
DELETE /tspublic/v1/session/homepinboard
----

=== Example request

.cURL
[source, cURL]
----
curl -X DELETE --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/homepinboard
----

=== Example response
If the home pinboard is set in the current logged-in user's account, the API returns the following response:

----
Response Code
200
----
=== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful operation.
|===
