= ThoughtSpot SpotDev Portal
:toc: true

:page-title: ThoughtSpot SpotDev Portal
:page-pageid: spotdev-portal
:page-description: Using ThoughtSpot SpotDev Portal

The ThoughtSpot SpotDev portal helps you learn how to use the ThoughtSpot SDKs, APIs, and developer tools to build your web applications with ThoughtSpot content. 
The SpotDev portal enables business application owners and developers to learn about ThoughtSpot APIs, and evaluate ThoughtSpot features that are available for embedding and application integration.
 
== Access SpotDev portal
SpotDev portal is available for both new and existing users of ThoughtSpot. 

New user?::
. Go to link://https://www.thoughtspot.com[www.thoughtspot.com].
. Click the *Developers* tab.
. To evaluate ThoughtSpot features, click *Sign Up* and register for a free trial. 
. To explore ThoughtSpot APIs, click *Playground*. 

Already a ThoughtSpot Cloud user?::
. Sign in to ThoughtSpot Cloud.
. Navigate to the *SpotDev* tab.
. Explore the SpotDev portal features, and build your sample code in the *Playground*. 
The SpotDev portal also allows users to customize styles and configure additional actions for visualizations and pinboards. 

== Find your way around  
The SpotDev portal includes several sections to assist you through your embedding journey.

Home::
The *Home* page of the SpotDev portal provides a pictorial view of the ThoughtSpot features that you can integrate with your applications.
The home page also includes links to the Developer Documentation and the *Playground* to preview the functions.

Guide::
The *Guide* menu displays the _ThoughtSpot Embed Developer Documentation_. The documentation portal provides step-by-step instructions on how to use the ThoughtSpot SDK and APIs to integrate ThoughtSpot features into your application.

Playground::
The *Playground* provides an API playground to explore the following ThoughtSpot features.
* Search 
* Visualizations
* Pinboards
* Full application

Customizations::
For ThoughtSpot users with administrator and developer privileges, the SpotDev portal displays the following customization settings:
[horizontal]
Styles:: A set of customization controls for white-labeling and rebranding the embedded ThoughtSpot content.
Actions:: Configuration settings for creating custom actions for the embedded pinboards and visualizations.
Settings:: Security controls for accessing embedded content from external applications.

== Explore the APIs
ThoughtSpot provides a set of APIs, SDK, and developer tools to integrate search analytics, data insights, visualizations, pinboards, and even the entire ThoughtSpot application in an external application, portal, or business solution.
The SpotDev Playground allows developers to preview the code, test it, and familiarize themselves with the application controls.

=== Search
To explore the search embed API and preview the code: 

. Go to *Playground* > *Search*.
. Select a data source or a saved search answer.
. If required, enable the *User experience customization* settings.
. Click *Run*.

==== User experience settings
Collapse data panel::
Minimizes the data panel on the left navigation bar. 
Hide data panel::
Hides the default data source. You can use your worksheet as a data source from which your users can draw search results.
Hide chart or table::
Hides the visualizations displayed as search results. 
Modify available actions::
Defines a list of actions to be disabled on the search answers page.  
Enable Search Assist::
Enables the Search Assist feature that helps users with simple search scenarios. Search Assist allows you to create a custom onboarding experience for your users by demonstrating how to search data from the example queries created on your worksheet. 
Add search tokens::
Sets search tokens in the search bar to programmatically construct a search query for your users. 
Set runtime filters::
Sets filters that will be applied to the search query parameters passed in the URL for the search results data.

=== Visualization
To explore the API for embedding visualizations: 

. Go to *Playground* > *Visualization*
. Select a pinboard or visualization.
. If required, enable the *User experience customization* settings.
. Click *Run*.

==== User experience settings
Modify available actions::
Defines a list of actions to be disabled on the visualizations page.  
Set runtime filters::
Sets filters that will be applied to the visualization.

=== Pinboard
To explore the Pinboard API:

. Go to *Playground* > *Pinboard*.
. Select a pinboard.
. If required, enable *User experience customization* settings.
. Click *Run*.

==== User experience settings
Hide title::
Hides the title and the description of the pinboard.
Hide filter bar::
Hides the pinboard filters.
Modify available actions
Modify available actions::
Defines a list of actions to be disabled on the *Pinboards* page, and each of the visualizations in the *Pinboards* page.  
Set runtime filters::
Sets filters that will be applied to the visualization.

=== Full Application
To explore the API for embedding full application:

. Go to *Playground* > *Full app*.
. Select a tab to set a default page view for embedded application users.
. If required, enable *User experience customization* settings.
. Click *Run*.

==== User experience settings
Hide navigation bar::
Hides the ThoughtSpot top navigation bar.
Set runtime filters::
Sets filters that will apply to visualizations and pinboards on any tab.

== Customize embedded content
* To xref:customize-style.adoc[white-label and rebrand the embedded ThoughtSpot content], click *Customizations* > *Styles*.
* To xref:customize-actions-menu.adoc[create custom actions] for the *Actions* menu (*...*) on visualizations and pinboards, go to *Customizations* > *Styles*.
* If you are a ThoughtSpot admin user and you want to xref:security-settings.adoc[configure security settings], such as enabling CORS, setting up trusted authentication service, or whitelisting client application domains, go to *Customizations* > *Settings*.
