= Manage your cluster state
:toc: true
:toclevels: 1

:page-title: Update cluster state
:page-pageid: tse-dynamic-sense-cluster
:page-description:  If you are using a ThoughtSpot Cloud cluster in the economy mode in your embedded deployments, use the APIs to restart an inactive cluster.

If you are using a ThoughtSpot Cloud cluster for embedded deployments in your development or production environment, you can enable idle sensing to save costs and allow your cluster to operate in `economy` mode. To enable this feature on your clusters, contact ThoughtSpot Support.

== Idle sensing and cluster states
If idle sensing is enabled on your cluster, your cluster will be automatically stopped if there is no user activity detected for a given time threshold. By default, the idle time threshold is set to 120 minutes.

At any given time, a ThoughtSpot cluster can be in any one of the following states:

* `ACTIVE` +
Indicates that the cluster is active and user activity is detected.
* `UNDER_MAINTENANCE` +
Indicates that the cluster is down for maintenance due to upgrade or patching.
* `STOPPED`
Indicates that the cluster is stopped and no user activity is detected.
* `STARTING`/`PENDING` +
The cluster is currently starting, or some other workflow is running on the cluster.

== Identify the status of your cluster
By default, a ThoughtSpot cluster running the `economy` mode stops if there is no user activity for two hours. When a user tries to access a cluster that's in the `STOPPED` state, the API calls will return the `"cluster-state": "Stopped"` in the response header.

[source,cURL]
----
 $ curl https://<cluster-name>.thoughtspot.cloud  --head
  HTTP/1.1 200 OK
  Server: awselb/2.0
  Date: Tue, 30 May 2023 15:27:01 GMT
  Content-Type: text/html
  Content-Length: 3348
  Connection: close
  Cluster-State: Stopped
----

To restart the cluster, complete the steps described in the following section.

== Start an inactive cluster using API
On a regular ThoughtSpot Cloud cluster, users can restart an inactive cluster using `CAPTCHA`. However, on embedded instances, the `CAPTCHA`-based cluster activation is not supported. Instead, the embedded  application user can send a `GET` request to their instance with the following query parameters in the request URL:

* `tse=true`
* `start_cluster=true`

For example, to start an inactive cluster, send a `GET` request in the following parameters:

.Production environment
[source,http]
----
https://<cluster-name>.thoughtspot.cloud/?tse=true&start_cluster=true
----

.Staging environment

[source,http]
----
https://<cluster-name>.thoughtspotstaging.cloud/?tse=true&start_cluster=true
----

.Development environment

[source,http]
----
https://<cluster-name>.thoughtspotdev.cloud/?tse=true&start_cluster=true
----

In the request header, you must also pass the `security-key`. The `security-key` is used for authenticating users and is generated when xref:trusted-authentication.adoc#trusted-auth-enable[trusted authentication is enabled] on a ThoughtSpot instance. Embedded application users can obtain the `security key` from their ThoughtSpot administrator.

The following example shows the cURL request for restarting a cluster:

[source, cURL]
----
$ curl -X GET 'https://<cluster-name>.thoughtspot.cloud/?tse=true&start_cluster=true' \
 -H 'security-key: e8ade677-c3f1-461d-8b7f-7f0fe4e024f0' --head \
  HTTP/1.1 200 OK
  Server: awselb/2.0
  Date: Tue, 30 May 2023 16:04:08 GMT
  Content-Type: text/html
  Content-Length: 0
  Connection: keep-alive
  Cluster-State: Starting
----

If the `GET` request is successful, the cluster starts.

== Response header
Note the cluster state in the response header:

* `STARTING` +
Indicates that the cluster is starting. It may take a few minutes for the cluster to become active.
* `UNKNOWN` +
Indicates a possible error. Contact your administrator or ThoughtSpot Support if the cluster does not start in 5-10 minutes.

== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful operation
|**400**|Invalid request
|**401**|Unauthorized access
|===
