= User API

:page-title: User API
:page-pageid: user-api
:page-description: User API

The User APIs allow you to programmatically manager ThoughtSpot users and user groups.

[width="100%" cols="2,3"]
|===
|`xref:user-api.adoc#user-list[GET /tspublic/v1/user/list]`|Gets a list of all users and user groups configured in the ThoughtSpot system
|`xref:user-api.adoc#change-pwd[POST /tspublic/v1/user/updatepassword]`|Changes the password of a ThoughtSpot user account. 
|`xref:user-api.adoc#updatepreference-api[POST /tspublic/v1/user/updatepreference]`|Updates profile setttings of a ThoughtSpot user. 
|`xref:user-api.adoc#user-sync[POST /tspublic/v1/user/sync]`|Synchronizes user accounts and user groups with ThoughtSpot. 
|`xref:user-api.adoc#transfer-ownership[POST /tspublic/v1/user/transfer/ownership]`|Transfers ownership of objects from one user to another.
|===
[NOTE]
====
If you want to get a list object headers associated with a user or user group, use the xref:metadata-api.adoc#headers-metadata-users[GET /tspublic/v1/metadata/listas] API.
====

---
[#user-list]
== Get a list of users and groups
To get a list of all users, groups, and their inter-dependencies in the form of principal objects, use the  `/tspublic/v1/user/list` API.

=== Resource URL
----
GET /tspublic/v1/user/list
----

=== Example request

.cURL
----
curl -X GET --header 'Accept: application/json' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/list'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/list
----

=== Example response

[source,JSON]
----
[
  {
    "name": "Administrator",
    "displayName": "Administration Group",
    "created": 1354006445722,
    "modified": 1354006445987,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT"
  },
  {
    "name": "Analyst",
    "displayName": "Analyst Group",
    "created": 1354006445722,
    "modified": 1354006445987,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT"
  },
  {
    "name": "rls-group-3",
    "displayName": "rls-group-3",
    "description": "Contains directly rls-group-1, rls-group-2 and belongs directly to rls-group-5",
    "created": 1459376495060,
    "modified": 1459376590681,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": rls-group-5,
    "visibility": "DEFAULT"
  }
  ]
----
==== Object properties
A typical principal object contains the following properties:

[width="100%" cols="1,3"]
[options='header']
|====
|Property|Description
|`name`|Name of the principal. This field, in conjunction with whether the object is a user or group, is used to identify a user or group. The name of the principal must be unique.
|`displayName`|Display name of the principal.
|`description`|Description of the principal.
|`mail`|The email address of the user. This field is populated only for the user objects. It is ignored if the object type is a group.
|`principalTypeEnum` a|Type of the user created in the ThoughtSpot system.
Valid values are:

* `LOCAL_USER`
* `LOCAL_GROUP`
|`password` a|The password of the user. This field is populated only for the user object. It is ignored in the case of groups.

Password is only required:

* if the user is of `LOCAL_USER` type
* when the user is created for the first time. In subsequent updates, the user password is not modified even if it changes in the source system.
|`groupNames` a|Name of the groups to which a principal belongs. For example, `Administrator`, `ALL_GROUP`, and so on. Users can belong to multiple groups.
|`visibility`| Whether the users of the group can share objects with other users in the group.
|====

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**|Successful operation.
|===
---
[#change-pwd]
== Change password
To change the password of a ThoughtSpot user account, use the `/tspublic/v1/user/updatepassword` API.

=== Resource URL
----
POST /tspublic/v1/user/updatepassword
----
=== Request parameters

[width="100%" cols="1,1,3"]
[options='header']
|====
|Form Parameter|Data Type|Description
|`name`|string|Name of the user.
|`currentpassword`|string|The current password of the user.
|`password`|string|A new password of the user.
|====
=== Example request

.cURL
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'name=guest&currentpassword=test&password=foobarfoobar' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/updatepassword'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/updatepassword
----

=== Response codes
[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**|If the password of the user is changed successfully.
|===

---
[#updatepreference-api]
== Update a user profile
To update the profile settings of a ThoughtSpot user  programmatically, you can use the `/tspublic/v1/user/updatepreference` API.

The `/tspublic/v1/user/updatepreference` API allows you to modify the following attributes of a ThoughtSpot user profile:

* Email address 
+
The email address of the user.

* Language preference 
+
The system locale setting. The locale setting determines the language of the ThoughtSpot UI, date, number, and currency format. 

* Notification setting 
+
User preference for receiving email notifications when another ThoughtSpot user shares search answers or pinboards. 

* Settings for revisiting the onboarding experience
+
The user preference for revisiting the onboarding experience. 

+
ThoughtSpot provides an interactive guided walkthrough to onboard new users. The onboarding experience leads users through a set of actions to help users get started and accomplish their tasks quickly. The users can turn off the Onboarding experience and access it again when they need assistance with the ThoughtSpot UI. 

[NOTE]
====
The `/tspublic/v1/user/updatepreference` API does not support modifying the profile picture of a user, the password of a user account, and the Answer experience preference settings in a user profile.  
====

=== Resource URL
----
POST /tspublic/v1/user/updatepreference
----

=== Request parameters
[width="100%", cols="1,1,2"]
[options="header"]
|===
|Form Parameter|Data Type|Description
|`userid` __Optional__|string|The ID of the user. The user ID is a GUID. 
|`username` __Optional__|string|Username of the user.  
|`preferences`|string a|The JSON map of user preferences. In the JSON map, you can define the attributes to set the following preferences for a user:

* change the display language of the ThoughtSpot UI
* receive email notifications when another user shares a search answer or a pinboard
* enable the onboarding experience 
|`preferencesProto` __Optional__|string| A 64-bit encoded string for setting user preferences in a secure manner. For example, `CgoKCAgBEAEYASAB`. 
|===

[NOTE]
====
If your browser or OS locale is set to a xref:user-api.adoc#locale-setting[ThoughtSpot supported locale], ThoughtSpot automatically defaults to that locale. If your browser locale is not supported in ThoughtSpot, ThoughtSpot sets `en-US` (US English) as your  default locale.
====

=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' -d 'userid=59481331-ee53-42be-a548-bd87be6ddd4a&preferences=%7B%22showWalkMe%22%3Atrue%2C%22notifyOnShare%22%3Atrue%2C%22analystOnboardingComplete%22%3Afalse%2C%22preferredLocale%22%3A%22en-IN%22%7D' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/updatepreference' 
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/updatepreference
----

.Example JSON String 

This example shows the following preference settings that you can pass as a JSON string. 

[source,JSON]
----
{
   "showWalkMe":true,
   "notifyOnShare":true,
   "analystOnboardingComplete":false,
   "preferredLocale":"en-CA"
}
----
* `showWalkMe` __Boolean__
+
Enables or disables the guided onboarding walkthrough. When set to `true`, the user can revisit the onboarding experience.

* `notifyOnShare` __Boolean__
+
Sets a notification preference for receiving emails when another user shares search answers or pinboards. 

* `analystOnboardingComplete` __Boolean__
+
Indicates if the user is onboarded. 

* `preferredLocale` __String__
+
Sets the ThoughtSpot locale for the specified user account. For example, to allow a user to view the ThoughtSpot UI in Deutsche, you can set the `prefrredLocale` parameter to `de-DE`. 
+
The allowed values are:
+
[#locale-setting]
[width="60%", cols="1,2"]
[options="header"]
|====================
| Locale | Language
| `da-DK` | Dansk  
| `de-DE` | Deutsche  
| `en-AU` | English (Australia)  
| `en-CA` | English (Canada) 
| `en-IN` | English (India) 
| `en-GB` | English (United Kingdom) 
| `en-US` | English (United States) 
| `es-US` | Español (Latinoamérica) 
| `es-ES` | Español (España) 
| `fr-CA` | Français (Canada) 
| `fr-FR` | Français (France) 
| `it-IT` | Italiano 
| `nl-NL` | Nederland
| `nb-NO` | Norsk 
| `pt-BR` | Português (Brasil) 
| `pt-PT` | Português (Portugal) 
| `fi-FI` | Suomi
| `sv-SE` | Svenska 
| `zh-CN` | 中文(简体)
| `ja-JP` | 日本語 
|====================

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**| Successful update of a user profile
|**400**| Invalid user ID
|===

---
[#transfer-ownership]
== Transfer ownership

To programmatically transfer ownership of _all_ objects from one user to another, use the `/tspublic/v1/user/transfer/ownership` API.

[NOTE]
ThoughtSpot does not support transferring objects to or from a system or admin user account.

=== Resource URL
----
POST /tspublic/v1/user/transfer/ownership
----
=== Request parameters
[width="100%" cols="2,2,4"]
[options='header']
|====
|Query Parameter|Data Type|Description
|`fromUserName`| string|Username to transfer from.
|`toUserName`|string|Username to transfer to.
|====

=== Example request

.cURL
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Requested-By: ThoughtSpot' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/transfer/ownership?fromUserName=guest&toUserName=guest1'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/transfer/ownership?fromUserName=guest&toUserName=guest1
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**|If the ownership of all objects is successfully transferred.
|**400**|In case of invalid `fromName` and `toName`, or if there is no user for a given username.
|===
---
[#user-sync]
== Synchronize principals
To programmatically synchronize user accounts and user groups with ThoughtSpot, use the `/tspublic/v1/user/sync` API.
The payload takes principals containing all users and groups present in the external database.
A successful API call returns the object that represents the changes made in the ThoughtSpot system.

During this operation:

* Objects (users or groups) present in ThoughtSpot, but not present in the external list are deleted in ThoughtSpot.
* Objects present in ThoughtSpot and the external list are updated such that the object attributes in ThoughtSpot match those present in the list.
+
This includes group membership.

* Objects not present in ThoughtSpot, but present in the external list  are created in ThoughtSpot.

=== Resource URL
----
POST /tspublic/v1/user/sync
----
=== Request parameters

This API uses `multipart/form-data` content type.
[width="100%" cols="1,1,4"]
[options='header']
|===
|Form Parameter|Data Type|Description

|`principals`|string|Specifies a list of principal objects.
This is a JSON file containing all users and groups present in the external database.

|`applyChanges`
|boolean
|A flag indicating whether to sync the users and groups to the system, and apply the difference evaluated.
Use this parameter to validate a difference before applying changes.

|`removeDeleted`
|boolean
|A flag indicating whether to remove deleted users/groups.
When true, this flag removes any deleted users or groups.

|`password`
|string
|Specifies a password.
|===

=== Example request

.cURL
[source, cURL]
----
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'applyChanges=false' 'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/sync'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/user/sync
----

=== Example response

This example covers user objects (with emails), group objects, and their relationships.

* `created` and `modified` dates may be left blank for new users.
* `principalTypeEnum` value specifies if the principal is a user or a group.

Here, `test1` user belongs to two groups, `Customer Success` and `Marketing`.
`test2` belongs to the group `Administrator`.
`All` is a default group to which every user belongs;
you may omit it from the input.

Set `visibility` to `NON_SHARABLE` if you do not want users to link:https://cloud-docs.thoughtspot.com/admin/users-groups/add-user.html#sharing-visibility[share objects, window=_blank] with other users in this group.

[source, JSON]
----
[
  { "name": "Customer Success",
    "displayName": "Customer Success",
    "description": "CS",
    "created": 1568926267025,
    "modified": 1568926982242,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT" },

  { "name": "All",
    "displayName": "All Group",
    "created": 1354006445722,
    "modified": 1354006445722,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT" },

  { "name": "Marketing",
    "displayName": "Marketing",
    "description": "Marketing Group",
    "created": 1587573582931,
    "modified": 1587573583003,
    "principalTypeEnum": "LOCAL_GROUP",
    "groupNames": [],
    "visibility": "DEFAULT" },

  { "name": "test1",
    "displayName": "test one",
    "description": "",
    "created": 1587573554475,
    "modified": 1587573589986,
    "mail": "test1@test.com",
    "principalTypeEnum": "LOCAL_USER",
    "groupNames": [ "All", "Customer Success", "Marketing" ],
    "visibility": "DEFAULT" },

  { "name": "test2",
    "displayName": "test two",
    "created": 1587573621279,
    "modified": 1587573621674,
    "mail": "test2@test.com",
    "principalTypeEnum": "LOCAL_USER",
    "groupNames": [ "Administrator", "All" ],
    "visibility": "DEFAULT" }
]
----

=== Response codes

[options="header", cols=".^2a,.^14a"]
|===
|HTTP Code|Description
|**200**| The user sync operation is successful.
|===
