= Developer access
:toc: true

:page-title: User configuration
:page-pageid: developer-access
:page-description: Configure users and groups with developer privileges

You will require a user account with `Developer` privilege to perform the following tasks in ThoughtSpot:

* Access the *Develop* tab in ThoughtSpot application.
* Customize and rebrand the look and feel of the ThoughtSpot UI.
* Add custom actions to a pinboard or visualization. 
* Customize the format of links used in system-generated emails and notifications. 
* Configure visual embed hosts for CORS and CSP.
 
ThoughtSpot administrators can create a user group with `Developer` privilege enabled and assign users to this group. Administrators can configure developer access either using the *Admin* tab in the UI or the Group REST APIs. 

The following sections describe how to configure developer access using the *Admin* tab in the UI. 
For information about managing users and groups using REST APIs, see xref:group-api.adoc[Group APIs] and xref:user-api.adoc[User APIs].

== Add a user group for developers
To add a user group with developer privileges:

. Log in to ThoughtSpot as an admin user.
. Go to *Admin* > *User management* > *Groups*.

+ 
The group configuration page appears.

. Click *+ Add Group*.
. In the *Add a new group* dialog, enter the following details:
+
Group name::
Name of the group. For example, `Developer Group`.
Display name::
Name of the group as it appears in ThoughtSpot. For example, `Embed Developer`.
Sharing visibility::
Specify if users can share objects with this group. When set to `SHAREABLE`, ThoughtSpot allows other users to share objects with the members of this group.
Description::
__Optional__. Enter a description for the group.
Privileges::
Select the *Has Developer privilege* checkbox.
. Click *Add*.

== Assign a user to a developer group

To assign a user to a developer group:

. Log in to ThoughtSpot. 
. Go to *Admin* > *Users management* > *Users*.
+
The user configuration page appears.

. Click *+ Add User*.
. In the *Add a new user* dialog, enter the following details:
+
Username::
A unique login name for the user. Usernames must be in lowercase.
Display name::
A unique name for the user. For example, the first and last name of the user.
Sharing visibility::
Specify if other users can share objects with this user. When set to *SHAREABLE*, this user is visible in the *Share* dialog when another user tries to share an object.
Change password::
A password for the user account. 
Confirm password::
Enter the password again.
Email::
The user's email address. ThoughtSpot uses this email address for notifications.
[NOTE]
Make sure the domain address of the email provider is added to the CSP allowed list on the *Develop* > *Security Settings* page.

Send a welcome email::
__Optional__. When checked, this option ensures that the new user receives a welcome email.

Email message text::
__Optional__. Enter the text to use in the welcome email.
Groups::
Select a group that has the Developer privilege enabled.

. Click *Add*.
