= User configuration
:toc: true

:page-title: User configuration
:page-pageid: user-roles
:page-description: Configure users and groups with developer privileges

To embed ThoughtSpot content in your application, you must have developer privileges. ThoughtSpot users with the `Developer` privilieges can perform the following tasks:

* Use Visual Embed SDK to embed ThoughtSpot in their host applications.
* Customize and rebrand the look and feel of the UI.
* Add custom actions to an embedded pinboard and visualization. 
* Modify security settings for visual embed hosts.

You can create a developer group and add users either using the *Admin* console in the UI, or REST APIs. The following sections describe how to configure a developer user group and assign users to a group in the *Admin* console. 
For information on managing users using REST APIs, see xref:api-user-group-management.adoc[Manage user groups] and see xref:api-user-management.adoc[Manage users].

[NOTE]
To add users and groups in the ThoughtSpot, you must have administrator privileges. For more information about ThoughtSpot user privileges, see link:https://cloud-docs.thoughtspot.com/admin/users-groups/about-users-groups.html[Understand groups and privileges, window=_blank]. 

== Add a user group for developers
To add a user group with developer privileges:

. Log in to ThoughtSpot.
. On the top navigation bar, click the *Admin* tab.
. On the *Admin* page, go to *User management* > *Groups*.

+ 
The group configuration page appears.

. Click *+ Add Group*.
. In the *Add a new group* dialog, enter the following details:
+
Group name::
Name of the group. For example, `Developer Group`.
Display name::
Name of the group as it appears in ThoughtSpot. For example, `Embed Developer`.
Sharing visibility::
Indicate whether objects can be shared with this group. When set to `SHAREABLE`, this group is an option in the Share dialog.
Description ::
__Optional__. Enter a description for the group.
Privileges::
Select the *Has Developer privilege* checkbox.
. Click *Add*.

== Add a user to a developer group

To add a user:

. In the ThoughtSpot application, go to *Admin* > *Users management* > *Users*.
+
The user configuration page appears.

. Click *+ Add User*.
. In the *Add a new user* dialog, enter the following details:
+
Username::
A login name for the user. Usernames must be unique and lowercase.
Display name::
A unique name for the user; for example, the first and last name of the user.
Sharing visibility::
Indicate whether objects can be shared with this user. When set to SHAREABLE, this user is listed in the *Share* dialog when sharing a pinboard or visualization.
Change password::
A password for the user account. 
Confirm password::
Enter the password again.
Email::
The user's email address. ThoughtSpot uses this email address for notifications.
[NOTE]
Make sure that the domain address of the email provider is added to the CSP whitelist on the *Security Settings* page.
Send a welcome email::
__Optional__. When checked, this option ensures that the new user receives a welcome email.

Email message text::
__Optional__. Enter the text for the welcome email.
Groups::
Assign the user to group that has developer privileges.

. Click *Add*.
+ 
The user profile with developer privileges is added to ThoughtSpot. 
You can use these login credentials to access ThoughtSpot Developer portal and the options available in the *Develop* tab.
