= Visual Embed SDK
:toc: true

:page-title: What is Visual Embed SDK
:page-pageid: visual-embed-sdk
:page-description: What is Visual Embed SDK

The Visual Embed SDK provides a Javascript library to embed ThoughtSpot elements in a host application.

You can use the Visual Embed SDK for the following purposes:

* Embed specific components of the ThoughtSpot application; for example, search, pinboards, and visualizations.
* Render full ThoughtSpot application within the host application.

== Visual Embed SDK APIs

The Visual Embed SDK includes the following embed modules:

SearchEmbed::
To xref:embed-search.adoc[embed the ThoughtSpot search] functionality.

PinboardEmbed::
To embed a ThoughtSpot xref:embed-a-viz.adoc[visualization] or  xref:embed-pinboard.adoc[pinboard].

AppEmbed::
To embed the xref:full-embed.adoc[full ThoughtSpot application] with or without the navigation bar.


== Configuration requirements for embedding

For information on configuration requirements, see the following sections:

* xref:integration-overview.adoc[Integration guidelines]
* xref:security-settings.adoc[Security settings]

== Optional settings for embedding

The URLs in data display as clickable links in ThoughtSpot tables.
By default, clicking on a link opens the URL in a separate tab.
However, there is a system-wide setting that can be changed to open the links within the context in which they appear.

Changing this setting opens the links.
Consider the possible link types, and how they open:

* Link in search result table in ThoughtSpot.
+
Same browser tab as ThoughtSpot application.

* Link in table embedded in  a DOM element.
+
Same `<iframe>` that contains the table.

* Link in full ThoughtSpot application embedded in a web page.
+
Same `<iframe>` that contains the application.

== Authentication
You can use any of the following authentication services for authenticating application users who want to access the embedded content.

Authentication with session REST API::
In this method, you can send a POST request to the `/tspublic/v1/session/login` API to allow a user to log in to Thoughtspot.

[WARNING]
This authentication method is intended to be used in initial development and testing phases. Do not use this authentication method in a production environment.

No Authentication::
This would require the user to be _already logged into ThoughtSpot_, before interacting with the client application.

[WARNING]
Do not use this authentication method in a production environment.

SAML SSO::
This method requires you to set up SAML SSO support on the ThoughtSpot admin console.
+

For more information, see xref:configure-saml.adoc[SAML SSO].

Trusted authentication service::
This method requires you to enable token-based trusted authentication service.
In this authentication method, ThoughtSpot provides your client application service with a token that allows it to authenticate on behalf of users.
+
For more information, see xref:trusted-authentication.adoc[Trusted Authentication].
