
= Visual Embed SDK

:toc: true

:page-title: What is Visual Embed SDK
:page-pageid: visual-embed-sdk
:page-description: What is Visual Embed SDK

The Visual Embed SDK provides a set of Javascript libraries to embed ThoughtSpot elements in a host application.

You can use the Visual Embed SDK for the following purposes:

* Embed specific components of ThoughtSpot application. For example, search bar, search answers page, pinboards, charts, and tables.
* Render full ThoughtSpot application within the host application.
* Render charts, visualizations, and pinboards.

== Visual Embed SDK libraries

The Visual Embed SDK includes the following Javascript libraries:

[horizontal]
SearchEmbed::
For xref:embed-search.adoc[embedding the ThoughtSpot search] functionality.

PinboardVizEmbed::
For embedding ThoughtSpot xref:embed-a-viz.adoc[visualizations] and xref:embed-pinboard.adoc[pinboards].


fullEmbed::
For embedding xref:full-embed.adoc[full ThoughtSpot application] with or without the navigation bar.


== Configuration requirements for embedding

For information on configuration requirements, see the following sections:

* xref:integration-overview.adoc[Integration guidelines]
* xref:security-settings.adoc[Security settings]


== Optional settings for embedding

One of these involves what happens when a user clicks on a link within the data.
The URLs in data display as clickable links in ThoughtSpot tables.
By default, clicking on a link opens the URL in a separate tab.
However, there is a system-wide setting that can be changed to open the links within the context in which they appear.

Changing this setting opens the links.
Consider the possible link types, and how they open:

* Link in search result table in ThoughtSpot.
+
Same browser tab as ThoughtSpot application.

* Link in table embedded in an `<iframe>`.
+
Same `<iframe>` that contains the table.

* Link in full ThoughtSpot application embedded in an `<iframe>` element
+
Same `<iframe>` that contains the application.

== Authentication
You can use any of the following authentication services for authenticating application users who want to access the embedded content.

No Authentication::
This would require the user to be _already logged into ThoughtSpot_, before interacting with the client application.
You can use this authentication approach for testing environments.
Do not use this in a production environment.

SAML::
This method requires you to set up SAML SSO support on the ThoughtSpot admin console.
+

For more information, see xref:configure.saml[SAML SSO].

Trusted authentication service::
This method requires you to enable token-based trusted authentication service.
In this authentication method, ThoughtSpot provides your client application service with a token that allows it to authenticate on behalf of users.
+
For more information, see xref:trusted-authentication[Trusted Authentication].
