= Visual Embed SDK
:toc: true

:page-title: Visual Embed SDK overview
:page-pageid: visual-embed-sdk
:page-description: Visual Embed SDK provides a set of APIs to embed and customize ThoughtSpot elements in your app.

The Visual Embed SDK provides a Javascript library to embed ThoughtSpot elements in your host application.

You can use the Visual Embed SDK for the following purposes:

* Embed specific components of the ThoughtSpot application; for example, search, Liveboards, and visualizations.
* Render full ThoughtSpot application within a host application.

Follow the steps described in the sections below to embed ThoughtSpot features in your application.


[div boxDiv boxFullWidth]
--
+++ <h5> Integration guidelines </h5>+++

Read the xref:integration-overview.adoc[integration guidelines] to understand the embedding requirements and recommendations.

--

[div boxDiv boxFullWidth]
--
+++<h5>Security settings </h5> +++

Before you get started, xref:security-settings.adoc[add your application domain to the CORS and CSP allowed list] and set your application as a trusted host for secure data exchange.
--


[div boxDiv boxFullWidth]
--
+++<h5>Get Started</h5>+++

Download the Visual Embed SDK package, set up your application environment, and xref:getting-started.adoc[get started with embedding].
--

[div boxDiv boxFullWidth]
--
+++<h5>Configure authentication method</h5>+++

Learn how to set up xref:configure-saml.adoc[SAML SSO] or xref:trusted-authentication.adoc[trusted authentication service], and xref:embed-authentication.adoc[configure authentication methods in SDK] to authenticate your  application users. 

--

[div boxDiv boxFullWidth]
--
+++<h5>Embed search</h5>+++

Learn xref:embed-search.adoc[how to embed ThoughtSpot search] in your application. 
--

[div boxDiv boxFullWidth]
--
+++<h5>Embed a visualization</h5>+++

Learn how to xref:embed-a-viz.adoc[embed a ThoughtSpot visualization] in your application.

--

[div boxDiv boxFullWidth]
--
+++<h5>Embed a Liveboard</h5>+++

Learn how to xref:embed-pinboard.adoc[render Liveboards and apply runtime controls on visualizations] embedded in your application.
--

[div boxDiv boxFullWidth]
--
+++<h5>Embed full ThoughtSpot experience</h5>+++

Learn how to xref:full-embed.adoc[embed full ThoughtSpot experience] in your application.

--


[div boxDiv boxFullWidth]
--
+++<h5>Embed ThoughtSpot in a React app</h5>+++

Learn how to xref:embed-ts-react-app.adoc[Embed ThoughtSpot in a React app].
--


[div boxDiv boxFullWidth]
--
+++<h5>Register and interact events</h5>+++

Learn how to xref:embed-events.adoc[register event handlers, trigger and interact with events].
--

== Useful resources

[div boxDiv boxFullWidth]
--

* link:{{visualEmbedSDKPrefix}}/modules.html[Visual Embed SDK Reference Guide, window=_blank] 
* link:https://developers.thoughtspot.com/guides[Visual Embed Tutorials]
* link:https://github.com/thoughtspot/visual-embed-sdk[Visual Embed SDK GitHub repository, window=_blank]
* link:https://github.com/thoughtspot/ts_everywhere_resources[ThoughtSpot Everywhere Resources on GitHub, window=_blank]
--
