= Visual Embed SDK
:toc: true

:page-title: What is Visual Embed SDK
:page-pageid: visual-embed-sdk
:page-description: What is Visual Embed SDK

The Visual Embed SDK provides a Javascript library to embed ThoughtSpot elements in your host application.

You can use the Visual Embed SDK for the following purposes:

* Embed specific components of the ThoughtSpot application; for example, search, pinboards, and visualizations.
* Render full ThoughtSpot application within the host application.

== Configuration requirements

[div boxDiv boxFullWidth]
--
*xref:integration-overview.adoc[Integration guidelines]*

Read through the integration guidelines to make sure you understand the embedding requirements.

--

[div boxDiv boxFullWidth]
--
*xref:security-settings.adoc[Security settings]*

Before you get started, add your application domain as a CORS and CSP host, and set up your application as a trusted host for secure data exchange.
--

== Start embedding

[div boxDiv boxFullWidth]
--
*xref:getting-started.adoc[Get Started]*

Download the Visual Embed SDK package and set up your application environment.
--

[div boxDiv boxFullWidth]
--
*xref:embed-authentication.adoc[Configure authentication method]*

Learn how to set up xref:configure-saml.adoc[SAML SSO] or xref:trusted-authentication.adoc[trusted authentication service] to authenticate your embed application users. 

--

[div boxDiv boxFullWidth]
--
*xref:embed-search.adoc[Embed search]*

Learn how to embed ThoughtSpot search in your application. 
--

[div boxDiv boxFullWidth]
--
*xref:embed-a-viz.adoc[Embed a visualization]*

Learn how to embed ThoughtSpot charts and tables in your application.

--

[div boxDiv boxFullWidth]
--
*xref:embed-a-pinboard.adoc[Embed a pinboard]*

Learn how to render pinboards and apply runtime controls on visualizations embedded in your application.

--

[div boxDiv boxFullWidth]
--
*xref:full-embed.adoc[Embed full ThoughtSpot experience]*

Learn how to embed full ThoughtSpot experience in your application.

--
////
== Authentication
You can use any of the following authentication services for authenticating application users who want to access the embedded content.

Authentication with session REST API::
In this method, you can send a POST request to the `/tspublic/v1/session/login` API to allow a user to log in to Thoughtspot.

[WARNING]
This authentication method is intended to be used in initial development and testing phases. Do not use this authentication method in a production environment.

No Authentication::
This would require the user to be _already logged into ThoughtSpot_, before interacting with the client application.

[WARNING]
Do not use this authentication method in a production environment.

SAML SSO::
This method requires you to set up SAML SSO support on the ThoughtSpot admin console.
+

For more information, see xref:configure-saml.adoc[SAML SSO].

Trusted authentication service::
This method requires you to enable token-based trusted authentication service.
In this authentication method, ThoughtSpot provides your client application service with a token that allows it to authenticate on behalf of users.
+
For more information, see xref:trusted-authentication.adoc[Trusted Authentication].

////

== Useful resources

[div boxDiv boxFullWidth]
--
* link:{{visualEmbedSDKPrefix}}/modules.html[Visual Embed SDK Reference Guide, window=_blank] 
* link:https://github.com/thoughtspot/visual-embed-sdk#readme[ReadMe, window=_blank]
* link:https://github.com/thoughtspot/visual-embed-sdk[Visual Embed SDK GitHub repository, window=_blank]
* link:https://developers.thoughtspot.com/guides[Visual Embed Tutorials]
--
