= Visual Embed SDK
:toc: true

:page-title: What is Visual Embed SDK
:page-pageid: visual-embed-sdk
:page-description: What is Visual Embed SDK

The Visual Embed SDK provides a Javascript library to embed ThoughtSpot elements in your host application.

You can use the Visual Embed SDK for the following purposes:

* Embed specific components of the ThoughtSpot application; for example, search, pinboards, and visualizations.
* Render full ThoughtSpot application within a host application.

== Configuration requirements

[div boxDiv boxFullWidth]
--
+++ <h4> Integration guidelines </h4>+++

Read the xref:integration-overview.adoc[integration guidelines] to understand the embedding requirements and recommendations.

--

[div boxDiv boxFullWidth]
--
+++<h4>Security settings </h4> +++

Before you get started, xref:security-settings.adoc[add your application domain to the CORS and CSP allowed list] and set your application as a trusted host for secure data exchange.
--

== Start embedding

[div boxDiv boxFullWidth]
--
+++<h4>Get Started</h4>+++

Download the Visual Embed SDK package, set up your application environment, and xref:getting-started.adoc[get started with embedding].
--

[div boxDiv boxFullWidth]
--
+++<h4>Configure authentication method</h4>+++

Learn how to set up xref:configure-saml.adoc[SAML SSO] or xref:trusted-authentication.adoc[trusted authentication service], and xref:embed-authentication.adoc[configure authentication methods in SDK] to authenticate your  application users. 

--

[div boxDiv boxFullWidth]
--
+++<h4>Embed search</h4>+++

Learn xref:embed-search.adoc[how to embed ThoughtSpot search] in your application. 
--

[div boxDiv boxFullWidth]
--
+++<h4>Embed a visualization</h4>+++

Learn how to xref:embed-a-viz.adoc[embed a ThoughtSpot visualization] in your application.

--

[div boxDiv boxFullWidth]
--
+++<h4>Embed a pinboard</h4>+++

Learn how to xref:embed-a-pinboard.adoc[render pinboards and apply runtime controls on visualizations] embedded in your application.
--

[div boxDiv boxFullWidth]
--
+++<h4>Embed full ThoughtSpot experience</h4>+++

Learn how to xref:full-embed.adoc[embed full ThoughtSpot experience] in your application.

--
////
== Authentication
You can use any of the following authentication services for authenticating application users who want to access the embedded content.

Authentication with session REST API::
In this method, you can send a POST request to the `/tspublic/v1/session/login` API to allow a user to log in to Thoughtspot.

[WARNING]
This authentication method is intended to be used in initial development and testing phases. Do not use this authentication method in a production environment.

No Authentication::
This would require the user to be _already logged into ThoughtSpot_, before interacting with the client application.

[WARNING]
Do not use this authentication method in a production environment.

SAML SSO::
This method requires you to set up SAML SSO support on the ThoughtSpot admin console.
+

For more information, see xref:configure-saml.adoc[SAML SSO].

Trusted authentication service::
This method requires you to enable token-based trusted authentication service.
In this authentication method, ThoughtSpot provides your client application service with a token that allows it to authenticate on behalf of users.
+
For more information, see xref:trusted-authentication.adoc[Trusted Authentication].

////

== Useful resources

[div boxDiv boxFullWidth]
--
* link:{{visualEmbedSDKPrefix}}/modules.html[Visual Embed SDK Reference Guide, window=_blank] 
* link:https://github.com/thoughtspot/visual-embed-sdk#readme[ReadMe, window=_blank]
* link:https://github.com/thoughtspot/visual-embed-sdk[Visual Embed SDK GitHub repository, window=_blank]
* link:https://developers.thoughtspot.com/guides[Visual Embed Tutorials]
--
