enum AuthType {
  None("None"),
  EmbeddedSSO("EmbeddedSSO"),
  SSO("SSO_SAML"),
  SAML("SSO_SAML"),
  SAMLRedirect("SSO_SAML"),
  OIDC("SSO_OIDC"),
  OIDCRedirect("SSO_OIDC"),
  AuthServer("AuthServer"),
  TrustedAuthToken("AuthServer"),
  TrustedAuthTokenCookieless("AuthServerCookieless"),
  Basic("Basic"),

  final String value;
  const AuthType(this.value);
}

enum HomeLeftNavItem {
  SearchData("search-data"),
  Home("insights-home"),
  Liveboards("liveboards"),
  Answers("answers"),
  MonitorSubscription("monitor-alerts"),
  SpotIQAnalysis("spotiq-analysis"),
  LiveboardSchedules("liveboard-schedules"),

  final String value;
  const HomeLeftNavItem(this.value);
}

enum RuntimeFilterOp {
  EQ("EQ"),
  NE("NE"),
  LT("LT"),
  LE("LE"),
  GT("GT"),
  GE("GE"),
  CONTAINS("CONTAINS"),
  BEGINS_WITH("BEGINS_WITH"),
  ENDS_WITH("ENDS_WITH"),
  BW_INC_MAX("BW_INC_MAX"),
  BW_INC_MIN("BW_INC_MIN"),
  BW_INC("BW_INC"),
  BW("BW"),
  IN("IN"),
  NOT_IN("NOT_IN"),

  final String value;
  const RuntimeFilterOp(this.value);
}

enum HomepageModule {
  Search("SEARCH"),
  Watchlist("WATCHLIST"),
  Favorite("FAVORITE"),
  MyLibrary("MY_LIBRARY"),
  Trending("TRENDING"),
  Learning("LEARNING"),

  final String value;
  const HomepageModule(this.value);
}

enum EmbedEvent {
  Init("init"),
  AuthInit("authInit"),
  Load("load"),
  Data("data"),
  QueryChanged("queryChanged"),
  Drilldown("drillDown"),
  DataSourceSelected("dataSourceSelected"),
  AddRemoveColumns("addRemoveColumns"),
  CustomAction("customAction"),
  VizPointDoubleClick("vizPointDoubleClick"),
  VizPointClick("vizPointClick"),
  Error("Error"),
  Alert("alert"),
  AuthExpire("ThoughtspotAuthExpired"),
  AuthFailure("ThoughtspotAuthFailure"),
  IdleSessionTimeout("IdleSessionTimeout"),
  AuthLogout("ThoughtspotAuthLogout"),
  EmbedHeight("EMBED_HEIGHT"),
  EmbedIframeCenter("EmbedIframeCenter"),
  GetDataClick("getDataClick"),
  RouteChange("ROUTE_CHANGE"),
  V1Data("exportVizDataToParent"),
  NoCookieAccess("noCookieAccess"),
  SAMLComplete("samlComplete"),
  DialogOpen("dialog-open"),
  DialogClose("dialog-close"),
  LiveboardRendered("PinboardRendered"),
  ALL("*"),
  Save("save"),
  Download("download"),
  DownloadAsPng("downloadAsPng"),
  DownloadAsPdf("downloadAsPdf"),
  DownloadAsCsv("downloadAsCsv"),
  DownloadAsXlsx("downloadAsXlsx"),
  AnswerDelete("answerDelete"),
  Pin("pin"),
  SpotIQAnalyze("spotIQAnalyze"),
  Share("share"),
  DrillInclude("context-menu-item-include"),
  DrillExclude("context-menu-item-exclude"),
  CopyToClipboard("context-menu-item-copy-to-clipboard"),
  UpdateTML("updateTSL"),
  EditTML("editTSL"),
  ExportTML("exportTSL"),
  SaveAsView("saveAsView"),
  CopyAEdit("copyAEdit"),
  ShowUnderlyingData("showUnderlyingData"),
  AnswerChartSwitcher("answerChartSwitcher"),
  APP_INIT("appInit"),
  LiveboardInfo("pinboardInfo"),
  AddToFavorites("addToFavorites"),
  Schedule("subscription"),
  Edit("edit"),
  MakeACopy("makeACopy"),
  Present("present"),
  Delete("delete"),
  SchedulesList("schedule-list"),
  Cancel("cancel"),
  Explore("explore"),
  CopyLink("embedDocument"),
  CrossFilterChanged("cross-filter-changed"),
  VizPointRightClick("vizPointRightClick"),
  InsertIntoSlide("insertInToSlide"),
  FilterChanged("filterChanged"),
  SageEmbedQuery("sageEmbedQuery"),
  SageWorksheetUpdated("sageWorksheetUpdated"),
  UpdateConnection("updateConnection"),
  CreateConnection("createConnection"),
  UpdatePersonalisedView("updatePersonalisedView"),
  SavePersonalisedView("savePersonalisedView"),
  ResetLiveboard("resetLiveboard"),
  DeletePersonalisedView("deletePersonalisedView"),
  CreateWorksheet("createWorksheet"),
  AskSageInit("AskSageInit"),
  Rename("rename"),
  OnBeforeGetVizDataIntercept("onBeforeGetVizDataIntercept"),
  ParameterChanged("parameterChanged"),
  TableVizRendered("TableVizRendered"),
  CreateLiveboard("createLiveboard"),

  final String value;
  const EmbedEvent(this.value);
}

enum HostEvent {
  Search("search"),
  DrillDown("triggerDrillDown"),
  Filter("filter"),
  Reload("reload"),
  GetIframeUrl("GetIframeUrl"),
  SetVisibleVizs("SetPinboardVisibleVizs"),
  SetActiveTab("SetActiveTab"),
  UpdateRuntimeFilters("UpdateRuntimeFilters"),
  Navigate("Navigate"),
  OpenFilter("openFilter"),
  AddColumns("addColumns"),
  RemoveColumn("removeColumn"),
  getExportRequestForCurrentPinboard("getExportRequestForCurrentPinboard"),
  Pin("pin"),
  LiveboardInfo("pinboardInfo"),
  Schedule("subscription"),
  SchedulesList("schedule-list"),
  ExportTML("exportTSL"),
  EditTML("editTSL"),
  UpdateTML("updateTSL"),
  DownloadAsPdf("downloadAsPdf"),
  MakeACopy("makeACopy"),
  Remove("delete"),
  Explore("explore"),
  CreateMonitor("createMonitor"),
  ManageMonitor("manageMonitor"),
  Edit("edit"),
  CopyLink("embedDocument"),
  Present("present"),
  GetTML("getTML"),
  ShowUnderlyingData("showUnderlyingData"),
  Delete("onDeleteAnswer"),
  SpotIQAnalyze("spotIQAnalyze"),
  Download("downloadAsPng"),
  DownloadAsPng("downloadAsPng"),
  DownloadAsCsv("downloadAsCSV"),
  DownloadAsXlsx("downloadAsXLSX"),
  Share("share"),
  Save("save"),
  SyncToSheets("sync-to-sheets"),
  SyncToOtherApps("sync-to-other-apps"),
  ManagePipelines("manage-pipeline"),
  ResetSearch("resetSearch"),
  GetFilters("getFilters"),
  UpdateFilters("updateFilters"),
  GetTabs("getTabs"),
  SetVisibleTabs("SetPinboardVisibleTabs"),
  SetHiddenTabs("SetPinboardHiddenTabs"),
  UpdateSageQuery("updateSageQuery"),
  GetAnswerSession("getAnswerSession"),
  AskSage("AskSage"),
  UpdateCrossFilter("UpdateCrossFilter"),
  ResetLiveboardPersonalisedView("ResetLiveboardPersonalisedView"),
  UpdateParameters("UpdateParameters"),
  GetParameters("GetParameters"),
  UpdatePersonalisedView("UpdatePersonalisedView"),
  InfoSuccess("InfoSuccess"),
  SaveAnswer("saveAnswer"),
  UIPassthrough("UiPassthrough"),
  TransformTableVizData("TransformTableVizData"),

  final String value;
  const HostEvent(this.value);
}

enum DataSourceVisualMode {
  Hidden("hide"),
  Collapsed("collapse"),
  Expanded("expand"),

  final String value;
  const DataSourceVisualMode(this.value);
}

enum Param {
  EmbedApp("embedApp"),
  DataSources("dataSources"),
  DataSourceMode("dataSourceMode"),
  DisableActions("disableAction"),
  DisableActionReason("disableHint"),
  ForceTable("forceTable"),
  preventLiveboardFilterRemoval("preventPinboardFilterRemoval"),
  SearchQuery("searchQuery"),
  HideActions("hideAction"),
  HideObjects("hideObjects"),
  HostAppUrl("hostAppUrl"),
  EnableVizTransformations("enableVizTransform"),
  EnableSearchAssist("enableSearchAssist"),
  EnablePendoHelp("enablePendoHelp"),
  HideResult("hideResult"),
  UseLastSelectedDataSource("useLastSelectedSources"),
  Tag("tag"),
  AutoLogin("autoLogin"),
  searchTokenString("searchTokenString"),
  executeSearch("executeSearch"),
  fullHeight("isFullHeightPinboard"),
  livedBoardEmbed("isLiveboardEmbed"),
  searchEmbed("isSearchEmbed"),
  vizEmbed("isVizEmbed"),
  Version("sdkVersion"),
  ViewPortHeight("viewPortHeight"),
  ViewPortWidth("viewPortWidth"),
  VisibleActions("visibleAction"),
  DisableLoginRedirect("disableLoginRedirect"),
  visibleVizs("pinboardVisibleVizs"),
  LiveboardV2Enabled("isPinboardV2Enabled"),
  DataPanelV2Enabled("enableDataPanelV2"),
  ShowAlerts("showAlerts"),
  Locale("locale"),
  CustomStyle("customStyle"),
  ForceSAMLAutoRedirect("forceSAMLAutoRedirect"),
  AuthType("authType"),
  IconSpriteUrl("iconSprite"),
  cookieless("cookieless"),
  ContextMenuTrigger("contextMenuEnabledOnWhichClick"),
  LinkOverride("linkOverride"),
  blockNonEmbedFullAppAccess("blockNonEmbedFullAppAccess"),
  ShowInsertToSlide("insertInToSlide"),
  PrimaryNavHidden("primaryNavHidden"),
  HideProfleAndHelp("profileAndHelpInNavBarHidden"),
  HideApplicationSwitcher("applicationSwitcherHidden"),
  HideOrgSwitcher("orgSwitcherHidden"),
  IsSageEmbed("isSageEmbed"),
  HideWorksheetSelector("hideWorksheetSelector"),
  DisableWorksheetChange("disableWorksheetChange"),
  HideSourceSelection("hideSourceSelection"),
  DisableSourceSelection("disableSourceSelection"),
  HideEurekaResults("hideEurekaResults"),
  HideEurekaSuggestions("hideEurekaSuggestions"),
  HideAutocompleteSuggestions("hideAutocompleteSuggestions"),
  HideLiveboardHeader("hideLiveboardHeader"),
  ShowLiveboardDescription("showLiveboardDescription"),
  ShowLiveboardTitle("showLiveboardTitle"),
  HiddenTabs("hideTabs"),
  VisibleTabs("visibleTabs"),
  HideTabPanel("hideTabPanel"),
  HideSampleQuestions("hideSampleQuestions"),
  WorksheetId("worksheet"),
  Query("query"),
  HideHomepageLeftNav("hideHomepageLeftNav"),
  ModularHomeExperienceEnabled("modularHomeExperience"),
  PendoTrackingKey("additionalPendoKey"),
  LiveboardHeaderSticky("isLiveboardHeaderSticky"),
  IsProductTour("isProductTour"),
  HideSearchBarTitle("hideSearchBarTitle"),
  HideSageAnswerHeader("hideSageAnswerHeader"),
  HideSearchBar("hideSearchBar"),
  ClientLogLevel("clientLogLevel"),
  OverrideNativeConsole("overrideConsoleLogs"),
  enableAskSage("enableAskSage"),
  CollapseSearchBarInitially("collapseSearchBarInitially"),
  DataPanelCustomGroupsAccordionInitialState("dataPanelCustomGroupsAccordionInitialState"),
  EnableCustomColumnGroups("enableCustomColumnGroups"),
  DateFormatLocale("dateFormatLocale"),
  NumberFormatLocale("numberFormatLocale"),
  CurrencyFormat("currencyFormat"),
  Enable2ColumnLayout("enable2ColumnLayout"),
  IsFullAppEmbed("isFullAppEmbed"),
  IsOnBeforeGetVizDataInterceptEnabled("isOnBeforeGetVizDataInterceptEnabled"),
  FocusSearchBarOnRender("focusSearchBarOnRender"),
  DisableRedirectionLinksInNewTab("disableRedirectionLinksInNewTab"),
  HomePageSearchBarMode("homePageSearchBarMode"),
  ShowLiveboardVerifiedBadge("showLiveboardVerifiedBadge"),
  ShowLiveboardReverifyBanner("showLiveboardReverifyBanner"),
  LiveboardHeaderV2("isLiveboardHeaderV2Enabled"),
  HideIrrelevantFiltersInTab("hideIrrelevantFiltersAtTabLevel"),
  SpotterEnabled("isSpotterExperienceEnabled"),
  IsUnifiedSearchExperienceEnabled("isUnifiedSearchExperienceEnabled"),
  OverrideOrgId("orgId"),
  OauthPollingInterval("oAuthPollingInterval"),
  IsForceRedirect("isForceRedirect"),
  DataSourceId("dataSourceId"),
  preAuthCache("preAuthCache"),
  ShowSpotterLimitations("showSpotterLimitations"),

  final String value;
  const Param(this.value);
}

enum Action {
  Save("save"),
  Update("update"),
  SaveUntitled("saveUntitled"),
  SaveAsView("saveAsView"),
  MakeACopy("makeACopy"),
  EditACopy("editACopy"),
  CopyLink("embedDocument"),
  ResetLayout("resetLayout"),
  Schedule("subscription"),
  SchedulesList("schedule-list"),
  Share("share"),
  AddFilter("addFilter"),
  AddDataPanelObjects("addDataPanelObjects"),
  ConfigureFilter("configureFilter"),
  CollapseDataSources("collapseDataSources"),
  CollapseDataPanel("collapseDataPanel"),
  ChooseDataSources("chooseDataSources"),
  AddFormula("addFormula"),
  AddParameter("addParameter"),
  AddColumnSet("addSimpleCohort"),
  AddQuerySet("addAdvancedCohort"),
  SearchOnTop("searchOnTop"),
  SpotIQAnalyze("spotIQAnalyze"),
  ExplainInsight("explainInsight"),
  SpotIQFollow("spotIQFollow"),
  ShareViz("shareViz"),
  ReplaySearch("replaySearch"),
  ShowUnderlyingData("showUnderlyingData"),
  Download("download"),
  DownloadAsPng("downloadAsPng"),
  DownloadAsPdf("downloadAsPdf"),
  DownloadAsCsv("downloadAsCSV"),
  DownloadAsXlsx("downloadAsXLSX"),
  DownloadTrace("downloadTrace"),
  ExportTML("exportTSL"),
  ImportTML("importTSL"),
  UpdateTML("updateTSL"),
  EditTML("editTSL"),
  Present("present"),
  ToggleSize("toggleSize"),
  Edit("edit"),
  EditTitle("editTitle"),
  Remove("delete"),
  Ungroup("ungroup"),
  Describe("describe"),
  Relate("relate"),
  CustomizeHeadlines("customizeHeadlines"),
  PinboardInfo("pinboardInfo"),
  LiveboardInfo("pinboardInfo"),
  SendAnswerFeedback("sendFeedback"),
  DownloadEmbraceQueries("downloadEmbraceQueries"),
  Pin("pin"),
  AnalysisInfo("analysisInfo"),
  Subscription("subscription"),
  Explore("explore"),
  DrillInclude("context-menu-item-include"),
  DrillExclude("context-menu-item-exclude"),
  CopyToClipboard("context-menu-item-copy-to-clipboard"),
  CopyAndEdit("context-menu-item-copy-and-edit"),
  DrillEdit("context-menu-item-edit"),
  EditMeasure("context-menu-item-edit-measure"),
  Separator("context-menu-item-separator"),
  DrillDown("DRILL"),
  RequestAccess("requestAccess"),
  QueryDetailsButtons("queryDetailsButtons"),
  AnswerDelete("onDeleteAnswer"),
  AnswerChartSwitcher("answerChartSwitcher"),
  AddToFavorites("addToFavorites"),
  EditDetails("editDetails"),
  CreateMonitor("createMonitor"),
  ReportError("reportError"),
  SyncToSheets("sync-to-sheets"),
  SyncToOtherApps("sync-to-other-apps"),
  ManagePipelines("manage-pipeline"),
  CrossFilter("context-menu-item-cross-filter"),
  SyncToSlack("syncToSlack"),
  SyncToTeams("syncToTeams"),
  RemoveCrossFilter("context-menu-item-remove-cross-filter"),
  AxisMenuAggregate("axisMenuAggregate"),
  AxisMenuTimeBucket("axisMenuTimeBucket"),
  AxisMenuFilter("axisMenuFilter"),
  AxisMenuConditionalFormat("axisMenuConditionalFormat"),
  AxisMenuSort("axisMenuSort"),
  AxisMenuGroup("axisMenuGroup"),
  AxisMenuPosition("axisMenuPosition"),
  AxisMenuRename("axisMenuRename"),
  AxisMenuEdit("axisMenuEdit"),
  AxisMenuNumberFormat("axisMenuNumberFormat"),
  AxisMenuTextWrapping("axisMenuTextWrapping"),
  AxisMenuRemove("axisMenuRemove"),
  InsertInToSlide("insertInToSlide"),
  RenameModalTitleDescription("renameModalTitleDescription"),
  RequestVerification("requestVerification"),
  MarkAsVerified("markAsVerified"),
  AddTab("addTab"),
  EnableContextualChangeAnalysis("enableContextualChangeAnalysis"),
  ShowSageQuery("showSageQuery"),
  EditSageAnswer("editSageAnswer"),
  SageAnswerFeedback("sageAnswerFeedback"),
  ModifySageAnswer("modifySageAnswer"),
  MoveToTab("onContainerMove"),
  ManageMonitor("manageMonitor"),
  PersonalisedViewsDropdown("personalisedViewsDropdown"),
  LiveboardUsers("liveboardUsers"),
  TML("tml"),
  CreateLiveboard("createLiveboard"),
  VerifiedLiveboard("verifiedLiveboard"),
  AskAi("AskAi"),
  AddToWatchlist("addToWatchlist"),
  RemoveFromWatchlist("removeFromWatchlist"),
  OrganiseFavourites("organiseFavourites"),
  AIHighlights("AIHighlights"),
  EditScheduleHomepage("editScheduleHomepage"),
  PauseScheduleHomepage("pauseScheduleHomepage"),
  ViewScheduleRunHomepage("viewScheduleRunHomepage"),
  UnsubscribeScheduleHomepage("unsubscribeScheduleHomepage"),
  ManageTags("manageTags"),
  DeleteScheduleHomepage("deleteScheduleHomepage"),
  KPIAnalysisCTA("kpiAnalysisCTA"),
  DisableChipReorder("disableChipReorder"),
  ChangeFilterVisibilityInTab("changeFilterVisibilityInTab"),
  PreviewDataSpotter("previewDataSpotter"),
  ResetSpotterChat("resetSpotterChat"),
  SpotterFeedback("spotterFeedback"),
  EditPreviousPrompt("editPreviousPrompt"),
  DeletePreviousPrompt("deletePreviousPrompt"),
  EditTokens("editTokens"),

  final String value;
  const Action(this.value);
}

enum PrefetchFeatures {
  FullApp("FullApp"),
  SearchEmbed("SearchEmbed"),
  LiveboardEmbed("LiveboardEmbed"),
  VizEmbed("VizEmbed"),

  final String value;
  const PrefetchFeatures(this.value);
}

enum ContextMenuTriggerOptions {
  LEFT_CLICK("left-click"),
  RIGHT_CLICK("right-click"),
  BOTH_CLICKS("both-clicks"),

  final String value;
  const ContextMenuTriggerOptions(this.value);
}

enum LogLevel {
  SILENT("SILENT"),
  ERROR("ERROR"),
  WARN("WARN"),
  INFO("INFO"),
  DEBUG("DEBUG"),
  TRACE("TRACE"),

  final String value;
  const LogLevel(this.value);
}