If you have enabled xref:trusted-authentication.adoc#trusted-auth-enable[trusted authentication] on ThoughtSpot and have access to the `secret key`, you can send an API request to the `/tspublic/v1/session/auth/token` endpoint and get a login token for a ThoughtSpot user. 

After you get the authentication token from ThoughtSpot via a REST API call to the `/tspublic/v1/session/auth/token` endpoint, use this token in your API request to the `/tspublic/v1/session/login/token` endpoint to authenticate and log in a user.

== Automate user provisioning and group assignment

Starting from 8.9.0.cl, the `/tspublic/v1/session/auth/token` API endpoint supports adding a user Just-in-Time (JIT) and dynamically assigning groups and privileges. If a user for whom you want to request an authentication token doesn't exist in the ThoughtSpot system, you can set the `autocreate` and `groups` properties in the API call to add the user and assign groups.

=== Resource URL
----
POST /tspublic/v1/session/auth/token
----
=== Request parameters

[width="100%" cols="1,4"]
[options='header']
|====
|Form parameter|Description
|`secret_key`|__String__. The secret key string provided by the ThoughtSpot application server. ThoughtSpot generates this secret key when you enable trusted authentication on an application instance.
|`username` a|__String__. The username of the user configured in ThoughtSpot. +

If the user doesn't exist in the ThoughtSpot system, you can set the `autocreate` flag to `true` to create a user account in ThoughtSpot.
|`access_level` a|__String__. User access privilege. Valid values are:
* `FULL` - Creates a session with full access.
* `REPORT_BOOK_VIEW` - Allows view access to the visualization or Liveboard.
|`id` |__String__. GUID of the ThoughtSpot object. If you have set the `access_level` attribute to `REPORT_BOOK_VIEW`, specify the GUID of the Liveboard or visualization object.
|`groups` __Optional__ a|__String__. A JSON array of groups to which the user belongs. For example, `["sales", "marketing"]`. +

* If the user doesn't exist in ThoughtSpot and `autocreate` is set to `true`, the user is assigned to the specified groups.
* If the user already exists in the ThoughtSpot system and `autocreate` is set to `false`, the API ignores the values specified in the `groups` attribute.
* If the user already exists in the ThoughtSpot system and `autocreate` is set to `true`, the API updates the user object.
* If `autocreate` is set to `true` and the group names are not defined in the `groups` property, ThoughtSpot does not update the user object.

|`autocreate` __Optional__ a|__Boolean__. When set to `true`, if the specified `username` does not exist in the ThoughtSpot system, a new user is created without a password. By default, the `autocreate` property is set to `false`.

|====

=== Example request

.cURL
[source, cURL]
----
curl -X POST \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: text/plain' \
-d 'secret_key=82749a88-1506-4cd9-803c-8316c7d41d7c&username=testUser2&access_level=FULL&groups=%5B%22sales%22%2C%20%22marketing%22%5D&autocreate=true' \
'https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/auth/token'
----

.Request URL
----
https://<ThoughtSpot-host>/callosum/v1/tspublic/v1/session/auth/token
----

=== Example response

If the API request is successful, ThoughtSpot returns an authentication token for the user.

[NOTE]
====
* If the username specified in the API request exists in the ThoughtSpot system, the API returns the token, else it returns the `user not found` error.
* If the user does not exist in ThoughtSpot and the `autocreate` property is set to `true`, the user is created. If `groups` and `orgid` attributes are defined, ThoughtSpot assigns the user to the specified groups and Org ID.
* If the user already exists in ThoughtSpot, `autocreate` is set to `true` and the group names are defined in the `groups` attribute, the user will be added to the groups specified in the API request. 
====

The following example shows the authentication token returned by ThoughtSpot after a successful API call.
----
JHNoaXJvMSRTSEEtMjU2JDUwMDAwMCRPMFA2S0ZlNm51Qlo4NFBlZUppdzZ3PT0kMnJKaSswSHN6Yy96ZGxqdXUwd1dXZkovNVlHUW40d3FLMVdBT3hYVVgxaz0
----

=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|The authentication token is generated successfully
|**400**|Invalid parameter value
|**401**|Unauthorized request or invalid token
|**500**|Token-based trusted authentication is not enabled on ThoughtSpot
|===
