
If your application instance requires callback custom actions to retrieve large data sets in answer payload, define a method to process data in batches and paginate the response.

[source, javascript]
----
.on(EmbedEvent.CustomAction, async(payload: any) => {
	const data = payload.data;
	if(data.id === 'show-data') {
		const fetchAnswerData = await payload.answerService.fetchData(offset, batchSize);
		console.log('fetchAnswerData:::', fetchAnswerData);
	}
})
----
offset::
__Integer__. Sets the starting point for the records retrieved from the search answer. For example, if you want to retrieve the initial set of records in 3 batches, set the value to `0`.

batchSize::
__Integer__. Divides the data set into batches. For example, if you specify the batchSize as 3, the three batches are processed independently for faster response.

If the dataset is divided into 10 batches, and the offset value is `0` and the batchSize is `3`, the first three batches of the dataset are retrieved in the answer payload in one UI query. Similarly, if the offset value is `1` and the batchSize is `3`, the next set of batches (4,5, and 6) are retrieved.
