export enum AuthType {
    SSO = 'SSO',
    AuthServer = 'AuthServer',
}

export interface EmbedConfig {
    thoughtSpotHost: string;
    authType: AuthType;
    authEndpoint?: string;
}

export interface LayoutConfig {}
export interface FrameParams {
    width?: number;
    height?: number;
}

export interface ViewConfig {
    layoutConfig?: LayoutConfig;
    frameParams?: FrameParams;
    theme?: string;
    styleSheet__unstable?: string;
}

export type MessagePayload = { data: any };
export type MessageCallback = (event: MessagePayload) => void;

export type QueryObject = any;

const DEFAULT_EMBED_WIDTH = 500;
const DEFAULT_EMBED_HEIGHT = 500;

/**
 * A simple ID generator that meets the following goals:
 * 1. Provide a way to generate a string guaranteed to be unique when compared
 *    to other strings generated by this function.
 * 2. Make the string complex enough that it is highly unlikely to be
 *    accidentally duplicated by hand (this is key if you're using `ID`
 *    as a private/protected name on an object).
 * Hat-tip: https://gist.github.com/gordonbrander/2230317
 */
const id = () => Math.random().toString(36).substr(2, 9);

let config = {} as EmbedConfig;

const init = (embedConfig: EmbedConfig) => {
    config = embedConfig;
};

const getThoughtSpotHost = () => {
    return config.thoughtSpotHost;
};

class TsEmbed {
    private el: Element;
    private iFrame: HTMLIFrameElement;

    private thoughtSpotHost: string;

    constructor(domSelector: string) {
        this.el = document.querySelector(domSelector);
        this.thoughtSpotHost = getThoughtSpotHost();
    }

    private showLoadingIndicator() {
        console.log('iFrame loading...');
    }

    private hideLoadingIndicator() {
        console.log('iFrame contents loaded');
    }

    private throwInitError() {
        throw new Error('You need to init the ThoughtSpot SDK module first');
    }

    protected getEmbedBasePath() {
        return `${this.thoughtSpotHost}/#/embed`;
    }

    protected renderIFrame(url: string, frameOptions: FrameParams) {
        if (!this.thoughtSpotHost) {
            this.throwInitError();
        }

        this.showLoadingIndicator();
        this.iFrame = document.createElement('iframe');
        this.iFrame.src = url;
        this.iFrame.width = `${frameOptions.width || DEFAULT_EMBED_WIDTH}`;
        this.iFrame.height = `${frameOptions.height || DEFAULT_EMBED_HEIGHT}`;
        this.iFrame.style.border = '0';
        this.iFrame.name = 'ThoughtSpot Embedded Analytics';
        this.iFrame.addEventListener('load', () => this.hideLoadingIndicator());
        this.el.appendChild(this.iFrame);
    }

    public getThoughtSpotHost() {
        return this.thoughtSpotHost;
    }

    public on(messageType: string, callback: MessageCallback) {
        // TODO: implement
        return this;
    }

    public trigger(messageType: string, data: MessagePayload) {
        this.iFrame.contentWindow.postMessage(
            {
                type: messageType,
                data,
            },
            this.thoughtSpotHost,
        );

        return this;
    }
}

class SearchEmbed extends TsEmbed {
    private viewConfig: ViewConfig;
    private id: string;

    constructor(domSelector: string, viewConfig: ViewConfig) {
        super(domSelector);
        this.viewConfig = viewConfig;
        this.id = id();
    }

    private getIFrameSrc(answerId?: string) {
        const answerPath = answerId ? `saved-answer/${answerId}` : 'answer';
        return `${this.getEmbedBasePath()}/${answerPath}`;
    }

    public getId() {
        return this.id;
    }

    public render(dataSources: string[], query: QueryObject, answerId: string) {
        const src = this.getIFrameSrc(answerId);
        this.renderIFrame(src, this.viewConfig.frameParams);
        return this;
    }
}

export { init, SearchEmbed };
