// eslint-disable-next-line no-shadow
export enum AuthType {
    SSO = 'SSO',
    AuthServer = 'AuthServer',
}

export interface EmbedConfig {
    thoughtSpotHost: string;
    authType: AuthType;
    authEndpoint?: string;
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface LayoutConfig {}
export interface FrameParams {
    width?: number;
    height?: number;
}

export interface ViewConfig {
    layoutConfig?: LayoutConfig;
    frameParams?: FrameParams;
    theme?: string;
    // eslint-disable-next-line camelcase
    styleSheet__unstable?: string;
}

export type MessagePayload = { type: string; data: any };
export type MessageCallback = (payload: MessagePayload) => void;

export type QueryObject = any;

// eslint-disable-next-line no-shadow
export enum EventType {
    Init = 'init',
    Load = 'load',
}

const DEFAULT_EMBED_WIDTH = 500;
const DEFAULT_EMBED_HEIGHT = 500;

/**
 * A simple ID generator that meets the following goals:
 * 1. Provide a way to generate a string guaranteed to be unique when compared
 *    to other strings generated by this function.
 * 2. Make the string complex enough that it is highly unlikely to be
 *    accidentally duplicated by hand (this is key if you're using `ID`
 *    as a private/protected name on an object).
 * Hat-tip: https://gist.github.com/gordonbrander/2230317
 */
const id = () => Math.random().toString(36).substr(2, 9);

let config = {} as EmbedConfig;

const init = (embedConfig: EmbedConfig): void => {
    config = embedConfig;
};

const getThoughtSpotHost = () => {
    return config.thoughtSpotHost;
};

class TsEmbed {
    private id: string;

    private el: Element;

    private iFrame: HTMLIFrameElement;

    private eventHandlerMap: Map<string, MessageCallback[]>;

    private thoughtSpotHost: string;

    constructor(domSelector: string) {
        this.el = document.querySelector(domSelector);
        this.id = id();
        this.thoughtSpotHost = getThoughtSpotHost();
        this.eventHandlerMap = new Map();
    }

    private executeCallbacks(eventType: EventType, data: any) {
        const callbacks = this.eventHandlerMap.get(eventType) || [];
        callbacks.forEach((callback) => {
            setTimeout(() => callback(data));
        });
    }

    private throwInitError() {
        throw new Error('You need to init the ThoughtSpot SDK module first');
    }

    private subscribeToEvents() {
        window.addEventListener('message', (event) => {
            const eventType = event.data?.type;
            const embedId = event.data?.embedId;
            if (embedId === this.getId()) {
                this.executeCallbacks(eventType, event.data);
            }
        });
    }

    protected getEmbedBasePath() {
        return `${this.thoughtSpotHost}/#/embed/${this.getId()}`;
    }

    protected renderIFrame(url: string, frameOptions: FrameParams) {
        if (!this.thoughtSpotHost) {
            this.throwInitError();
        }

        this.executeCallbacks(EventType.Init, {
            data: {
                timestamp: Date.now(),
            },
        });
        this.iFrame = document.createElement('iframe');
        this.iFrame.src = url;
        this.iFrame.width = `${frameOptions.width || DEFAULT_EMBED_WIDTH}`;
        this.iFrame.height = `${frameOptions.height || DEFAULT_EMBED_HEIGHT}`;
        this.iFrame.style.border = '0';
        this.iFrame.name = 'ThoughtSpot Embedded Analytics';
        this.iFrame.addEventListener('load', () =>
            this.executeCallbacks(EventType.Load, {
                data: {
                    timestamp: Date.now(),
                },
            }),
        );
        this.el.appendChild(this.iFrame);

        this.subscribeToEvents();
    }

    public getId() {
        return this.id;
    }

    public getThoughtSpotHost() {
        return this.thoughtSpotHost;
    }

    public on(messageType: string, callback: MessageCallback) {
        const callbacks = this.eventHandlerMap.get(messageType) || [];
        callbacks.push(callback);
        this.eventHandlerMap.set(messageType, callbacks);

        return this;
    }

    public trigger(messageType: string, data: any) {
        this.iFrame.contentWindow.postMessage(
            {
                type: messageType,
                data,
            },
            this.thoughtSpotHost,
        );

        return this;
    }
}

class SearchEmbed extends TsEmbed {
    private viewConfig: ViewConfig;

    constructor(domSelector: string, viewConfig: ViewConfig) {
        super(domSelector);
        this.viewConfig = viewConfig;
    }

    private getIFrameSrc(answerId?: string) {
        const answerPath = answerId ? `saved-answer/${answerId}` : 'answer';
        return `${this.getEmbedBasePath()}/${answerPath}`;
    }

    public render(
        dataSources: string[],
        query: QueryObject,
        answerId: string,
    ): SearchEmbed {
        const src = this.getIFrameSrc(answerId);
        this.renderIFrame(src, this.viewConfig.frameParams);

        return this;
    }
}

export { init, SearchEmbed };
