/**
 * Copyright (c) 2020
 *
 * Common utility functions for ThoughtSpot Embed UI SDK
 *
 * @summary Utils
 * @author Ayon Ghosh <ayon.ghosh@thoughtspot.com>
 */

/**
 * A simple ID generator that meets the following goals:
 * 1. Provide a way to generate a string guaranteed to be unique when compared
 *    to other strings generated by this function.
 * 2. Make the string complex enough that it is highly unlikely to be
 *    accidentally duplicated by hand (this is key if you're using `ID`
 *    as a private/protected name on an object).
 * Hat-tip: https://gist.github.com/gordonbrander/2230317
 */
export const id = (): string => Math.random().toString(36).substr(2, 9);
