name: CSS Variables Sync Check

on:
  pull_request:
    paths:
      - 'src/css-variables.ts'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Test repository access
        run: |
          echo "🔍 Testing repository access..."
          echo "Repository: thoughtspot/Thoughtspot-theme-builder"
          echo "Branch: release"
          
          # Test if we can access the repository
          if curl -s -H "Authorization: token ${{ secrets.THEME_BUILDER_TOKEN }}" \
              "https://api.github.com/repos/thoughtspot/Thoughtspot-theme-builder" | grep -q "full_name"; then
              echo "✅ Repository access confirmed"
          else
              echo "❌ Cannot access repository. Possible issues:"
              echo "1. Repository name is incorrect"
              echo "2. Repository is under different organization"
              echo "3. Token doesn't have access to this repository"
              echo "4. Repository doesn't exist"
              exit 1
          fi

      - name: Checkout theme builder repo
        uses: actions/checkout@v2
        with:
          repository: thoughtspot/Thoughtspot-theme-builder
          path: theme-builder
          ref: release
          token: ${{ secrets.THEME_BUILDER_TOKEN }}

      - name: Validate CSS variables
        run: |
          node scripts/validate-css-variables.js "$(cat theme-builder/src/data/sdkVariable.ts)"
