name: CSS Variables Validation

on:
  pull_request:
    paths:
      - 'src/css-variables.ts'
  workflow_dispatch: # Allow manual triggering

jobs:
  validate-css-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout theme builder repository
        uses: actions/checkout@v2
        with:
          repository: thoughtspot/Thoughtspot-theme-builder
          path: theme-builder
          ref: main
          token: ${{ secrets.THEME_BUILDER_TOKEN }}
          fetch-depth: 1

      - name: Verify theme builder file access
        run: |
          echo "🔍 Verifying theme builder file access..."
          echo "✅ Theme builder file: theme-builder/src/data/sdkVariable.ts"
          echo "File size: $(wc -c < theme-builder/src/data/sdkVariable.ts) bytes"

      - name: Validate CSS variables consistency
        run: |
          echo "🔍 Starting CSS variables validation..."
          echo "Interface file: src/css-variables.ts"
          echo "Implementation file: theme-builder/src/data/sdkVariable.ts"
          echo "Running validation..."
          
          node scripts/validate-css-variables.js "$(cat theme-builder/src/data/sdkVariable.ts)"
          
          echo "✅ CSS variables validation completed successfully!"
